Add support for named stages
se-passau/VaRA-Tool-Suite pull request #100
Opened 2019-06-28 14:26 UTC by julianbreiteneicher

resolves se-passau/VaRA#433

They can already be used with the 'per_year_add'
extension stragegy by using the '--revs_year_sep'
parameter.

To update the case-study files to the new format, the following command can be used:
```
find . -name "*.case_study" -exec sed -i '/^- !CSStage/a \ \ _CSStage__name: null' {} \;
```

2019-07-04 15:57 UTC, julianbreiteneicher commented
@vulder: New revisions are now inserted at the correct position of the stages
list.

2019-07-04 15:58 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3785060&bid=13264240)

2019-07-04 16:01 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3785060&bid=13264240)

2019-07-04 21:18 UTC, vulder requested changes

2019-07-04 21:18 UTC, vulder commented on varats/paper/paper_config_manager.py
> +            stage_name = stages[stage_num].name
```
            stage_name = stages[stage_num].name
```
this line could be move into the if

2019-07-04 21:18 UTC, vulder commented on varats/paper/case_study.py
> +    def insert_empty_stage(self, pos: int) -> None:
```suggestion
    def insert_empty_stage(self, pos: int) -> CSStage:
```

2019-07-04 21:18 UTC, vulder commented on varats/paper/case_study.py
> +    def insert_empty_stage(self, pos: int) -> None:
maybe we should directly return the created stage, so it becomes easier for the user to interact with it.
E.g., this is always tedious in std::vector code where you `push_back()` and then afterwards need to call vec.back() to interact with the newly created element

2019-07-04 21:26 UTC, julianbreiteneicher commented on varats/paper/paper_config_manager.py
> +            stage_name = stages[stage_num].name
I don't understand what you mean. stage_name is used two times here

2019-07-04 21:28 UTC, julianbreiteneicher commented on varats/paper/case_study.py
> +    def insert_empty_stage(self, pos: int) -> None:
I think this would contradict the `stages` getter of the `CaseStudy` class for example,
because the getter creates a copy of the stages list and returns that, so that the internal stage of the `CaseStudy` cannot be modified directly from the outside.

2019-07-05 07:53 UTC, vulder commented on varats/paper/case_study.py
> +    def insert_empty_stage(self, pos: int) -> None:
I don't think it does. `.stages` only creates a new list so the caller cannot manipulate the internal state of the stages list but the stages are not copied, they are references.

2019-07-05 07:55 UTC, vulder commented on varats/paper/paper_config_manager.py
> +            stage_name = stages[stage_num].name
ah yeah, it's also used in the condition

2019-07-05 11:44 UTC, julianbreiteneicher commented on varats/paper/case_study.py
> +    def insert_empty_stage(self, pos: int) -> None:
OK, in this case, it should be ok.
I'll change that

2019-07-05 11:48 UTC, julianbreiteneicher commented on varats/paper/case_study.py
> +    def insert_empty_stage(self, pos: int) -> None:
Done

2019-07-05 16:31 UTC, vulder approved these changes

2019-07-05 16:32 UTC, merged