Enable custom file types for successful reports
se-passau/VaRA-Tool-Suite pull request #112
Opened 2019-07-29 20:04 UTC by labrenz

Allows different reports to specify their own file type extension, while vara-cs still recognizes them as successful runs and paints their statuses accordingly.

2019-08-19 17:22 UTC, vulder requested changes
only found a small nit

we also need a small bash command to migrate the data like we did before probably something similar like this should do:
```
cd vara/results/
rename -v '.yaml' '_success.yaml' **/*
```
what other renames do we also need?
PS: `-n` let's rename run without changing files, for local testing

2019-08-19 17:22 UTC, vulder commented on tests/data/test_report.py
> +        self.assertTrue(
you can remove this, we don't need to check if a filename keeps being correct after we did no change

2019-08-19 17:45 UTC, labrenz commented on tests/data/test_report.py
> +        self.assertTrue(
All right, i will provide a small bash script to update the old data.
I figured the tests was pointless, yet was to scared to remove it, but i will do so, the updates should follow in a commit tomorrow.

2019-08-20 14:59 UTC, labrenz commented on tests/data/test_report.py
> +        self.assertTrue(
Ok i added the commits, thanks for the tip with rename.
It would have been much more effort with sed, xargs and all that pre-installed bash stuff.

However the path to the vara results is currently hard encoded, and i am not quite happy with that yet.

2019-08-26 20:16 UTC, labrenz commented on tests/data/test_report.py
> +        self.assertTrue(
The call for changing the names is: ``rename -n 's/.yaml/_sucess.yaml/' **/*``
You have to be in the results directory first, in my case you can get there by: ``cd ~/vara/results``

I will also remove the script, i uploaded.

2019-08-26 20:55 UTC, labrenz commented on tests/data/test_report.py
> +        self.assertTrue(
I just removed the script since it was faulty and also should not be in the repo.
However, to rename all old files, run these commands:
 ```
cd vara/results/
rename 's/.yaml/_sucess.yaml/' **/*
rename 's/.failed/_failed.yaml/' **/*
rename 's/.cerror/_cerror.yaml/' **/*
```
**Make sure you run the command renaming the existing yamls first**, otherwise it will also transform already renamed, which then would have multiple extensions.

2019-09-05 12:20 UTC, vulder commented
@labrenz can you please post the update script, you want users to apply for fixing, here so I can add it to the commit when merging?

2019-09-05 14:52 UTC, labrenz commented
As mentioned in the conversation earlier:
> I just removed the script since it was faulty and also should not be in the repo.
> However, to rename all old files, run these commands:
> 
```
cd vara/results/
rename 's/.yaml/_sucess.yaml/' **/*
rename 's/.failed/_failed.yaml/' **/*
rename 's/.cerror/_cerror.yaml/' **/*
``` 
**Make sure you run the command renaming the existing yamls first**, otherwise it will also transform the already renamed files, which then would have multiple extensions.

2019-09-07 16:39 UTC, vulder commented
@labrenz ah, sry I somehow missed that

2019-09-07 18:03 UTC, labrenz commented
Np

2019-09-09 19:09 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3927888&bid=13642747)

2019-09-09 19:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3927888&bid=13642747)

2019-09-09 19:56 UTC, vulder approved these changes

2019-09-09 19:59 UTC, merged