Add interaction filter support to GitBlameAnnotationReport experiment
se-passau/VaRA-Tool-Suite pull request #128
Opened 2019-09-21 20:56 UTC by julianbreiteneicher

By default, the GitBlameAnnotationReport experiment looks for an interaction filter file
named `InteractionFilter-GitBlameAnnotationReport-{project_name}.yaml`.

The used file name can be further customized by subclassing the experiment.
Instead of the string "GitBlameAnnotationReport", the user can use a different string
by calling the experiment's superclass constructor with the appropriate string.

2019-09-21 20:59 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/git_blame_annotation_report.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4198282&bid=14361745)

2019-09-23 10:19 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/git_blame_annotation_report.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4198282&bid=14361745)

2019-10-01 18:34 UTC, vulder requested changes

2019-10-01 18:34 UTC, vulder commented on varats/experiments/git_blame_annotation_report.py
> +            run_cmd = opt.__getitem__(opt_params)
using private functions is kinda meh
it should work if you just expand the list into arguments to `opt` like: `opt[*opt_params]`

2019-10-06 17:13 UTC, julianbreiteneicher commented on varats/experiments/git_blame_annotation_report.py
> +            run_cmd = opt.__getitem__(opt_params)
Done. Btw, `opt[*opt_params]` is invalid syntax. `opt(*opt_params)` worked, however.

2019-10-06 17:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/git_blame_annotation_report.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4198282&bid=14361745)

2019-10-08 18:01 UTC, vulder commented on varats/experiments/git_blame_annotation_report.py
> +            run_cmd = opt.__getitem__(opt_params)
that is strange, `()` are plumbum execute cmd `[]` are return command opj
does it work? meaning is run_cmd then afterwards really the command or the stdout/stderr/ret triple

2019-10-08 18:19 UTC, vulder approved these changes

2019-10-08 18:37 UTC, julianbreiteneicher commented on varats/experiments/git_blame_annotation_report.py
> +            run_cmd = opt.__getitem__(opt_params)
`()` works for me, yes.
I got the two different ways (`__getitem__` and `(*params)`) from here: https://stackoverflow.com/questions/45679202/pass-parameters-to-python-plumbum-command-from-a-list

2019-10-18 08:41 UTC, merged