Add support for supplementary result files
se-passau/VaRA-Tool-Suite pull request #129
Opened 2019-09-27 15:52 UTC by julianbreiteneicher

This PR enables experiments to create supplementary
result files in addition to the main result file.

The `CommitReport.get_supplementary_file_name` method
can be used to generate a supplementary report file.
Multiple supplementary files per revision are also
possible.
They can be differentiated by the methods `info_type`
parameter.

The experiment can then use the generated filenames
to create these files and store additional information
or results of the experiment (e.g. the experiments duration
time).

Contrary to the "normal" result files, these supplementary
files do not indictate a success or failure of the experiment.
They are intended to provide additional information about
successful experiment runs.

This means that if an experiment fails, supplementary files
that have already been created should be deleted.
This can easily be done by the experiment by passing a
list of files to the experiments `PEErrorHandler`.

If the experiment fails and the error handler is called,
it will automatically delete all files of the passed list.

2019-09-27 15:55 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/revisions.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4231983&bid=14466489)

2019-10-01 18:27 UTC, vulder requested changes
Other than my remark, looks good :+1: 

PS: could you please resolve the merge conflicts

2019-10-01 18:27 UTC, vulder commented on varats/data/revisions.py
> +                                   ) -> tp.List[tp.Tuple[Path, str, str]]:
Should we maybe allow the user to pass a info_type? So we could filter an only return supp files that are needed.

2019-10-13 18:08 UTC, julianbreiteneicher commented on varats/data/revisions.py
> +                                   ) -> tp.List[tp.Tuple[Path, str, str]]:
@vulder: Done

2019-10-13 18:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/revisions.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4231983&bid=14466489)

2019-10-13 18:24 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/revisions.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4231983&bid=14466489)

2019-10-17 12:52 UTC, vulder approved these changes
lgtm :)
I'll merge when the conflicts are resolved

2019-10-20 17:10 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/revisions.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4231983&bid=14466489)

2019-10-20 17:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/revisions.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4231983&bid=14466489)

2019-10-20 17:28 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/revisions.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4231983&bid=14466489)

2019-10-20 17:31 UTC, julianbreiteneicher commented
> lgtm :)
> I'll merge when the conflicts are resolved

done.

2019-10-20 21:07 UTC, merged