F taint propagation experiment
se-passau/VaRA-Tool-Suite pull request #134
Opened 2019-10-07 18:38 UTC by labrenz

Allow to run vara's taint analysis on designed set of test files for propagation evaluation.

The compiled cpp files and their filecheck files can be found under [this repo](https://github.com/se-passau/vara-perf-tests/tree/f-taintTests/taint-tests).

The result of each filecheck is stored into a result file for each test file.
If the output of vara matches the expected filecheck an empty file with the `_success` file ending is created, otherwise an `_failed.txt` file will be created. The content of the failed run's output is stored in the result file.

2019-10-07 18:42 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- varats/data/reports/taint_report.py  1
- varats/projects/test_projects/taint_tests.py  3
- varats/experiments/taint_propagation.py  4
         

Clones added
============
- varats/projects/c_projects/lrzip.py  1
- varats/experiments/git_blame_annotation_report.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/experiments/taint_propagation.py  2
         

Clones removed
==============
+ varats/projects/c_projects/xz.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4280681&bid=14603033)

2019-10-07 19:09 UTC, labrenz commented
Closing again, while i correctly resolve all merging issues with the vara-dev branch.

2019-10-07 21:31 UTC, labrenz commented
Conflicts should all be resolved now.

2019-10-08 18:19 UTC, vulder requested changes

2019-10-08 18:19 UTC, vulder commented on varats/data/reports/taint_report.py
> +    SHORTHAND = "TAINT"
maybe we should use something more specific here, TAINTPROP or short TP? or maybe `TPR` ?

2019-10-08 18:19 UTC, vulder commented on varats/data/reports/taint_report.py
> +        with open(path, "r") as stream:
why do you open the file as a `stream` but do not use it?

2019-10-08 18:19 UTC, vulder commented on varats/data/reports/taint_report.py
> +                self._path = path
```suggestion
                self.__path = path
```
private vars should have two underscores

2019-10-08 18:19 UTC, vulder commented on varats/data/reports/taint_report.py
> +        return self._path
```suggestion
        return self.__path
```

2019-10-08 18:19 UTC, vulder commented on varats/data/reports/taint_report.py
> +    SHORTHAND = "TAINT"
you used `TPR` later in the `__repr__` impl maybe this is the best solution

2019-10-08 18:19 UTC, vulder commented on varats/data/reports/taint_report.py
> +        return "TPR: " + os.path.basename(self.path)
```suggestion
        return self.SHORTHAND + ": " + os.path.basename(self.path)
```

2019-10-08 18:19 UTC, vulder commented on varats/experiments/taint_propagation.py
> +
```suggestion
```

2019-10-08 18:19 UTC, vulder commented on varats/experiments/taint_propagation.py
> +            analysis_actions.append(FileCheckExpected(project))
Is it really needed to cache the filecheck outputs? Normally only generating the `.bc` files is expensive, reanalyzing a already generated `.bc` file should be cheap in comparison.

2019-10-09 16:55 UTC, labrenz commented on varats/data/reports/taint_report.py
> +        with open(path, "r") as stream:
Resolved in commit 87f44bdb0f23d4317a52197ddc4f6e83ee21949b.

2019-10-09 16:55 UTC, labrenz commented on varats/data/reports/taint_report.py
> +        return self._path
Resolved in commit 87f44bdb0f23d4317a52197ddc4f6e83ee21949b.

2019-10-09 16:55 UTC, labrenz commented on varats/experiments/taint_propagation.py
> +
Resolved in commit 87f44bdb0f23d4317a52197ddc4f6e83ee21949b.

2019-10-09 16:55 UTC, labrenz commented on varats/experiments/taint_propagation.py
> +            analysis_actions.append(FileCheckExpected(project))
Resolved in commit 87f44bdb0f23d4317a52197ddc4f6e83ee21949b.

Removed the txt files from the BC_FILES directory and make use of benchbuilds tmp directory.

2019-10-14 14:38 UTC, labrenz reviewed
Reviewed further changes, applied requested feedback and merged the new vara-dev.

2019-10-29 07:03 UTC, vulder approved these changes
Please fix the two nits otherwise it's fine, I'll merge it afterwards.

2019-10-29 07:03 UTC, vulder commented on varats/data/reports/taint_report.py
> +        return self.SHORTHAND + ":" + os.path.basename(self.path)
```suggestion
        return self.SHORTHAND + ": " + os.path.basename(self.path)
```
I normally find a space after a colon easier to comprehend and copy. If you want it without or if the formatting is necessary, it's fine with me.

2019-10-29 07:03 UTC, vulder commented on varats/experiments/vara_full_mtfa.py
> +
```suggestion
```

2019-11-04 10:11 UTC, merged