Add custom parser and writer for case study
se-passau/VaRA-Tool-Suite pull request #135
Opened 2019-10-08 15:10 UTC by boehmseb

Adds a parser for the case study yaml format, as well as an appropriate writer.
Fixes se-passau/VaRA#484

2019-10-08 15:47 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- tests/paper/test_paper_config_manager.py  1
- tests/paper/test_case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4286043&bid=14616734)

2019-10-08 19:03 UTC, vulder requested changes

2019-10-08 19:03 UTC, vulder commented on varats/paper/case_study.py
> +    def __init__(self,
```suggestion

    def __init__(self,
```

2019-10-08 19:03 UTC, vulder commented on varats/paper/case_study.py
> +                 revisions: tp.List[HashIDTuple] = []) -> None:
```suggestion
                 revisions: tp.Optional[tp.List[HashIDTuple]] = None) -> None:
```
Default parameter in python have reference binding, meaning if you add something to the list in this object other objects will see the same list

2019-10-08 19:03 UTC, vulder commented on varats/paper/case_study.py
> +        self.__revisions: tp.List[HashIDTuple] = revisions
```suggestion
        self.__revisions: tp.List[
            HashIDTuple] = revisions if revisions is not None else []
```
adapted change here, github currently does not allow multi line suggestions :)

2019-10-08 19:03 UTC, vulder commented on varats/paper/case_study.py
> +        if len(revision_list) > 0:
```suggestion
        if revision_list:
```

2019-10-08 19:03 UTC, vulder commented on varats/paper/case_study.py
> +                 stages: tp.List[CSStage] = []) -> None:
same list fix needed here

2019-10-08 19:03 UTC, vulder commented on varats/paper/case_study.py
> +    def get_dict(self) -> tp.Dict[
```suggestion
    def get_dict(
```

2019-10-08 19:03 UTC, vulder commented on varats/paper/case_study.py
> +        str, tp.Union[str, tp.List[tp.Dict[str, tp.Union[str, int]]]]]:
```suggestion
            self
    ) -> tp.Dict[str, tp.Union[str, tp.List[tp.Dict[str, tp.
                                                    Union[str, int]]]]]:
```
line continuation should have more indentation as the prevs line

2019-10-08 19:03 UTC, vulder commented on varats/paper/case_study.py
> +        str, tp.Union[str, tp.List[tp.Dict[str, tp.Union[str, int]]]]]]]]:
same continuation problem, does Intelij use yapf to autoformat this? because my version would look different

2019-10-08 19:03 UTC, vulder commented on varats/paper/case_study.py
> +    def get_dict(self) -> tp.Dict[str, tp.Union[str, int]]:
public methods should have a simple doc string :wink:

2019-10-09 07:22 UTC, boehmseb commented on varats/paper/case_study.py
> +    def __init__(self,
Resolved in 4cd506d

2019-10-09 07:22 UTC, boehmseb commented on varats/paper/case_study.py
> +                 revisions: tp.List[HashIDTuple] = []) -> None:
Resolved in 4cd506d

2019-10-09 07:23 UTC, boehmseb commented on varats/paper/case_study.py
> +        self.__revisions: tp.List[HashIDTuple] = revisions
Resolved in 4cd506d

2019-10-09 07:23 UTC, boehmseb commented on varats/paper/case_study.py
> +                 stages: tp.List[CSStage] = []) -> None:
Resolved in 4cd506d

2019-10-09 07:23 UTC, boehmseb commented on varats/paper/case_study.py
> +    def get_dict(self) -> tp.Dict[
Resolved in 4cd506d

2019-10-09 07:23 UTC, boehmseb commented on varats/paper/case_study.py
> +        str, tp.Union[str, tp.List[tp.Dict[str, tp.Union[str, int]]]]]:
Resolved in 4cd506d

2019-10-09 07:23 UTC, boehmseb commented on varats/paper/case_study.py
> +        str, tp.Union[str, tp.List[tp.Dict[str, tp.Union[str, int]]]]]]]]:
Resolved in 4cd506d

2019-10-09 07:23 UTC, boehmseb commented on varats/paper/case_study.py
> +    def get_dict(self) -> tp.Dict[str, tp.Union[str, int]]:
Resolved in 4cd506d

2019-10-09 07:24 UTC, boehmseb commented on varats/paper/case_study.py
> +        if len(revision_list) > 0:
Resolved in 4cd506d

2019-10-09 07:25 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/paper/test_paper_config_manager.py  1
- tests/paper/test_case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4286043&bid=14616734)

2019-10-09 08:18 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/paper/test_paper_config_manager.py  1
- tests/paper/test_case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4286043&bid=14616734)

2019-10-09 13:27 UTC, vulder approved these changes
lgtm

2019-10-10 12:59 UTC, merged