Adds BlameReport and corresponding experiment.
se-passau/VaRA-Tool-Suite pull request #147
Opened 2019-11-05 21:34 UTC by vulder

2019-11-05 21:36 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  3
- tests/data/test_blame_report.py  3
- varats/experiments/blame_report_experiment.py  3
- varats/experiments/blame_experiment.py  3
         

Clones added
============
- varats/experiments/git_blame_annotation_report.py  4
- varats/experiments/blame_report_experiment.py  3
- varats/experiments/blame_experiment.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4445398&bid=15031319)

2019-11-05 21:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/blame_experiment.py  3
- varats/experiments/blame_report_experiment.py  3
- tests/data/test_blame_report.py  3
- varats/data/reports/blame_report.py  3
         

Clones added
============
- varats/experiments/blame_experiment.py  2
- varats/experiments/blame_report_experiment.py  3
- varats/experiments/git_blame_annotation_report.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4445398&bid=15031319)

2019-11-05 21:57 UTC, vulder commented
the clones will be cleaned up with a separate commit

2019-11-07 16:40 UTC, boehmseb requested changes
A couple of docstrings are broken and therefore hard to understand. Otherwise, this looks fine.

2019-11-07 16:40 UTC, boehmseb commented on tests/data/test_blame_report.py
> +    Test if a blame report is correctly reconstruction from yaml.
typo: reconstructed

2019-11-07 16:40 UTC, boehmseb commented on varats/data/reports/blame_report.py
> +    An interaction of between other commits an a base.
?

2019-11-07 16:40 UTC, boehmseb commented on varats/experiments/blame_report_experiment.py
> +VaRA.
That sentence is broken.

2019-11-08 08:23 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- varats/experiments/blame_experiment.py  3
- tests/data/test_blame_report.py  3
- varats/data/reports/blame_report.py  3
- varats/experiments/blame_report_experiment.py  3
         

Clones added
============
- varats/experiments/blame_experiment.py  2
- varats/experiments/git_blame_annotation_report.py  4
- varats/experiments/blame_report_experiment.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4445398&bid=15031319)

2019-11-08 08:36 UTC, boehmseb approved these changes

2019-11-08 08:48 UTC, merged