Revision range compile functions
se-passau/VaRA-Tool-Suite pull request #149
Opened 2019-11-07 17:09 UTC by boehmseb

This PR's goal is to make more revisions of our case studies compile by specifying different compile functions for different revision ranges. Therefore, it introduces functionality to check whether a commit lies in a specific _revision range_.

This is currently applied to the following case studies (see se-passau/vara-paper-configs#1):
 
- [ ] doxygen
- [ ]  git
- [x]  gravity
- [ ]  gzip
- [ ]  libvpx
- [ ]  lrzip
- [ ]  tmux
- [ ]  vim
- [x]  x264 (partially)
- [x]  xz (partially)

I suggest to wait with merging until this is done for all the listed case studies.

However, this works mostly for changes in the build system but does not cover all cases of failing builds. 
To cover revisions that cannot be compiled at all, I also work on revision blacklisting (see PR TODO).
For case study-specific dependencies, wee need a system for specifying and checking such dependencies, which will also be a different PR (see se-passau/VaRA#448).

2019-11-07 17:10 UTC, boehmseb commented
If somebody is more familiar with a specific case study, feel free to contribute to this PR. The case study `gravity` can be used as a template for how to use revision ranges.

2019-11-07 17:11 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/xz.py  2
- varats/projects/c_projects/x264.py  2
         

Clones added
============
- varats/projects/c_projects/xz.py  1
- varats/projects/c_projects/gravity.py  1
         

Clones removed
==============
+ varats/projects/c_projects/x264.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4460067&bid=15069528)

2019-11-08 10:13 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/xz.py  2
- varats/projects/c_projects/x264.py  2
         

Clones added
============
- varats/projects/c_projects/xz.py  1
- varats/projects/c_projects/gravity.py  1
         

Clones removed
==============
+ varats/projects/c_projects/x264.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4460067&bid=15069528)

2019-11-08 15:28 UTC, vulder requested changes

2019-11-08 15:28 UTC, vulder commented on varats/projects/c_projects/gravity.py
> +            print("CMAKE")
```suggestion
```
Remove debug print

2019-11-08 15:28 UTC, vulder commented on varats/projects/c_projects/gravity.py
> +            print("MAKE")
```suggestion
```
remove debug print

2019-11-08 15:28 UTC, vulder commented on varats/projects/c_projects/xz.py
> +                "5d018dc03549c1ee4958364712fb0c94e1bf2741", "fda4724d8114fccfa31c1839c15479f350c2fb4c")
```suggestion
                "5d018dc03549c1ee4958364712fb0c94e1bf2741",
                "fda4724d8114fccfa31c1839c15479f350c2fb4c")
```

2019-11-08 15:28 UTC, vulder commented on varats/utils/project_util.py
> +def get_all_revisions_between(a: str, b: str) -> tp.List[str]:
```suggestion
def get_all_revisions_between(c_start: str, c_end: str) -> tp.List[str]:
```
var names could be a bit more precise :smile: `c_start` or `start_commit`... etc

2019-11-11 08:07 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/xz.py  2
- varats/projects/c_projects/x264.py  2
         

Clones added
============
- varats/projects/c_projects/xz.py  1
- varats/projects/c_projects/gravity.py  1
         

Clones removed
==============
+ varats/projects/c_projects/x264.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4460067&bid=15069528)

2019-11-12 09:43 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/xz.py  2
- varats/projects/c_projects/x264.py  2
         

Clones added
============
- varats/projects/c_projects/xz.py  1
- varats/projects/c_projects/gravity.py  1
         

Clones removed
==============
+ varats/projects/c_projects/x264.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4460067&bid=15069528)

2019-11-12 10:48 UTC, vulder approved these changes
lgtm

2019-11-12 10:52 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/xz.py  2
- varats/projects/c_projects/x264.py  2
         

Clones added
============
- varats/projects/c_projects/xz.py  2
- varats/projects/c_projects/gravity.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4460067&bid=15069528)

2019-11-12 11:18 UTC, merged