Revision blacklisting
se-passau/VaRA-Tool-Suite pull request #150
Opened 2019-11-08 09:39 UTC by boehmseb

This PR introduces the possibility to mark single revisions or revision ranges of case studies as _blocked_.

Blocked revisions cannot be used sensibly in experiments for some reason (e.g. the revision contains a bug that prevents it from compiling).

As an example to demonstrate how blocked revisions could be handled by other tools of the TS, I added support for blocked revisions to `vara-cs status`.

Blocked revisions are currently applied to the following case studies (see se-passau/vara-paper-configs#1):
 
- [ ] doxygen
- [ ]  git
- [x]  gravity (partially)
- [ ]  gzip
- [ ]  libvpx
- [ ]  lrzip
- [ ]  tmux
- [ ]  vim
- [ ]  x264
- [ ]  xz

For a clean merge, I suggest to wait until #149 is merged as this PR depends on some of its functionality.

2019-11-08 09:41 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Clones removed
==============
+ varats/projects/c_projects/gravity.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4463811&bid=15077903)

2019-11-08 10:16 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 10
           

Clones removed
==============
+ varats/projects/c_projects/gravity.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4463811&bid=15077903)

2019-11-08 15:43 UTC, vulder requested changes
This should be rebased after merging #149

2019-11-08 15:43 UTC, vulder commented on varats/data/report.py
> +                                                FileStatusExtension.Blocked)
```suggestion
                                                 FileStatusExtension.Blocked)
```

2019-11-08 15:43 UTC, vulder commented on varats/projects/c_projects/gravity.py
> +    def __compile_cmake(self):
did you include your other work from PR #149  here too?

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    return result
same #149

2019-11-08 15:43 UTC, vulder commented on varats/projects/c_projects/gravity.py
> +                run(make["-j", int(CFG["jobs"])])
same #149

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    def __init__(self, id: str, reason: tp.Optional[str] = None):
`id` is a python builtin and naming the var like this redefines this builtin

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    def reason(self):
should have a short comment to describe the property

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    def reason(self):
same

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    Delegate for the
for the ???

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    def is_blocked_revision(self, id: str) -> tp.Tuple[bool, tp.Optional[str]]:
missing comment

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    def block_revision(self, id: str, reason: tp.Optional[str] = None) -> None:
missing comment and `id`

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    Implementors must initialize the delegate with a call to
```suggestion
    Implementors must initialize the delegate with a call to
```

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +
```suggestion

```

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    def block_revision(cls, id: str, reason: tp.Optional[str] = None) -> None:
`id`

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +    def is_blocked_revision(cls, id: str) -> tp.Tuple[bool, tp.Optional[str]]:
`id`

2019-11-08 15:43 UTC, vulder commented on varats/utils/project_util.py
> +        BlockedRevisionCheckerDelegate] = None
Isn't this static method overwritten when another project initializes a BRChecker?

2019-11-11 08:03 UTC, boehmseb commented on varats/projects/c_projects/gravity.py
> +    def __compile_cmake(self):
No, but this was in the same commit as the needed `get_all_revisions_between`.

2019-11-11 08:44 UTC, boehmseb commented on varats/utils/project_util.py
> +        BlockedRevisionCheckerDelegate] = None
You are right. I thought that this call would act as if it was called via `super()`, but it does not.
Even worse: this cannot be done at all inside the (sub-) class definition, as the corresponding class object does not even exist at that point.
A decorator might help in this case. I will look into that later.

2019-11-11 12:11 UTC, boehmseb commented
I rewrote the revision blocking code to be a decorator. This is even easier to use, needs less code and resolves the problem stated above.

2019-11-11 12:13 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones removed
==============
+ varats/projects/c_projects/gravity.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4463811&bid=15077903)

2019-11-11 12:18 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones removed
==============
+ varats/projects/c_projects/gravity.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4463811&bid=15077903)

2019-11-11 13:34 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones removed
==============
+ varats/projects/c_projects/gravity.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4463811&bid=15077903)

2019-11-11 13:53 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ varats/projects/c_projects/gravity.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4463811&bid=15077903)

2019-11-11 13:56 UTC, boehmseb commented
The current CI fail is caused by mypy and will be gone after rebasing onto PR #149.

2019-11-12 11:54 UTC, vulder approved these changes
lgtm

2019-11-12 11:58 UTC, merged