Implements new case study qemu
se-passau/VaRA-Tool-Suite pull request #182
Opened 2019-12-05 18:46 UTC by vulder

2019-12-05 18:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/projects/c_projects/qemu.py  3
         

Clones added
============
- varats/projects/c_projects/qemu.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4625012&bid=15506196)

2019-12-06 09:42 UTC, boehmseb requested changes

2019-12-06 09:42 UTC, boehmseb commented on varats/projects/c_projects/qemu.py
> +from varats.utils.project_util import (get_all_revisions_between,
```suggestion
from varats.utils.project_util import wrap_paths_to_binaries
```

2019-12-06 09:42 UTC, boehmseb commented on varats/projects/c_projects/qemu.py
> +                                       wrap_paths_to_binaries, block_revisions,
```suggestion
```

2019-12-06 09:42 UTC, boehmseb commented on varats/projects/c_projects/qemu.py
> +                                       BlockedRevisionRange, BugAndFixPair,
```suggestion
```

2019-12-06 09:42 UTC, boehmseb commented on varats/projects/c_projects/qemu.py
> +                                       BlockedRevision)
```suggestion
```

2019-12-06 09:42 UTC, boehmseb commented on varats/projects/c_projects/qemu.py
> +from benchbuild.utils.cmd import make, cmake, git
```suggestion
from benchbuild.utils.cmd import make, cmake
```

2019-12-12 20:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/qemu.py  3
         

Clones added
============
- varats/projects/c_projects/qemu.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4625012&bid=15506196)

2019-12-17 12:08 UTC, boehmseb approved these changes
lgtm

2019-12-17 12:13 UTC, merged