Adds max/avg distribution plots
se-passau/VaRA-Tool-Suite pull request #183
Opened 2019-12-15 11:06 UTC by vulder

2019-12-15 11:08 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  2
- varats/utils/git_util.py  3
         

Clones added
============
- varats/plots/blame_interaction_degree.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4678130&bid=15650871)

2019-12-15 11:15 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/utils/git_util.py  3
- varats/plots/blame_interaction_degree.py  1
- varats/data/reports/blame_report.py  2
         

Clones added
============
- varats/plots/blame_interaction_degree.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4678130&bid=15650871)

2019-12-15 11:21 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  2
- varats/utils/git_util.py  3
- varats/plots/blame_interaction_degree.py  1
         

Clones added
============
- varats/plots/blame_interaction_degree.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4678130&bid=15650871)

2019-12-18 09:20 UTC, boehmseb requested changes

2019-12-18 09:20 UTC, boehmseb commented on varats/data/reports/blame_report.py
>  from varats.utils.project_util import get_local_project_git
```suggestion
```

2019-12-18 09:20 UTC, boehmseb commented on varats/utils/git_util.py
> +    # Skip 0000 hashes that we added to mark uncommited files
```suggestion
    # Skip 0000 hashes that we added to mark uncommitted files
```

2019-12-23 10:10 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  2
- varats/utils/git_util.py  3
- varats/plots/blame_interaction_degree.py  1
         

Clones added
============
- varats/plots/blame_interaction_degree.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=4678130&bid=15650871)

2019-12-26 23:13 UTC, merged