Calucaltes and plots repository code churn
se-passau/VaRA-Tool-Suite pull request #184
Opened 2019-12-26 23:16 UTC by vulder

2019-12-26 23:18 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/repository_churn.py  6
- varats/utils/git_util.py  8
- varats/plots/blame_interaction_degree.py  3
         

Clones removed
==============
+ varats/plots/blame_interaction_degree.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4736088&bid=15810180)

2020-01-06 09:02 UTC, boehmseb requested changes

2020-01-06 09:02 UTC, boehmseb commented on varats/plots/repository_churn.py
> +        axis.set_yscale('symlog')
I would argue that log-scale is not always the best choice here. Can we make this optional?

2020-01-06 09:02 UTC, boehmseb commented on varats/plots/repository_churn.py
> +    # code_churn = cs_selector(code_churn)
```suggestion
```

2020-01-06 09:02 UTC, boehmseb commented on varats/plots/blame_interaction_degree.py
> +            churn_axis.set_yscale('symlog')
I would argue that log-scale is not always the best choice here. Can we make this optional?

2020-01-06 09:02 UTC, boehmseb commented on varats/plots/blame_interaction_degree.py
> +            # for rev in uniq_revisions[::1]:
```suggestion
```

2020-01-06 09:02 UTC, boehmseb commented on varats/plots/blame_interaction_degree.py
> +            #     main_axis.axvline(rev, color='0.90', linewidth=1)
```suggestion
```

2020-01-06 09:02 UTC, boehmseb commented on varats/plots/blame_interaction_degree.py
> +
```suggestion
```

2020-01-09 10:12 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/repository_churn.py  6
- varats/utils/git_util.py  8
- varats/plots/blame_interaction_degree.py  3
         

Clones removed
==============
+ varats/plots/blame_interaction_degree.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4736088&bid=15810180)

2020-01-09 14:29 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/repository_churn.py  6
- varats/utils/git_util.py  8
- varats/plots/blame_interaction_degree.py  3
         

Clones removed
==============
+ varats/plots/blame_interaction_degree.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4736088&bid=15810180)

2020-01-15 10:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/repository_churn.py  6
- varats/utils/git_util.py  8
- varats/plots/blame_interaction_degree.py  3
         

Clones removed
==============
+ varats/plots/blame_interaction_degree.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4736088&bid=15810180)

2020-01-15 10:36 UTC, boehmseb approved these changes
lgtm

2020-01-15 22:49 UTC, merged