Implements configurable code churn
se-passau/VaRA-Tool-Suite pull request #191
Opened 2020-02-04 13:14 UTC by vulder

The code churn api now allows the user to pass a config object that
specifies which files should be included in the churn calculation.
ChurnConfig provides a default and different generator functions for
often used languages.

resolves se-passau/VaRA#556

2020-02-05 08:59 UTC, boehmseb requested changes

2020-02-05 08:59 UTC, boehmseb commented on varats/utils/git_util.py
> +        Checks if all file extensions are valid.
That's not what this method does

2020-02-05 08:59 UTC, boehmseb commented on varats/plots/blame_lorenz_curve.py
> +            repo, ChurnConfig.create_c_style_languages_config())
Maybe add a `TODO: refactor into plot config` or similar?

2020-02-05 08:59 UTC, boehmseb commented on varats/plots/repository_churn.py
> +    # By default we only look at c-style code files
Maybe add a `TODO: refactor into plot config` or similar?

2020-02-05 10:19 UTC, vulder commented on varats/utils/git_util.py
> +        Checks if all file extensions are valid.
why not? If no specific lang. is selected all file extensions are valid.

2020-02-05 10:24 UTC, vulder commented on varats/plots/blame_lorenz_curve.py
> +            repo, ChurnConfig.create_c_style_languages_config())
the plot config was more meant to allow matplotlib config stuff
if a plot directly wants configurability, so the user can customize it, I used the extend parser functions
But depending on how we design the plot config and how we relate this to the artifacts it could help to allow further configuration for specific plots. This would require to somehow extend the plot config with plot specific stuff

2020-02-05 15:14 UTC, boehmseb commented on varats/plots/blame_lorenz_curve.py
> +            repo, ChurnConfig.create_c_style_languages_config())
So how would you configure this instead? If you just hard code the language and leave it that way, you don't need the ChurnConfig at all.

2020-02-05 15:14 UTC, boehmseb commented on varats/utils/git_util.py
> +        Checks if all file extensions are valid.
Oh, I see you can also understand it that way.
I would rather write something like this to avoid misunderstandings: `Checks if all files should be considered in the code churn.`

2020-02-06 08:43 UTC, vulder commented on varats/plots/blame_lorenz_curve.py
> +            repo, ChurnConfig.create_c_style_languages_config())
My first idea was in the direction of using sub classes of the plot, RepoChurnFull, RepoChurnCStyle etc. but I guess putting it into one plot config, which is the customized via this is  a better abstraction.

2020-02-06 08:43 UTC, vulder commented on varats/utils/git_util.py
> +        Checks if all file extensions are valid.
kk

2020-02-06 13:21 UTC, vulder commented on varats/utils/git_util.py
> +        Checks if all file extensions are valid.
```suggestion
        Checks if all files should be considered in the code churn.
```

2020-02-06 13:23 UTC, boehmseb approved these changes

2020-02-06 13:24 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- tests/utils/test_git_util.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4942192&bid=16338107)

2020-02-06 13:37 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/utils/test_git_util.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4942192&bid=16338107)

2020-02-06 13:39 UTC, merged