Adds plot auto-detection.
se-passau/VaRA-Tool-Suite pull request #192
Opened 2020-02-06 13:11 UTC by boehmseb

Adds an automtated plot registry (similar to project registry) so creating a new plot no longer involves manually creating an entry in the list of available plots.

resolves se-passau/VaRA#549

2020-02-06 13:13 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4957273&bid=16381693)

2020-02-06 13:23 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4957273&bid=16381693)

2020-02-06 13:31 UTC, vulder requested changes
could you please also check if we can fix the naming problem in the help string for vara-plots with the new metaclass.
At the moment, vara-plot prints strange strings als options for the plot type. Can we use the new NAME attr there?

2020-02-06 13:31 UTC, vulder commented on varats/paper/case_study.py
> +    new_revisions = set([
```suggestion
    new_revisions = {
```

2020-02-06 13:31 UTC, vulder commented on varats/paper/case_study.py
> +    ])
```suggestion
    }
```

2020-02-06 13:31 UTC, vulder commented on varats/paper/case_study.py
> +    new_revisions = set([
using python set comprehension

2020-02-06 13:31 UTC, vulder commented on varats/plots/plots.py
> +    from varats.plots.plot import Plot
that's nice, did not know that :D

2020-02-06 13:40 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4957273&bid=16381693)

2020-02-06 14:10 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/plots/plots.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4957273&bid=16381693)

2020-02-06 14:16 UTC, boehmseb commented
> could you please also check if we can fix the naming problem in the help string for vara-plots with the new metaclass.
> At the moment, vara-plot prints strange strings als options for the plot type. Can we use the new NAME attr there?

See my latest commit.

2020-02-10 21:35 UTC, vulder commented
> > could you please also check if we can fix the naming problem in the help string for vara-plots with the new metaclass.
> > At the moment, vara-plot prints strange strings als options for the plot type. Can we use the new NAME attr there?
> 
> See my latest commit.
This only shows if the user types it wrong, is there a way to show the list of all plots in the `--help` menu of `vara-plot`? In the old version this only printed a list of enumish like things but no clear plot names.

2020-02-10 21:36 UTC, vulder requested changes
looks good except for the `--help` issue, do you think we can add this?

If not we can also merge it this way

2020-02-11 07:33 UTC, boehmseb commented
Should be possible. I can look into it later today.

2020-02-12 08:34 UTC, boehmseb commented
This commit adds a listing of available plot types to the output of `vara-plot -h`.

2020-02-12 08:35 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4957273&bid=16381693)

2020-02-12 08:41 UTC, vulder approved these changes
nice, this looks good now :smile:

2020-02-12 08:53 UTC, merged