Refactor overview plot
se-passau/VaRA-Tool-Suite pull request #193
Opened 2020-02-12 08:56 UTC by boehmseb

Refactors the `paper_config_overview_plot` also show blocked revisions.

2020-02-12 08:58 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/paper_config_overview.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4989833&bid=16473660)

2020-02-12 09:00 UTC, boehmseb commented
Do we need a legend or some additional explanation for the labels in the heatmap?
Also I would have liked to have three colors (success, blocked, fail as in `vara-cs status`) and use [barycentric coordinates](https://en.wikipedia.org/wiki/Barycentric_coordinate_system) to assign an appropriate color, but it seems that this is not easily possible using a heatmap.

2020-02-12 09:09 UTC, vulder requested changes

2020-02-12 09:09 UTC, vulder commented on varats/plots/paper_config_overview.py
> +                                             revs_total)
Can this be made easier using f-strings?

2020-02-12 09:13 UTC, vulder commented
> Do we need a legend or some additional explanation for the labels in the heatmap?
> Also I would have liked to have three colors (success, blocked, fail as in `vara-cs status`) and use [barycentric coordinates](https://en.wikipedia.org/wiki/Barycentric_coordinate_system) to assign an appropriate color, but it seems that this is not easily possible using a heatmap.

1) legend would be nice, I guess, especially, when we add more different colors/status
2) do you have an idea how to solves this? Not 100% used to the barycentri coord thing but what I read makes sense for this case

2020-02-12 09:16 UTC, boehmseb commented on varats/plots/paper_config_overview.py
> +                                             revs_total)
Aparrently yes.

2020-02-12 09:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/paper_config_overview.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4989833&bid=16473660)

2020-02-12 09:22 UTC, boehmseb commented
> > Do we need a legend or some additional explanation for the labels in the heatmap?
> > Also I would have liked to have three colors (success, blocked, fail as in `vara-cs status`) and use [barycentric coordinates](https://en.wikipedia.org/wiki/Barycentric_coordinate_system) to assign an appropriate color, but it seems that this is not easily possible using a heatmap.
> 
>     1. legend would be nice, I guess, especially, when we add more different colors/status
I will try to add one.
> 
>     2. do you have an idea how to solves this? Not 100% used to the barycentri coord thing but what I read makes sense for this case
The problem is that the heatmap plot only allows to specify a colormap. My approach requires to map entries in the heatmap to arbitrarty colors. With my current knowledge about seaborn/matplotlib I believe that one would have to custom-build a plot (or at least heavily customize the heatmap).

2020-02-12 16:52 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/paper_config_overview.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4989833&bid=16473660)

2020-02-12 16:55 UTC, boehmseb commented
Now with correct colors and legend.

2020-02-12 16:56 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/paper_config_overview.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4989833&bid=16473660)

2020-02-13 10:54 UTC, vulder requested changes
Found some small things but, otherwise, this looks quite nice now :smiley:

2020-02-13 10:54 UTC, vulder commented on varats/plots/paper_config_overview.py
> +                    if success == FileStatusExtension.Success)
Would this look nicer if we used list len + comprehension?
I think this should be easier to understand what this code whats to compute.

2020-02-13 10:54 UTC, vulder commented on varats/plots/paper_config_overview.py
> +                    if success == FileStatusExtension.Blocked)
same

2020-02-13 10:54 UTC, vulder commented on varats/plots/paper_config_overview.py
> +        i + 0.5 if t > 0 else np.nan for i, t in enumerate(revs_total.flatten())
as I understand this you want to just round up the value?
In that case using math.ceil would make this more clear

2020-02-13 10:54 UTC, vulder commented on varats/plots/paper_config_overview.py
>      dpi = 1200
If we need to compute based on dpi we should use the value that is specified in the default plot save function, otherwise, these will diverge.
You can refactor dpi from `plot.save()` into the plot_config and use the value in the computation

2020-02-13 11:20 UTC, boehmseb commented on varats/plots/paper_config_overview.py
> +        i + 0.5 if t > 0 else np.nan for i, t in enumerate(revs_total.flatten())
No. I have a colormap with color ranges `[i * delta, (i+1) * delta]`with `delta = 1/len(data)` and I need element `i` to lie inside that range. There is no rounding involved.
Without the `+0.5`, `i` would always be mapped to `i * delta` and sometimes, it happened that the previous color was chosen instead of the correct one. The `+0.5` shifts that value to the middle of the range so this should completely eliminate the issue.

2020-02-13 11:24 UTC, boehmseb commented on varats/plots/paper_config_overview.py
>      dpi = 1200
Can we dispose this until I tackle se-passau/VaRA#545? I see no immediate benefit in fixing this now and I will address that issue in the new future anyway.
In the meanwhile, a TODO should be enough.

2020-02-13 11:28 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/paper_config_overview.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4989833&bid=16473660)

2020-02-13 12:33 UTC, vulder commented on varats/plots/paper_config_overview.py
>      dpi = 1200
TODO is fine

2020-02-13 12:36 UTC, vulder commented on varats/plots/paper_config_overview.py
> +        i + 0.5 if t > 0 else np.nan for i, t in enumerate(revs_total.flatten())
ok

2020-02-13 13:08 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/paper_config_overview.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4989833&bid=16473660)

2020-02-13 13:22 UTC, vulder commented on varats/plots/paper_config_overview.py
> +    #TODO: refactor dpi into plot_config. see se-passau/VaRA#545.
```suggestion
    #TODO (se-passau/VaRA#545): refactor dpi into plot_config. see.
```

2020-02-13 13:23 UTC, vulder approved these changes

2020-02-13 13:24 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/paper_config_overview.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4989833&bid=16473660)

2020-02-13 13:26 UTC, vulder commented on varats/plots/paper_config_overview.py
> +        # TODO: refactor dpi into plot_config. see se-passau/VaRA#545.
```suggestion
        # TODO (se-passau/VaRA#545): refactor dpi into plot_config. see.
```

2020-02-13 13:28 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/paper_config_overview.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=4989833&bid=16473660)

2020-02-13 13:31 UTC, merged