Introduces Artefacts to Paper Configs
se-passau/VaRA-Tool-Suite pull request #199
Opened 2020-02-19 13:04 UTC by boehmseb

This PR inttroduces artefacts to the tool suite.
This allows to attach artefact definitions to a paper config.
This way, the artefacts, like plots or result tables,
can be generated from result files automatically.

Typically, a paper config has a file `artefacts.yaml` that manages artefact definitions.
The new command `vara-art` allows to manage artefact definitions and generate the artefacts from the definitions.

2020-02-19 13:07 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/paper/paper_config.py  1
- varats/utils/yaml_util.py  3
- varats/tools/driver_artefacts.py  9
- varats/paper/artefacts.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-20 10:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/tools/driver_artefacts.py  9
- varats/utils/yaml_util.py  3
- varats/plots/plot.py  1
- varats/paper/paper_config.py  1
- tests/paper/test_artefacts.py  2
- varats/paper/artefacts.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-20 11:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- tests/paper/test_artefacts.py  2
- varats/tools/driver_artefacts.py  9
- varats/paper/artefacts.py  3
- varats/utils/yaml_util.py  3
- varats/paper/paper_config.py  1
- varats/plots/plot.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-20 14:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- tests/paper/test_artefacts.py  2
- varats/utils/yaml_util.py  3
- varats/tools/driver_artefacts.py  8
- varats/plots/plot.py  1
- varats/paper/artefacts.py  3
- varats/paper/paper_config.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-20 15:16 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- tests/paper/test_artefacts.py  2
- varats/paper/artefacts.py  3
- varats/utils/yaml_util.py  3
- varats/tools/driver_artefacts.py  8
- varats/plots/plot.py  1
- varats/paper/paper_config.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-21 13:31 UTC, vulder requested changes
found a few things and two questions :laughing: 
otherwise, this design looks good :+1:

2020-02-21 13:31 UTC, vulder commented on docs/source/vara-ts-api/paper.rst
>  ----------------------------
Can you add a small section above, below the paper config part, to describe the purpose of artefacts and how they should be use.

2020-02-21 13:31 UTC, vulder commented on docs/source/vara-ts-api/tools.rst
> +Note the double qoutes around the artefact name. They are only needed if the
if you like you can also use
```
.. note::
```
to make an actual note that gets render differently

2020-02-21 13:31 UTC, vulder commented on varats/paper/artefacts.py
> +        Returns: A dict representation of this artefact.
I have put my return desc always in the next line, it this the "right" way to do it?
We should all use the same style.

2020-02-21 13:31 UTC, vulder commented on varats/paper/artefacts.py
> +        """
```suggestion
        r"""
```
https://www.flake8rules.com/rules/W605.html
some python stuff because of escapes

2020-02-21 13:31 UTC, vulder commented on varats/paper/artefacts.py
> +    """
```suggestion
    r"""
```
same as below

2020-02-21 13:31 UTC, vulder commented on varats/paper/case_study.py
> +        __store_case_study_to_file(case_study, case_study_location / file_name)
would this be easier to just call:
```
if case_study_location.suffix != '.case_study':
    file_name = "{project_name}_{version}.case_study".format(
            project_name=case_study.project_name, version=case_study.version)
    case_study_location /= file_name

__store_case_study_to_file(case_study, case_study_location) 
```

2020-02-21 13:31 UTC, vulder commented on varats/paper/paper_config.py
> +        Args: The case study to add.
```suggestion
        Args:
            case_study: the case study to add.
```

2020-02-21 13:31 UTC, vulder commented on varats/paper/paper_config.py
> +            artefact: The artefact to add.
```suggestion
            artefact: the artefact to add
```
???
I don't write full sentences for the param desc, I normally even try to reuse the param name in a quick desc
Do you think it is necessary to write full sentences here?

2020-02-24 08:17 UTC, boehmseb commented on varats/paper/paper_config.py
> +            artefact: The artefact to add.
Mostly personal preference I guess.
However, if you look at this [example](https://vara.readthedocs.io/en/vara-dev/vara-ts-api/paper.html#varats.paper.case_study.generate_case_study), I find it better readable if the description does not reuse the parameter name.

2020-02-24 08:21 UTC, boehmseb commented on varats/paper/artefacts.py
> +        Returns: A dict representation of this artefact.
I don't know if there is a "right" way to do it. But I agree, we should use the same formatting. Then, i guess,  starting in the next line makes more sense, as this leaves more space for longer return value descriptions.

2020-02-24 08:25 UTC, boehmseb commented
I'll address your other suggestions later today.

2020-02-24 08:26 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/plots/plot.py  1
- varats/paper/artefacts.py  3
- tests/paper/test_artefacts.py  2
- varats/paper/paper_config.py  1
- varats/tools/driver_artefacts.py  8
- varats/utils/yaml_util.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-24 11:42 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/plots/plot.py  1
- varats/paper/paper_config.py  1
- tests/paper/test_artefacts.py  2
- varats/utils/yaml_util.py  3
- varats/tools/driver_artefacts.py  8
- varats/paper/artefacts.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-24 13:05 UTC, vulder commented on varats/paper/case_study.py
> +        __store_case_study_to_file(case_study, case_study_location / file_name)
:+1:

2020-02-24 13:08 UTC, vulder commented on varats/paper/artefacts.py
> +        Returns: A dict representation of this artefact.
ok, next line it is :)

2020-02-24 13:11 UTC, vulder approved these changes
lgtm

2020-02-24 13:11 UTC, vulder commented on varats/paper/artefacts.py
> +        Returns:
```suggestion
        Returns:
```

2020-02-24 13:13 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/tools/driver_artefacts.py  8
- varats/paper/artefacts.py  3
- varats/plots/plot.py  1
- varats/utils/yaml_util.py  3
- tests/paper/test_artefacts.py  2
- varats/paper/paper_config.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-24 13:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/driver_artefacts.py  8
- varats/paper/artefacts.py  3
- varats/plots/plot.py  1
- varats/utils/yaml_util.py  3
- varats/paper/paper_config.py  1
- tests/paper/test_artefacts.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-24 13:21 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/plot.py  1
- varats/utils/yaml_util.py  3
- varats/tools/driver_artefacts.py  8
- varats/paper/artefacts.py  3
- tests/paper/test_artefacts.py  2
- varats/paper/paper_config.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-24 13:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/paper/test_artefacts.py  2
- varats/paper/paper_config.py  1
- varats/tools/driver_artefacts.py  8
- varats/plots/plot.py  1
- varats/utils/yaml_util.py  3
- varats/paper/artefacts.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-24 15:09 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/driver_artefacts.py  8
- varats/paper/artefacts.py  3
- tests/paper/test_artefacts.py  2
- varats/plots/plot.py  1
- varats/utils/yaml_util.py  3
- varats/paper/paper_config.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-24 15:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/utils/yaml_util.py  3
- varats/plots/plot.py  1
- varats/paper/artefacts.py  3
- varats/tools/driver_artefacts.py  8
- varats/paper/paper_config.py  1
- tests/paper/test_artefacts.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VaRA/VaRA-Tool-Suite/pullRequest?prid=5032392&bid=16579850)

2020-02-24 15:44 UTC, merged