Polished the docs for paper configs
se-passau/VaRA-Tool-Suite pull request #202
Opened 2020-02-21 09:18 UTC by vulder

resolves se-passau/VaRA#573

2020-02-21 10:30 UTC, boehmseb requested changes

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +Whenever we desing experiments that look at specific revision of a project, we run into the problem that to reevaluate our experiment data we need to preserve the set of revision.
```suggestion
Whenever we desing experiments that look at specific revisions of a project, we run into the problem that to re-evaluate our experiment data, we need to preserve the set of revisions.
```

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +Exactly for this problem the tool suite provides case studies, to preserve the information about which revision of a project was analyzed.
```suggestion
Exactly for this problem, the tool suite provides case studies that preserve the information about which revision of a project was analyzed.
```

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +In addition, to fully preserve also the set of project that were analyzed we designed paper configs, as a collection of different case studies.
```suggestion
In addition, to fully preserve also the set of projects that were analyzed, we designed paper configs as a collection of different case studies.
```

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +Furthermore, we can use paper configs and case studies not only to reevaluate our own experiment but we also allow others to reproduce our data or design their own experiment, based on our project an
```suggestion
Furthermore, we can use paper configs and case studies not only to re-evaluate our own experiment, but we also allow others to reproduce our data or design their own experiment based on our project and revision selection.
```

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +Take, for example, the case where one wants to analyze different projects, gzip and git, for the evaluation of a paper that get's submitted to `ase-17`.
```suggestion
Take, for example, the case where one wants to analyze the projects, gzip and git, for the evaluation of a paper that get's submitted to `ase-17`.
```

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +First, one creates different case studies for each project, selecting the different revision that should be analyzed.
```suggestion
First, one creates different case studies for each project selecting the different revisions that should be analyzed.
```

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +Second, all case studies related to the evaluation for `ase-17` are grouped into a folded -- the paper config -- to related them to the paper.
```suggestion
Second, all case studies related to the evaluation for `ase-17` are grouped into a folder -- the paper config -- to relate them to the paper.
```

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +Next, we can now desgin and run our experiment for `ase-17` on all revisions added through case studies in the paper config and generate our experiment results.
```suggestion
Now we can design and run our experiment for `ase-17` on all revisions added through case studies in the paper config and generate our experiment results.
```
Or: Next, we can design

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +Furthermore, this is also helpfull for other researchers that are now able to reproduce our results.
```suggestion
This is also helpfull for other researchers that are now able to reproduce our results.
```

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +For example, a setup could look like::
```suggestion
For example, a setup could look like this::
```

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +If we now want to evaluate our set for ``icse-18`` we set the paper-config folder to the root of our config tree and select the ``icse-18`` folder as our current config, like this::
Maybe add a note that this has to be set in `.vara.yaml`

2020-02-21 10:30 UTC, boehmseb commented on docs/source/vara-ts-api/paper.rst
> +The current status of all case study, belonging to the current paper config, can be visualized with :ref:`vara-cs status`::
```suggestion
The current status of all case studies belonging to the current paper config, can be visualized with :ref:`vara-cs status`::
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +project, where each encaspulate a fixed set of revision to evaluate. This
```suggestion
project, where each encaspulates a fixed set of revision to evaluate. This
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +allows users to specify which revisions of what project have been analyzed.
```suggestion
allows users to specify which revisions of what project have to be analyzed.
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +    Paper config, a specify set of case studies, e.g.,  for a publication.
Not quite sure how I would fix this sentence :wink:

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +        Return case study specific revision filter. If a one case study
```suggestion
        Return a case study specific revision filter. If one case study
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +        includes a revision it the filter function will return ``True``.
```suggestion
        includes a revision the filter function will return ``True``.
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +        This can be used to automatically filter out revision that are not
```suggestion
        This can be used to automatically filter out revisions that are not
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +        Persist the current state of the paper config, saving all case studies
```suggestion
        Persist the current state of the paper config saving all case studies
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +        current active paper config
```suggestion
        currently active paper config
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +    Loads a paper config from yaml file, initializes the paper config and sets
```suggestion
    Loads a paper config from a yaml file, initializes the paper config and sets
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +    it to the current active paper config. If no config path is provided, the
```suggestion
    it to the currently active paper config. If no config path is provided, the
```

2020-02-21 10:30 UTC, boehmseb commented on varats/paper/paper_config.py
> +        current paper config
```suggestion
        currently active paper config
```

2020-02-21 12:58 UTC, vulder commented on docs/source/vara-ts-api/paper.rst
> +Furthermore, this is also helpfull for other researchers that are now able to reproduce our results.
I'd like to keed the furthermore to make it clear that this is a completely different use case that the one we talked about before.

2020-02-21 12:59 UTC, vulder commented on docs/source/vara-ts-api/paper.rst
> +If we now want to evaluate our set for ``icse-18`` we set the paper-config folder to the root of our config tree and select the ``icse-18`` folder as our current config, like this::
```suggestion
If we now want to evaluate our set for ``icse-18`` we set the paper-config folder to the root of our config tree and select the ``icse-18`` folder as our current config in the settings file ``.vara.yaml``, like this::
```

2020-02-21 13:00 UTC, vulder commented on varats/paper/paper_config.py
> +    Paper config, a specify set of case studies, e.g.,  for a publication.
```suggestion
    Paper config, a specific set of case studies, e.g.,  for a publication.
```

2020-02-24 08:10 UTC, boehmseb approved these changes
lgtm

2020-02-24 08:16 UTC, merged