Adding CVE/CWE utilities
se-passau/VaRA-Tool-Suite pull request #213
Opened 2020-03-06 13:40 UTC by MarcJose

2020-03-19 10:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 68
           

Complexity increasing per file
==============================
- varats/utils/security_util.py  8
- varats/tools/driver_security.py  3
- varats/security.py  5
- tests/utils/test_security.py  3
- varats/tools/security_map.py  14
         

Clones added
============
- varats/tools/security_map.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-19 10:45 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 22
           

Complexity increasing per file
==============================
- tests/utils/test_security.py  3
- varats/tools/driver_security.py  3
- varats/tools/security_map.py  14
- varats/utils/security_util.py  8
- varats/security.py  5
         

Clones added
============
- varats/tools/security_map.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-23 12:52 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 10
           

Complexity increasing per file
==============================
- varats/tools/driver_cve.py  3
- varats/data/provider/cve/cve.py  8
- varats/data/provider/provider.py  2
- varats/data/provider/cve/cve_provider.py  5
- varats/data/provider/cve/cve_map.py  14
- tests/data/test_cve.py  3
         

Clones added
============
- varats/data/provider/cve/cve_map.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-25 11:50 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 15
           

Complexity increasing per file
==============================
- varats/plots/cve_annotation.py  8
- varats/utils/git_util.py  1
- tests/data/test_cve.py  3
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/provider.py  2
- varats/data/provider/cve/cve_map.py  14
- varats/tools/driver_cve.py  3
- varats/data/provider/cve/cve_provider.py  5
- varats/data/provider/cve/cve.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-25 14:59 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 10
           

Complexity increasing per file
==============================
- varats/plots/cve_annotation.py  8
- varats/data/provider/cve/cve_map.py  14
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/cve/cve.py  8
- tests/data/test_cve.py  3
- varats/data/provider/cve/cve_provider.py  5
- varats/tools/driver_cve.py  3
- varats/utils/git_util.py  1
- varats/data/provider/provider.py  2
         

Clones added
============
- varats/projects/c_projects/lrzip.py  1
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/opus.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/tmux.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/openssl.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-25 15:12 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 10
           

Complexity increasing per file
==============================
- varats/plots/cve_annotation.py  8
- varats/tools/driver_cve.py  3
- varats/data/provider/cve/cve_provider.py  5
- varats/plots/blame_interaction_degree.py  2
- tests/data/test_cve.py  3
- varats/data/provider/cve/cve_map.py  14
- varats/utils/git_util.py  1
- varats/data/provider/provider.py  2
- varats/data/provider/cve/cve.py  8
         

Clones added
============
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/tmux.py  3
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/opus.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-25 15:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- varats/plots/cve_annotation.py  8
- varats/data/provider/cve/cve_map.py  14
- varats/utils/git_util.py  1
- varats/data/provider/provider.py  2
- varats/plots/blame_interaction_degree.py  2
- tests/data/test_cve.py  3
- varats/data/provider/cve/cve_provider.py  5
- varats/data/provider/cve/cve.py  8
- varats/tools/driver_cve.py  3
         

Clones added
============
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/git.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-25 15:35 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- varats/tools/driver_cve.py  3
- varats/utils/git_util.py  1
- varats/data/provider/cve/cve.py  8
- varats/data/provider/cve/cve_provider.py  5
- varats/data/provider/cve/cve_map.py  14
- varats/plots/blame_interaction_degree.py  2
- tests/data/test_cve.py  3
- varats/data/provider/provider.py  2
- varats/plots/cve_annotation.py  8
         

Clones added
============
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/glibc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-25 15:52 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- varats/plots/cve_annotation.py  8
- varats/tools/driver_cve.py  3
- varats/utils/git_util.py  1
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/cve/cve_map.py  14
- varats/data/provider/cve/cve.py  8
- varats/data/provider/cve/cve_provider.py  5
- varats/data/provider/provider.py  2
- tests/data/test_cve.py  3
         

Clones added
============
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/libvpx.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-25 15:55 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- tests/data/test_cve.py  3
- varats/data/provider/provider.py  2
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/cve/cve.py  8
- varats/data/provider/cve/cve_map.py  14
- varats/plots/cve_annotation.py  8
- varats/utils/git_util.py  1
- varats/tools/driver_cve.py  3
- varats/data/provider/cve/cve_provider.py  5
         

Clones added
============
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/libvpx.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-26 10:09 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- varats/plots/cve_annotation.py  8
- tests/data/test_cve.py  3
- varats/data/provider/provider.py  2
- varats/utils/git_util.py  1
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/cve/cve_map.py  14
- varats/tools/driver_cve.py  3
- varats/data/provider/cve/cve.py  8
- varats/data/provider/cve/cve_provider.py  5
         

Clones added
============
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/glibc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-27 15:25 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/cve/cve_provider.py  5
- varats/data/provider/cve/cve_map.py  14
- tests/data/test_cve.py  3
- varats/utils/git_util.py  1
- varats/tools/driver_cve.py  3
- varats/plots/cve_annotation.py  8
- varats/data/provider/cve/cve.py  8
- varats/data/provider/provider.py  2
         

Clones added
============
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/lrzip.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-27 15:38 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/provider/provider.py  2
- varats/data/provider/cve/cve.py  8
- varats/tools/driver_cve.py  3
- varats/utils/git_util.py  1
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/cve/cve_provider.py  5
- tests/data/test_cve.py  3
- varats/data/provider/cve/cve_map.py  14
- varats/plots/cve_annotation.py  8
         

Clones added
============
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/git.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-27 15:57 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/provider/provider.py  2
- varats/plots/blame_interaction_degree.py  2
- tests/data/test_cve.py  3
- varats/data/provider/cve/cve_provider.py  5
- varats/tools/driver_cve.py  3
- varats/data/provider/cve/cve_map.py  14
- varats/plots/cve_annotation.py  8
- varats/utils/git_util.py  1
- varats/data/provider/cve/cve.py  8
         

Clones added
============
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/git.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-27 16:23 UTC, vulder requested changes

2020-03-27 16:23 UTC, vulder commented on docs/source/vara-ts-api/data_providers/cve_provider.rst
> +    :show-inheritance:
should we add the other cve related modules/classes to this docs? It's kind hard to work with CVEs without docs but on the otherside I would not create special pages for everything

2020-03-27 16:23 UTC, vulder commented on varats/data/provider/cve/cve_map.py
> +        commits: a list of commits
```suggestion
        commits: a list of commits in textual form
```
as I understand it, commit means the full commit as a text?
should we also rename the arg name?

2020-03-27 16:23 UTC, vulder commented on varats/data/provider/cve/cve_map.py
> +        commits: a list of commits
same as above

2020-03-27 16:23 UTC, vulder commented on varats/data/provider/cve/cve_map.py
> +        commits: a list of commits
same

2020-03-27 16:23 UTC, vulder commented on varats/data/provider/cve/cve_map.py
> +
`Args: ` missing, this should be a list of commit_hash cve mapping results, if I'm correct^^

2020-03-27 16:23 UTC, vulder commented on varats/projects/c_projects/gzip.py
> +        return [("gzip", "gzip"), ("gnu", "gzip")]
I think you mentioned to me that if one adds multiple vendor/product tuples they are all merged together, a I right?

2020-03-27 16:23 UTC, vulder commented on varats/projects/c_projects/x264.py
>      GROUP = 'c_projects'
there are no cves for x264?

2020-03-27 16:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/blame_interaction_degree.py  2
- tests/data/test_cve.py  3
- varats/data/provider/cve/cve_provider.py  5
- varats/utils/git_util.py  1
- varats/plots/cve_annotation.py  8
- varats/data/provider/cve/cve.py  8
- varats/tools/driver_cve.py  3
- varats/data/provider/cve/cve_map.py  14
- varats/data/provider/provider.py  2
         

Clones added
============
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/glibc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-30 06:53 UTC, boehmseb commented on varats/projects/c_projects/gzip.py
> +        return [("gzip", "gzip"), ("gnu", "gzip")]
Yes, that's correct

2020-03-30 06:54 UTC, boehmseb commented on varats/projects/c_projects/x264.py
>      GROUP = 'c_projects'
I could not find any.

2020-03-30 07:06 UTC, boehmseb commented on docs/source/vara-ts-api/data_providers/cve_provider.rst
> +    :show-inheritance:
see 815ee35

2020-03-30 07:07 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/blame_interaction_degree.py  2
- varats/utils/git_util.py  1
- varats/data/provider/cve/cve.py  8
- varats/tools/driver_cve.py  3
- varats/data/provider/cve/cve_provider.py  5
- tests/data/test_cve.py  3
- varats/data/provider/provider.py  2
- varats/data/provider/cve/cve_map.py  14
- varats/plots/cve_annotation.py  8
         

Clones added
============
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/libvpx.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-30 11:52 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- tests/data/test_cve.py  3
- varats/data/provider/provider.py  2
- varats/data/provider/cve/cve.py  8
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/cve/cve_map.py  14
- varats/utils/git_util.py  1
- varats/data/provider/cve/cve_provider.py  5
- varats/tools/driver_cve.py  3
- varats/plots/cve_annotation.py  8
         

Clones added
============
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/openssl.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-30 12:30 UTC, vulder approved these changes
lgtm

2020-03-30 12:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/tools/driver_cve.py  3
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/provider.py  2
- tests/data/test_cve.py  3
- varats/data/provider/cve/cve_provider.py  5
- varats/data/provider/cve/cve_map.py  14
- varats/utils/git_util.py  1
- varats/plots/cve_annotation.py  8
- varats/data/provider/cve/cve.py  8
         

Clones added
============
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/opus.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-30 13:29 UTC, vulder commented on varats/data/provider/cve/cve_map.py
```suggestion

```
you should remove all trailing whitespace :wink:

2020-03-30 15:46 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/provider/cve/cve_map.py  14
- varats/utils/git_util.py  1
- varats/plots/blame_interaction_degree.py  2
- varats/data/provider/cve/cve_provider.py  5
- varats/tools/driver_cve.py  3
- varats/plots/cve_annotation.py  8
- varats/data/provider/provider.py  2
- varats/data/provider/cve/cve.py  8
- tests/data/test_cve.py  3
         

Clones added
============
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/openssl.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-30 16:01 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/cve_annotation.py  8
- varats/data/provider/cve/cve_map.py  14
- tests/data/test_cve.py  3
- varats/data/provider/provider.py  2
- varats/utils/git_util.py  1
- varats/data/provider/cve/cve.py  8
- varats/data/provider/cve/cve_provider.py  5
- varats/plots/blame_interaction_degree.py  2
- varats/tools/driver_cve.py  3
         

Clones added
============
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/git.py  1
- varats/projects/c_projects/vim.py  1
- varats/projects/c_projects/lrzip.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5174691&bid=16985828)

2020-03-30 16:25 UTC, merged