Rework VaRA-TS buildsetup infrastructure
se-passau/VaRA-Tool-Suite pull request #235
Opened 2020-03-19 14:20 UTC by vulder

Refactors the build infrastructure of VaRA-TS to support multiple research tools for initializing and building.

2020-03-19 15:58 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 10
           

Complexity increasing per file
==============================
- varats/tools/driver_build_setup.py  4
- varats/tools/research_tools/vara.py  7
- varats/utils/filesystem_util.py  1
- varats/tools/research_tools/research_tool.py  3
         

Clones added
============
- varats/vara_manager.py  1
- varats/tools/research_tools/research_tool.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5210406&bid=17086041)

2020-03-19 16:08 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 10
           

Complexity increasing per file
==============================
- varats/tools/research_tools/research_tool.py  3
- varats/tools/driver_build_setup.py  4
- varats/utils/filesystem_util.py  1
- varats/tools/research_tools/vara.py  7
         

Clones added
============
- varats/tools/research_tools/research_tool.py  1
- varats/vara_manager.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5210406&bid=17086041)

2020-03-20 07:56 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 10
           

Complexity increasing per file
==============================
- varats/utils/filesystem_util.py  1
- varats/tools/research_tools/research_tool.py  3
- varats/tools/research_tools/vara.py  7
- varats/tools/driver_build_setup.py  5
         

Clones added
============
- varats/tools/research_tools/research_tool.py  1
- varats/vara_manager.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5210406&bid=17086041)

2020-03-20 08:46 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/tools/research_tools/vara.py  7
- varats/utils/filesystem_util.py  1
- varats/tools/research_tools/research_tool.py  3
- varats/tools/driver_build_setup.py  5
         

Clones added
============
- varats/tools/research_tools/research_tool.py  1
- varats/vara_manager.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5210406&bid=17086041)

2020-03-20 09:37 UTC, boehmseb requested changes
Looks good in general.
Suggestions are mostly typos and some smaller remarks.

2020-03-20 09:37 UTC, boehmseb commented on docs/source/vara-ts-api/tools/research_tools.rst
> +To add a new research tool one has to implement to classes.
```suggestion
To add a new research tool one has to implement two classes.
```

2020-03-20 09:37 UTC, boehmseb commented on docs/source/vara-ts-api/tools/research_tools.rst
> +The ``CodeBase`` makes it convenient to interact with the, possible multiple, repository of a research tool to setup and manage the code.
```suggestion
The ``CodeBase`` makes it convenient to interact with the repository (or repositories) of a research tool to setup and manage the code.
```

2020-03-20 09:37 UTC, boehmseb commented on docs/source/vara-ts-api/tools/research_tools.rst
> +Furthmore, the tool suite provides different helper function an services that depend on the ``CodeBase`` abstraction, e.g., :ref:`vara-develop`.
```suggestion
Furthmore, the tool suite provides different helper functions and services that depend on the ``CodeBase`` abstraction, e.g., :ref:`vara-develop`.
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/research_tool.py
> +            Specifies the full qualified path to the sub project folder.
```suggestion
            Specifies the absolute path to the sub project folder.
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/research_tool.py
> +    A ``CodeBase`` depicts the layout of a project, specifying where the a
```suggestion
    A ``CodeBase`` depicts the layout of a project, specifying where a
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/research_tool.py
> +        which markes the base folder of the code base structure.
```suggestion
        which marks the base folder of the code base structure.
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/research_tool.py
> +    are setup by VaRA-TS and usable through the tool suites experiments and
```suggestion
    are set up by VaRA-TS and usable through the tool suites experiments and
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/research_tool.py
> +        checkouts the correct branches and prepares the research tool to be
```suggestion
        checks out the correct branches and prepares the research tool to be
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/research_tool.py
> +                                 init_all_submodules, update_all_submodules)
If we use `vara_manager` here, maybe we should rename that module, or at least refactor the non-vara specific parts into a separate module.

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/vara.py
> +    optinaly phasar, for static analysis.
```suggestion
    optinaly phasar for static analysis.
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/vara.py
> +        Sets up VaRA specific upstream remotes for projects that where forked.
```suggestion
        Sets up VaRA specific upstream remotes for projects that were forked.
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/vara.py
> +        Setup build-config folder link for VaRAs default build setup scripts.
```suggestion
        Setup build-config folder link for VaRA's default build setup scripts.
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/vara.py
> +        tool to be build.
```suggestion
        tool to be built.
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/vara.py
> +        LOG.info(f"Checking out VaRA version {version}" + dev_suffix)
Would something like this work:

```suggestion
        dev_suffix = "-dev" if use_dev_branches else ""
        LOG.info(f"Checking out VaRA version {str(version) + dev_suffix}")
```

I don't like that mix of fstr and string concatenation.

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/vara.py
> +    def setup(self, source_folder: Path, **kwargs: tp.Any) -> None:
```suggestion
    @check_required_args(["install_prefix"])
    def setup(self, source_folder: Path, **kwargs: tp.Any) -> None:
```

Don't forget the import.

Also, maybe `plot_utils` isn't the best location for that decorator.

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/research_tools/vara.py
> +        version = kwargs["version"]
```suggestion
        version = kwargs.get("version")
```

2020-03-20 09:37 UTC, boehmseb commented on varats/tools/driver_build_setup.py
> +
```suggestion
```

2020-03-21 10:16 UTC, vulder commented on varats/tools/driver_build_setup.py
> +
I actually wanted to leave this in, so one could out commented it and use the old style install. But not sure if this would help because I reworked the args...

2020-03-21 10:18 UTC, vulder commented on varats/tools/research_tools/research_tool.py
> +                                 init_all_submodules, update_all_submodules)
I want to remove the vara_manager part an rename it. I just delayed this a bit because I'm not sure if at some point the old stuff will become use full. In addition, not all functionality is currently ported to the new interface, therefore, the old stuff is still needed. 

https://github.com/se-passau/VaRA/issues/600

2020-03-21 10:21 UTC, vulder commented on varats/tools/research_tools/vara.py
> +        LOG.info(f"Checking out VaRA version {version}" + dev_suffix)
I guess

2020-03-21 10:23 UTC, vulder commented on varats/tools/research_tools/vara.py
> +    def setup(self, source_folder: Path, **kwargs: tp.Any) -> None:
Yeah, we should consider moving it at some point.
I also had the idea of making the implementation use introspection to figure out what is requested from 'kwargs', so the user does not have to provide the list.

2020-03-21 10:43 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/tools/research_tools/research_tool.py  3
- varats/tools/research_tools/vara.py  7
- varats/utils/filesystem_util.py  1
- varats/tools/driver_build_setup.py  5
         

Clones added
============
- varats/vara_manager.py  1
- varats/tools/research_tools/research_tool.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5210406&bid=17086041)

2020-03-21 10:46 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/driver_build_setup.py  5
- varats/tools/research_tools/vara.py  7
- varats/tools/research_tools/research_tool.py  3
- varats/utils/filesystem_util.py  1
         

Clones added
============
- varats/vara_manager.py  1
- varats/tools/research_tools/research_tool.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5210406&bid=17086041)

2020-03-21 16:03 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/utils/filesystem_util.py  1
- varats/tools/driver_build_setup.py  5
- varats/tools/research_tools/research_tool.py  3
- varats/tools/research_tools/vara.py  7
         

Clones added
============
- varats/vara_manager.py  1
- varats/tools/research_tools/research_tool.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5210406&bid=17086041)

2020-03-23 08:12 UTC, boehmseb commented on varats/tools/research_tools/research_tool.py
> +                                 init_all_submodules, update_all_submodules)
ok

2020-03-23 08:13 UTC, boehmseb commented on varats/tools/driver_build_setup.py
> +
Then also postpone this to se-passau/VaRA#600?

2020-03-23 08:15 UTC, boehmseb approved these changes

2020-03-23 09:01 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/research_tools/vara.py  7
- varats/tools/driver_build_setup.py  5
- varats/utils/filesystem_util.py  1
- varats/tools/research_tools/research_tool.py  3
         

Clones added
============
- varats/vara_manager.py  1
- varats/tools/research_tools/research_tool.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5210406&bid=17086041)

2020-03-23 09:05 UTC, merged