Updates documentation for data modules
se-passau/VaRA-Tool-Suite pull request #237
Opened 2020-03-24 13:27 UTC by vulder

resolves se-passau/VaRA#571

2020-03-24 13:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5236199&bid=17163751)

2020-03-24 13:42 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5236199&bid=17163751)

2020-03-25 08:23 UTC, boehmseb requested changes

2020-03-25 08:23 UTC, boehmseb commented on docs/source/vara-ts-api/data.rst
>  Reports
I cannot comment there, but:
- in line 12 it should say `an interfact`, not `a interface`
- in line 13, there is a comma missing after `In each filename`

2020-03-25 08:23 UTC, boehmseb commented on varats/data/cache_helper.py
> +    similar data.
```suggestion
    Identifiers for cached plot dataframes. These identifiers allow a plot to
    refer to a possibly cached dataframe.  Identifiers can be used in multiple
    plots that use the same or a similar dataframe layout, e.g., are based on
    similar data.
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/cache_helper.py
> +    Compose the identifier und project into a file path that points to the
```suggestion
    Compose the identifier and project into a file path that points to the
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/report.py
> +minimal interface `BaseReport` to implement own reports.
```suggestion
minimal interface ``BaseReport`` to implement own reports.
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/commit_report.py
> +    Encapsulates the informations gathered for a single functions.
```suggestion
    Encapsulates the information gathered for a single functions.
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/commit_report.py
> +    ``FunctionInfo``'s.
```suggestion
    A graph like structure that represents the connections between
    ``FunctionInfo``s.
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/commit_report.py
> +            project_version: version of the analysed project, i.e., commit hash
```suggestion
            project_version: version of the analyzed project, i.e., commit hash
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/commit_report.py
> +            extension_type: to specifed the status of the generated report
```suggestion
            extension_type: to specify the status of the generated report
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/blame_report.py
> +            extension_type: to specifed the status of the generated report
```suggestion
            extension_type: to specify the status of the generated report
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/blame_report.py
> +            project_version: version of the analysed project, i.e., commit hash
```suggestion
            project_version: version of the analyzed project, i.e., commit hash
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/report.py
> +            extension_type: to specifed the status of the generated report
```suggestion
            extension_type: to specify the status of the generated report
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/report.py
> +            project_version: version of the analysed project, i.e., commit hash
```suggestion
            project_version: version of the analyzed project, i.e., commit hash
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/report.py
> +            project_version: version of the analysed project, i.e., commit hash
```suggestion
            project_version: version of the analyzed project, i.e., commit hash
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/report.py
> +            extension_type: to specifed the status of the generated report
```suggestion
            extension_type: to specify the status of the generated report
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/report.py
> +            project_version: version of the analysed project, i.e., commit hash
```suggestion
            project_version: version of the analyzed project, i.e., commit hash
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/commit_report.py
> +            project_version: version of the analysed project, i.e., commit hash
```suggestion
            project_version: version of the analyzed project, i.e., commit hash
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/empty_report.py
> +            project_version: version of the analysed project, i.e., commit hash
```suggestion
            project_version: version of the analyzed project, i.e., commit hash
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/empty_report.py
> +            extension_type: to specifed the status of the generated report
```suggestion
            extension_type: to specify the status of the generated report
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/taint_report.py
> +            project_version: version of the analysed project, i.e., commit hash
```suggestion
            project_version: version of the analyzed project, i.e., commit hash
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/taint_report.py
> +            extension_type: to specifed the status of the generated report
```suggestion
            extension_type: to specify the status of the generated report
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/env_trace_report.py
> +            project_version: version of the analysed project, i.e., commit hash
```suggestion
            project_version: version of the analyzed project, i.e., commit hash
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/reports/env_trace_report.py
> +            extension_type: to specifed the status of the generated report
```suggestion
            extension_type: to specify the status of the generated report
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/revisions.py
> +Module for handling revision specific files.  When analyzing project, result
```suggestion
Module for handling revision specific files.  When analyzing a project, result
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/revisions.py
> +function to manage and access these revision specific files, e.g., get all
```suggestion
functionality to manage and access these revision specific files, e.g., to get all
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/revisions.py
> +        a list of file paths to correctly processed revision files.
```suggestion
        a list of file paths to correctly processed revision files
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/revisions.py
>                          be returned.
```suggestion
        revision: the revision for which the result files should
                        be returned
```

2020-03-25 08:23 UTC, boehmseb commented on varats/data/revisions.py
> +        suppl_info_type: Only include result files of the specified type
```suggestion
        suppl_info_type: only include result files of the specified type
```

2020-03-25 10:02 UTC, vulder commented
fixed all remarked issues

2020-03-25 10:08 UTC, boehmseb approved these changes

2020-03-25 10:08 UTC, merged