Updates documentation for tool suite experiments
se-passau/VaRA-Tool-Suite pull request #238
Opened 2020-03-24 19:15 UTC by vulder

resolves se-passau/VaRA#572

2020-03-24 19:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/wllvm.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5238778&bid=17171267)

2020-03-25 08:01 UTC, boehmseb requested changes

2020-03-25 08:01 UTC, boehmseb commented on docs/source/vara-ts-api/experiments.rst
> +* First, create a new python module in the experiments directory and add a experiment class which inherits from ``benchbuild.experiment.Experiment``.
```suggestion
* First, create a new python module in the ``experiments`` directory and add an experiment class which inherits from ``benchbuild.experiment.Experiment``.
```

2020-03-25 08:01 UTC, boehmseb commented on docs/source/vara-ts-api/experiments.rst
> +  If VaRA-TS should provide automatic support for analyzing different version, i.e., different revisions of a git based project, use :class:`~varats.utils.experiment_util.VersionExperiment` as base c
```suggestion
  If VaRA-TS should provide automatic support for analyzing different versions, i.e., different revisions of a git based project, use :class:`~varats.utils.experiment_util.VersionExperiment` as base class.
```

2020-03-25 08:01 UTC, boehmseb commented on docs/source/vara-ts-api/experiments.rst
> +  Each action the experiment does is call a ``Step`` and will be executed by BenchBuild in order.
```suggestion
  Each action the experiment does is called a ``Step`` and will be executed by BenchBuild in order.
```

2020-03-25 08:01 UTC, boehmseb commented on docs/source/vara-ts-api/experiments.rst
> +  Details on how to run experiments can be found :ref:`here<Running experiments with BenchBuild>`
```suggestion
  Details on how to run experiments can be found :ref:`here<Running experiments with BenchBuild>`.
```

2020-03-25 08:01 UTC, boehmseb commented on docs/source/vara-ts-api/experiments.rst
> +If you're looking for a simple example experiment, consider taking a look at :class:`~varats.experiments.just_compile.JustCompileReport`
```suggestion
If you're looking for a simple example experiment, consider taking a look at :class:`~varats.experiments.just_compile.JustCompileReport`.
```

2020-03-25 08:01 UTC, boehmseb commented on varats/experiments/blame_report_experiment.py
> +with VaRAs blame analysis and generates a BlameReports.
```suggestion
with VaRA's blame analysis and generates a BlameReport.
```

2020-03-25 08:01 UTC, boehmseb commented on docs/source/vara-ts/benchbuild.rst
> +In order to execute an experiment on a project we use BenchBuild, an empirical-research toolkit.
Maybe link to BB github?

2020-03-25 08:01 UTC, boehmseb commented on docs/source/vara-ts/benchbuild.rst
> +First, we need to generate a folder with a configuration file for BenchBuild in the vara root directory, this is done with:
```suggestion
First, we need to generate a folder with a configuration file for BenchBuild in the vara root directory. This is done with:
```

2020-03-25 08:01 UTC, boehmseb commented on docs/source/vara-ts/benchbuild.rst
> +Second, we change into the benchbuild folder and run an experiment that generates `BlameReports` for provided projects, in this case we use `gzip`.
```suggestion
Second, we change into the benchbuild folder and run an experiment that generates `BlameReports` for provided projects. In this case we use `gzip`.
```

2020-03-25 08:01 UTC, boehmseb commented on docs/source/vara-ts/benchbuild.rst
> +The generated result files are place in the `vara/results/$PROJECT_NAME` folder and can be further visualized with VaRA-TS graph generators.
```suggestion
The generated result files are place in the ``vara/results/$PROJECT_NAME`` folder and can be further visualized with VaRA-TS graph generators.
```

2020-03-25 08:01 UTC, boehmseb commented on varats/experiments/blame_report_experiment.py
>          """Returns the specified steps to run the project(s) specified in
```suggestion
        """
        Returns the specified steps to run the project(s) specified in
```

2020-03-25 08:01 UTC, boehmseb commented on varats/utils/experiment_util.py
> +        result_folder_template: where the results would be placed
```suggestion
        result_folder_template: where the results will be placed
```

2020-03-25 10:07 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/wllvm.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5238778&bid=17171267)

2020-03-25 10:07 UTC, boehmseb approved these changes

2020-03-25 10:08 UTC, vulder commented on docs/source/vara-ts/benchbuild.rst
> +In order to execute an experiment on a project we use BenchBuild, an empirical-research toolkit.
good idea, done

2020-03-25 10:09 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/wllvm.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5238778&bid=17171267)

2020-03-25 10:19 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/wllvm.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5238778&bid=17171267)

2020-03-25 10:28 UTC, merged