Refactor data handling
se-passau/VaRA-Tool-Suite pull request #251
Opened 2020-04-07 15:25 UTC by boehmseb

Resolves se-passau/VaRA#608
Resolves se-passau/VaRA#550

Open TODOs:

- [ ] compress cache files (gzip/xz/etc.)
- [ ] check if other plots can use this infrastructure
- [ ] write docs

2020-04-07 15:28 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_database.py  1
- varats/data/cache_helper.py  2
- varats/data/databases/blame_interaction_degree_database.py  1
- varats/data/databases/database.py  7
         

Complexity decreasing per file
==============================
+ varats/plots/commit_interactions.py  -4
         

Clones added
============
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/blame_interaction_degree_database.py  1
         

Clones removed
==============
+ varats/plots/blame_lorenz_curve.py  -1
+ varats/plots/blame_interaction_degree.py  -1
+ varats/plots/commit_interactions.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5321630&bid=17415746)

2020-04-07 16:02 UTC, vulder requested changes
Any resolution on the `database` name issue?

2020-04-07 16:02 UTC, vulder commented on varats/data/cache_helper.py
> +            plot_name=data_id, project_name=project_name)
change to f-string

2020-04-07 16:02 UTC, vulder commented on varats/data/cache_helper.py
> +def load_cached_df_or_none(data_id: str,
With the cache type gone, is `data_id` from now on just an arbitrary string or will we add something later here?

2020-04-07 16:02 UTC, vulder commented on varats/data/databases/database.py
> +    COLUMNS = ["revision", "time_id"]
you do you add revision and time_id here in the general database impl?

2020-04-07 16:02 UTC, vulder commented on varats/data/databases/database.py
> +                                          "to override it?")
We could also add a check in the init method to verify if subclasses override `CACHE_ID` similar to `MetaReport`

2020-04-07 16:44 UTC, boehmseb commented on varats/data/cache_helper.py
> +def load_cached_df_or_none(data_id: str,
I had the idea to replace the cache type with the database class, but that caused all sorts of issues with mypy. That's why I only use strings now. The `Database` base class now takes care of passing the correct string here and has some checks in place (see the assertions in `Database.get_data_for_project()`) to ensure correct usage.

2020-04-07 16:53 UTC, boehmseb commented on varats/data/databases/database.py
> +    COLUMNS = ["revision", "time_id"]
What's your concern with this: do you think this is too specific and we should have a subclass `DatabaseWithRevision` or similar, or do you want to know why it is here and not only in the subclasses?

For the latter case: Actually, I would like `CACHE_ID` to be abstract, and I want to force subclasses to always include these two columns. Currently, this is needed for the case study filter logic and for caching. However, as we are working on the class-level here, and not on the instance-level, I could not find how to do this properly. Therefore, I have these class variables here for documentation purposes (and to help auto-completion engines) and check the desired properties of the dataframe with assertions.

2020-04-07 16:56 UTC, boehmseb commented on varats/data/databases/database.py
> +                                          "to override it?")
Well, I never actually instantiate these classes, as they do not need to have state, hence, `__init__()` won't help here. You would need a metaclass for this, but that role is already filled by `ABC`. It's basically a tradeoff what we want to check where.

2020-04-07 16:57 UTC, boehmseb commented
> Any resolution on the `database` name issue?

I kind of settled with this for now; couldn't find anything better. Maybe `DataAccess`?

2020-04-08 12:53 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- varats/data/cache_helper.py  2
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/database.py  7
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_degree_database.py  1
         

Complexity decreasing per file
==============================
+ varats/plots/commit_interactions.py  -4
         

Clones added
============
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_degree_database.py  1
         

Clones removed
==============
+ varats/plots/blame_lorenz_curve.py  -1
+ varats/plots/blame_interaction_degree.py  -1
+ varats/plots/commit_interactions.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5321630&bid=17415746)

2020-04-08 12:59 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- varats/data/databases/database.py  7
- varats/data/databases/blame_interaction_degree_database.py  1
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/commit_interaction_database.py  1
- varats/data/cache_helper.py  2
         

Complexity decreasing per file
==============================
+ varats/plots/commit_interactions.py  -4
         

Clones added
============
- varats/data/databases/blame_interaction_degree_database.py  1
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/commit_interaction_database.py  1
         

Clones removed
==============
+ varats/plots/blame_interaction_degree.py  -1
+ varats/plots/blame_lorenz_curve.py  -1
+ varats/plots/commit_interactions.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5321630&bid=17415746)

2020-04-09 14:53 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/database.py  7
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/blame_interaction_degree_database.py  1
- varats/data/cache_helper.py  2
         

Complexity decreasing per file
==============================
+ varats/plots/commit_interactions.py  -4
         

Clones added
============
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/blame_interaction_degree_database.py  1
         

Clones removed
==============
+ varats/plots/commit_interactions.py  -2
+ varats/plots/blame_interaction_degree.py  -1
+ varats/plots/blame_lorenz_curve.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5321630&bid=17415746)

2020-04-09 15:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- varats/data/databases/blame_interaction_database.py  1
- varats/data/cache_helper.py  2
- varats/data/databases/database.py  7
- varats/data/databases/blame_interaction_degree_database.py  1
- varats/data/databases/commit_interaction_database.py  1
         

Complexity decreasing per file
==============================
+ varats/plots/commit_interactions.py  -4
         

Clones added
============
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/blame_interaction_degree_database.py  1
- varats/data/databases/commit_interaction_database.py  1
         

Clones removed
==============
+ varats/plots/commit_interactions.py  -2
+ varats/plots/blame_interaction_degree.py  -1
+ varats/plots/blame_lorenz_curve.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5321630&bid=17415746)

2020-04-10 20:58 UTC, vulder commented
> > Any resolution on the `database` name issue?
> 
> I kind of settled with this for now; couldn't find anything better. Maybe `DataAccess`?

Or just add a prefix like: `AnalysisDatabase`, `ReportDatabase` or `EvaluationDatabase`

I pers. like `EvalDatabase` or `EvaluationDatabase`

2020-04-10 21:01 UTC, vulder submitted a review, later dismissed

2020-04-10 21:01 UTC, vulder commented on varats/data/cache_helper.py
> +def load_cached_df_or_none(data_id: str,
ok

2020-04-10 21:07 UTC, vulder commented on varats/data/databases/database.py
> +    COLUMNS = ["revision", "time_id"]
My question is more in the usage intention. Do you ensure that subclasses have these two `COLUMNS`? Could a subclass leave them out, e.g., by mistake?

2020-04-10 21:23 UTC, vulder commented on varats/data/databases/database.py
> +                                          "to override it?")
I think these are the two magic function you're looking for.
If you want to check it in a meta class you can implement it in `__new__`
Otherwise, for normal classes there is a function called `__init_subclass__`
See: https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__
This allows you to check if sub classes implement things as you like them to.

2020-04-10 21:25 UTC, vulder requested changes
Looks good, after we resolved the naming and COLUMNS part we can merge this

2020-04-10 21:29 UTC, vulder commented
One more thing, please switch the asserts with raise AssertionError so we also have for release version

2020-04-20 13:24 UTC, boehmseb commented on varats/data/databases/database.py
> +    COLUMNS = ["revision", "time_id"]
That would be detected by my assertions

2020-04-20 14:23 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- varats/data/cache_helper.py  2
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/evaluationdatabase.py  5
- varats/data/databases/blame_interaction_degree_database.py  1
         

Complexity decreasing per file
==============================
+ varats/plots/commit_interactions.py  -4
         

Clones added
============
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/blame_interaction_degree_database.py  1
         

Clones removed
==============
+ varats/plots/blame_interaction_degree.py  -1
+ varats/plots/blame_lorenz_curve.py  -1
+ varats/plots/commit_interactions.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5321630&bid=17415746)

2020-04-20 14:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/cache_helper.py  2
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/evaluationdatabase.py  5
- varats/data/databases/blame_interaction_degree_database.py  1
         

Complexity decreasing per file
==============================
+ varats/plots/commit_interactions.py  -4
         

Clones added
============
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_database.py  1
- varats/data/databases/blame_interaction_degree_database.py  1
         

Clones removed
==============
+ varats/plots/blame_lorenz_curve.py  -1
+ varats/plots/blame_interaction_degree.py  -1
+ varats/plots/commit_interactions.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5321630&bid=17415746)

2020-04-21 08:05 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/databases/evaluationdatabase.py  5
- varats/data/databases/blame_interaction_degree_database.py  1
- varats/data/cache_helper.py  2
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_database.py  1
         

Complexity decreasing per file
==============================
+ varats/plots/commit_interactions.py  -4
         

Clones added
============
- varats/data/databases/blame_interaction_degree_database.py  1
- varats/data/databases/commit_interaction_database.py  1
- varats/data/databases/blame_interaction_database.py  1
         

Clones removed
==============
+ varats/plots/commit_interactions.py  -2
+ varats/plots/blame_interaction_degree.py  -1
+ varats/plots/blame_lorenz_curve.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5321630&bid=17415746)

2020-04-21 09:05 UTC, vulder approved these changes

2020-04-21 09:16 UTC, merged