Reworks VaRA documentation
se-passau/VaRA-Tool-Suite pull request #254
Opened 2020-04-13 21:06 UTC by vulder

Migrates old docs from VaRA readme to docs and updates the information.
Adds an overview of the tool suite.
Adds VaRA logo to VaRA docs page.

resolves se-passau/VaRA#593
resolves se-passau/VaRA#570
resolves se-passau/VaRA#567

2020-04-15 11:46 UTC, cormensratio commented on docs/source/index.rst
> +Tool-suite overview
```suggestion
Tool-Suite overview
```

2020-04-15 11:53 UTC, cormensratio commented on docs/source/research_tool_docs/vara/setup.rst
> +Third, to complet the setup link the prepared VaRA build scripts into a build folder.
```suggestion
Third, to complete the setup link the prepared VaRA build scripts into a build folder.
```

2020-04-15 12:00 UTC, cormensratio commented on docs/source/vara-ts/benchbuild.rst
> +BenchBuilds configuration file ``.benchbuild.yml`` normaly is placed inside the `benchbuild` folder, which is located in the vara root folder.
```suggestion
BenchBuild's configuration file ``.benchbuild.yml`` normally is placed inside the `benchbuild` folder, which is located in the vara root folder.
```

2020-04-15 12:01 UTC, cormensratio commented on docs/source/vara-ts/benchbuild.rst
> +To adapt and tune BenchBuild further a lot of different configuration flags can be adapted, the following list shows the most important ones:
```suggestion
To adapt and tune BenchBuild further a lot of different configuration flags can be adapted. The following list shows the most important ones:
```

2020-04-15 12:03 UTC, cormensratio commented on docs/source/vara-ts/benchbuild.rst
> +* Loading other experiments or projects can be specifying similar to python imports
```suggestion
* Loading other experiments or projects can be specified similar to python imports
```

2020-04-15 12:07 UTC, cormensratio commented on docs/source/vara-ts/benchbuild.rst
> +* Adapt the number of threads that should be for running project compilation.
```suggestion
* Adapt the number of threads that should be running for project compilation.
```

2020-04-15 12:12 UTC, cormensratio commented on docs/source/research_tool_docs/vara/debugging.rst
> +VaRA can produce specific debug output to ease debugging, to enable this output use LLVM debugging options.
```suggestion
VaRA can produce specific debug output to ease debugging. To enable this output use LLVM debugging options.
```

2020-04-15 12:15 UTC, cormensratio reviewed
lgtm

2020-04-15 12:16 UTC, cormensratio commented
In the Tool-suite overview section, the LLVM Logo and VaRA Logo is slightly overlapping.

2020-04-15 13:31 UTC, vulder commented on docs/source/index.rst
> +Tool-suite overview
```suggestion
Tool-Suite Overview
```

2020-04-15 13:32 UTC, vulder commented on docs/source/index.rst
> +Tool-Suite overview
```suggestion
Tool-Suite Overview
```

2020-04-15 13:33 UTC, vulder commented
> In the Tool-suite overview section, the LLVM Logo and VaRA Logo is slightly overlapping.

This is intended. The idea is to show that VaRA is integrated into llvm.

2020-04-20 08:53 UTC, boehmseb commented
What I find a bit annoying is that the VaRA logo behind the LLVM logo has a different aspect ratio, i.e. it is stretched.

2020-04-20 08:56 UTC, boehmseb commented
Also, the contrast between the logos and the background in this box is quite bad and creates noise around the edges of the LLVM logo.

2020-04-20 09:24 UTC, boehmseb requested changes

2020-04-20 09:24 UTC, boehmseb commented on docs/source/research_tool_docs/vara/debugging.rst
> +For testing of commit and git related analyses, VaRA offers additional testing repositories, which are automatically provided to your regression or unittests.
```suggestion
For testing of commit and git related analyses, VaRA offers additional testing repositories which are automatically provided to your regression or unittests.
```

2020-04-20 09:24 UTC, boehmseb commented on docs/source/research_tool_docs/vara/debugging.rst
> +For unittests, just include the ``UnittestHelper.h`` and load a repository by specifying it's subpath, relative to the ``TestRepositories`` folder.
```suggestion
For unittests, just include the ``UnittestHelper.h`` and load a repository by specifying its subpath, relative to the ``TestRepositories`` folder.
```

2020-04-20 09:24 UTC, boehmseb commented on docs/source/research_tool_docs/vara/debugging.rst
> +Add the corresponding debug flag to your run line `-debug-only=$DB_FLAG`
```suggestion
Add the corresponding debug flag to your run line ``-debug-only=$DB_FLAG``
```

2020-04-20 09:24 UTC, boehmseb commented on docs/source/research_tool_docs/vara/setup.rst
> +VaRA can be automatically set up with :ref:`vara-buildsetup` from the tool suite, for instructions see setup.
Missing link `setup`

2020-04-20 09:24 UTC, boehmseb commented on docs/source/research_tool_docs/vara/setup.rst
> +To create your own setup or integrate VaRA into LLVM follow these instructions.
```suggestion
To create your own setup or integrate VaRA into LLVM, follow these instructions.
```

2020-04-20 09:24 UTC, boehmseb commented on docs/source/vara-ts/benchbuild.rst
> +BenchBuild's configuration file ``.benchbuild.yml`` normally is placed inside the `benchbuild` folder, which is located in the vara root folder.
```suggestion
BenchBuild's configuration file ``.benchbuild.yml`` normally is placed inside the ``benchbuild`` folder, which is located in the vara root folder.
```

2020-04-20 09:24 UTC, boehmseb commented on docs/source/vara-ts/benchbuild.rst
> +To adapt and tune BenchBuild further a lot of different configuration flags can be adapted. The following list shows the most important ones:
```suggestion
To adapt and tune BenchBuild further, you can moify the different configuration flags in this config file. The following list shows the most important ones:
```

2020-04-20 09:24 UTC, boehmseb commented on docs/source/vara-ts/benchbuild.rst
> +* Loading other experiments or projects can be specified similar to python imports
```suggestion
* Other experiments or projects can be loaded similar to python imports
```

2020-04-20 09:24 UTC, boehmseb commented on docs/source/vara-ts/benchbuild.rst
> +* Adapt the number of threads that should be running for project compilation.
```suggestion
* Adapt the number of threads that should be used for project compilation.
```

2020-04-20 11:40 UTC, boehmseb approved these changes

2020-04-20 12:24 UTC, merged