feat(doc): Update documentation for vara-buildsetup
se-passau/VaRA-Tool-Suite pull request #255
Opened 2020-04-15 13:29 UTC by ognarb

* Move vara-buildsetup existing documentation from README to docs folder
* Add information about various environment variables

2020-04-15 14:50 UTC, vulder requested changes
Some questions, otherwise lgtm.

2020-04-15 14:50 UTC, vulder commented on docs/source/vara-ts/vara-buildsetup.rst
> +`vara-buildsetup` is the tool used to install and build VaRA.
```suggestion
:ref:`vara-buildsetup` is the tool used to install and build VaRA.
```
We should add a link to the specific tool docs.

2020-04-15 14:50 UTC, vulder commented on README.md
>  ```
We should also mention the Install deps in the `Install VaRA with vara-buildsetup` docs part.

2020-04-15 14:50 UTC, vulder commented on README.md
> -#### Install to python user-directory (easier)
The special `How to install VaRA section` in the docs sounds good.
However, I'm not sure how much we should remove from the README.
Some specific VaRA install parts belong in the docs and should be removed.

Should we keep the instructions on how to setup the tool suite? For people starting this could be helpful, but I'm not sure because it also duplicates parts of the doc and I don't want to remove them from there.

Side note: I'm currently working on putting a license on the project and uploading pypi so it can be installed with pip.
Maybe this could be a good split: Put the developer stuff, i.e., how to setup virtual envs..., into docs and just have the pip install line for users in the README.

What's your opinion?

2020-04-15 14:50 UTC, vulder commented on docs/source/vara-ts/vara-buildsetup.rst
> +
This hint is useful for testing, good addition :+1:

2020-04-20 13:56 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5362809&bid=17573806)

2020-04-20 14:01 UTC, ognarb commented on README.md
> +pip3 install TODO-PACKAGE-NAME
TODO change with the package name when uploaded to pip

2020-04-20 14:03 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5362809&bid=17573806)

2020-04-21 10:30 UTC, vulder approved these changes
lgtm
As a follow-up I will update the VaRA README to match this information.

2020-04-21 10:30 UTC, vulder commented on README.md
> +The easiest way to install VaRa is to use the `vara-buildsetup` tool. You can find more information
```suggestion
The easiest way to install VaRA is to use the `vara-buildsetup` tool. You can find more information
```

2020-04-21 10:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5362809&bid=17573806)

2020-04-21 10:34 UTC, vulder commented on README.md
```suggestion
```

2020-04-21 11:33 UTC, merged