WIP: Adds the BlameVerifierExperiment and BlameVerifierReport
se-passau/VaRA-Tool-Suite pull request #259
Opened 2020-04-22 10:33 UTC by cormensratio

2020-04-22 10:34 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-04-23 12:39 UTC, vulder commented
@cormensratio could you please fix the travis issue so I can test this on my machine.

2020-04-23 15:05 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-04-23 15:13 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-04-23 15:35 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-04-23 15:38 UTC, cormensratio commented
Fixed the travis issues, however currently the report is empty.

2020-04-24 09:23 UTC, vulder requested changes

2020-04-24 09:23 UTC, vulder commented on varats/experiments/blame_verifier_experiment.py
> +            * -yaml-report-outfile=<path>: specify the path to store the results
is this used on the verifier?

2020-04-24 09:23 UTC, vulder commented on varats/experiments/blame_verifier_experiment.py
> +    call.
copy paste error

2020-04-24 09:23 UTC, vulder commented on varats/experiments/blame_verifier_experiment.py
> +
you have to add `-g` as flag to the c/cxx flags of a project, otherwise, you'll not have debug infos.

2020-04-24 09:23 UTC, vulder commented on varats/experiments/blame_verifier_experiment.py
> +                project_version=project.version))
You need to create a new specific name for bc files with dbg data, otherwise, you'll not see anything when files without are cached. This also needs a extension to the basic setup to specify an adapted name.

2020-04-25 09:39 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/blame_verifier_experiment.py  3
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  4
- varats/experiments/blame_report_experiment.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-04-25 10:45 UTC, vulder requested changes

2020-04-25 10:45 UTC, vulder commented on varats/experiments/blame_experiment.py
> +
Why should we add this to the basic setup? If the experiment wants to add extra flags it can do so in the experiment specific code.

2020-04-30 17:40 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/blame_verifier_experiment.py  3
         

Clones added
============
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/vara_full_mtfa.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-05-02 18:40 UTC, vulder reviewed
Not sure if it is the case but please make sure that you use the `yapf` version specified in the requirements.txt to format your code.

2020-05-02 18:40 UTC, vulder commented on varats/experiments/wllvm.py
> +
Please keep the 'old style' for the template just make it private. The names make it easier to see what the different parts are used for.

2020-05-02 18:40 UTC, vulder commented on varats/experiments/wllvm.py
> +                                  project_version, dbg)
Please use python f-strings, they are a more modern form of formatting strings.
https://docs.python.org/3.7/tutorial/inputoutput.html#formatted-string-literals

2020-05-02 18:40 UTC, vulder commented on varats/experiments/wllvm.py
> +            dbg = ""
In general you can keep this pattern. Just put a `-{extension}` part into the template. This allows us to add the dbg extensions or further customize the code in the future.

2020-05-02 18:40 UTC, vulder commented on varats/experiments/wllvm.py
> +                         project_version: str, dbg: bool = False):
Needs docs :)

2020-05-02 18:40 UTC, vulder commented on varats/experiments/wllvm.py
>                  project_version=str(project.version))
When extract creates the `bc_cache_file` name it does not add extensions to it, e.g., `dbg`. Therefore, the cached `.bc` files name is wrong if one wants to load a `_dbg` file.

2020-05-12 17:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/blame_report_experiment.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-05-12 17:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/blame_verifier_experiment.py  3
         

Clones added
============
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/blame_verifier_experiment.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-05-12 20:53 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/blame_report_experiment.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-05-13 09:37 UTC, vulder commented on varats/experiments/blame_experiment.py
> +    project: Project, extensions: list
`list` is not the precise type here, use the python typing annotations to specify the type. See the return type of the function as an example.

2020-05-13 09:37 UTC, vulder commented on varats/experiments/commit_report_experiment.py
> +                        str(interaction_filter_file)
Could be a f-string

2020-05-13 09:37 UTC, vulder commented on varats/experiments/phasar_env_analysis.py
> +
Why was this added here?

2020-05-13 09:37 UTC, vulder commented on varats/experiments/commit_report_experiment.py
> +                    ) + Extract.BC_FILE_TEMPLATE.format(
Outside of Extract, we should only call the new static function and not access the template directly.

2020-05-13 09:37 UTC, vulder commented on varats/experiments/commit_report_experiment.py
> +                bc_cache_folder / Extract.BC_FILE_TEMPLATE.format(
Outside of Extract, we should only call the new static function and not access the template directly.

2020-05-13 09:37 UTC, vulder commented on varats/experiments/wllvm.py
> +class Extensions(Enum):
`Extensions` is to generic name, especially because we have different kinds of extensions. You should adapt the name to something like: `BCFileExtensions` or `BitcodeFileExtensions`

2020-05-14 09:09 UTC, cormensratio commented on varats/experiments/phasar_env_analysis.py
> +
I think this was a merge error. It has been removed now.

2020-05-14 09:10 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
         

Clones added
============
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/vara_full_mtfa.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-05-14 09:11 UTC, cormensratio commented on varats/experiments/wllvm.py
> +
Is this resolved, or do you want it to be a local?

2020-05-14 17:46 UTC, vulder requested changes
Looks quite workable now, just a few remarks.
PS: please also add a unit test for `get_bc_file_name` and the `blame_verifier_report` similar to the other report tests. I know it's not much to test but I try to have by default a test file for the reports. Hopefully, this brings people to extend it when working on the report.

2020-05-14 17:46 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +    TODO: Add further description (Currently empty report)
One should aadd a description here, I guess :)

2020-05-14 17:46 UTC, vulder commented on varats/experiments/blame_experiment.py
> +    project: Project, bc_file_extensions: tp.List[BCFileExtensions]
The common case is that we don't have any extra extensions. We should make this parameter optional or default to an empty list.

2020-05-14 17:46 UTC, vulder commented on varats/experiments/blame_verifier_experiment.py
> +        pass
It would be better to implement the method here and just pass everything that is different for opt builds via the constructor of the subclass, e.g., opt flag and corresponding extension.

2020-05-14 17:46 UTC, vulder commented on varats/experiments/blame_verifier_experiment.py
> +    REPORT_TYPE = BVR
The report type needs to be different for the different opt experiments, otherwise, two reports can not exists side by side.

2020-05-14 17:46 UTC, vulder commented on varats/experiments/wllvm.py
> +
I did not mean to make it a global variable but a static private class variable. Sorry for to being specific enough.
But with the new method design it's ok as a variable inside the `get_bc_file_name` method.

2020-05-14 17:46 UTC, vulder commented on varats/experiments/wllvm.py
> +            project_bc_file_ext += bc_file_extensions[-1].value
```suggestion
            ext_sep = ""
            for ext in bc_file_extensions:
                project_bc_file_ext += (ext_sep + ext.value)
                ext_sep =  '_'
```
That looks kinda hacky with indexing and list shorting, with this code pattern where we use a prefix it is easier to have separators between names without indexing.

2020-05-14 17:49 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/blame_verifier_experiment.py  3
         

Clones added
============
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/vara_full_mtfa.py  1
- varats/experiments/blame_verifier_experiment.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-05-26 09:23 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/blame_verifier_experiment.py  3
         

Clones added
============
- varats/experiments/vara_full_mtfa.py  1
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/blame_verifier_experiment.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-05-28 12:25 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 7
           

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- tests/data/test_blame_verifier_report.py  1
- varats/data/reports/blame_verifier_report.py  1
- tests/data/test_wllvm.py  1
- varats/experiments/blame_experiment.py  1
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  2
- varats/experiments/vara_full_mtfa.py  1
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/phasar_env_analysis.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-05-28 15:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- tests/data/test_blame_verifier_report.py  1
- varats/data/reports/blame_verifier_report.py  1
- tests/data/test_wllvm.py  1
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/vara_full_mtfa.py  1
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/blame_report_experiment.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-05-30 10:38 UTC, vulder requested changes
Could you also please fix the travis and codacy issue and close resolved conversation so I better see what you already addressed.
Otherwise, the code looks quite workable now :+1:

2020-05-30 10:38 UTC, vulder commented on tests/data/test_blame_verifier_report.py
> +        test_file_ext = ".txt"
The parts that are duplicated can be moved into a `setUpClass` method on the project class.

2020-05-30 10:38 UTC, vulder commented on tests/data/test_wllvm.py
> +        test_project_version = "testProjectVersion1"
same here

2020-05-30 10:38 UTC, vulder commented on tests/data/test_blame_verifier_report.py
> +        # Arrange
```suggestion
        # Given
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_blame_verifier_report.py
> +        # Act
```suggestion
        # When
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_blame_verifier_report.py
> +        # Assert
```suggestion
        # Then
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_blame_verifier_report.py
> +        # Act
```suggestion
        # When
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_blame_verifier_report.py
> +        # Arrange
```suggestion
        # Given
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_blame_verifier_report.py
> +        # Assert
```suggestion
        # Then
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_wllvm.py
> +        # Arrange
```suggestion
        # Given
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_wllvm.py
> +        # Act
```suggestion
        # When
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_wllvm.py
> +        # Assert
```suggestion
        # Then
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_wllvm.py
> +        # Arrange
```suggestion
        # Given
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_wllvm.py
> +        # Act
```suggestion
        # When
```

2020-05-30 10:38 UTC, vulder commented on tests/data/test_wllvm.py
> +        # Assert
```suggestion
        # Then
```

2020-05-30 10:38 UTC, vulder commented on varats/experiments/blame_verifier_experiment.py
> +    optimizations.
```suggestion
    BlameVerifierReportExperiment generalizes the implementation and usage over different
    optimization levels.
```

2020-05-30 10:38 UTC, vulder commented on varats/experiments/blame_verifier_experiment.py
> +    Only its subclasses should be instantiated.
```suggestion
```
If it has no `NAME` it cannot be created by BB

2020-05-30 10:38 UTC, vulder commented on varats/experiments/wllvm.py
> +               f"{experiment_bc_file_ext}.bc"
I seems there is a miss understanding here in combination with my remark above.
When you use f-strings here you can remove `__BC_FILE_TEMPLATE`, otherwise, make the file template a local variable here inside the method and use .format instead of f-strings. Both is not useful. I hope this makes it clearer :)

2020-05-30 10:38 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +    SHORTHAND = 'BVR_NoOpt'
Did you test that this works when parsing the filename?

2020-05-30 11:21 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- tests/data/test_blame_verifier_report.py  1
- tests/data/test_wllvm.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
         

Clones added
============
- varats/experiments/vara_full_mtfa.py  1
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/phasar_env_analysis.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-06-08 18:36 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/blame_experiment.py  1
- tests/data/test_blame_verifier_report.py  1
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/wllvm.py  1
- tests/data/test_wllvm.py  1
         

Clones added
============
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/commit_report_experiment.py  1
- varats/experiments/vara_full_mtfa.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-06-08 19:05 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/blame_experiment.py  1
- tests/data/test_wllvm.py  1
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/blame_verifier_experiment.py  3
- tests/data/test_blame_verifier_report.py  1
- varats/experiments/wllvm.py  1
         

Clones added
============
- varats/experiments/commit_report_experiment.py  1
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/vara_full_mtfa.py  2
- varats/experiments/blame_report_experiment.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-06-09 18:02 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/data/test_wllvm.py  1
- varats/experiments/wllvm.py  1
- tests/data/test_blame_verifier_report.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/blame_experiment.py  1
         

Clones added
============
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/commit_report_experiment.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/vara_full_mtfa.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-06-13 20:24 UTC, vulder approved these changes
lgtm

2020-06-13 20:24 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +    verifier-options, e.g. the diff of VaRA-hashes and debug-hashes, without any
```suggestion
    verifier-options, e.g., the diff of VaRA-hashes and debug-hashes, without any
```

2020-06-13 20:24 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +    verifier-options, e.g. the diff of VaRA-hashes and debug-hashes, with
```suggestion
    verifier-options, e.g., the diff of VaRA-hashes and debug-hashes, with
```

2020-06-15 08:37 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- tests/data/test_blame_verifier_report.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/blame_experiment.py  1
- varats/experiments/wllvm.py  1
- tests/data/test_wllvm.py  1
         

Clones added
============
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/vara_full_mtfa.py  2
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/commit_report_experiment.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-06-15 08:46 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/wllvm.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/blame_experiment.py  1
- tests/data/test_wllvm.py  1
- tests/data/test_blame_verifier_report.py  1
         

Clones added
============
- varats/experiments/commit_report_experiment.py  1
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/blame_verifier_experiment.py  3
- varats/experiments/vara_full_mtfa.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-06-15 08:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/data/test_blame_verifier_report.py  1
- varats/data/reports/blame_verifier_report.py  1
- varats/experiments/blame_experiment.py  1
- varats/experiments/wllvm.py  1
- tests/data/test_wllvm.py  1
- varats/experiments/blame_verifier_experiment.py  3
         

Clones added
============
- varats/experiments/commit_report_experiment.py  1
- varats/experiments/vara_full_mtfa.py  2
- varats/experiments/blame_report_experiment.py  1
- varats/experiments/phasar_env_analysis.py  1
- varats/experiments/blame_verifier_experiment.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5401052&bid=17706103)

2020-06-15 08:58 UTC, merged