Adds functionality to diff BlameReports
se-passau/VaRA-Tool-Suite pull request #274
Opened 2020-05-04 16:35 UTC by vulder

Adds a BlameReportDiff class that represents the diff between two
BlameReports and shows all interactions that changed.

2020-05-04 16:37 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  10
         

Clones added
============
- tests/data/test_blame_report.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5467441&bid=17919615)

2020-05-05 08:49 UTC, boehmseb commented on varats/data/reports/blame_report.py
> +def _calc_diff_between_func_entries(
Maybe a matter of taste, but is there a reason why you keep this part of the diffing logic in the data-holding class while the rest is in the diffing-class?

2020-05-05 13:39 UTC, boehmseb requested changes
The diff logic itself looks fine to me. Just one typo and a design-related comment.

2020-05-05 13:39 UTC, boehmseb commented on varats/data/reports/blame_report.py
> +            prev_inter = prev_interactions[prev_inter_idx]
```suggestion
            prev_inter = prev_interactions.pop(prev_inter_idx)
```
And remove the `del` below.

2020-05-05 13:39 UTC, boehmseb commented on varats/data/reports/blame_report.py
> +            del prev_interactions[prev_inter_idx]
Why use `del` here? I would suggest to use `pop()` above and remove this line.

2020-05-05 13:39 UTC, boehmseb commented on varats/data/reports/blame_report.py
> +    Diff class that contains all interactions that changed between to report
```suggestion
    Diff class that contains all interactions that changed between two report
```

2020-05-05 21:26 UTC, vulder commented on varats/data/reports/blame_report.py
> +def _calc_diff_between_func_entries(
As discussed we keep this for now

2020-05-05 21:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  10
         

Clones added
============
- tests/data/test_blame_report.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5467441&bid=17919615)

2020-05-05 21:34 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  10
         

Clones added
============
- tests/data/test_blame_report.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5467441&bid=17919615)

2020-05-05 21:54 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  10
         

Clones added
============
- tests/data/test_blame_report.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5467441&bid=17919615)

2020-05-05 22:49 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  10
         

Clones added
============
- tests/data/test_blame_report.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5467441&bid=17919615)

2020-05-06 08:55 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  10
         

Clones added
============
- tests/data/test_blame_report.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5467441&bid=17919615)

2020-05-06 09:05 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  10
         

Clones added
============
- tests/data/test_blame_report.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5467441&bid=17919615)

2020-05-06 09:34 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  10
         

Clones added
============
- tests/data/test_blame_report.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5467441&bid=17919615)

2020-05-07 14:48 UTC, boehmseb approved these changes

2020-05-07 14:49 UTC, vulder commented on .travis.yml
> +  # - git clone https://git.savannah.gnu.org/git/gzip.git gzip
```suggestion
  # - git clone https://git.savannah.gnu.org/git/gzip.git gzip
```

2020-05-07 14:52 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_report.py  10
         

Clones added
============
- tests/data/test_blame_report.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5467441&bid=17919615)

2020-05-07 14:54 UTC, merged