Integrate pre-commit and update files
se-passau/VaRA-Tool-Suite pull request #276
Opened 2020-05-06 18:31 UTC by vulder

2020-05-06 18:33 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-06 18:38 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-06 19:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
           

Clones added
============
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/lrzip.py  4
- varats/projects/c_projects/glibc.py  4
- varats/projects/c_projects/libvpx.py  4
- varats/projects/c_projects/openssl.py  4
- varats/projects/c_projects/xz.py  3
- varats/projects/c_projects/tmux.py  4
- varats/projects/c_projects/coreutils.py  3
- varats/projects/c_projects/gravity.py  3
- varats/projects/c_projects/busybox.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-07 09:20 UTC, boehmseb requested changes
There seems to be an issue with the import formatter that causes lines to exceed the 80-char limit. I have marked these lines with comments.

2020-05-07 09:20 UTC, boehmseb commented on tests/paper/test_artefacts.py
> +from varats.paper.artefacts import ArtefactType, PlotArtefact, load_artefacts_from_file
This line is too long.

2020-05-07 09:20 UTC, boehmseb commented on tests/test_vara_manager.py
> +from varats.vara_manager import LLVMProjects, VaRAExtraProjectsIter, VaRAProjectsIter
This line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/experiments/vara_fc_taint_analysis.py
> +from varats.utils.experiment_util import PEErrorHandler, exec_func_with_pe_error_handler
This line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/gui/views/cr_bar_view.py
> +from varats.data.reports.commit_report import CommitMap, CommitReport, CommitReportMeta
This line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/paper/case_study.py
> +from varats.data.provider.release.release_provider import ReleaseProvider, ReleaseType
Line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/paper/paper_config_manager.py
> +from varats.paper.case_study import CaseStudy, get_newest_result_files_for_case_study
Line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/plots/blame_lorenz_curve.py
> +from varats.data.databases.blame_interaction_database import BlameInteractionDatabase
Line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/plots/blame_lorenz_curve.py
> +from varats.plots.repository_churn import build_repo_churn_table, draw_code_churn
Line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/plots/commit_interactions.py
> +from varats.data.databases.commit_interaction_database import CommitInteractionDatabase
Line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/projects/c_projects/x264.py
> +from varats.utils.project_util import get_all_revisions_between, wrap_paths_to_binaries
Line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/tools/research_tools/vara.py
> +from varats.tools.research_tools.research_tool import CodeBase, ResearchTool, SubProject
Line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/tools/driver_build_setup.py
> +from varats.tools.research_tools.research_tool import ResearchTool, SpecificCodeBase
Line is too long.

2020-05-07 09:20 UTC, boehmseb commented on varats/vara_manager.py
> +from PyQt5.QtCore import QObject, QProcess, QRunnable, QThreadPool, pyqtSignal, pyqtSlot
Line is too long.

2020-05-07 12:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Clones added
============
- varats/projects/c_projects/gravity.py  3
- varats/projects/c_projects/lrzip.py  4
- varats/projects/c_projects/libvpx.py  4
- varats/projects/c_projects/glibc.py  4
- varats/projects/c_projects/openssl.py  4
- varats/projects/c_projects/busybox.py  5
- varats/projects/c_projects/tmux.py  4
- varats/projects/c_projects/coreutils.py  3
- varats/projects/c_projects/xz.py  3
- varats/projects/c_projects/gzip.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-07 12:34 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Clones added
============
- varats/projects/c_projects/openssl.py  4
- varats/projects/c_projects/coreutils.py  3
- varats/projects/c_projects/glibc.py  4
- varats/projects/c_projects/gravity.py  3
- varats/projects/c_projects/busybox.py  5
- varats/projects/c_projects/lrzip.py  4
- varats/projects/c_projects/xz.py  3
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/tmux.py  4
- varats/projects/c_projects/libvpx.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-07 12:58 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Clones added
============
- varats/projects/c_projects/lrzip.py  4
- varats/projects/c_projects/tmux.py  4
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/glibc.py  4
- varats/projects/c_projects/xz.py  3
- varats/projects/c_projects/libvpx.py  4
- varats/projects/c_projects/openssl.py  4
- varats/projects/c_projects/busybox.py  5
- varats/projects/c_projects/coreutils.py  3
- varats/projects/c_projects/gravity.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-07 14:34 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Clones added
============
- varats/projects/c_projects/tmux.py  4
- varats/projects/c_projects/coreutils.py  3
- varats/projects/c_projects/gravity.py  3
- varats/projects/c_projects/busybox.py  5
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/lrzip.py  4
- varats/projects/c_projects/libvpx.py  4
- varats/projects/c_projects/openssl.py  4
- varats/projects/c_projects/xz.py  3
- varats/projects/c_projects/glibc.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-07 14:45 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
           

Clones added
============
- varats/projects/c_projects/lrzip.py  4
- varats/projects/c_projects/libvpx.py  4
- varats/projects/c_projects/gzip.py  1
- varats/experiments/commit_report_experiment.py  1
- varats/projects/c_projects/openssl.py  4
- varats/experiments/just_compile.py  1
- varats/projects/c_projects/tmux.py  4
- varats/projects/c_projects/xz.py  3
- varats/projects/c_projects/glibc.py  4
- varats/projects/c_projects/gravity.py  3
- varats/projects/c_projects/busybox.py  5
- varats/projects/c_projects/coreutils.py  3
- varats/experiments/phasar_env_analysis.py  2
- varats/experiments/vara_full_mtfa.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-07 14:59 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
           

Clones added
============
- varats/projects/c_projects/libvpx.py  4
- varats/projects/c_projects/tmux.py  4
- varats/projects/c_projects/gravity.py  3
- varats/projects/c_projects/coreutils.py  3
- varats/projects/c_projects/gzip.py  1
- varats/experiments/just_compile.py  1
- varats/experiments/phasar_env_analysis.py  2
- varats/experiments/commit_report_experiment.py  1
- varats/projects/c_projects/xz.py  3
- varats/experiments/vara_full_mtfa.py  2
- varats/projects/c_projects/busybox.py  5
- varats/projects/c_projects/glibc.py  4
- varats/projects/c_projects/openssl.py  4
- varats/projects/c_projects/lrzip.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-07 15:04 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
           

Clones added
============
- varats/projects/c_projects/tmux.py  4
- varats/projects/c_projects/gravity.py  3
- varats/projects/c_projects/openssl.py  4
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/xz.py  3
- varats/projects/c_projects/glibc.py  4
- varats/projects/c_projects/busybox.py  5
- varats/experiments/commit_report_experiment.py  1
- varats/experiments/vara_full_mtfa.py  2
- varats/projects/c_projects/libvpx.py  4
- varats/projects/c_projects/lrzip.py  4
- varats/experiments/phasar_env_analysis.py  2
- varats/projects/c_projects/coreutils.py  3
- varats/experiments/just_compile.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-07 15:05 UTC, boehmseb approved these changes

2020-05-07 15:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
           

Clones added
============
- varats/projects/c_projects/gzip.py  1
- varats/projects/c_projects/busybox.py  5
- varats/projects/c_projects/xz.py  3
- varats/projects/c_projects/openssl.py  4
- varats/projects/c_projects/lrzip.py  4
- varats/projects/c_projects/glibc.py  4
- varats/experiments/commit_report_experiment.py  1
- varats/projects/c_projects/coreutils.py  3
- varats/projects/c_projects/libvpx.py  4
- varats/experiments/vara_full_mtfa.py  2
- varats/experiments/phasar_env_analysis.py  2
- varats/experiments/just_compile.py  1
- varats/projects/c_projects/gravity.py  3
- varats/projects/c_projects/tmux.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5482658&bid=17966584)

2020-05-07 15:20 UTC, merged