Adds tables.
se-passau/VaRA-Tool-Suite pull request #279
Opened 2020-05-11 14:27 UTC by boehmseb

Adds tables as generate-able artefacts.

TODO:
- [ ] add table artefact type
- [ ] write docs
- [ ] moar tests
- [ ] example table(s)

2020-05-11 14:29 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/driver_table.py  11
- varats/tables/tables.py  3
- varats/tables/table.py  5
- varats/tables/__init__.py  2
         

Clones added
============
- varats/tools/driver_table.py  2
- varats/tables/tables.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-11 14:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tables/__init__.py  2
- varats/tools/driver_table.py  11
- varats/tables/tables.py  3
- varats/tables/table.py  5
         

Clones added
============
- varats/tools/driver_table.py  2
- varats/tables/tables.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-11 14:39 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tables/table.py  5
- varats/tables/tables.py  3
- varats/tools/driver_table.py  11
- varats/tables/__init__.py  2
         

Clones added
============
- varats/tables/tables.py  1
- varats/tools/driver_table.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-11 15:34 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tables/table.py  5
- varats/tables/__init__.py  2
- varats/tools/driver_table.py  11
- varats/tables/tables.py  3
         

Clones added
============
- varats/tools/driver_table.py  2
- varats/tables/tables.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-11 16:02 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/driver_table.py  11
- varats/tables/tables.py  3
- varats/tables/__init__.py  2
- varats/tables/table.py  4
         

Clones added
============
- varats/tools/driver_table.py  2
- varats/tables/tables.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-11 21:34 UTC, vulder reviewed
overall this looks quite good, for details I would need to build my own test table an try out the interface.
Do you have any specific questions/parts I should look at?

2020-05-11 21:34 UTC, vulder commented on varats/settings.py
> +        "desc": "Folder for generated plots",
```suggestion
        "desc": "Folder for generated tables",
```

2020-05-11 21:34 UTC, vulder commented on varats/tables/table.py
> +                stages='S' if self.table_kwargs['sep_stages'] else '',
Did you try f-strings here?

2020-05-12 08:08 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tables/tables.py  3
- varats/tables/__init__.py  2
- varats/tables/table.py  4
- varats/tools/driver_table.py  11
         

Clones added
============
- varats/tables/tables.py  1
- varats/tools/driver_table.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-12 08:08 UTC, boehmseb commented
If you have an idea for a table we need, I would be happy to try it out myself as an example.

2020-05-15 12:35 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tables/__init__.py  2
- varats/tables/tables.py  3
- varats/tables/overview_table.py  6
- varats/tables/table.py  4
- varats/tools/driver_table.py  11
         

Clones added
============
- varats/tables/tables.py  1
- varats/tools/driver_table.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-17 18:37 UTC, vulder requested changes
Works quite well for me :), we should talk on Monday about the current state and possible future problems, if there are any.

PS: I currently get this warning:
/home/vulder/git/vara-tool-suite/varats/tables/overview_table.py:50: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  keys=[case_study.project_name for case_study in case_studies]

2020-05-17 18:37 UTC, vulder commented on varats/tables/overview_table.py
> +    NAME = "overview"
```suggestion
    NAME = "b_diff_correlation_overview"
```

2020-05-17 18:37 UTC, vulder commented on varats/settings.py
> +        "default": None,
should we give this one a good default?

2020-05-17 18:37 UTC, vulder commented on varats/settings.py
> +        "desc": "Local data cache to store preprocessed files."
should be duplicate this? I would assume that tables use mostly the same databases as plots, therefore, the two config values should point to the same folder. Maye we should move `data_cache` to the general level of options so it is not in the sub config space of plots.

2020-05-17 18:37 UTC, vulder commented on varats/tools/driver_table.py
> +            LOG.error(f"Could not find output dir {args['table_dir']}")
in general we should create these folders if they are not there. If I remember correctly this currently is done in `settings.py` when generating a new config.

2020-05-17 18:37 UTC, vulder commented on varats/tables/overview_table.py
> +            keys=[case_study.project_name for case_study in case_studies]
I assume this correctly attaches the project names as key for the generated values.
In general `project_name` for case studies is not unique, one can create to versions of a case study from the same project. So, depending on if we have a duplicate project name, we should attach the version to the name.

2020-05-18 12:04 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tables/__init__.py  2
- varats/tables/tables.py  3
- varats/tools/driver_table.py  11
- varats/tables/table.py  4
- varats/tables/overview_table.py  6
         

Clones added
============
- varats/tables/tables.py  1
- varats/tools/driver_table.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-18 14:49 UTC, boehmseb commented on varats/settings.py
> +        "default": None,
`plot_dir` doesn't have one so I didn't assign one here either. But we can change that if you want.

2020-05-18 14:51 UTC, boehmseb commented on varats/settings.py
> +        "default": None,
`plots` creates a default in `save_config()`. I assume this is to get the absolute path right. I will do the same for tables.

2020-05-18 15:25 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/settings.py  1
- varats/tables/tables.py  3
- varats/tables/diff_correlation_overview_table.py  5
- varats/tables/__init__.py  2
- varats/tools/driver_table.py  11
- varats/tables/table.py  4
         

Clones added
============
- varats/tables/tables.py  1
- varats/tools/driver_table.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-18 15:25 UTC, boehmseb commented on varats/tools/driver_table.py
> +            LOG.error(f"Could not find output dir {args['table_dir']}")
I added an entry to the function you mentioned, but I am leaving this check anyway because in theory this can still happen.

2020-05-18 15:25 UTC, boehmseb commented on varats/tables/overview_table.py
> +            keys=[case_study.project_name for case_study in case_studies]
I created a helper function in `case_study.py` to do this assuming that we will need this again in the future.

2020-05-18 15:26 UTC, boehmseb commented on varats/settings.py
> +        "desc": "Local data cache to store preprocessed files."
I lifted this option to the `varats` namespace

2020-05-18 15:33 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tables/diff_correlation_overview_table.py  6
- varats/tables/tables.py  3
- varats/tables/__init__.py  2
- varats/tools/driver_table.py  11
- varats/settings.py  1
- varats/tables/table.py  4
         

Clones added
============
- varats/tables/tables.py  1
- varats/tools/driver_table.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-19 08:59 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tables/table.py  4
- varats/tools/driver_table.py  11
- varats/tables/diff_correlation_overview_table.py  6
- varats/tables/tables.py  3
- varats/settings.py  1
- varats/tables/__init__.py  2
         

Clones added
============
- varats/tools/driver_table.py  2
- varats/tables/tables.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-20 06:50 UTC, boehmseb commented
> PS: I currently get this warning:
> /home/vulder/git/vara-tool-suite/varats/tables/overview_table.py:50: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
> of pandas will change to not sort by default.
> 
> To accept the future behavior, pass 'sort=False'.
> 
> To retain the current behavior and silence the warning, pass 'sort=True'.
> 
> keys=[case_study.project_name for case_study in case_studies]

Pandas 1.0.3 does not give me this warning.

2020-05-20 06:53 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/settings.py  1
- varats/tables/__init__.py  2
- varats/tables/diff_correlation_overview_table.py  6
- varats/tools/driver_table.py  11
- varats/tables/tables.py  3
- varats/tables/table.py  4
         

Clones added
============
- varats/tools/driver_table.py  2
- varats/tables/tables.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-20 10:50 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tables/tables.py  3
- varats/tables/__init__.py  2
- varats/tables/table.py  4
- varats/tools/driver_table.py  11
- varats/settings.py  1
- varats/tables/diff_correlation_overview_table.py  6
         

Clones added
============
- varats/tables/tables.py  1
- varats/tools/driver_table.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-20 10:58 UTC, vulder approved these changes
2 small nits otherwise we can merge this

2020-05-20 10:58 UTC, vulder commented on varats/tables/diff_correlation_overview_table.py
> +import typing as tp
hmm the module comment is missing, should't be this detected by the CI?

2020-05-20 10:58 UTC, vulder commented on varats/tables/tables.py
> +    to_snake_case_pattern = re.compile(r'(?<!^)(?=[A-Z])')
For constants I always used UPPER_CASE_SNAKE_CASE

2020-05-20 13:18 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/settings.py  1
- varats/tools/driver_table.py  11
- varats/tables/table.py  4
- varats/tables/tables.py  3
- varats/tables/diff_correlation_overview_table.py  6
- varats/tables/__init__.py  2
         

Clones added
============
- varats/tools/driver_table.py  2
- varats/tables/tables.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5503557&bid=18038708)

2020-05-20 13:43 UTC, merged