Implements block revision filter for case study generation
se-passau/VaRA-Tool-Suite pull request #286
Opened 2020-05-15 22:34 UTC by vulder

Adds a new flag to vara-cs, which allows the user to specify to ignore
blocked revisions when sampling revisions for a case study.

2020-05-15 22:35 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/data/test_revisions.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5535263&bid=18143994)

2020-05-18 14:47 UTC, boehmseb requested changes

2020-05-18 14:47 UTC, boehmseb commented on varats/paper/case_study.py
> +            rev_item[0], get_project_cls_by_name(case_study.project_name)
Extract variable `project_cls` to avoid making the lookup in every iteration.

2020-05-18 14:47 UTC, boehmseb commented on varats/paper/case_study.py
> +                commit_hash, get_project_cls_by_name(case_study.project_name)
Extract variable `project_cls` to avoid making the lookup in every iteration.

2020-05-19 18:46 UTC, vulder commented on varats/paper/case_study.py
> +            rev_item[0], get_project_cls_by_name(case_study.project_name)
good catch, done

2020-05-19 18:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/data/test_revisions.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5535263&bid=18143994)

2020-05-19 20:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/data/test_revisions.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5535263&bid=18143994)

2020-05-20 07:15 UTC, boehmseb approved these changes

2020-05-20 07:55 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/data/test_revisions.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5535263&bid=18143994)

2020-05-20 07:59 UTC, merged