F bug provider
se-passau/VaRA-Tool-Suite pull request #301
Opened 2020-05-29 14:25 UTC by SimonFedick

Introduces a bug.py file containing the classes PygitBug and HashBug, as well as functions to work with them. PygitBug Objects represent their introducing/fixing commits by Pygit2 Commit Objects while HashBug Objects represent them as Commit Hashes in strings.

2020-05-29 14:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/bug_annotation.py  8
- varats/plots/blame_interaction_degree.py  3
- varats/utils/github_util.py  5
- varats/data/provider/bug/bug_provider.py  5
- varats/data/provider/bug/bug.py  1
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-05-30 16:07 UTC, boehmseb reviewed
In general, I think this interface looks good.
I do not really like the name `HashCommit`, but then, I also can't come up with something better.
I added two comments, one of which is about docs formatting, and the other one is a question we should address in our next meeting.

2020-05-30 16:07 UTC, boehmseb commented on varats/data/provider/bug/bug.py
> +def find_pygit_bug_by_fix(fixing_commit: str) -> tp.Optional[PygitBug]:
Would it make sense for the _pygit_ versions of the functions to also take `pygit.Commit` objects as arguments?
I certainly would not do both versions as this will become too cluttered.

2020-05-30 16:07 UTC, boehmseb commented on varats/data/provider/bug/bug.py
> +    """Bug representation using the pygit2 Commit Class."""
```suggestion
    """Bug representation using the ``pygit2.Commit`` class."""
```
I always use monospaced font (enclose in two backticks for docstrings) for class names, functions, etc. so that it is clear that we are talking about program constructs and not more general concepts (e.g., ``pygit2.Commit`` vs commit).

Also, nouns are in general written in lowercase, except for actual class names of course ;)

2020-06-01 14:00 UTC, vulder commented on varats/data/provider/bug/bug.py
> +class HashBug:
hmm the name sounds a bit strange, alternatives?
@boehmseb 
@SimonFedick

2020-06-01 14:00 UTC, vulder commented on varats/data/provider/bug/bug.py
> +def find_pygit_bug_by_fix(fixing_commit: str) -> tp.Optional[PygitBug]:
Both could be cluttered yes, but from my perspective I would suggest to just use `str`. The caller normally should have a hash an not an commit. An in the case he has one, retrieving the hash is easy.
Or alternative is also to provide both with the same method and use python ducktyping + instanceof tricks to find out what was passed.

2020-06-01 14:00 UTC, vulder commented on varats/data/provider/bug/bug_provider.py
> +        return {}
@boehmseb as I understood the provider structure, the caller only has an provider and needs to call the accessor functions on the provider. Currently they are just functions in the bug module.

2020-06-01 14:00 UTC, vulder commented on varats/settings.py
> +    }
```suggestion
```
Provider should not define their own cache but use the general `data_cache` in the base config.

2020-06-01 14:00 UTC, vulder commented on varats/utils/github_util.py
> +import logging
Module docstring missing

2020-06-01 14:00 UTC, vulder commented on varats/utils/github_util.py
> +import logging
Should we put the github interacting stuff into utils? Will this be used by other code than just but the inter bug provider?
If only the bug code uses it, we should move the module into the `bug/` subfolder

2020-06-01 14:00 UTC, vulder commented on varats/utils/github_util.py
> +        CFG["provider"]["data_cache"])) / f"pygithub_{cache_file_name}"
needs adaption to use the general `data_cache`

2020-06-01 14:00 UTC, vulder commented on varats/plots/bug_annotation.py
> +Annotate CVE/CWE data to a plot.
Is this module/function shared between bugs and cve's or is it a different impl adapted for bugs?

2020-06-01 14:11 UTC, vulder commented on varats/data/provider/bug/bug.py
> +class HashBug:
RawBug it is :)

2020-06-01 14:15 UTC, boehmseb commented on varats/data/provider/bug/bug_provider.py
> +        return {}
Yes, the module-level functions from bug.py should be integrated here as an interface.

2020-06-01 14:16 UTC, boehmseb commented on varats/plots/bug_annotation.py
> +Annotate CVE/CWE data to a plot.
Its an adapted implementation where I forgot to change this doc string.

2020-06-01 15:01 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/utils/github_util.py  5
- varats/data/provider/bug/bug_provider.py  5
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug.py  1
- varats/plots/bug_annotation.py  8
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-06-21 20:46 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           

Complexity increasing per file
==============================
- varats/plots/blame_interaction_degree.py  3
- varats/utils/github_util.py  5
- varats/plots/bug_annotation.py  8
- varats/data/provider/bug/bug_provider.py  5
- varats/data/provider/bug/bug.py  1
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-06-22 14:06 UTC, vulder commented on varats/utils/github_util.py
> +import logging
let's keep it in utils

2020-06-23 14:13 UTC, SimonFedick commented on varats/data/provider/bug/bug_provider.py
> +        return {}
The BugProvider class now provides wrapper functions for the bug.py functions.

2020-06-23 14:14 UTC, SimonFedick commented on varats/settings.py
> +    }
Provider now uses the general data cache instead.

2020-06-23 14:16 UTC, SimonFedick commented on varats/utils/github_util.py
> +import logging
Does the new docstring fit its module?

2020-06-23 14:20 UTC, SimonFedick commented on varats/utils/github_util.py
> +        CFG["provider"]["data_cache"])) / f"pygithub_{cache_file_name}"
It now uses the general data_cache.

2020-06-23 14:51 UTC, boehmseb commented on varats/utils/github_util.py
> +import logging
I would say, this module is more general. Maybe something like `Utility module for working with the pygithub API.`

2020-06-23 15:49 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 24
           

Complexity increasing per file
==============================
- varats/utils/github_util.py  5
- varats/data/provider/bug/bug_provider.py  5
- varats/plots/blame_interaction_degree.py  3
- varats/plots/bug_annotation.py  8
- varats/data/provider/bug/bug.py  1
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-06-24 18:23 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 24
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  1
- varats/plots/bug_annotation.py  8
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug_provider.py  5
- varats/utils/github_util.py  5
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-06-24 18:24 UTC, SimonFedick commented on varats/utils/github_util.py
> +import logging
Alright, I went with that.

2020-07-20 08:43 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 17
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug_provider.py  2
- varats/plots/bug_annotation.py  8
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug.py  1
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-07-20 09:01 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 16
           

Complexity increasing per file
==============================
- varats/plots/bug_annotation.py  8
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug_provider.py  2
- varats/data/provider/bug/bug.py  1
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-07-20 10:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 16
           

Complexity increasing per file
==============================
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug.py  1
- varats/data/provider/bug/bug_provider.py  2
- varats/plots/bug_annotation.py  7
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-07-20 22:39 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 16
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  1
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug_provider.py  2
- varats/plots/bug_annotation.py  7
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-07-30 09:15 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 14
           

Complexity increasing per file
==============================
- varats/plots/bug_annotation.py  7
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug.py  1
- varats/data/provider/bug/bug_provider.py  2
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-07-30 09:17 UTC, vulder requested changes

2020-07-30 09:17 UTC, vulder commented on varats/data/provider/bug/bug.py
> +        Name of the project in which to search for bugs
```suggestion
    Args:
        project_name: Name of the project in which to search for bugs
```

2020-07-30 09:17 UTC, vulder commented on varats/data/provider/bug/bug.py
> +        A set of PygitBug Objects.
```suggestion
    Returns: A set of PygitBug Objects.
```

2020-07-30 09:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 12
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  1
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug_provider.py  2
- varats/plots/bug_annotation.py  7
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-07-30 09:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 13
           

Complexity increasing per file
==============================
- varats/plots/bug_annotation.py  7
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug_provider.py  2
- varats/data/provider/bug/bug.py  1
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-07-30 09:56 UTC, SimonFedick commented on varats/data/provider/bug/bug.py
> +        A set of PygitBug Objects.
I adjusted the format as requested.

2020-07-30 09:57 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 13
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  1
- varats/plots/blame_interaction_degree.py  3
- varats/plots/bug_annotation.py  7
- varats/data/provider/bug/bug_provider.py  2
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-07-30 11:11 UTC, vulder approved these changes

2020-07-30 11:11 UTC, vulder commented on requirements.txt
> +benchbuild>=4.0.1
```suggestion
benchbuild>=4.1.0
```

2020-07-30 11:13 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 13
           

Complexity increasing per file
==============================
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug.py  1
- varats/plots/bug_annotation.py  7
- varats/data/provider/bug/bug_provider.py  2
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5608203&bid=18375623)

2020-07-30 12:04 UTC, merged