Implements setup for research tool phasar
se-passau/VaRA-Tool-Suite pull request #304
Opened 2020-05-30 23:40 UTC by vulder

2020-05-31 11:09 UTC, boehmseb requested changes
Found a few places where you forgot to replace _vara_ and a few other small things.
Otherwise, this works fine for me.

2020-05-31 11:09 UTC, boehmseb commented on varats/tools/research_tools/phasar.py
> +        Checkout out a specific version of VaRA.
```suggestion
        Checkout out a specific version of phasar.
```

2020-05-31 11:09 UTC, boehmseb commented on varats/tools/research_tools/phasar.py
> +    def checkout_phasar_version(self, use_dev_branche: bool) -> None:
`use_dev_branche` -> `use_dev_branch`

2020-05-31 11:09 UTC, boehmseb commented on varats/tools/research_tools/phasar.py
> +        Setup the research tool VaRA with it's code base. This method sets up
```suggestion
        Setup the research tool phasar with it's code base. This method sets up
```

2020-05-31 11:09 UTC, boehmseb commented on varats/tools/research_tools/research_tool.py
> +    @abc.abstractstaticmethod
`@abc.abstractstaticmethod` is deprecated. Use `@staticmethod` with `@abstractmethod` instead.
Same goes for `@classmethod` and similar, if you should need them.

2020-05-31 11:09 UTC, boehmseb commented on varats/utils/cli_util.py
> +def get_research_tool_type(name: str) -> tp.Type[ConcreteResearchTool]:
According to https://github.com/python/mypy/issues/2756, this `TypeVar`s cannot depend on `TypeVar`s in the current type system of python. Replacing `SpecificCodeBase` with `CodeBase` or `Any` did not help either, as the types of the concrete research tools cannot be matched then.

The best solution I could find is:
```suggestion
def get_research_tool_type(name: str) -> tp.Type[ResearchTool[tp.Any]]:
```

2020-05-31 11:09 UTC, boehmseb commented on varats/utils/cli_util.py
> +    return ["VaRA", "vara", "phasar"]
I suggest to drop `VaRA` from this list. Instead, you could now specify a `key_normalizer` in the CLI-parser (s. https://github.com/madman-bob/python-argparse-utils). 

```suggestion
    return ["vara", "phasar"]
```

2020-05-31 14:53 UTC, boehmseb approved these changes
lgtm

2020-06-02 09:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/tools/research_tools/phasar.py  6
         

Clones added
============
- varats/tools/research_tools/phasar.py  1
- varats/tools/research_tools/vara.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5612609&bid=18386596)

2020-06-02 10:24 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/research_tools/phasar.py  6
         

Clones added
============
- varats/tools/research_tools/vara.py  1
- varats/tools/research_tools/phasar.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5612609&bid=18386596)

2020-06-02 10:53 UTC, pdschubert approved these changes
Looks good to me.

2020-06-02 12:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/research_tools/phasar.py  6
         

Clones added
============
- varats/tools/research_tools/phasar.py  1
- varats/tools/research_tools/vara.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5612609&bid=18386596)

2020-06-02 12:40 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/research_tools/phasar.py  6
         

Clones added
============
- varats/tools/research_tools/vara.py  1
- varats/tools/research_tools/phasar.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5612609&bid=18386596)

2020-06-02 12:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/research_tools/phasar.py  6
         

Clones added
============
- varats/tools/research_tools/vara.py  1
- varats/tools/research_tools/phasar.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5612609&bid=18386596)

2020-06-02 12:59 UTC, merged