F phasar experiment rework
se-passau/VaRA-Tool-Suite pull request #306
Opened 2020-05-31 21:38 UTC by vulder

2020-06-01 17:40 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- varats/utils/bb_config.py  5
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- tests/utils/test_bb_config.py  7
- varats/tools/research_tools/phasar.py  6
- varats/experiments/phasar/add_experiment_name.py  3
- varats/experiments/vara/blame_report_experiment.py  3
- tests/utils/test_cli_util.py  2
         

Clones added
============
- varats/experiments/vara/vara_fc_taint_analysis.py  1
- varats/tools/research_tools/phasar.py  1
- varats/tools/research_tools/vara.py  1
- varats/experiments/phasar/add_experiment_name.py  4
- varats/experiments/vara/blame_report_experiment.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-02 14:12 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- varats/experiments/vara/blame_report_experiment.py  3
- tests/utils/test_bb_config.py  7
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- varats/experiments/phasar/add_experiment_name.py  3
- varats/utils/bb_config.py  5
- tests/utils/test_cli_util.py  2
         

Clones added
============
- varats/experiments/vara/blame_report_experiment.py  2
- varats/experiments/vara/vara_fc_taint_analysis.py  1
- varats/experiments/phasar/add_experiment_name.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-02 14:38 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/utils/test_cli_util.py  2
- tests/utils/test_bb_config.py  7
- varats/utils/bb_config.py  5
- varats/experiments/vara/blame_report_experiment.py  3
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  8
         

Clones added
============
- varats/experiments/vara/blame_report_experiment.py  2
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
- varats/experiments/vara/vara_fc_taint_analysis.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-02 14:57 UTC, vulder commented on varats/experiments/phasar/ide_linear_constant_experiment.py
> +    DESCRIPTION = "TODO"  # TODO (@pdschubert): please add
@pdschubert Could you please add a short description here?

2020-06-03 12:29 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- varats/utils/bb_config.py  5
- varats/experiments/vara/blame_report_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- tests/utils/test_bb_config.py  7
- tests/utils/test_cli_util.py  2
         

Clones added
============
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
- varats/experiments/vara/blame_report_experiment.py  2
- varats/experiments/vara/vara_fc_taint_analysis.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-03 14:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/utils/test_cli_util.py  2
- varats/utils/bb_config.py  5
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- varats/experiments/vara/blame_report_experiment.py  3
- tests/utils/test_bb_config.py  7
- varats/experiments/vara/vara_fc_taint_analysis.py  8
         

Clones added
============
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
- varats/experiments/vara/blame_report_experiment.py  2
- varats/experiments/vara/vara_fc_taint_analysis.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-03 17:26 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/utils/test_cli_util.py  2
- tests/utils/test_bb_config.py  7
- varats/utils/bb_config.py  5
- varats/experiments/vara/blame_report_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
         

Clones added
============
- varats/experiments/vara/blame_report_experiment.py  2
- varats/experiments/vara/vara_fc_taint_analysis.py  1
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-03 19:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- tests/utils/test_bb_config.py  7
- tests/utils/test_cli_util.py  2
- varats/utils/bb_config.py  5
- varats/experiments/vara/blame_report_experiment.py  3
         

Clones added
============
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
- varats/experiments/vara/vara_fc_taint_analysis.py  1
- varats/experiments/vara/blame_report_experiment.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-10 11:41 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/utils/test_cli_util.py  2
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- tests/utils/test_bb_config.py  7
- varats/experiments/vara/blame_report_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- varats/utils/bb_config.py  5
         

Clones added
============
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
- varats/experiments/vara/blame_report_experiment.py  2
- varats/experiments/vara/vara_fc_taint_analysis.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-12 10:16 UTC, boehmseb requested changes

2020-06-12 10:16 UTC, boehmseb commented on tests/utils/test_cli_util.py
> +        with replace_config() as vara_cfg:
If you pass your temp dir to the `replace_config` context manager it will also use it for the rest of the "mokced" environment instead of creating an own temp dir.

2020-06-12 10:16 UTC, boehmseb commented on tests/utils/test_cli_util.py
> +        with replace_config() as _:
If the `as` is not used, you can omit it (this holds for all context managers).

```suggestion
        with replace_config():
```

2020-06-12 10:16 UTC, boehmseb commented on varats/experiments/phasar/ide_linear_constant_experiment.py
> +    """Analysis step to run phasars IDELinearConstantAnalysis on a project."""
```suggestion
    """Analysis step to run phasar's IDELinearConstantAnalysis on a project."""
```

2020-06-12 10:16 UTC, boehmseb commented on varats/experiments/phasar/ide_linear_constant_experiment.py
> +        """Run phasars IDELinearConstantAnalysis analysis."""
```suggestion
        """Run phasar's IDELinearConstantAnalysis analysis."""
```

2020-06-12 13:26 UTC, boehmseb approved these changes

2020-06-12 22:45 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- varats/experiments/vara/blame_report_experiment.py  3
- varats/utils/bb_config.py  5
- tests/utils/test_bb_config.py  7
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- tests/utils/test_cli_util.py  2
         

Clones added
============
- varats/experiments/vara/vara_fc_taint_analysis.py  1
- varats/experiments/vara/blame_report_experiment.py  2
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-13 20:46 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/vara/blame_report_experiment.py  3
- tests/utils/test_cli_util.py  2
- tests/utils/test_bb_config.py  7
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- varats/utils/bb_config.py  5
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
         

Clones added
============
- varats/experiments/vara/blame_report_experiment.py  2
- varats/experiments/vara/vara_fc_taint_analysis.py  1
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-15 16:10 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- varats/experiments/vara/blame_report_experiment.py  3
- tests/utils/test_bb_config.py  7
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- varats/experiments/vara/blame_verifier_experiment.py  3
- tests/utils/test_cli_util.py  2
- varats/utils/bb_config.py  5
         

Clones added
============
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- varats/experiments/vara/blame_report_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  1
- varats/experiments/vara/blame_verifier_experiment.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-15 16:54 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- varats/utils/bb_config.py  5
- varats/experiments/vara/blame_verifier_experiment.py  3
- tests/utils/test_bb_config.py  7
- varats/experiments/vara/blame_report_experiment.py  3
- tests/utils/test_cli_util.py  2
         

Clones added
============
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
- varats/experiments/vara/vara_fc_taint_analysis.py  1
- varats/experiments/vara/blame_verifier_experiment.py  3
- varats/experiments/vara/blame_report_experiment.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-16 08:22 UTC, pdschubert commented on varats/experiments/phasar/ide_linear_constant_experiment.py
> +    DESCRIPTION = "TODO"  # TODO (@pdschubert): please add
Done.

2020-06-16 08:22 UTC, pdschubert approved these changes

2020-06-16 08:23 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/utils/test_bb_config.py  7
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- tests/utils/test_cli_util.py  2
- varats/utils/bb_config.py  5
- varats/experiments/vara/blame_report_experiment.py  3
- varats/experiments/vara/blame_verifier_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  8
         

Clones added
============
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
- varats/experiments/vara/blame_report_experiment.py  3
- varats/experiments/vara/blame_verifier_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-16 08:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/experiments/vara/blame_report_experiment.py  3
- tests/utils/test_cli_util.py  2
- tests/utils/test_bb_config.py  7
- varats/experiments/vara/vara_fc_taint_analysis.py  8
- varats/utils/bb_config.py  5
- varats/experiments/phasar/ide_linear_constant_experiment.py  3
- varats/experiments/vara/blame_verifier_experiment.py  3
         

Clones added
============
- varats/experiments/vara/blame_report_experiment.py  3
- varats/experiments/vara/vara_fc_taint_analysis.py  1
- varats/experiments/phasar/ide_linear_constant_experiment.py  4
- varats/experiments/vara/blame_verifier_experiment.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5614223&bid=18391682)

2020-06-16 11:05 UTC, merged