Adds BlameMDVerifier Report to allow plots to access verifier results
se-passau/VaRA-Tool-Suite pull request #315
Opened 2020-06-26 11:36 UTC by cormensratio

Adds access functions to the BlameMDVerifier Report to allow plots to gain (Successful, Failed, Total) results of the verifier
closes #656

2020-06-26 11:38 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  4
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-06-28 11:57 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  4
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-06-30 15:33 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  4
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-06-30 15:57 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  6
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-06-30 16:09 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  6
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-01 09:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  8
         

Clones added
============
- tests/data/test_blame_verifier_report.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-01 09:50 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  8
         

Clones added
============
- tests/data/test_blame_verifier_report.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-01 09:56 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  8
         

Clones added
============
- tests/data/test_blame_verifier_report.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-01 11:07 UTC, vulder requested changes
Please do not attach full analysis files for testing. Test files should be reduced to only contain relevant content for testing.

2020-07-01 11:07 UTC, vulder commented on tests/data/test_blame_verifier_report.py
> +        # Given
You don't have to add these comments all the time, just an empty line normally is enough for small test cases.

2020-07-01 11:07 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +    redundancy in its BlameVerifierReport-Subclasses.
```suggestion
    Mixin to that implements shared functionality between different `BlameVerifierReports` with various extracted methods to avoid redundancy in its BlameVerifierReport-Subclasses, without adapting the Report hierarchy.
```

2020-07-01 11:07 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +            pattern = re.compile(result_regex.value)
You could give the pattern a better name to denote which kind/use case this pattern has.

2020-07-01 11:07 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +                                f"comparisons could not be "
Is this a comparisons? The word seems wrong to me in this context.

2020-07-01 11:07 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +                        )
You could also implement parsing for the failure cases.

2020-07-01 11:07 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +                warnings.warn(
This should not be a warning, because the case of `0` is just natural. Maybe use Info here.

2020-07-01 11:07 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +class BlameVerifierReportMixin(BaseReport):
This is not a mixin in the sense we talked about. This just introduces a base class. What we discussed was to add a mixin class that is pulled in via multiple inheritance. If you want an intermediate class in the hierarchy you should rename the class.

2020-07-01 11:07 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +        pass
This should not a report class, nothing generates 'mixin' reports. What you want is a class or function that just encapsulates the parsing and data access part, the class itself is not a report.

2020-07-01 11:07 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +class BlameVerifierReportMixin(BaseReport):
How is this used in the different BlameVerifierReports? I cannot find any accessor methods for users or any data that is parsed and saved in variables.

How can a user that has a file get easy access to the data?
```
my_blame_report = BlameVerifierReportOpt(Path('file path'))
failures = my_blame_report.????
```

2020-07-06 11:19 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  8
         

Clones added
============
- tests/data/test_blame_verifier_report.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-06 12:53 UTC, cormensratio commented on varats/data/reports/blame_verifier_report.py
> +            pattern = re.compile(result_regex.value)
Renamed to: result_annotation_regex

2020-07-06 12:58 UTC, cormensratio commented on varats/data/reports/blame_verifier_report.py
> +                        )
This is already implemented in the lines above. The number of failed annotations is retrieved by subtracting the successful annot. from the total annot., since they are not explicitly written in the BV-result files.

2020-07-06 12:58 UTC, cormensratio commented on varats/data/reports/blame_verifier_report.py
> +                                f"comparisons could not be "
Changed to: "annotations"

2020-07-06 13:38 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  8
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-09 14:35 UTC, vulder requested changes

2020-07-09 14:35 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +        )
This part belongs to the mixin. Furthermore, you should only parse the file once and save the computed numbers in local member variables. With this approach everytime one accesses, e.g., total annotations, everything needs to be recomputed.

2020-07-09 14:35 UTC, vulder commented on varats/data/reports/blame_verifier_report.py
> +        )
When generalized to the mixin only one imple of the accessor functions is needed

2020-07-10 17:33 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  10
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-16 09:37 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  10
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-16 09:50 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  10
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-16 10:20 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/data/reports/blame_verifier_report.py  10
         

Clones added
============
- tests/data/test_blame_verifier_report.py  2
- varats/data/reports/blame_verifier_report.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5763523&bid=18865732)

2020-07-20 22:22 UTC, vulder approved these changes

2020-07-20 22:22 UTC, merged