F find bugs
se-passau/VaRA-Tool-Suite pull request #318
Opened 2020-07-09 12:37 UTC by SimonFedick

Began implementing methods to find bugs in bug.py

2020-07-09 12:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 30
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug_provider.py  5
- varats/plots/bug_annotation.py  8
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug.py  5
- varats/utils/github_util.py  5
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-07-20 13:42 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 25
           

Complexity increasing per file
==============================
- varats/utils/github_util.py  5
- varats/data/provider/bug/bug_provider.py  2
- varats/data/provider/bug/bug.py  5
- varats/plots/blame_interaction_degree.py  3
- varats/plots/bug_annotation.py  8
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-07-20 14:01 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 23
           

Complexity increasing per file
==============================
- varats/plots/bug_annotation.py  8
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug_provider.py  2
- varats/utils/github_util.py  5
- varats/data/provider/bug/bug.py  5
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-07-30 10:37 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 17
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug_provider.py  2
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug.py  5
- varats/utils/github_util.py  5
- varats/plots/bug_annotation.py  7
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-07-30 10:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 12
           

Complexity increasing per file
==============================
- varats/plots/blame_interaction_degree.py  3
- varats/data/provider/bug/bug_provider.py  2
- varats/plots/bug_annotation.py  7
- varats/utils/github_util.py  5
- varats/data/provider/bug/bug.py  5
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-08-23 22:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 10
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug_provider.py  2
- varats/plots/bug_annotation.py  7
- varats/data/provider/bug/bug.py  6
- varats/utils/github_util.py  5
- varats/plots/blame_interaction_degree.py  3
         

Clones added
============
- varats/plots/bug_annotation.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-08-25 07:33 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 6
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  5
- varats/utils/github_util.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-08-25 07:44 UTC, vulder requested changes
Method naming is nice, makes the code easily readable.

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +    Loads and returns all issue events from a given project.
```suggestion
    Loads and returns all issue events for a given project.
```

2020-08-25 07:44 UTC, vulder commented on varats/utils/github_util.py
> +def get_github_instance() -> Github:
should this function be public and allow everyone to get directly an access token? Or is it only used inside the github_util?

2020-08-25 07:44 UTC, vulder commented on varats/utils/github_util.py
> +        LOG.error(e)
Can you provide a bit more information in the log message, before printing the actual error?

2020-08-25 07:44 UTC, vulder commented on varats/utils/github_util.py
> +) -> tp.Optional[PyGithubObj]:
Docs missing

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +    Decides for a given issue event whether it closes an issue representing a
```suggestion
    Determines for a given issue event whether it closes an issue representing a
```

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +def _has_closed_a_bug(issue_event: IssueEvent) -> bool:
Maybe add a few tests for this one, to check different cases and preserve basic functionality into the future, so we notice when we change something here.

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +) -> tp.Optional[tp.List[IssueEvent]]:
Can we remove the optional when we use an empty list in the case, where we currently use `None`?

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +        for issue_event in issue_events:
Check could be removed if we get rid of the optional.

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +    return frozenset(raw_bugs)
We could merge parts of this code with the PygitBug case and only factor out the different Bug creation strategies.

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +    return frozenset(resulting_pygit_bugs)
Same here, the basic skeleton of working on the issues is always the same.

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +    return frozenset(resulting_raw_bugs)
same

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +    return frozenset(resulting_pygit_bugs)
Also similar, but here we do more. Maybe the issue_event loop could be a good candidate to be factored out.

2020-08-25 07:44 UTC, vulder commented on varats/data/provider/bug/bug.py
> +                fixing_id = issue_event.commit_id
same

2020-08-25 08:02 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 6
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  5
- varats/utils/github_util.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-08-25 08:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 6
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  5
- varats/utils/github_util.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-08-25 08:39 UTC, boehmseb requested changes

2020-08-25 08:39 UTC, boehmseb commented on varats/data/provider/bug/bug.py
> +) -> tp.Optional[tp.List[IssueEvent]]:
Should be possible

2020-08-25 08:39 UTC, boehmseb commented on varats/utils/github_util.py
> +def get_github_instance() -> Github:
This is a convenience accessor to the Github API object that automatically uses an access token if set in the configuration.
I think we should leave this public, at least as long as the caching is not completely implemented (see below).

2020-08-25 08:39 UTC, boehmseb commented on varats/utils/github_util.py
> +def get_cached_github_object(
I'm not sure if `PaginatedList`s are handled correctly. @SimonFedick have you tested this?

2020-08-25 08:39 UTC, boehmseb commented on varats/data/provider/bug/bug.py
> +                        fixing_id, introducing_ids, issue_event.issue.number
Type error: `fixing_id` is a `Optional[str]` but `RawBug` expects a `str`.

2020-08-25 08:39 UTC, boehmseb commented on varats/data/provider/bug/bug.py
> +                                fixing_id, introducing_ids,
Type error: `fixing_id` is a `Optional[str]` but `RawBug` expects a `str`.

2020-08-25 08:39 UTC, boehmseb commented on varats/data/provider/bug/bug.py
> +    return get_cached_github_object(cache_file_name, load_issue_events)
Type error: `get_cached_github_object` returns an `Optional[PyGithubObj]'

2020-08-25 08:39 UTC, boehmseb commented on varats/utils/github_util.py
> +            return tp.cast(PyGithubObj, github.load(cache_file))
Type error: Argument 1 to "load" of "Github" has incompatible type "Path"; expected "BytesIO"

2020-08-25 08:39 UTC, boehmseb commented on varats/utils/github_util.py
> +        github.dump(obj_to_cache, cache_file, protocol=4)
Type error: Argument 1 to "dump" of "Github" has incompatible type "Path"; expected "BytesIO"

2020-08-25 08:39 UTC, boehmseb commented on varats/data/provider/bug/bug_provider.py
>  from github import Github
`Github` and  `Repository` are unused imports.

2020-09-05 23:23 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 8
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  5
- varats/utils/github_util.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-05 23:42 UTC, SimonFedick commented on varats/data/provider/bug/bug.py
> +    return frozenset(raw_bugs)
I factored out the common part of the issue event loop into the separate functions `_search_corresponding_pygit_bug` and `_search_corresponding_raw_bug`.

2020-09-06 15:03 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 8
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  5
- varats/utils/github_util.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-07 12:17 UTC, vulder commented on varats/data/provider/bug/bug.py
> +    return frozenset(resulting_pygit_bugs)
```suggestion
    def some_usefull_name(issue_event):
          pygit_repo = get_local_project_git(project_name)
          pybug: PygitBug = _search_corresponding_pygit_bug(
              issue_event, pygit_repo
          )

          if pybug:
              for introducing_pycommit in pybug.introducing_commits:
                  if introducing_pycommit.hex is introducing_commit:
                      return {pybug}
                      # search can be terminated here, found wanted ID
           return set()

    return for_all_issue_events(some_usefull_name)
```

+

```
def for_all_issue_events(process_issue_event: tp.Callable[[IssueEvent], tp.Set[PygitBug]]):
    resulting_pygit_bugs = set()

    issue_events = _get_all_issue_events(project_name)
    if issue_events:
        for issue_event in issue_events:
            resulting_pygit_bugs.update(process_issue_event(issue_event))

    return frozenset(resulting_pygit_bugs)
```

2020-09-07 12:58 UTC, boehmseb commented on varats/utils/github_util.py
> +            obj_to_cache = [item for item in obj_to_cache]
```suggestion
            obj_to_cache = list(obj_to_cache)
```

2020-09-15 17:02 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 7
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  5
- varats/utils/github_util.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-15 17:47 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 8
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  4
- varats/utils/github_util.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-15 18:21 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 9
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  4
- varats/utils/github_util.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-15 18:39 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 9
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  4
- varats/utils/github_util.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-15 18:54 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 9
           

Complexity increasing per file
==============================
- varats/data/provider/bug/bug.py  4
- varats/utils/github_util.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-16 15:24 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 18
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-17 07:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 9
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-18 20:57 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 8
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-18 21:33 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 6
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-18 21:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 6
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-21 07:41 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 6
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-21 07:57 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-21 08:10 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 3
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-21 12:24 UTC, boehmseb commented on tests/utils/test_github_util.py
> +        # with tempfile.TemporaryDirectory() as tmpdir:
```suggestion
```

2020-09-21 12:24 UTC, boehmseb commented on tests/utils/test_github_util.py
> +        # with tempfile.TemporaryDirectory() as tmpdir:
```suggestion
```

2020-09-21 12:25 UTC, vulder approved these changes

2020-09-21 17:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 3
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-22 08:15 UTC, boehmseb requested changes
There is still a line that is too long.

After fixing that and a couple of tests we should be ready for merging

2020-09-22 08:15 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +        issue_filter_function: Function that determines for an issue event whether it produces
This line is still too long.

2020-09-22 19:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 6
           

Complexity increasing per file
==============================
- tests/provider/test_bug_provider.py  1
- tests/utils/test_github_util.py  2
- varats-core/varats/provider/bug/bug.py  4
- varats-core/varats/utils/github_util.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-22 19:24 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 2
           

Complexity increasing per file
==============================
- varats-core/varats/provider/bug/bug.py  4
- tests/utils/test_github_util.py  2
- varats-core/varats/utils/github_util.py  5
- tests/provider/test_bug_provider.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-23 08:01 UTC, boehmseb commented on tests/provider/test_bug_provider.py
> +        )
You are using `Mock` not quite correctly. The `return_value` is only used for functions. Other members can be assigned directly. Also, I recommend using autospeccing, as this ensures that the mock has the same interface as the real object.

You need to fix this in all of your tests, as the other two tests only pass by chance.

Here an example for the first test case:
```suggestion
        # mock issue with correct labels
        bug_label = create_autospec(Label)
        bug_label.name = "bug"
        irrelevant_label = create_autospec(Label)
        irrelevant_label.name = "good first issue"

        issue = create_autospec(Issue)
        issue.labels = [irrelevant_label, bug_label]
        issue.id = 1

        # sane mock issue event
        issue_event_bug = create_autospec(IssueEvent)
        issue_event_bug.event = "closed"
        issue_event_bug.commit_id = "1234"
        issue_event_bug.issue = issue

        # mock issue event without corresponding commit
        issue_event_no_commit = create_autospec(IssueEvent)
        issue_event_no_commit.event = "closed"
        issue_event_no_commit.commit_id = None
        issue_event_no_commit.issue = issue
```

2020-09-23 08:03 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +def _search_corresponding_pygit_bug(
Would be nice to also have a test for this.

2020-09-23 14:17 UTC, SimonFedick commented on varats-core/varats/provider/bug/bug.py
> +def _search_corresponding_pygit_bug(
I'm not entirely sure how to simulate introducing commits for a test case yet and I would fail them so far since that part is not yet implemented. For now, I could test whether the method detects and parses the fixing commit correctly (and whether it returns "None" in case of `_has_closed_a_bug` returning `false`, but I'm already covering that method).

2020-09-23 14:23 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +def _search_corresponding_pygit_bug(
> For now, I could test whether the method detects and parses the fixing commit correctly

Exactly that.

2020-09-26 13:53 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 7
           

Complexity increasing per file
==============================
- tests/provider/test_bug_provider.py  1
- varats-core/varats/utils/github_util.py  5
- tests/utils/test_github_util.py  2
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-26 14:07 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 3
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- tests/provider/test_bug_provider.py  1
- varats-core/varats/provider/bug/bug.py  4
- varats-core/varats/utils/github_util.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-26 14:16 UTC, SimonFedick commented on varats-core/varats/provider/bug/bug.py
> +def _search_corresponding_pygit_bug(
Should I also test this for `_search_corresponding_raw_bug`?

2020-09-26 14:58 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 2
           

Complexity increasing per file
==============================
- tests/utils/test_github_util.py  2
- tests/provider/test_bug_provider.py  1
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-26 15:05 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 2
           

Complexity increasing per file
==============================
- varats-core/varats/utils/github_util.py  5
- varats-core/varats/provider/bug/bug.py  4
- tests/provider/test_bug_provider.py  1
- tests/utils/test_github_util.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-28 09:07 UTC, boehmseb approved these changes

2020-09-28 09:13 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 2
           

Complexity increasing per file
==============================
- varats-core/varats/utils/github_util.py  5
- tests/utils/test_github_util.py  2
- tests/provider/test_bug_provider.py  1
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5828276&bid=19082835)

2020-09-28 09:18 UTC, merged