Converts first LibraryAnalysis repository to a benchbuild project
se-passau/VaRA-Tool-Suite pull request #324
Opened 2020-08-06 21:30 UTC by cormensratio

2020-08-06 21:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- varats/projects/cpp_projects/elementalist.py  3
         

Clones added
============
- varats/projects/cpp_projects/elementalist.py  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-08-12 17:01 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-08-16 20:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-08-24 15:39 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         

Clones added
============
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-08-25 18:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         

Clones added
============
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-01 10:35 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         

Clones added
============
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-02 10:52 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         

Clones added
============
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-02 11:22 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         

Clones added
============
- varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-02 12:26 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         

Clones added
============
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-02 13:00 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         

Clones added
============
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-02 13:05 UTC, cormensratio commented
Codacy: Should I try to find another name for the whole project, since the name does not conform with snake style naming?

- Is the addition of the project name to the bb_config.py everything i need to do, in order to (run experiments)/(find the new project)?
- Can I assume that the current project state works if just_compile finishes without an error?

2020-09-03 10:34 UTC, vulder commented
> Codacy: Should I try to find another name for the whole project, since the name does not conform with snake style naming?
> 
> * Can I assume that the current project state works if just_compile finishes without an error?

Yes, for the class and module name you should choose a valid name.

If just_compile finishes without errors it normally works.

2020-09-03 10:39 UTC, vulder requested changes
Found a fews things, did you just copy the compile function? This seems a bit off for your library.

2020-09-03 10:39 UTC, vulder commented on varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py
> +    DOMAIN = 'analysis'
```suggestion
    DOMAIN = 'library-testproject'
```

2020-09-03 10:39 UTC, vulder commented on varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py
> +        return wrap_paths_to_binaries(["elementalist"])
Is this really the full path to the generated binary?

2020-09-03 10:39 UTC, vulder commented on varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py
> +        git_path = get_local_project_git_path(self.NAME)
```suggestion
        library_source_folder = get_local_project_git_path(self.NAME)
```

2020-09-03 10:39 UTC, vulder commented on varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py
> +                bb.watch(make)("-j", get_number_of_jobs(bb_cfg()))
Why do you need a special compile function for make? If I remember correctly, you only support cmake in your lib.

2020-09-03 10:39 UTC, vulder commented on varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py
> +        version_source = bb.path(self.source_of_primary)
```suggestion
        version_source = local.path(self.source_of_primary)
```

2020-09-03 10:39 UTC, vulder commented on varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py
> +        version_source = bb.path(self.source_of_primary)
```suggestion
        version_source = local.path(self.source_of_primary)
```

2020-09-03 11:12 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         

Clones added
============
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-07 06:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-07 12:18 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-11 08:54 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-15 13:05 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-17 13:04 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-17 14:15 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-18 12:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-22 12:40 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-22 18:26 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-25 08:19 UTC, cormensratio commented
As long as multiple VaraTestRepoSources are not working, one has to ensure that the necessary libs are located as git repositories in the benchbuild/tmp dir.

2020-09-28 11:54 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-28 13:14 UTC, vulder approved these changes
lgtm

2020-09-28 13:14 UTC, vulder commented on varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py
> +        path_to_libs_in_tmp = version_source / "../../../../../tmp"
You can get the path to the BB tmp dir from the BB config

2020-09-28 13:52 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5977264&bid=19599711)

2020-09-28 14:02 UTC, merged