Refactors CaseStudy out into varats-core
se-passau/VaRA-Tool-Suite pull request #366
Opened 2020-09-15 08:52 UTC by vulder

2020-09-15 08:56 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 78
- Added 33
           

Complexity increasing per file
==============================
- varats/varats/paper_mgmt/paper_config.py  6
- varats/varats/utilss/cli_util.py  8
- varats-core/varats/base/sampling_method.py  3
- varats-core/varats/provider/cve/cve_provider.py  5
- varats-core/varats/provider/cve/cve_map.py  14
- varats/varats/paper_mgmt/case_study.py  7
- varats/varats/utilss/git_util.py  14
- varats-core/varats/report/report.py  4
- varats-core/varats/provider/bug/bug_provider.py  2
- varats-core/varats/provider/release/release_provider.py  10
- varats/varats/utilss/experiment_util.py  13
- varats/varats/utilss/bb_config.py  5
- varats/varats/paper_mgmt/paper_config_manager.py  11
- varats/varats/data/discover_reports.py  1
- varats-core/varats/paper/case_study.py  8
- varats/varats/paper_mgmt/artefacts.py  3
- varats-core/varats/provider/cve/cve.py  8
         

Clones added
============
- varats/varats/data/databases/blame_interaction_database.py  1
- varats/varats/utilss/git_util.py  2
- varats/varats/data/databases/blame_interaction_degree_database.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6180505&bid=20172618)

2020-09-15 12:00 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 78
- Added 33
           

Complexity increasing per file
==============================
- varats/varats/paper_mgmt/paper_config_manager.py  11
- varats/varats/paper_mgmt/artefacts.py  3
- varats-core/varats/provider/release/release_provider.py  10
- varats-core/varats/provider/bug/bug_provider.py  2
- varats-core/varats/base/sampling_method.py  3
- varats-core/varats/provider/cve/cve_map.py  14
- varats/varats/paper_mgmt/paper_config.py  6
- varats/varats/utilss/cli_util.py  8
- varats/varats/utilss/git_util.py  14
- varats-core/varats/paper/case_study.py  8
- varats-core/varats/report/report.py  4
- varats/varats/utilss/bb_config.py  5
- varats-core/varats/provider/cve/cve.py  8
- varats/varats/paper_mgmt/case_study.py  7
- varats-core/varats/provider/cve/cve_provider.py  5
- varats/varats/data/discover_reports.py  1
- varats/varats/utilss/experiment_util.py  13
         

Clones added
============
- varats/varats/data/databases/blame_interaction_database.py  1
- varats/varats/utilss/git_util.py  2
- varats/varats/data/databases/blame_interaction_degree_database.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6180505&bid=20172618)

2020-09-15 12:10 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 78
- Added 33
           

Complexity increasing per file
==============================
- varats-core/varats/provider/cve/cve_provider.py  5
- varats-core/varats/base/sampling_method.py  3
- varats-core/varats/provider/cve/cve.py  8
- varats/varats/utilss/cli_util.py  8
- varats-core/varats/provider/bug/bug_provider.py  2
- varats/varats/paper_mgmt/paper_config_manager.py  11
- varats/varats/paper_mgmt/case_study.py  7
- varats-core/varats/paper/case_study.py  8
- varats/varats/utilss/bb_config.py  5
- varats-core/varats/provider/release/release_provider.py  10
- varats/varats/utilss/git_util.py  14
- varats/varats/paper_mgmt/paper_config.py  6
- varats/varats/paper_mgmt/artefacts.py  3
- varats/varats/utilss/experiment_util.py  13
- varats/varats/data/discover_reports.py  1
- varats-core/varats/provider/cve/cve_map.py  14
- varats-core/varats/report/report.py  4
         

Clones added
============
- varats/varats/utilss/git_util.py  2
- varats/varats/data/databases/blame_interaction_database.py  1
- varats/varats/data/databases/blame_interaction_degree_database.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6180505&bid=20172618)

2020-09-15 12:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 79
- Added 33
           

Complexity increasing per file
==============================
- varats-core/varats/provider/cve/cve.py  8
- varats/varats/paper_mgmt/paper_config.py  6
- varats/varats/utilss/git_util.py  14
- varats/varats/paper_mgmt/artefacts.py  3
- varats-core/varats/provider/release/release_provider.py  10
- varats-core/varats/provider/cve/cve_provider.py  5
- varats-core/varats/provider/cve/cve_map.py  14
- varats-core/varats/paper/case_study.py  8
- varats/varats/paper_mgmt/case_study.py  7
- varats-core/varats/base/sampling_method.py  3
- varats/varats/data/discover_reports.py  1
- varats-core/varats/report/report.py  4
- varats/varats/utilss/experiment_util.py  13
- varats/varats/paper_mgmt/paper_config_manager.py  11
- varats/varats/utilss/cli_util.py  8
- varats/varats/utilss/bb_config.py  5
- varats-core/varats/provider/bug/bug_provider.py  2
         

Clones added
============
- varats/varats/utilss/git_util.py  2
- varats/varats/data/databases/blame_interaction_database.py  1
- varats/varats/data/databases/blame_interaction_degree_database.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6180505&bid=20172618)

2020-09-15 18:15 UTC, boehmseb requested changes

2020-09-15 18:15 UTC, boehmseb commented on docs/source/vara-ts-api/data.rst
> +You can implement your own provider by creating a subclass of :class:`~varats.provider.provider.Provider` in its own subdirectory of ``data/provider``.
```suggestion
You can implement your own provider by creating a subclass of :class:`~varats.provider.provider.Provider` in its own subdirectory of ``provider`` in varats-core.
```

2020-09-15 18:15 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +#from varats.data.discover_reports import foo
```suggestion
```

2020-09-15 18:15 UTC, boehmseb commented on varats/varats/plots/blame_lorenz_curve.py
> +#from varats.data.discover_reports import foo
```suggestion
```

2020-09-15 18:15 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +#from varats.data.discover_reports import foo
```suggestion
```

2020-09-16 07:39 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 79
- Added 33
           

Complexity increasing per file
==============================
- varats/varats/paper_mgmt/paper_config.py  6
- varats-core/varats/provider/bug/bug_provider.py  2
- varats/varats/data/discover_reports.py  1
- varats/varats/paper_mgmt/case_study.py  7
- varats/varats/paper_mgmt/artefacts.py  3
- varats/varats/paper_mgmt/paper_config_manager.py  11
- varats-core/varats/provider/cve/cve_map.py  14
- varats/varats/utilss/bb_config.py  5
- varats-core/varats/report/report.py  4
- varats/varats/utilss/git_util.py  14
- varats-core/varats/provider/release/release_provider.py  10
- varats/varats/utilss/cli_util.py  8
- varats/varats/utilss/experiment_util.py  13
- varats-core/varats/paper/case_study.py  8
- varats-core/varats/provider/cve/cve.py  8
- varats-core/varats/base/sampling_method.py  3
- varats-core/varats/provider/cve/cve_provider.py  5
         

Clones added
============
- varats/varats/data/databases/blame_interaction_database.py  1
- varats/varats/utilss/git_util.py  2
- varats/varats/data/databases/blame_interaction_degree_database.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6180505&bid=20172618)

2020-09-16 07:47 UTC, boehmseb approved these changes

2020-09-16 07:48 UTC, merged