Add GUI and CLI support for building own libgit2
se-passau/VaRA-Tool-Suite pull request #37
Opened 2019-01-23 10:06 UTC by tobiH94

Closes se-passau/VaRA#316

2019-01-24 16:37 UTC, vulder requested changes
This currently only allows us to active building our own libgit2, should we add support to deactivate it, meaning unset the cmake flag? I switch the flag on/off for testing but I'm not sure how common this case is.

Could you also please resolve the merge conflicts.
thanks

2019-01-24 16:37 UTC, vulder commented on varats/vara_manager.py
> +def build_vara(own_libgit, path_to_llvm: str, install_prefix: str,
could you add the type bool here

2019-01-24 16:37 UTC, vulder commented on varats/vara_manager.py
> +            if not own_libgit:
why do we init/update in the case we do not want our own libgit?

2019-01-24 16:37 UTC, vulder commented on varats/vara_manager.py
> +            if not own_libgit:
same

2019-01-24 16:37 UTC, vulder commented on uicomponents/BuildMenu.ui
> +         <string>Own Libgit</string>
```suggestion
         <string>Build own libgit2</string>
```

2019-01-24 16:37 UTC, vulder commented on varats/driver.py
> +    parser.add_argument("--ownlibgit", action="store_true", default=False,
```suggestion
    parser.add_argument("--own-libgit2", action="store_true", default=False,
```

2019-01-24 17:34 UTC, tobiH94 commented on varats/vara_manager.py
> +            if not own_libgit:
Okay, I think I misunderstood. Which one is our own libgit? The one that is already installed on our own system, or the one that is provided by VaRA through downloading in external?
I thought it was the one installed on the system.

2019-01-29 20:10 UTC, vulder commented on varats/driver.py
> +               args.installprefix, args.ownlibgit, vara_version, build_type,
```Traceback (most recent call last):
  File ".local/bin/vara-buildsetup", line 11, in <module>
    load_entry_point('VaRA-Tool-Suite', 'gui_scripts', 'vara-buildsetup')()
  File "git/vara-tool-suite/varats/driver.py", line 110, in build_setup
    args.installprefix, args.ownlibgit, vara_version, build_type,
AttributeError: 'Namespace' object has no attribute 'ownlibgit'
```

2019-01-29 20:50 UTC, vulder requested changes

2019-01-29 20:50 UTC, vulder commented on varats/gui/buildsetup_window.py
> +        vara_manager.build_vara(self.own_libgit,
We need a way to check if the submodule is setup. If the user initialzied vara without the submodule but ticks to build his own libgit2 and the builds vara, we only set the cmake flag, but do not initialize the submodule.

2019-01-29 20:50 UTC, vulder commented on uicomponents/BuildMenu.ui
> +         <string>Build own libgit2</string>
After changing this Label, we need to regenerate the ui_BuildMenu.py file, otherwise the change will not take effekt.

2019-02-14 22:56 UTC, vulder commented on varats/vara_manager.py
> +        git["submodule", "init"] & FG
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Statement seems to have no effect](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3099182)

2019-02-14 22:56 UTC, vulder commented on varats/vara_manager.py
> +        git["submodule", "update"] & FG
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Statement seems to have no effect](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3099182)

2019-02-15 11:48 UTC, vulder commented on varats/vara_manager.py
> +        git["submodule", "init"] & FG
```python
git("submodule", "init")
```
should do the trick

2019-02-24 13:45 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/vara_manager.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3099182&bid=11339477)

2019-02-25 17:41 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/vara_manager.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3099182&bid=11339477)

2019-02-25 20:08 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- varats/vara_manager.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3099182&bid=11339477)

2019-02-25 20:18 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- varats/vara_manager.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3099182&bid=11339477)

2019-03-06 07:45 UTC, vulder commented on varats/vara_manager.py
> +        init_all_submodules(path_to_llvm + "/tools/VaRA/")
This initializes all sub modules even if we do not want our own libgit.

2019-03-28 09:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/vara_manager.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3099182&bid=11339477)

2019-03-28 11:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- varats/vara_manager.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3099182&bid=11339477)

2019-04-01 10:46 UTC, vulder approved these changes

2019-04-01 10:47 UTC, merged