Adds interface for configuration and sampling types
se-passau/VaRA-Tool-Suite pull request #381
Opened 2020-09-24 13:06 UTC by vulder

2020-09-24 13:08 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 21
           

Complexity increasing per file
==============================
- varats-core/varats/base/configuration.py  3
- tests/base/test_commandline_option.py  3
- tests/mapping/test_configuration_map.py  2
- tests/test_helper_config.py  4
- varats-core/varats/base/commandline_option.py  3
- varats-core/varats/mapping/configuration_map.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-25 07:41 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 21
           

Complexity increasing per file
==============================
- varats-core/varats/base/configuration.py  3
- tests/mapping/test_configuration_map.py  2
- varats-core/varats/base/commandline_option.py  3
- tests/base/test_commandline_option.py  3
- tests/test_helper_config.py  4
- varats-core/varats/mapping/configuration_map.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-25 13:45 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 25
           

Complexity increasing per file
==============================
- varats-core/varats/base/configuration.py  3
- varats-core/varats/base/commandline_option.py  3
- tests/mapping/test_configuration_map.py  2
- tests/test_helper_config.py  4
- varats-core/varats/mapping/configuration_map.py  4
- tests/base/test_commandline_option.py  3
         

Complexity decreasing per file
==============================
+ varats-core/varats/base/sampling_method.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-28 10:45 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 23
           

Complexity increasing per file
==============================
- tests/base/test_commandline_option.py  3
- tests/mapping/test_configuration_map.py  2
- tests/test_helper_config.py  4
- varats-core/varats/mapping/configuration_map.py  4
- varats-core/varats/base/commandline_option.py  3
- varats-core/varats/base/configuration.py  3
         

Complexity decreasing per file
==============================
+ varats-core/varats/base/sampling_method.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-28 13:18 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 33
           

Complexity increasing per file
==============================
- tests/mapping/test_configuration_map.py  2
- varats-core/varats/base/configuration.py  3
- tests/base/test_sampling_method.py  1
- varats-core/varats/base/commandline_option.py  3
- tests/base/test_commandline_option.py  3
- tests/test_helper_config.py  4
- varats-core/varats/mapping/configuration_map.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-28 13:55 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 33
           

Complexity increasing per file
==============================
- tests/base/test_sampling_method.py  1
- tests/base/test_commandline_option.py  3
- varats-core/varats/mapping/configuration_map.py  4
- varats-core/varats/base/configuration.py  3
- tests/test_helper_config.py  4
- tests/mapping/test_configuration_map.py  2
- varats-core/varats/base/commandline_option.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-28 14:13 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 17
           

Complexity increasing per file
==============================
- varats-core/varats/mapping/configuration_map.py  4
- varats-core/varats/base/commandline_option.py  3
- tests/test_helper_config.py  4
- varats-core/varats/base/configuration.py  3
- tests/base/test_commandline_option.py  3
- tests/mapping/test_configuration_map.py  2
- tests/base/test_sampling_method.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-29 07:45 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 17
           

Complexity increasing per file
==============================
- varats-core/varats/mapping/configuration_map.py  4
- tests/base/test_sampling_method.py  1
- tests/test_helper_config.py  4
- tests/base/test_commandline_option.py  3
- varats-core/varats/base/configuration.py  3
- varats/varats/tools/driver_casestudy.py  1
- tests/mapping/test_configuration_map.py  2
- varats-core/varats/base/commandline_option.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-29 09:08 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 23
           

Complexity increasing per file
==============================
- varats-core/varats/mapping/configuration_map.py  4
- varats/varats/tools/driver_casestudy.py  1
- tests/test_helper_config.py  4
- tests/base/test_configuration.py  1
- varats-core/varats/base/commandline_option.py  3
- tests/base/test_sampling_method.py  1
- tests/mapping/test_configuration_map.py  2
- tests/base/test_commandline_option.py  3
- varats-core/varats/base/configuration.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-29 09:36 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 19
           

Complexity increasing per file
==============================
- varats-core/varats/mapping/configuration_map.py  4
- tests/test_helper_config.py  4
- tests/mapping/test_configuration_map.py  2
- tests/base/test_sampling_method.py  1
- varats-core/varats/base/configuration.py  3
- tests/base/test_configuration.py  1
- tests/base/test_commandline_option.py  3
- varats-core/varats/base/commandline_option.py  3
- varats/varats/tools/driver_casestudy.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6230787&bid=20304466)

2020-09-29 18:27 UTC, boehmseb requested changes

2020-09-29 18:27 UTC, boehmseb commented on varats-core/varats/base/configuration.py
> +        """Current set value of the option."""
```suggestion
        """Currently set value of the option."""
```

2020-09-29 18:27 UTC, boehmseb commented on varats-core/varats/base/sampling_method.py
> +    This class is designed make the configuration of a sampling method
```suggestion
    This class is designed to make the configuration of a sampling method
```

2020-09-29 18:27 UTC, boehmseb commented on varats-core/varats/base/sampling_method.py
> +        that should be persisted."""
```suggestion
        """
        Returns a configuration dict with config values from the sub class
        that should be persisted.
        
        Implementations in subclasses should always call 
        `super()._extend_config()` first.
        """
```

2020-09-29 18:27 UTC, boehmseb commented on varats-core/varats/base/sampling_method.py
> +        that should be persisted."""
```suggestion
        """
        Returns a configuration dict with config values from the sub class
        that should be persisted.
        
        Implementations in subclasses should always call 
        `super()._extend_config()` first.
        """
```

2020-09-29 18:27 UTC, boehmseb commented on varats-core/varats/base/sampling_method.py
> +        that should be persisted."""
```suggestion
        """
        Returns a configuration dict with config values from the sub class
        that should be persisted.
        
        Implementations in subclasses should always call 
        `super()._extend_config()` first.
        """
```

2020-09-29 18:27 UTC, boehmseb commented on varats-core/varats/mapping/configuration_map.py
> +    """A configuration map builds a relation between an unique ID and the
```suggestion
    """A configuration map builds a relation between a unique ID and the
```

2020-10-01 11:25 UTC, boehmseb approved these changes

2020-10-01 19:52 UTC, ChristianKaltenecker commented on tests/base/test_configuration.py
> +        """Test to compare config option to to each other."""
```suggestion
        """Test to compare config option to each other."""
```

2020-10-01 19:52 UTC, ChristianKaltenecker commented on tests/test_helper_config.py
> +        Creates a `Configuration` from it's string representation.
```suggestion
        Creates a `Configuration` from its string representation.
```

2020-10-01 19:52 UTC, ChristianKaltenecker commented on tests/test_helper_config.py
> +        configuration dumpred previously.
```suggestion
        configuration dumped previously.
```

2020-10-01 19:52 UTC, ChristianKaltenecker commented on varats-core/varats/base/configuration.py
> +        Creates a `Configuration` from it's string representation.
```suggestion
        Creates a `Configuration` from its string representation.
```

2020-10-02 08:01 UTC, ChristianKaltenecker approved these changes

2020-10-02 08:17 UTC, merged