Refactor naming of TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject
se-passau/VaRA-Tool-Suite pull request #385
Opened 2020-09-28 15:20 UTC by cormensratio

Removes underscores in project name by changing TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject into TwoLibsOneProjectInteractionDiscreteLibsSingleProject

2020-09-28 15:25 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/TwoLibsOneProjectInteractionDiscreteLibsSingleProject.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6248280&bid=20348258)

2020-09-29 09:20 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6248280&bid=20348258)

2020-10-01 19:18 UTC, vulder requested changes

2020-10-01 19:18 UTC, vulder commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +two_libs_one_project_interaction_discrete_libs_single_project."""
Shouldn't this also be spelled in camel case?

2020-10-02 10:46 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6248280&bid=20348258)

2020-10-02 10:51 UTC, cormensratio commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +two_libs_one_project_interaction_discrete_libs_single_project."""
Mypy complains that it should be snake case style.

2020-10-02 10:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6248280&bid=20348258)

2020-10-02 12:30 UTC, vulder approved these changes

2020-10-02 12:31 UTC, vulder commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +two_libs_one_project_interaction_discrete_libs_single_project."""
Wut? And if you write something like `Project implementation for the CamleCase test library`

2020-10-02 12:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6248280&bid=20348258)

2020-10-02 14:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6248280&bid=20348258)

2020-10-02 14:35 UTC, cormensratio commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +two_libs_one_project_interaction_discrete_libs_single_project."""
Maybe pylint is triggered by the last word of the doc string. Wrapped in a sentence, pylint does not complain anymore.

2020-10-05 08:37 UTC, merged