Extend the functionality of the blame_verifier_report_plot to plot paper configs with multiple projects
se-passau/VaRA-Tool-Suite pull request #388
Opened 2020-09-30 13:26 UTC by cormensratio

Extends the functionality of the blame_verifier_report_plot to plot paper configs with multiple projects
closes: #657

2020-09-30 13:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/plots/blame_verifier_report_plots.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6260905&bid=20386812)

2020-10-06 15:32 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/plots/blame_verifier_report_plots.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6260905&bid=20386812)

2020-10-07 09:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/plots/blame_verifier_report_plots.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6260905&bid=20386812)

2020-10-07 21:08 UTC, vulder requested changes
overall this looks good for a first version of the plot

2020-10-07 21:08 UTC, vulder commented on varats/varats/plots/blame_verifier_report_plots.py
> +from sklearn import preprocessing
When you use this for the plot you need to update the dependencies in `setup.py` and requirements.txt

2020-10-07 21:08 UTC, vulder commented on varats/varats/plots/blame_verifier_report_plots.py
> +    return False
You can keep this for now but we should change this after wards so the user can specify from the outside if he wants to see all projects or a specific one, even when there is more than one case study in the current PC.

2020-10-08 13:00 UTC, cormensratio commented on varats/varats/plots/blame_verifier_report_plots.py
> +from sklearn import preprocessing
I think that it is already included in both as scikit-learn. Is there a way to efficiently search which imported python module comes with what package?

2020-10-08 13:02 UTC, cormensratio commented on varats/varats/plots/blame_verifier_report_plots.py
> +    return False
Okay, just tell me when you want it to be changed.

2020-10-08 14:39 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/plots/blame_verifier_report_plots.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6260905&bid=20386812)

2020-10-10 12:45 UTC, vulder commented on varats/varats/plots/blame_verifier_report_plots.py
> +from sklearn import preprocessing
Ah, kk I miss searched the lib name and did not find in the setup.py. Should be alright :)

2020-10-10 12:46 UTC, vulder approved these changes

2020-10-10 12:47 UTC, merged