Extend the commit lookup to support commits from multiple git repositories
se-passau/VaRA-Tool-Suite pull request #397
Opened 2020-10-08 16:46 UTC by cormensratio

Extends the commit lookup to support the retrieval and interactions of commits from multiple git repositories.

2020-10-08 16:49 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6308262&bid=20512294)

2020-10-09 12:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6308262&bid=20512294)

2020-10-12 12:47 UTC, vulder commented on varats-core/varats/project/project_util.py
> +    if git_name is not None:
```suggestion
    if git_name:
```

2020-10-21 13:19 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +    if git_name.startswith(primary_source_name):
I will change the "startswith" back to "==" if i have new BRs to verify that the git_names are correct, or i can do it in this PR if you want.

2020-10-21 19:46 UTC, vulder approved these changes
Looks good

2020-10-21 19:46 UTC, vulder commented on varats-core/varats/project/project_util.py
> +    if git_name.startswith(primary_source_name):
You can change it now. The code is merged to generate the correct reports.

2020-10-22 09:16 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +    if git_name.startswith(primary_source_name):
Done

2020-10-23 20:37 UTC, vulder requested changes
I added a few questions. I don't quite understand you look up logic.

2020-10-23 20:37 UTC, vulder commented on varats-core/varats/project/project_util.py
> +    return Path(target_prefix() + "/" + source.local)
```suggestion
    return Path(target_prefix()) / source.local
```
You don't need to put everything together and the create a path. It's easier to use the path extender syntax with the `/` operator.

2020-10-23 20:37 UTC, vulder commented on varats-core/varats/project/project_util.py
> +    primary_source_name = os.path.basename(project_cls.SOURCE[0].local)
Use the get_primary_source functions for this. It could be that some time in the future it is not the first one. The accessor function should always work.

2020-10-23 20:37 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +            git_name_to_commit_hash_dict[git_name] = c_hash
Why do you cache commit_hashes keyed on `git_name`?
This "cache" only contains one hash per repo because it's overwritten every time a new hash in this repo is looked up.

2020-10-23 20:37 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +    commit_hash_cache_dict: tp.Dict[str, pygit2.Commit] = {}
Commits cannot be cached based on the commit hash alone. Commit hashes are only unique in on repository, i.e., two repository can have the same commit hash for different commits.

2020-10-23 20:37 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +    git_name_to_commit_hash_dict: tp.Dict[str, str] = {}
What is the purpose of this dict? I don't understand why you want to cache `git_name` -> `commit_hash` relations?

2020-10-26 18:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6308262&bid=20512294)

2020-10-30 19:50 UTC, vulder requested changes

2020-10-30 19:50 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +                                                          pygit2.Commit]]] = {}
This mapping makes no sense to me. Why would you first map git name to another dict which then uses repo objects as a key?

2020-10-30 19:50 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +    cache_dict: tp.Dict[tp.Optional[str], tp.Dict[pygit2.Repository,
Why is the key to the first map optional? If the user did not pass in a `git_name` we take the default dict (primary source) which has a name, so we can just use it.

2020-11-06 10:53 UTC, vulder requested changes
I added just a few stylistic remarks, otherwise, this looks good.

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/project/project_util.py
> +                  the name of the primary source is used
```suggestion
        git_name: name of the git repository, i.e., the name of the repository folder.
                  If no git_name is provided, the name of the primary source is used.
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        the path to the local download location of the git repository.
```suggestion
        Path to the local download location of the git repository.
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/project/project_util.py
> +    LookupError if no match was found within the given benchbuild project.
```suggestion
    Get benchbuild BaseSource specified by the git_name or raise a
    LookupError if no match was found within the given benchbuild project.
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        project_name: the name of the given benchbuild project
```suggestion
        project_name: name of the given benchbuild project
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        project_name: the name of the given benchbuild project
```suggestion
        project_name: name of the given benchbuild project
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        git_name: the name of the git repository
```suggestion
        git_name: name of the git repository
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        the benchbuild BaseSource of the searched git repository
```suggestion
        benchbuild BaseSource of the searched git repository
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        git_name: the name of the git repository
```suggestion
        project_name: name of the given benchbuild project
        git_name: name of the git repository
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        the git repository that matches the given git_name.
```suggestion
        git repository that matches the given git_name.
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +        project_name: the name of the given benchbuild project
```suggestion
        project_name: name of the given benchbuild project
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +        corresponding commit.
```suggestion
        a Callable that maps a commit hash and repository name to the corresponding commit.
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +            c_hash: the commit hash of the searched commit
```suggestion
            c_hash: commit hash of the searched commit
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +                      primary source is used.
```suggestion
            git_name: name of the repository, wherein the commit is being
                      searched. If no git_name is provided, the name of the
                      primary source is used.
```

2020-11-06 10:53 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +            repository name.
```suggestion
            commit, which corresponds to the given commit hash within the given
            repository.
```

2020-11-09 22:42 UTC, vulder approved these changes
looks good, thanks

2020-11-09 22:43 UTC, merged