Bug Detection by using Commit Messages
se-passau/VaRA-Tool-Suite pull request #399
Opened 2020-10-11 21:13 UTC by SimonFedick

Added a bug detection strategy using Commit Messages in addition to the former Issue Event strategy.

2020-10-11 21:15 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 3
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-11 23:38 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-11 23:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-11 23:59 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-12 08:36 UTC, boehmseb requested changes
We should keep the implementation for the different bug detection strategies separate, 
as, e.g., the detection by commit message can also be used by projects that do not have a github repo. The provider can then decide what detection strategies it wants to use and can take care of merging the results.

2020-10-12 08:36 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +                self.introducing_commits == other.introducing_commits and
This only works for ordered lists.
Depending on the implementation of the introducing commit detection, we might want to also allow unordered lists to pass this check, e.g., something like this:
```suggestion
                set(self.introducing_commits) == set(other.introducing_commits) and
```

2020-10-12 08:36 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +            (self.fixing_commit, self.introducing_commits, self.issue_id)
Same problem as above. Maybe switch the type of the `introducing_commits` property from `list` to `set`?

2020-10-12 08:36 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +                self.introducing_commits == other.introducing_commits and
Same as above.

2020-10-12 08:36 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +            (self.fixing_commit, self.introducing_commits, self.issue_id)
Same as above.

2020-10-12 08:36 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +    match = re.search(r'fix|fixed|fixes', first_line, re.IGNORECASE)
This regex is redundant. If `fixed` or `fixes` match, `fix` will also match.

In this case, something like this would be more suitable than a regex:
```python
any([keyword in first_line.split() for keyword in ['fix', 'fixed', 'fixes']])
```

2020-10-12 16:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-12 16:32 UTC, SimonFedick commented on varats-core/varats/provider/bug/bug.py
> +            (self.fixing_commit, self.introducing_commits, self.issue_id)
I decided to make the `introducing_commits` attribute a `set` as I suppose for now the order will not be relevant to the user.

2020-10-12 16:35 UTC, SimonFedick commented on varats-core/varats/provider/bug/bug.py
> +    match = re.search(r'fix|fixed|fixes', first_line, re.IGNORECASE)
For now I went with the suggested change. Maybe `'fix'` could be a good stem if we want to use stemming, though.

2020-10-13 07:22 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +    match = re.search(r'fix|fixed|fixes', first_line, re.IGNORECASE)
Lets finish the basic version first. Then, we can talk about improvements.

2020-10-13 07:22 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +            (self.fixing_commit, self.introducing_commits, self.issue_id)
Sounds good.

2020-10-18 18:37 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-18 18:52 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-19 07:44 UTC, boehmseb requested changes
There is one typing issue that somehow is not detected by mypy.

Also, it would be good to have tests for at least all the `_filter_all_*` functions.
This should be relatively straight forward if you mock the `_get_all_issue_events()` and `Repository.walk()` functions.

2020-10-19 07:44 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +    PygitBugs using the commit history.
```suggestion
    RawBugs using the commit history.
```

2020-10-19 07:44 UTC, boehmseb commented on varats-core/varats/provider/bug/bug_provider.py
> +            bug.find_all_commit_message_pygit_bugs(self.project.SOURCE)
This is actually does not typecheck. I do not know why mypy does not detect this.

Also, from what I see, it is sufficient to only pass the project name here. You should change that for all functions. Remember to also change the type of the parameters to `str` then.

```suggestion
            bug.find_all_commit_message_pygit_bugs(self.project.NAME)
```

2020-10-22 14:09 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-22 14:15 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-22 14:44 UTC, boehmseb commented on varats-core/varats/provider/bug/bug_provider.py
> +            bug.find_all_commit_message_pygit_bugs(self.project.name)
Technically, the instances of `tp.Type[Project]` have no attribute `name`. Use `NAME` instead.
```suggestion
            bug.find_all_commit_message_pygit_bugs(self.project.NAME)
```

2020-10-22 14:44 UTC, boehmseb commented on varats-core/varats/provider/bug/bug_provider.py
> +            bug.find_all_commit_message_raw_bugs(self.project.name)
```suggestion
            bug.find_all_commit_message_raw_bugs(self.project.NAME)
```

2020-10-22 14:44 UTC, boehmseb commented on varats-core/varats/provider/bug/bug_provider.py
> +                self.project.name, fixing_commit
```suggestion
                self.project.NAME, fixing_commit
```

2020-10-22 14:44 UTC, boehmseb commented on varats-core/varats/provider/bug/bug_provider.py
> +                self.project.name, fixing_commit
```suggestion
                self.project.NAME, fixing_commit
```

2020-10-22 14:44 UTC, boehmseb commented on varats-core/varats/provider/bug/bug_provider.py
> +                self.project.name, introducing_commit
```suggestion
                self.project.NAME, introducing_commit
```

2020-10-22 14:44 UTC, boehmseb commented on varats-core/varats/provider/bug/bug_provider.py
> +                self.project.name, introducing_commit
```suggestion
                self.project.NAME, introducing_commit
```

2020-10-22 15:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-26 18:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- varats-core/varats/provider/bug/bug_provider.py  1
         

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-26 19:37 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 18
           

Complexity increasing per file
==============================
- tests/provider/test_bug_provider.py  2
- varats-core/varats/provider/bug/bug_provider.py  1
         

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-27 16:42 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 15
           

Complexity increasing per file
==============================
- tests/provider/test_bug_provider.py  3
- varats-core/varats/provider/bug/bug_provider.py  1
         

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-27 18:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 17
           

Complexity increasing per file
==============================
- tests/provider/test_bug_provider.py  3
- varats-core/varats/provider/bug/bug_provider.py  1
         

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-28 01:11 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- tests/provider/test_bug_provider.py  3
- varats-core/varats/provider/bug/bug_provider.py  1
         

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-28 01:16 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- tests/provider/test_bug_provider.py  3
- varats-core/varats/provider/bug/bug_provider.py  1
         

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-28 03:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- tests/provider/test_bug_provider.py  3
- varats-core/varats/provider/bug/bug_provider.py  1
         

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-10-28 03:39 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- tests/provider/test_bug_provider.py  3
- varats-core/varats/provider/bug/bug_provider.py  1
         

Clones added
============
- varats-core/varats/provider/bug/bug.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6319782&bid=20543648)

2020-11-09 10:31 UTC, boehmseb reviewed
Looks good except for my two small comments.

2020-11-09 10:31 UTC, boehmseb commented on varats-core/varats/utils/github_util.py
> +def get_github_repo_name_for_project(
Please add a docstring to this function.

2020-11-09 10:31 UTC, boehmseb commented on varats-core/varats/provider/bug/bug_provider.py
> +        if hasattr(primary_source, "fetch"):
I think it would be good to extract the `hasattr` check into a function `is_git_source(source: BaseSource)` in the `project_utils.py` module.
We will need this functionality in other places and we need to be able to easily change the implementation of this check in the future.

2020-11-09 13:17 UTC, boehmseb approved these changes

2020-11-09 23:02 UTC, vulder approved these changes
Found just two small issues, otherwise, this looks good. I'm excited how well this will perform :smiley:

2020-11-09 23:02 UTC, vulder commented on varats-core/varats/provider/bug/bug.py
> +            raise AssertionError
```suggestion
            raise AssertionError
```
What does this assert? Could you please add a small message to the AssertionError that explains this case.

2020-11-09 23:02 UTC, vulder commented on varats-core/varats/provider/bug/bug.py
> +    raise AssertionError
```suggestion
    raise AssertionError(f"No github repo found for project {project_name}")
```
It's better to put the reasoning into the message. So a user get's more information when the assertion is triggered.

2020-11-10 13:22 UTC, merged