Adds save function for NoOpt plots
se-passau/VaRA-Tool-Suite pull request #401
Opened 2020-10-13 09:37 UTC by cormensratio

The save function for NoOpt verifier plots was missing and therefore single plot files were created for every project. Multiple project plots now get plotted only once in one file.

2020-10-13 09:42 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/plots/blame_verifier_report_plots.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6329372&bid=20567054)

2020-10-13 10:39 UTC, cormensratio commented
If this PR is merged, pls have a look at PR #402

2020-10-15 08:14 UTC, vulder requested changes

2020-10-15 08:14 UTC, vulder commented on varats/varats/plots/blame_verifier_report_plots.py
> +    def save(
This seems to be the same `save` methods as in the OptPlot, wouldn't it make sense to move the save method into the `BlameVerifierPlot` base class?

2020-10-15 10:58 UTC, cormensratio commented on varats/varats/plots/blame_verifier_report_plots.py
> +    def save(
Makes sense to me ;), i forgot about that.

2020-10-15 11:08 UTC, vulder approved these changes

2020-10-15 11:29 UTC, merged