Handle empty plot data exception in multi plot
se-passau/VaRA-Tool-Suite pull request #402
Opened 2020-10-13 10:24 UTC by cormensratio

When multiple case studies are present and one or more do not provide plotting data, the plot should not fail completely but plot the remaining project data into the file. This commit handles the described scenario for multiple projects where some projects do not provide data.

2020-10-13 10:27 UTC, cormensratio commented
I noticed that for every case study the plot() function gets called and possibly creates a huge overhead, since a single call to plot() already delivers all information about the case studies we need. Can we circumvent the multiple call to plot() or should we introduce an early exit after the first case study (first call to plot()) got executed successfully?

2020-10-13 10:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/plots/blame_verifier_report_plots.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6329702&bid=20567826)

2020-10-15 13:09 UTC, vulder requested changes
I understand the problem, however, we should try to find a solution that does not need Runtime exceptions as a way of special case handling.

2020-10-15 13:09 UTC, vulder commented on varats/varats/plots/blame_verifier_report_plots.py
> +
Error handling by Exception is a very bad design practice. We should find another way to check before or exit this call instead of `raise.

2020-10-16 10:15 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/varats/plots/blame_verifier_report_plots.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6329702&bid=20567826)

2020-10-19 17:38 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/varats/plots/blame_verifier_report_plots.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6329702&bid=20567826)

2020-10-19 18:03 UTC, vulder approved these changes
Except for the one log call everything looks fine :)

2020-10-19 18:03 UTC, vulder commented on varats/varats/plots/blame_verifier_report_plots.py
> +        LOG.warning("No plot data was provided")
You don't need to log this you self the plotting framework already does this.

2020-10-19 18:03 UTC, vulder commented on varats/varats/plots/blame_verifier_report_plots.py
>          )
If you specifically want to log the opt level this is fine. Project name would also logged by the plotting framework

2020-10-20 10:04 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/varats/plots/blame_verifier_report_plots.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6329702&bid=20567826)

2020-10-20 10:10 UTC, vulder approved these changes

2020-10-20 10:11 UTC, merged