Add option to vara-art generate to build a html overview.
se-passau/VaRA-Tool-Suite pull request #403
Opened 2020-10-14 08:44 UTC by boehmseb

2020-10-14 08:47 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/varats/tools/driver_artefacts.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6336641&bid=20585267)

2020-10-14 08:54 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/varats/tools/driver_artefacts.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6336641&bid=20585267)

2020-10-15 07:55 UTC, vulder commented
This should be the missing issue number, is it closed afterwards or is something missing?

related se-passau/VaRA#644

2020-10-15 08:01 UTC, boehmseb commented
> This should be the missing issue number, is it closed afterwards or is something missing?
> 
> related [se-passau/VaRA#644](https://github.com/se-passau/VaRA/issues/644)

As far as I remember, we had something slightly different in mind back then. 
This overview does not include all plots, but only those that are generated for all case studies/projects in a paper config.
Other plots will be missing.

2020-10-15 08:05 UTC, vulder requested changes
Just one remark, otherwise, the html generation code looks good :grin:

2020-10-15 08:05 UTC, vulder commented on varats/varats/tools/driver_artefacts.py
> +            if artefact.artefact_type == ArtefactType.plot
Maybe it would be better to move this into the artefacts.py and create a `plot_artefacts_filter` or `filter_plot_artefacts` method, which get's called if one wants only plot artefacts.
The method could take a list of `Artefacts` and only return an iterable of `PlotArtefacts`.
Afterwards we can just use this method here.

I think, this would be a better separation because so the details `when is an Artefact a PlotArtefact` are contained in the artefacts module. Hence, the user does not need to care about it and just get's his PlotArtefacts.

2020-10-15 08:18 UTC, boehmseb commented on varats/varats/tools/driver_artefacts.py
> +            if artefact.artefact_type == ArtefactType.plot
Resolved in 77dc43d

2020-10-15 08:58 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6336641&bid=20585267)

2020-10-15 09:10 UTC, vulder approved these changes
lgtm

2020-10-15 10:25 UTC, vulder commented
> > This should be the missing issue number, is it closed afterwards or is something missing?
> > related [se-passau/VaRA#644](https://github.com/se-passau/VaRA/issues/644)
> 
> As far as I remember, we had something slightly different in mind back then.
> This overview does not include all plots, but only those that are generated for all case studies/projects in a paper config.
> Other plots will be missing.

hmm, I thought the idea was to generate an index.html hat acts as an overview of all artefacts generated, so we can easier switch and investigate the plots.
Are you thinking about the one index.html include all plots as png test that I once build?

2020-10-15 10:27 UTC, boehmseb commented
> > > This should be the missing issue number, is it closed afterwards or is something missing?
> > > related [se-passau/VaRA#644](https://github.com/se-passau/VaRA/issues/644)
> > 
> > 
> > As far as I remember, we had something slightly different in mind back then.
> > This overview does not include all plots, but only those that are generated for all case studies/projects in a paper config.
> > Other plots will be missing.
> 
> hmm, I thought the idea was to generate an index.html hat acts as an overview of all artefacts generated, so we can easier switch and investigate the plots.
That is what we wanted with the issue.

> Are you thinking about the one index.html include all plots as png test that I once build?
That is what this PR is.

2020-10-15 11:07 UTC, vulder commented
Yeah, you right then the other one is still missing so we should not close the issue.

2020-10-15 11:07 UTC, merged