Performance improvements for data loading and plot generation
se-passau/VaRA-Tool-Suite pull request #405
Opened 2020-10-19 19:10 UTC by boehmseb

This PR contains various performance improvements for data loading and plot generation.

For me, this reduces the time it takes to generate all plots of our current dataset (with an initially empty cache) from 96 minutes to 46 minutes.

2020-10-19 19:14 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ varats/varats/data/databases/blame_diff_metrics_database.py  -2
+ varats/varats/data/databases/blame_interaction_degree_database.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6365121&bid=20657545)

2020-10-19 20:45 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ varats/varats/data/databases/blame_diff_metrics_database.py  -2
+ varats/varats/data/databases/blame_interaction_degree_database.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6365121&bid=20657545)

2020-10-20 07:44 UTC, vulder requested changes
Looks good, for some changes I don't understand why they make a difference.

2020-10-20 07:44 UTC, vulder commented on varats-core/varats/plot/plot.py
> -        if 'plot_case_study' in self.plot_kwargs:
This makes a difference? And I personally, find the old one better to read than to get something that one does not use only to hope for a `None` default to skip the if.

2020-10-20 07:44 UTC, vulder commented on varats-core/varats/utils/git_util.py
> -    with local.cwd(repo_path):
What makes the old code slow here? From my understanding this function should only be called once per plot/repo so change dir vs use git with `-C` cannot have such a huge impact. What am I missing? Is it maybe that we call this more often on subranges in other use cases?

2020-10-20 07:44 UTC, vulder commented on varats/varats/data/databases/evaluationdatabase.py
> +                              apply(lambda x: revisions.has_node(x) != 0)]
Using a CharTrie makes sense but why don't you need the `axis=1` param to apply anymore?

2020-10-20 07:44 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +    commit_lookup: tp.Callable[[str], pygit2.Commit], bucket_size: int,
Maybe we should add a special type for this `tp.Callable[[str], pygit2.Commit]` in the git_util module. Simon is current changing the signature. And if we want to use this all over the code base it should be easier for the user to get the correct type.

2020-10-20 08:09 UTC, boehmseb commented on varats-core/varats/plot/plot.py
> -        if 'plot_case_study' in self.plot_kwargs:
That's just a bug I found. I messed up the commit message with that one.

2020-10-20 08:11 UTC, boehmseb commented on varats-core/varats/utils/git_util.py
> -    with local.cwd(repo_path):
The important part is below in `calc_code_churn()`, but I changed in both places to be consistent.

2020-10-20 08:12 UTC, boehmseb commented on varats/varats/data/databases/evaluationdatabase.py
> +                              apply(lambda x: revisions.has_node(x) != 0)]
Because I `apply` is called on a series. Note that I moved the selection out of the lambda.

2020-10-20 08:13 UTC, boehmseb commented on varats/varats/data/reports/blame_report.py
> +    commit_lookup: tp.Callable[[str], pygit2.Commit], bucket_size: int,
I can do that.

2020-10-20 08:28 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ varats/varats/data/databases/blame_diff_metrics_database.py  -2
+ varats/varats/data/databases/blame_interaction_degree_database.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6365121&bid=20657545)

2020-10-20 10:17 UTC, vulder requested changes
Just a nit about the name. The rest I understand now :)

2020-10-20 10:17 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +    commit_lookup: CommitLookupHelper, bucket_size: int
```suggestion
    commit_lookup: CommitLookupFTy, bucket_size: int
```
Hmm, I personally prefer to end types with `Ty` or `Type` so it sticks out that this is not a normal class but a type.
So maybe: `CommitLookupFTy` or `CommitLookupTy` or `CommitLookupType`

2020-10-20 10:22 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ varats/varats/data/databases/blame_interaction_degree_database.py  -1
+ varats/varats/data/databases/blame_diff_metrics_database.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6365121&bid=20657545)

2020-10-20 12:09 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ varats/varats/data/databases/blame_diff_metrics_database.py  -2
+ varats/varats/data/databases/blame_interaction_degree_database.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6365121&bid=20657545)

2020-10-20 12:22 UTC, vulder approved these changes

2020-10-20 12:23 UTC, merged