Table for displaying bug metrics
se-passau/VaRA-Tool-Suite pull request #411
Opened 2020-11-12 20:10 UTC by SimonFedick

Adds a new Table subclass BugOverviewTable able to display bug data for a given project.

2020-11-15 13:47 UTC, vulder reviewed
looks good :+1: 
a small test would help, we should talk on Monday about creating a small test repository with bug tags, which we can use for testing.

2020-11-16 08:10 UTC, boehmseb requested changes

2020-11-16 08:10 UTC, boehmseb commented on varats/varats/tables/bug_overview_table.py
> +    def save(
You do not need to override `save()` here. You only need to do that in certain cases (e.g., when your table uses multiple projects at the same time). But in your case, the default `save()` should suffice.

2020-11-16 08:10 UTC, boehmseb commented on varats/varats/tables/bug_overview_table.py
> +        with BugProvider.create_provider_for_project(
Why are you using a context manager here? Providers are not implemented as such and do not need to be. I don't even know what the defined behaviour is in that case.

2020-11-16 08:10 UTC, boehmseb commented on varats/varats/tables/bug_overview_table.py
> +                )
You do not need to do this. Just call `BugProvider.get_provider_for_project(...)`. This takes care of constructing a default provider if necessary. That's why we have them in the first place.

2020-11-22 15:40 UTC, boehmseb requested changes
Please have a look at the name of the test project. Otherwise looks good.

2020-11-22 15:40 UTC, boehmseb commented on varats/varats/projects/test_projects/bug_provider_test_repos.py
> +class BasicTestRepo(bb.Project):  # type: ignore
Please choose a name (class name and project `NAME`) that reflects that this project is for testing bug detection. In many situations, the project name appears without the module name and then it will be hard to distinguish this from other test projects.

2020-11-22 18:33 UTC, SimonFedick commented on varats/varats/projects/test_projects/bug_provider_test_repos.py
> +class BasicTestRepo(bb.Project):  # type: ignore
Is `BasicBugDetectionTestRepo` alright or would that be too long of a name?

2020-11-23 08:09 UTC, boehmseb commented on varats/varats/projects/test_projects/bug_provider_test_repos.py
> +class BasicTestRepo(bb.Project):  # type: ignore
Should be fine. We have test projects with longer names ;)

2020-11-23 08:10 UTC, boehmseb approved these changes

2020-11-23 13:16 UTC, vulder approved these changes

2020-11-23 13:22 UTC, merged