Extend blame interaction degree to support multiple repositories
se-passau/VaRA-Tool-Suite pull request #413
Opened 2020-11-13 10:56 UTC by cormensratio

2020-11-16 09:25 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +        library name.
Map of ...

2020-12-22 10:52 UTC, cormensratio commented on varats-core/varats/utils/git_util.py
> +        diff_base_params.append(":")
For my system it either works if there is a whitespace after the ":" or a "." instead of the ":", followed by a whitespace.

2020-12-29 22:52 UTC, vulder requested changes
I made a first pass over the code. Looks mostly fine but some of the function/code could be split up a bit more to make it better understandable.

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/databases/blame_interaction_degree_database.py
> +            )
The idea behind type annotations is that we can verify that expected type is what we get. Casting everything to the type we expect defeats the purpose of type annotations.
If the types do not match, please find out where and why they don't match. In some cases, we can create variables with the correct type, or in other cases we can at least make sure at the point of variable assignment/creation that we have the correct type.

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +                    repo_name]:
Wrong/strange line continuation, warp the condition into `()` so you can easier add a line break.

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +                        not in tmp_degree_of_libs:
```suggestion
                if inter_hash_repo_name not in tmp_degree_of_libs:
```

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +                        not in categorised_degree_dict[base_repo_name]:
```suggestion
                if (inter_hash_repo_name 
                        not in categorised_degree_dict[base_repo_name]):
```
With `()` you get sometimes better line breaks for long conditions.

PS: run format after applying suggestion

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +    categorised_degree_dict: tp.Dict[str, tp.Dict[str, tp.Dict[int, int]]] = {}
Maybe we should add a type def with a describing name for this type. This would make it easier to understand, instead of dict in dict without context.

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +        report: The blame report
```suggestion
        report: blame report
```

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +            )
Why do you need a cast here?

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/databases/blame_interaction_degree_database.py
> +                        lib_amount = tp.cast(tp.List[int], inter_amounts)[i]
more casts

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/databases/blame_interaction_degree_database.py
> +                generate_lib_dependent_degrees(report)
```suggestion
            categorised_degree_occurrences = generate_lib_dependent_degrees(report)
```
+ format

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/databases/blame_interaction_degree_database.py
> +                        in categorised_degree_occurrences.items():
```suggestion
                for _, lib_dict in categorised_degree_occurrences.items():
```

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/databases/blame_interaction_degree_database.py
> +                                              )
```suggestion
            list_of_author_degree_occurrences = generate_author_degree_tuples(report, commit_lookup)
```
+ format

2020-12-29 22:52 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +        diff_base_params.append(":")
Can you please find out why you need a white space here? From the git spec and bash this is not required an the select should. We need to figure out why this is problematic because if not, we don't now which other systems we break if we change something here.

2020-12-29 22:52 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +def generate_lib_dependent_degrees(
We should add a few tests for this to make sure that the data is correctly calcualted.

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +    def _fraction_overview_plot(
I think you put some of the local functions, declared local in this func, as private functions into the class. The function is quite long and hard to understand. Maybe we could also split up this function a bit more, it's quite long.

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +            str, tp.List[float]]]:
Maybe, the long type should have a name.

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +        def _gen_multi_lib_degree_plot() -> None:
Maybe this function could be moved out.

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +        ) -> tp.Tuple[tp.List[tp.List[float]], tp.List[tp.List[float]]]:
same here

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +                in_axis = fig.add_subplot(grid_spec[1, :])
can be move out of the if, the same condition is in the then branch

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +                out_axis = fig.add_subplot(grid_spec[0, :])
see below

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +                in_axis = fig.add_subplot(grid_spec[1, :])
see below

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +            legend_in = in_axis.legend(
maybe setting up the legend could be a separate function

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +    def _library_interactions(
The name could be clearer, "what" library interactions? Plotting, calculating, ...?

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +        ) -> tp.Tuple[tp.Dict[str, tp.Any], tp.Dict[str, tp.Dict[int, str]]]:
looks like the same large type

2020-12-29 22:52 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +
```suggestion
```

2020-12-30 15:07 UTC, cormensratio commented on varats/varats/data/reports/blame_report.py
> +            )
I first thought that mypy falsely gets a tp.List[int] instead of tp.List[tp.Tuple[int,int]], but it seems that my typechecker is the only one complaining ;). I'll remove the cast.

2020-12-31 08:17 UTC, cormensratio commented on varats/varats/data/reports/blame_report.py
> +    categorised_degree_dict: tp.Dict[str, tp.Dict[str, tp.Dict[int, int]]] = {}
Added: DegreeAmountMappingTy = tp.Dict[int, int]

2020-12-31 10:22 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +            str, tp.List[float]]]:
Added: `BaseAndInterLibToFractionListMappingsTuple = tp.Tuple[tp.Dict[str, tp.List[float]], tp.Dict[str, tp.List[float]]]`

2020-12-31 10:26 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +        ) -> tp.Tuple[tp.List[tp.List[float]], tp.List[tp.List[float]]]:
Added: `BaseAndInterLibFractionListsTuple = tp.Tuple[tp.List[tp.List[float]],tp.List[tp.List[float]]]`

2020-12-31 12:12 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +        ) -> tp.Tuple[tp.Dict[str, tp.Any], tp.Dict[str, tp.Dict[int, str]]]:
Not the same large type, but another.
Added: `LibsToColormapsAndLibsToIndexWithShadesMappingsTuple = tp.Tuple[tp.Dict[str, tp.Any], tp.Dict[str,tp.Dict[int, str]]]`

2020-12-31 12:16 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +    def _fraction_overview_plot(
I wrongly named some inner function names with "_", if you meant that. If we decide to keep the function after the next meeting i will try to split it further.

2020-12-31 12:17 UTC, cormensratio commented on varats-core/varats/utils/git_util.py
> +        diff_base_params.append(":")
I agree. I will investigate it further.

2021-01-11 09:06 UTC, boehmseb requested changes
There is a problem in the interaction degree database.

2021-01-11 09:06 UTC, boehmseb commented on varats/varats/data/databases/blame_interaction_degree_database.py
> +            author_degrees_untyped, author_amounts_untyped = map(
All these map calls will fail if the `list_of_foo` is empty.
To fix this, you can do something like this:

```python
degrees = []
amounts = []
list_of_degree_occurrences = generate_degree_tuples(report)
if list_of_degree_occurrences:
degrees, amounts = map(list, zip(*list_of_degree_occurrences))
total = sum(amounts)
```

2021-01-11 13:53 UTC, vulder approved these changes
For the `unique_revisions` lists, if you don't need the ordering you could use a set here.

The rest overall is now better understandable.

2021-01-11 13:53 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +    def get_modified_file_extensions(self,
Why did you not directly modify the `get_extensions_repr` method? I think we only need one of the two and can just replace the old one.

2021-01-11 13:53 UTC, vulder commented on varats/varats/data/databases/blame_interaction_degree_database.py
> +            author_degrees_untyped, author_amounts_untyped = map(
This also gives one the possibility to define the types of the different lists in advance so we should not need the cast later.

2021-01-11 13:53 UTC, cormensratio commented on varats/varats/data/databases/blame_interaction_degree_database.py
> +            author_degrees_untyped, author_amounts_untyped = map(
Refactored it to function: `_get_tuple_of_degree_amount_lists()`

2021-01-11 17:37 UTC, cormensratio commented on varats-core/varats/utils/git_util.py
> +    def get_modified_file_extensions(self,
I wasn't sure if we need the original functionality of the method in other code parts. I will adapt the method and change the usages to the new one.

2021-01-11 18:07 UTC, cormensratio commented
> For the `unique_revisions` lists, if you don't need the ordering you could use a set here.

I think that the set would not work because e.g., the passed data for the stackplot must be hashable. As already mentioned by you the order of the unique revisions is in fact important because the revisions are sorted by their time.
Therefore I would stay with the unique list.

2021-01-13 11:35 UTC, vulder approved these changes
lgtm

2021-02-04 16:57 UTC, boehmseb approved these changes

2021-02-05 10:41 UTC, merged