Latex Document Wrapper for Tables
se-passau/VaRA-Tool-Suite pull request #415
Opened 2020-11-25 18:58 UTC by SimonFedick

Adds a --wrap-document option to the vara-table command and adds a corresponding wrapper for optionally wrapping latex tables in a document. Wrapper requires the pylatex library.

2020-11-26 08:57 UTC, boehmseb requested changes

2020-11-26 08:57 UTC, boehmseb commented on varats-core/varats/table/table.py
> +            landscape_mode = "true" if self.__name == "bug_overview" else "false"
Please no subclass-specific code in the base class.

2020-11-26 08:57 UTC, boehmseb commented on varats-core/varats/table/table.py
> +            doc.generate_tex()
Move this code to `wrap_table_in_document` and make that function return a `str` (I hope that is easily possible).
That way, we can do:
```python
if wrap_table:
    table = wrap_table_in_document(table)
```

To make things like landscape mode easily configurable, split the wrap function into two functions:
one function that takes the options as parameters, and an abstract function that does not take the parameters and calls the first one with the desired parameters. Subclasses then only need to override the second function with its own parameters.

2020-11-26 08:57 UTC, boehmseb commented on varats-core/varats/table/table.py
> +                whole document.
```suggestion
                complete document.
```

2020-11-26 08:57 UTC, boehmseb commented on varats/varats/tables/diff_correlation_overview_table.py
> +            doc.generate_tex()
This should collapse into a simple call to `wrap_table_in_document(table)` once you addressed my other comments.

2020-11-26 13:50 UTC, vulder requested changes

2020-11-26 13:50 UTC, vulder commented on varats-core/varats/table/table.py
> +                end of the filename.
```suggestion
            include_filetype: flags whether to include the file extension at the
                              end of the filename.
```

2020-11-26 13:50 UTC, vulder commented on varats-core/varats/table/table.py
> +        return f"{table_ident}{self.name}{sep_stages}"
```suggestion
        table_file_name = f"{table_ident}{self.name}{sep_stages}"
        if include_filetype:
            table_file_name += f".{filetype}"
        return table_file_name
```

2020-11-26 13:50 UTC, vulder commented on varats-core/varats/table/table.py
> +                whole document.
And also align the word `complete` with flags so it forms a block

2020-11-29 15:02 UTC, SimonFedick commented on varats-core/varats/table/table.py
> +            doc.generate_tex()
This now happens in an abstract method `wrap_table` that calls `wrap_table_in_document` with `self.tabulate` and its desired parameters for each subclass respectively.

2020-11-30 08:28 UTC, boehmseb commented on varats/setup.py
> +        "pylatex>=1.4.1"
```suggestion
        "pylatex>=1.4.1",
```

2020-11-30 11:46 UTC, boehmseb requested changes

2020-11-30 11:46 UTC, boehmseb commented on varats-core/varats/table/table.py
> +    def wrap_table(self) -> str:
Make the table content an argument of this function so that the save function always calls `tabulate()` and the `wrap_table()` function only does the wrapping.

2020-11-30 11:47 UTC, boehmseb commented
The rest looks good now btw.

2020-11-30 13:15 UTC, boehmseb approved these changes

2020-11-30 13:17 UTC, vulder approved these changes
lgtm

2020-12-08 18:39 UTC, vulder commented
@SimonFedick Hi, could you please resolve the conflicts, I would merge the PR after wards. :smiley:

2020-12-09 23:46 UTC, merged