Let `vara-art generate` create a HTML overview
se-passau/VaRA-Tool-Suite pull request #416
Opened 2020-11-26 11:44 UTC by boehmseb

This resolves se-passau/VaRA#644.

2020-11-26 13:28 UTC, vulder requested changes
A few things but overall looks good :)

2020-11-26 13:28 UTC, vulder commented on varats/varats/tools/html_utils.py
> +__HTML_BASE_TEMPLATE = """<!DOCTYPE html>
Would it be better to put these "templates" into a separate template file? Similar to how BB renders slurm scripts. With the template engine replacing special values is trivial :smile:

2020-11-26 13:28 UTC, vulder commented on varats/varats/tools/driver_artefacts.py
> +def _generate_artefact_html(artefact: Artefact,
Maybe we should add simple tests for the html generation of artefacts/table methods, so we can make sure they stay correct.

2020-11-26 13:47 UTC, boehmseb commented on varats/varats/tools/html_utils.py
> +__HTML_BASE_TEMPLATE = """<!DOCTYPE html>
I don't see the benefit right now, but that might change if we use this in other places in the future.
As I use some of these snippets in different situations and combinations, I decided against this for now. Instead, I started this module.

2020-11-26 13:48 UTC, boehmseb commented on varats/varats/tools/driver_artefacts.py
> +def _generate_artefact_html(artefact: Artefact,
Yes, you are right. I will add some tests.

2020-11-26 13:49 UTC, boehmseb commented on varats/varats/tools/html_utils.py
> +"""Utility module for generating html files."""
@vulder do you think this is the right place for this module? Or should we find a better place?

2020-11-26 13:53 UTC, vulder commented on varats/varats/tools/html_utils.py
> +"""Utility module for generating html files."""
Hmm, good point. Normally we put all utils code into core so other people could work with them. Is the html overview part generic enough for that?
If not I see two options.
1) keep it in tools as is
2) create another folder for specific tool suite utils
Not sure what is better here.

2020-11-26 13:56 UTC, vulder commented on varats/varats/tools/html_utils.py
> +__HTML_BASE_TEMPLATE = """<!DOCTYPE html>
Reuse is one thing, having better separation and easier insertion are the other two.
+ editing/testing the files in python is a bit cumbersome, e.g., simple viewing the current html in a browser or testing different css foo.

2020-11-26 14:04 UTC, boehmseb commented on varats/varats/tools/html_utils.py
> +"""Utility module for generating html files."""
What is in the module right now *could* be generic enough for core (that's why I left the other more specific templates in the driver module), but I'm not sure whether this is actually interesting for core.

I also thought of your two suggestions. In my opinion, it would fit better inside a `utils` package/folder, but I was not sure if we tried to get rid of this during the split of core, or whether the utils modules all moved to core by chance.

2020-11-26 14:11 UTC, boehmseb commented on varats/varats/tools/html_utils.py
> +__HTML_BASE_TEMPLATE = """<!DOCTYPE html>
A disadvantage of having separate files would be that it takes more work to make the templates available to the user (e.g., what templates or styles are available).
And editing is not cumbersome at all if you have an IDE that can interpret strings as any language you want :wink: 

As I said, at least for now, I don't see the benefit. This will of course change if we add more fancy CSS/js, etc., but we can still change that then.

2020-11-26 14:57 UTC, vulder commented on varats/varats/tools/html_utils.py
> +__HTML_BASE_TEMPLATE = """<!DOCTYPE html>
For now, ok. But we should later fix this.

Regarding the editing, the problem is that I cannot open it with chrome and edit HTML/css directly to see the impact. Dose pyChar render the HTML for you in the IDE from a string?

2020-11-26 14:58 UTC, vulder commented on varats/varats/tools/html_utils.py
> +"""Utility module for generating html files."""
It was by chance because everything was reusable/used in core code.

Then just create a special name `utils` package for varats.

2020-11-26 15:01 UTC, boehmseb commented on varats/varats/tools/html_utils.py
> +__HTML_BASE_TEMPLATE = """<!DOCTYPE html>
You can inject almost any language in any string literal in PyCharm and others. That means I can use all HTML-editing capabilities of my IDE inside any String literal I want.

2020-11-26 20:51 UTC, vulder commented on varats/varats/tools/html_utils.py
> +__HTML_BASE_TEMPLATE = """<!DOCTYPE html>
That part I know, but I want it to be rendered and the rendering on the fly updatable like in chrome with dev tools.

2020-11-27 09:08 UTC, boehmseb commented on varats/varats/tools/html_utils.py
> +__HTML_BASE_TEMPLATE = """<!DOCTYPE html>
I just checked and it seems like this is not possible. You can edit the string like it is its own file (you even get a new tab for this), but it seems this file is only virtual.

2020-11-27 14:54 UTC, vulder requested changes
Except for the folder name, this looks good.

2020-11-27 14:54 UTC, vulder commented on varats/varats/utils/html_utils.py
> +"""Utility module for generating html files."""
You cannot/should directly name the fold `utils`. This is the same as in `varats-core` namespace package, hence we can get a clash/race between the two inits when importing 'varats.utils.html_utils.py`.
We need to find a unique name for the package folder.

2020-11-30 14:27 UTC, vulder approved these changes

2020-11-30 14:27 UTC, merged