Adds a wrapper for benchbuild GitSubmodules in vara-test-repos
se-passau/VaRA-Tool-Suite pull request #418
Opened 2020-11-30 21:06 UTC by cormensratio

2020-12-06 22:07 UTC, vulder requested changes

2020-12-06 22:07 UTC, vulder commented on varats-core/varats/project/project_util.py
> +def rename_to_git():
Could you please try to replace find with our renaming impl from VaRA. `find`, used like this` has the problem of creating unwanted files.
see se-passau/VaRA#677

2020-12-06 22:07 UTC, vulder commented on varats-core/varats/project/project_util.py
>          source.fetch()
Why is it wrong to `fetch` here? Checking for a specific class looks a bit strange from a design point of view. Maybe we should adapt the `fetch` method if it does not do the right thing.

2020-12-06 22:07 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        version_filter: tp.Callable[[str], bool] = lambda version: True
If you don't change the defaults here, just forward the *args or *kw args that the user gave instead of copy pasting the current state of the super class.

2020-12-06 22:07 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        submodules: tp.Optional[tp.List[VaraTestSubmoduleSource]] = None
same

2020-12-06 22:07 UTC, vulder commented on varats-core/varats/project/project_util.py
> +                submodule_path = vara_test_repos_path + "/" + submodule.remote
Just make vara_test_repos_path a actual Path and just use `/` to concat paths together

2020-12-06 22:07 UTC, vulder commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +
a) why can you not just add everything into the SOURCE list like BB requests?
b) executing code at class parse time for filling class variables looks like bad design to me, why do you need this?

2020-12-07 08:40 UTC, boehmseb requested changes

2020-12-07 08:40 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +    if not isinstance(source, GitSubmodule) and hasattr(source, "fetch"):
Why not fetch submodules here?

Also, use `is_git_source()` here:
```suggestion
    if not isinstance(source, GitSubmodule) and is_git_source(source):
```

2020-12-07 08:40 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +    def version(self, target_dir: str, version: str = 'HEAD') -> pb.LocalPath:
Why do you need to override this?

2020-12-07 08:40 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +                    rename_to_git()
Doesn't this break the existing Git/Submodule abstraction, since the main git now also takes care to fetch its submodules as separate repos?
I think it would be better to also have a class `VaraTestRepoSubmodule(GitSubmodule)`. It might be that we then need a better way to distinguish Git sources from GitSubmodule sources, but that can be handled by some function similar to `is_git_source()`.

@vulder what's your take on this?

2020-12-07 08:40 UTC, boehmseb commented on varats/varats/projects/c_projects/gzip.py
> +    CONTAINER = ContainerImage()
You should do this in all project classes since they all will break with a BB upgrade.

Which reminds me: we need to upgrade the BB dependency. @vulder maybe we want a new BB release for this?

2020-12-07 09:10 UTC, cormensratio commented on varats/varats/projects/c_projects/gzip.py
> +    CONTAINER = ContainerImage()
I had not in mind that this PR should add a container for all projects, but i can of course do that.

2020-12-07 09:22 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +    def version(self, target_dir: str, version: str = 'HEAD') -> pb.LocalPath:
At least at one point in the report generation, the original version() call would produce an error similar to this:
```
Stderr:       | fatal: repository 'LibraryAnalysisRepos/TwoLibsOneProjectInteractionDiscreteLibsSingleProject/Elementalist' does not exist
```
As in the overwritten fetch() of VaraTestRepoSource, we have to provide a correct path to the local repository in the version() call, which needs another kind of wrapper for the paths. Therefore I provided the missing path parts in the overwritten version() and removed the insignificant clone flags for a local repository clone.

2020-12-07 09:28 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +    if not isinstance(source, GitSubmodule) and hasattr(source, "fetch"):
But why do we not fetch submodules? I would assume that if we get the git path to a submodule, we want to access it and hence, it should be fetched.

2020-12-07 09:29 UTC, boehmseb commented on varats/varats/projects/c_projects/gzip.py
> +    CONTAINER = ContainerImage()
We have to because of the implicit BB upgrade.

2020-12-07 09:31 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +                    rename_to_git()
Since benchbuild's Git() handles and initializes its submodules and the actual GitSubmodule() only provides an entry point in code to distinguish between main repository and submodule, I ensured that the corresponding wrapper (VaraTestRepoSource) does the same with the local repositories.

2020-12-07 09:34 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +def rename_to_git():
I will try to replace it.

2020-12-07 09:40 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +    def version(self, target_dir: str, version: str = 'HEAD') -> pb.LocalPath:
Ah, I see. Seems like git still checks whether the remote repository exists despite the `--dissociate` and `--reference`.

2020-12-07 09:49 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +                    rename_to_git()
Yes, you are right. Somehow I overlooked that obvious problem.
But still, I think we should have this extra class for submodules as I said above. You can then simply call `fetch()` on each submodule and copy it afterwards. Depending on the repo, it could even be that `git submodule --init` will work afterwards.

2020-12-07 10:29 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +    if not isinstance(source, GitSubmodule) and hasattr(source, "fetch"):
Your question is related to one question of @vulder regarding the SOURCES list. I'll test if your proposed idea can solve both problems and let you know.

2020-12-07 10:45 UTC, simbuerg commented on varats/varats/projects/c_projects/gzip.py
> +    CONTAINER = ContainerImage()
I think that should be a bug-report for benchbuild. An empty source declaration should not be necessary.

2020-12-07 12:51 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +    if not isinstance(source, GitSubmodule) and hasattr(source, "fetch"):
The main problem is that we need the initialized submodules already when the main repo gets initialized. This is also the reason why I built the submodule list in the SOURCES before the VaraTestRepoSource. Considering that, I saw no reason to fetch() the submodules, at the referred code part, again.
I could not figure out how i can circumvent the non-optimal definition of SOURCES and the execution of code at class parse time, which @vulder already mentioned. But your proposed wrapper (VaraTestRepoSubmodule) for the GitSubmodules enables us to call fetch() on a submodule without an path-error, therefore i can remove the ```if not isinstance(source, GitSubmodule)``` part.

2020-12-07 12:51 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +                    rename_to_git()
As mentioned above, I added a wrapper for the GitSubmodules. Currently I replaced this code part with a loop over the submodules and call fetch on each one.

2020-12-07 13:00 UTC, cormensratio commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +
As I wrote in a lower comment to @boehmseb , we need the initialized submodules already when the main repo gets initialized. Currently I have found no other way to provide the main repo with the extracted submodules, therefore I initialize them at the same time, when we fetch and initialize the main repo. To do so, the main repo has to know which submodules it has to initialize, so i pass a list of its submodules. 
This would also mirror the behaviour of benchbuilds Git(), as it initializes/manages its submodules.
But i totally agree that this probably is a bad design. If you have a recommendation to improve this, let me know.

2020-12-07 13:02 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +        version_filter: tp.Callable[[str], bool] = lambda version: True
Done

2020-12-07 13:03 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +                submodule_path = vara_test_repos_path + "/" + submodule.remote
Done

2020-12-07 13:06 UTC, cormensratio commented on varats-core/varats/project/project_util.py
>          source.fetch()
I now have adapted the fetch of the VaraTestRepoSubmodule. See lower conversations with boehmseb.

2020-12-07 13:10 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +    if not isinstance(source, GitSubmodule) and hasattr(source, "fetch"):
Those are actually two different problems. 
For our test repo sources, we probably will not be able to get rid of this forward-reference.
This comment here and the wrapper around `GitSubmodule` are needed to preserve the submodule-abstraction built into benchbuild.

2020-12-07 13:12 UTC, boehmseb commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +
I agree with Simon here. I fear we will not be able to get rid of this forward-reference for our test repos.

2020-12-07 13:28 UTC, vulder commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +
I understand the problem but we have to find another way to specify this. In the current state this requires to much knowledge between the different Git/Submodules becoming brittle if either the project or something else changes.

In general, we need to find a way so that our normal VaraTestGit can do a submodule initialization without the VaraTestGitSubmodules. All needed information is already present in the .gitted/.gitsubmouldes files we just need to find a way to map this back to our TestRepo structure, so we can initialize the submodules -- as git would to with submodule init -- without a relation to the VaraTestGitSubmodule class. But I'm not sure how easy this is to implement.

Discussing this in detail in the next meeting sound good to me.

2020-12-07 13:34 UTC, cormensratio commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +
:+1:

2020-12-07 14:16 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +def rename_to_git():
Done

2020-12-16 09:31 UTC, vulder approved these changes
Looks good, found just a few nits.
Can you afterwards in a new PR also clean up VaRATestRepo source with the new `copy_renamed...` method and checkout if the issue is fixed? thanks :smile: 

@boehmseb I think we need a BB version bump for this, do we already have a BB release that includes this or are we still waiting for the container fix?

2020-12-16 09:31 UTC, vulder commented on varats-core/varats/project/project_util.py
> +          2. extract the specified submodule from the vara-test-repos repo
Should also mention that we do the .gitted -> .git rewriting

2020-12-16 09:31 UTC, vulder commented on varats/varats/projects/c_projects/gzip.py
> +    CONTAINER = ContainerImage()
@cormensratio If you already filed the bug report, just add a comment here:
```
TODO (PolyJIT/benchbuild#42): remove after BB provides implicit default
```

2020-12-16 09:31 UTC, vulder commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +    CONTAINER = ContainerImage()
same

2020-12-16 13:26 UTC, boehmseb commented
> @boehmseb I think we need a BB version bump for this, do we already have a BB release that includes this or are we waiting for the container fix?

The following issues on benchbuild side need to be resolved first: PolyJIT/benchbuild#345, PolyJIT/benchbuild#346, and PolyJIT/benchbuild#347. The last one asks for a new release.

2020-12-16 14:45 UTC, boehmseb reviewed
Two quick questions. Otherwise looks good.

2020-12-16 14:45 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> -        limit=1
Is there any specific reason why you removed this?
Yes, in practice, we do not use those variables, since we do not call `versions()` on this repo. But technically, we only want the first revision of HEAD of this repo.

2020-12-16 14:45 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +                os.rename(os.path.join(root, name), os.path.join(root, ".git"))
Can this case happen? Isn't `.git` (and hence, `.gitted`) always a dir?

2020-12-16 15:42 UTC, boehmseb requested changes

2020-12-16 15:42 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +            ).split('\n')
This fails for repos without a `.gitmodules`. You should check first if this file exists and skip this whole step if not.

2020-12-17 10:38 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +          2. extract the specified submodule from the vara-test-repos repo
Added 
```3. rename files that were made git_storable (e.g., .gitted) back to their original name (e.g., .git)```

2020-12-17 10:39 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> -        limit=1
The default value for "refspec" in BBs Git is already "HEAD", but I will add it again to make it clear. The deletion of limit was unintentional.

2020-12-17 10:39 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +                os.rename(os.path.join(root, name), os.path.join(root, ".git"))
It seems that git can create .git files. 
See a prior discussion: https://github.com/se-passau/VaRA/pull/668#discussion_r486217970

2020-12-17 10:39 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +            ).split('\n')
You are right. Always talking about submodules makes you forget that not every repo has them ;).

2020-12-17 10:40 UTC, cormensratio commented on varats/varats/projects/cpp_projects/two_libs_one_project_interaction_discrete_libs_single_project.py
> +    CONTAINER = ContainerImage()
Done

2020-12-17 11:00 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +                os.rename(os.path.join(root, name), os.path.join(root, ".git"))
Ok

2020-12-18 10:53 UTC, boehmseb commented on varats/varats/projects/test_projects/bug_provider_test_repos.py
> +            limit=1,
For the projects, the limit needs to stay `None`, otherwise only the newest revision gets cloned. We want this only for the `vara-test-repos` repo.

Easiest fix is to revert 52fdb07cf5664dd70fb8a1447ac862b18092766e

2020-12-29 19:24 UTC, vulder requested changes
@boehmseb Do we have a smoke test for our own GitWrappers?
If no, maybe we should add a call that would trigger an error if something breaks.

Overall this seems fine to me :smile: 
After cleaning up with the BB release and small fixes we can merge this.

2020-12-29 19:24 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        return
This looks like we fail silently here, maybe we should write at least a error message to the log. Providing a wrong `dest_dir` seems like a clear error/misshap to me.

2020-12-29 19:24 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        cp("-r", main_repo_src_local + "/.", tgt_loc)
Is the `"/."` needed here? I would assume that `cp` defaults to the dir.

2020-12-29 19:24 UTC, vulder commented on varats/varats/projects/c_projects/gzip.py
> +    CONTAINER = ContainerImage()
Can be fixed with the next BB release.

2020-12-30 13:39 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +        return
You are rigth. I will add a log error message.

2020-12-30 13:40 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +        cp("-r", main_repo_src_local + "/.", tgt_loc)
It is needed. Your assumption is correct, but since the target directory got already created in line 377, we only want to copy the contents to avoid nesting e.g., the Elementalist folder twice.

2020-12-30 13:40 UTC, cormensratio commented on varats/varats/projects/c_projects/gzip.py
> +    CONTAINER = ContainerImage()
I added the new bb release to the requirements.txt, setup.py and removed the todos.

2021-01-04 09:10 UTC, boehmseb approved these changes
lgtm

2021-01-07 10:21 UTC, cormensratio commented on requirements.txt
> +benchbuild>=6.0.1
PR https://github.com/se-passau/VaRA/issues/488, which got merged in vara-dev, uses the benchbuild version `"benchbuild>=5.2,<6.0.0"`. I do not know if this version range is required for the PR to work, but a bb version >= 6.0.1 is required for this PR.

2021-01-11 08:20 UTC, boehmseb approved these changes
Found one small bug (maybe we should add a test for that). Otherwise looks good

2021-01-11 08:20 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +            return tgt_loc
You still have to do the checkout, even if no submodules are present.

```suggestion
        if not Path(tgt_loc / ".gitmodules").exists():
            with pb.local.cwd(tgt_loc):
                git("checkout", "--detach", version)
            return tgt_loc
```

2021-01-11 08:20 UTC, boehmseb commented on requirements.txt
> +benchbuild>=6.0.1
That was to pin the version to pre-6.0 since no migration to the new BB version was done there. But we have done the migration here, so 6.0.1 is fine.

2021-01-11 09:03 UTC, vulder approved these changes

2021-01-11 09:03 UTC, vulder commented on varats-core/varats/project/project_util.py
> +# pylint: disable=too-many-ancestors
This disable is wrong, this would disable all too-many-ancestors errors in the whole file

2021-01-11 11:35 UTC, cormensratio commented on varats-core/varats/project/project_util.py
> +# pylint: disable=too-many-ancestors
I changed it to target the corresponding line only.

2021-01-11 11:58 UTC, merged