Result folder cleanup utility resolves se-passau/VaRA#488
se-passau/VaRA-Tool-Suite pull request #420
Opened 2020-12-07 13:11 UTC by Sinerum

Implemented the cleanup utility for old files and user specified regex as described in  se-passau/VaRA#488

2020-12-07 14:06 UTC, boehmseb requested changes
As this is your first PR, there is a bit more to say about our development guidelines:

Typing:
---------

We use mypy to statically typecheck our code. This can be donw from the commandline via `mypy --strict -p varats`. If you encounter lots of errors from benchbuild modules, just add a ` | grep -v "error: unused 'type: ignore' comment"`. Please fix all type errors that are related to your code.

Linting:
----------

We use pylint for static code analysis. you should be able to run it with `pylint varats`. Again, please fix all errors related to your code if possible, or silence them otherwise.

Formatting:
---------------

We have a mechanism to install and manage git hooks that take care of formatting, import ordering and such. Simply run `pre-commit install` in your environment to activate those git hooks. You can run the hooks manually via `pre-commit run --all-files`.

Usually our CI would also enforce that a PR adheres to these requirements, but travis has ceased to support open source projects apparently and does not work currently.


As for the code itself:
----------------------------

I added some comments to address typos and some smaller mistakes.
Also, please make the inner functions of `__casestudy_cleanup()` top-level functions as they do not really depend on their outer function. You can make them private (one leading `_` indtead of two) so they can still be tested easily.

2020-12-07 14:06 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +                        newer_files.__setitem__(commit_hash,opt_res_file)
```suggestion
                        newer_files[commit_hash] = opt_res_file
```

2020-12-07 14:06 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +                            nnewer_files.__setitem__(commit_hash,opt_res_file)
Typo?

```suggestion
                            newer_files[commit_hash] = opt_res_file
```

2020-12-07 14:06 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +            old_files = []
add type annotation

2020-12-07 14:06 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +                if os.path.exists(file):
As you already have a `Path` here, prefer the pathlib API over `os`:
```suggestion
                if file.exists():
```

2020-12-07 14:06 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +            todelete = []
Add type annotation.

2020-12-07 14:06 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +        if filter == "":
Empty strings are `False` in python.

```suggestion
        if not filter:
```

2020-12-07 14:06 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +                print(f"{file_name}")
I'm not sure if we want to list all files here. What do you think @vulder?

2020-12-07 14:06 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +                if cli_yn_choice("Do you whant to delte these files","n"):
```suggestion
                if cli_yn_choice("Do you whant to delete these files","n"):
```

2020-12-07 14:06 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +                        if os.path.exists(result_dir_path / file_name):
Use `Path.exists()`.

2020-12-07 15:43 UTC, vulder requested changes
Overall functionality looks good and matches what I had in mind when writing the issue :+1: .
I remarked a few things that we should clean up/fix before merging.

A large part of the remarks would be automatically solved in the future when we fix your setup. If you have question just write me or @boehmseb.

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +def __casestudy_cleanup(args: tp.Dict[str, tp.Any],parser: ArgumentParser) -> None:
Formatting, should be automatically checked/fixed in the future by the precommit checker. To fix this just use yapf directly or integrate yapf into your IDE. Assuming PyCharm @boehmseb can help you on how to set it up.

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +                if cli_yn_choice("Do you whant to delte these files","n"):
`cli_yn_choice` is not defined in this context, I guess there is a import missing.

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +            except:
This is a cache all without a specific exception type, which exception did you want to catch here?

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +                EOFError
This statement has no effect, did you want to cache EOFErrors here?

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +                continue
When does this happen? Just catching and skipping the exception without any logging/user message seems a bit strange to me.

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +        filter = args["filter"]
`filter` is a python build in function, maybe rename this var to `filter_regex`?

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +        if filter == "":
```suggestion
        if not filter:
```

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +            todelete = []
```suggestion
            files_to_delete: tp.List[?] = []
```
Maybe `files_to_delete` is a clearer name.
+ For empty list constructions we should add a type annotation to specify the type, so miss use later would be caught.

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +                   todelete.append(result_file_name);
```suggestion
                match =  re.match(filter,result_file_name)
                if match is not None:
                    todelete.append(result_file_name);
```
Wrong indentation depth

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +            try:
```suggestion
                print(f"{file_name}")
            print(f"Found {len(todelete)} matching result files in {result_dir_path}:")
            
            try:
```
I would add a space here, makes it a bit easier to spot where the user check happens.

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
>          result_dir_paths = find_result_dir_paths_of_projects()
Is method was started by cormensratio but we should fix it an clean it up in this PR, so it works correctly.

a) `__contains__` should not me called directly
b) the contains check is not necessary use:
```
MetaReport.result_file_has_status_*
```
For error files we should check `error` and `cerror` here.

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
>      def remove_result_files_by_regex() -> None:
@boehmseb What do you think, should be also restrict regex deletion (by default) to the current case study?

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +                                opt_res_file.stat().st_mtime
If I remember correctly, we need to use `st_mtime_ns` here, with `st_time` we run into the strange floating point time comparison bug.
@boehmseb

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +                            nnewer_files.__setitem__(commit_hash,opt_res_file)
`nnewer_files` looks like a typo, because it's not defined in this scope.
Furthermore, to set a item in a map just use the `[]`operator instead of calling `__setitem__` cirectly.
```
foo_dict = {}
foo_dict["key"] = bar_value
```

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +            old_files = []
Should have a type annotation

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +                continue
```suggestion
                continue

```

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +                        newer_files.__setitem__(commit_hash,opt_res_file)
operator `[]`

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
>      def remove_old_result_files() -> None:
@boehmseb Maybe we should move these cleaning functions into a separate module, any suggestions where they would have a nice place to live and feel welcome?
Ideas:
* paper_mgmt
* report.report
* new one

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +        help="Filter when unsing regex",
```suggestion
        help="Regex to determine which report files should be deleted.",
```

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +        "--filter",
In `vara-cs status` we called it `--filter-regex`, using the same here would make the option consistent.
```suggestion
        "--filter-regex",
```

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +        __casestudy_cleanup(args,parser)
```suggestion
        __casestudy_cleanup(args, parser)
```
Just formatting thins but running yapf once should automatically fix everything :smile:

2020-12-07 15:43 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +        remove_result_files_by_regex()
Maybe we should use an enum here to mark the different cases.

2020-12-07 15:45 UTC, vulder commented
Oh boy :laughing: some of my comments overlap with @boehmseb , somehow github did not refresh for me and show me your comments^^

2020-12-10 10:01 UTC, Sinerum commented on varats/varats/tools/driver_casestudy.py
> +                continue
EOFError occurs when the input to the confirmation is terminated. I would treat that as a no in this case and move or would you expect different behavior?

2020-12-12 13:54 UTC, Sinerum commented on varats/varats/tools/driver_casestudy.py
>          result_dir_paths = find_result_dir_paths_of_projects()
i could not find error in the FileStatusExtension enum so i only check CompileError

2020-12-17 13:55 UTC, vulder approved these changes
The enum fix is missing,otherwise, this looks good to me. Thanks for implementing this :smile:

2020-12-17 13:55 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +    if cleanup_type == "error":
The enum is still missing

2020-12-17 14:03 UTC, boehmseb approved these changes

2020-12-17 14:03 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +                #  deleted files.
I would say we don't need this, so the TODO can be removed

2020-12-18 23:25 UTC, vulder approved these changes
I found 2 small nits, please clean them up before I merge it but there is no further review required afterwards :).
The tool looks good :+1:  thanks for implementing and fixing the issue.

2020-12-18 23:25 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +                MetaReport.result_file_has_status(
Just a quick tipp here, you don't have to directly pass the FSE you want to check, there are helper methods that make calling code easier to read/write.
Just use:
```
MetaReport.result_file_has_status_failed(result_file_name)
```

2020-12-18 23:25 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
>              ) and MetaReport.is_result_file(result_file_name):
Small side note: If you want to check if `result_file_name` is actually a result file, i.e., conforms to the filename formatting, you should do it before checking the status because checking the status on a wrong formatted file will most likely not work. This would in the end not cause an error because the status checks would return `False` and everything is OK. However, with check result file first it is "logically" the correct ordering and makes the checks in order a bit easier to understand.

2020-12-28 15:58 UTC, vulder approved these changes

2021-01-05 21:32 UTC, merged