Initial container support for varats
se-passau/VaRA-Tool-Suite pull request #422
Opened 2020-12-17 15:43 UTC by boehmseb

Still need to wait for PolyJIT/benchbuild#347 and related issues before merging.

What works:
- [x] declaring/building base containers
- [x] using custom BB/varats versions in the container
- [x] using pip to install BB/varats in the container
- [x] running BB experiments inside a container
- [x] result files are written to specified results directory
- [x]  documentation

What does not work yet:
- [ ] installing research tools into a container
- [ ] running containers on slurm (see PolyJIT/benchbuild#322)

2021-01-13 10:05 UTC, vulder requested changes

2021-01-13 10:05 UTC, vulder commented on docs/source/vara-ts-api/containers.rst
> +    └─────────────────────────────────┘
```suggestion
    ┌───────────────────────────────────┐  \
    │ Base Container (e.g., Debian 10)  │   |
    └───────────────────────────────────┘   |
                      +                     |
    ┌───────────────────────────────────┐   |
    │              varats               │   |
    └───────────────────────────────────┘   |
                      +                      > Base Image
    ┌───────────────────────────────────┐   |
    │            benchbuild             │   |
    └───────────────────────────────────┘   |
                      +                     |
    ┌───────────────────────────────────┐   |
    │    Research Tool (e.g., VaRA)     │   |
    └───────────────────────────────────┘  /
                      +
    ┌───────────────────────────────────┐
    │         Project Specific          │
    └───────────────────────────────────┘
                      +
    ┌───────────────────────────────────┐
    │        Experiment Specific        │
    └───────────────────────────────────┘
```

2021-01-13 10:05 UTC, vulder commented on docs/source/vara-ts-api/projects.rst
> +To ensure that the container already contains everything required by BenchBuild, you should use one of our base images using the function :func:`~varats.containers.containers.get_base_image()`. You c
Maybe we should add a small example after this how one can add dependencies, e.g., with an apt call.

2021-01-13 10:05 UTC, vulder commented on docs/source/vara-ts-api/tables.rst
> +.. automodule:: varats.table.table
Is this the adaption the make the folder naming schema consistent? How is this related to the container PR?

2021-01-13 10:05 UTC, vulder commented on docs/source/vara-ts-api/tools/vara-container.rst
> +TODO: add section about tool selection once implemented
Do you want to fix this before merging? Otherwise, please slap an issue onto the TODO :)

2021-01-13 10:05 UTC, vulder commented on docs/source/vara-ts/benchbuild.rst
> +To use BenchBuild's container support, you first need to setup `buildah <https://github.com/containers/buildah/blob/master/install.md>`_ and `podman <https://podman.io/getting-started/installation>`_
```suggestion
To use BenchBuild's container support, you first need to setup `buildah <https://github.com/containers/buildah/blob/master/install.md>`_ and `podman <https://podman.io/getting-started/installation>`_ on your system.
Please follow their install instructions on how to setup both tools.
Keep in mind that you have to set a subuid and subgid mapping on all machines that need to run containers. 
```

2021-01-13 10:05 UTC, vulder commented on docs/source/vara-ts/benchbuild.rst
> +
We wanted to reword/rework this so these options are only presented to the reader as config knobs. The current settings are now generated by default.

2021-01-13 10:05 UTC, vulder commented on varats-core/varats/utils/settings.py
> +            "checkout or pip.",
```suggestion
            "source checkout or pip.",
```

2021-01-13 10:05 UTC, vulder commented on varats-core/varats/utils/settings.py
> +        "desc": "The local checkout of varats to use for the source install.",
```suggestion
        "desc": "Path to the local checkout of varats to use for the source install.",
```

2021-01-13 10:05 UTC, vulder commented on varats/varats/containers/containers.py
> +BB_ROOT = "/app/"
Maybe prefix this with `CONTAINER_`, otherwise, this could be confused with the root outside of the container.

2021-01-13 10:05 UTC, vulder commented on varats/varats/containers/containers.py
> +BB_ROOT = "/app/"
Further, it could be helpful to declare these vars as a `Path`, because they represent paths and the following code makes a lot of modifications, where when some `/` is not correctly added the resulting string will result in a crash.

2021-01-13 10:11 UTC, vulder commented
List of other things we found yesterday:

- [ ] add bulidah/podman aliases to docs + small helper section how to manually access containers
- [x] container registry clear (will be handled by BB)
- [ ] add crun dependency to docs
- [x] research_tool selection (already in TODOs)

2021-01-20 08:19 UTC, boehmseb commented on docs/source/vara-ts-api/tables.rst
> +.. automodule:: varats.table.table
It is an oversight from that PR that I fixed while I was at it.

2021-01-20 15:36 UTC, boehmseb commented
> List of other things we found yesterday:
>     * [ ]  small helper section how to manually access containers

You still know how you did this right? Because I did never really do this.
 
>     * [ ]  BB config not correctly found if not duplicated in vara-root

I cannot reproduce this.

2021-03-22 12:14 UTC, boehmseb commented
CI will work again when BB releases a new version.

2021-06-11 07:43 UTC, vulder commented
resolves se-sic/VaRA#718

2021-06-11 08:13 UTC, vulder approved these changes

2021-06-11 08:13 UTC, vulder commented on varats/setup.py
> +        "benchbuild>=6.1.1",
```suggestion
        "benchbuild>=6.2.0",
```
Following the requirements.txt this should be 6.2

2021-06-11 08:28 UTC, merged