added libjpeg-turbo as a project
se-passau/VaRA-Tool-Suite pull request #430
Opened 2021-01-14 16:30 UTC by Sinerum

Added [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo) as a Project.
Resolves se-passau/VaRA#704

2021-01-18 21:12 UTC, vulder requested changes

2021-01-18 21:12 UTC, vulder commented on varats/varats/projects/c_projects/libjpeg-turbo.py
> +class Libxml2(bb.Project, CVEProviderHook):  # type: ignore
The class name seems wrong :wink:

2021-01-18 21:12 UTC, vulder commented on varats/varats/projects/c_projects/libjpeg-turbo.py
> +"""Project file for libjpeg-turbo."""
You need to write the file as name as `libjpeg_turbo.py`

2021-01-18 21:12 UTC, vulder commented on varats/varats/projects/c_projects/libjpeg-turbo.py
> +            ("libjpeg.so.62.3.0", BinaryType.shared_library)
That wont work for other versions, is there maybe a symlink `libjpeg.so` that we can use?

2021-01-18 21:16 UTC, vulder commented
Otherwise, the project builds fine on my machine :+1:

2021-01-18 21:27 UTC, vulder commented on varats/varats/projects/c_projects/libjpeg-turbo.py
> +    NAME = 'libjpeg-turbo'
```suggestion
    NAME = 'libjpeg_turbo'
```
A, one thing I missed. We also need to use a `_` here, otherwise, our NAME detection breaks^^
I probably should setup a test that no wrong project names are introduced :laughing: (se-passau/VaRA#721)

2021-01-19 18:45 UTC, vulder commented on varats/varats/projects/c_projects/libjpeg_turbo.py
> +            version_filter=project_filter_generator("libjpeg-turbo")
```suggestion
            version_filter=project_filter_generator("libjpeg_turbo")
```

2021-01-19 18:49 UTC, vulder approved these changes

2021-01-19 18:51 UTC, boehmseb approved these changes

2021-01-19 18:52 UTC, merged