Adds a check for VaRA major releases
se-passau/VaRA-Tool-Suite pull request #431
Opened 2021-01-25 14:40 UTC by cormensratio

closes https://github.com/se-passau/VaRA/issues/565

2021-02-03 20:41 UTC, vulder requested changes
Could you add a few tests maybe for smaller methods that we at least can check the regex matches etc.?

Otherwise, in general this should work :+1:

2021-02-03 20:41 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +class UnixColors(Enum):
Please don't build your own solution here, plumbum already supports colored console output.

2021-02-03 20:41 UTC, vulder commented on varats/varats/tools/research_tools/research_tool.py
> +        """Returns true if a newer major release of VaRA is available."""
This method should probably return a `bool` an not `None`.
Furthermore, if the method is called `is_up_to_data` returning `true` to indicate that there is a newer version is a bit confusing :wink:

2021-02-03 20:41 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +            )
This method should only to the checking an return `true`/`false` when a miss match is detected. User output/handling what happens when this is not the case should be done in the driver or another appropriate location.

2021-02-03 20:41 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +            return highest_version
These two methods look very similar, I think we could merge this into on generic method.

2021-02-15 22:58 UTC, vulder requested changes
Overall this looks ok, I plan a new release for the next comming weeks to I'll wait to merge this until the release is done :)

2021-02-15 22:58 UTC, vulder commented on varats/varats/tools/driver_build_setup.py
> +    else:
I think it would be enough to only output something if this is not the case but I'm not sure.
@boehmseb What do you think? Should we always output the version check or just when it fails?

2021-02-15 22:58 UTC, vulder commented on varats/varats/tools/driver_build_setup.py
> +        print_up_to_date_message(tool)
Hmm, shouldn't we run this check before building the "possible" outdated version? Maybe it would be useful to ask the user if he wants to continue building should the version be out of date.

2021-02-15 22:58 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
>                  )
Just create the error string with an f-string
```
warning_str = f"No {sub_prj_name} ..."
LOG.warning(warning_str)
```

2021-02-16 08:06 UTC, boehmseb commented on varats/varats/tools/driver_build_setup.py
> +    else:
I would expect such a message only if no update and no upgrade was done.

2021-02-16 08:10 UTC, boehmseb commented on varats/varats/tools/driver_build_setup.py
> +        print_up_to_date_message(tool)
Same goes for update btw.

2021-02-16 09:08 UTC, cormensratio commented on varats/varats/tools/driver_build_setup.py
> +        print_up_to_date_message(tool)
Initially i did not intend to interrupt the build by asking the user if he wants to update and placed the update check at the end to minimize the risk for the user to skip it unintentionally. If interrupting the build process at the beginning for a release check prompt is okay, I think it would be the better solution.

2021-02-16 09:22 UTC, vulder commented on varats/varats/tools/driver_build_setup.py
> +        print_up_to_date_message(tool)
Yes, we should do the check before.

Update it self than, does not need a release check.

2021-02-16 09:22 UTC, vulder commented on varats/varats/tools/driver_build_setup.py
> +    else:
I thought so, then let's just print something in the case we have an outdated version.

2021-02-19 21:37 UTC, vulder commented on varats/varats/tools/driver_build_setup.py
> +        user_choice = input("> ")
Just use the choice util we already implemented in utils.

2021-04-12 08:07 UTC, vulder approved these changes

2021-05-30 21:14 UTC, merged