Introducing Commit Detection via Simple SZZ Algorithm
se-passau/VaRA-Tool-Suite pull request #433
Opened 2021-01-28 19:59 UTC by SimonFedick

Adds PyDriller as dependency and uses PyDriller version of the SZZ algorithm to identify fix inducing/introducing changes

2021-02-04 11:54 UTC, vulder reviewed
overall this looks quite simple with just using the pydriller API, however, we should carefully test this to not miss use their approach and check what results we get

2021-02-22 08:37 UTC, boehmseb requested changes
Implementation looks good, tests could use a little work.

2021-02-22 08:37 UTC, boehmseb commented on tests/provider/test_bug_provider.py
> +            return_value={}
Since you use this in multiple tests, it could make sense to make this a member (`self.mock_pydrill_repo`) and initialize it in a setup function.

2021-02-22 08:37 UTC, boehmseb commented on tests/provider/test_bug_provider.py
> +        self.assertEqual(rawbug_first_intro_ids, expected_first)
I think it  would make sense to test raw bugs and pygit bugs in separate tests, since two different API functions are tested here. But make sure to not introduce any duplicated code when splitting.

2021-03-01 13:13 UTC, boehmseb approved these changes

2021-04-30 11:25 UTC, boehmseb requested changes
Looks good overall, but I found a couple of smaller things.

2021-04-30 11:25 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +        Returns None if the set is empty.
If so, then the return type should be `Optional[pygit2.Commit]`.
But if I read this correctly, an exception is raised if the set is empty.

Also, please use the correct docstring syntax for returns:
```
Returns:
    ...
```

2021-04-30 11:25 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +                    suspect_tuple.clear_suspect(suspect)
You may want to terminate the for loop here.

2021-04-30 11:25 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +                    suspect_tuple.clear_suspect(suspect)
You may want to terminate the for loop here.

2021-04-30 11:25 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +                    suspect_tuple.clear_suspect(suspect)
You may want to terminate the for loop here.

2021-04-30 11:25 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +                    suspect_tuple.clear_suspect(suspect)
You may want to terminate the for loop here.

2021-04-30 12:14 UTC, SimonFedick commented on varats-core/varats/provider/bug/bug.py
> +        Returns None if the set is empty.
This is a remaining piece of the old interface where the return type was Optional type, but I figured an `is_cleared()` function to check whether there are still uncleared suspects and then just allowing to call this function if the tuple isn't cleared yet was more convenient for me than needing to check if the return type of this function is `None` or not every time.
Do you think I should adjust the docstring or go back to the old interface of this?

2021-04-30 14:18 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +        Returns None if the set is empty.
Just fix the docstring.

2021-04-30 14:19 UTC, boehmseb approved these changes

2021-04-30 15:06 UTC, SimonFedick commented on varats-core/varats/provider/bug/bug.py
> +        Returns None if the set is empty.
Great! That's what I did.

2021-05-01 10:47 UTC, vulder requested changes
Code looks ok to me. Am I seeing this right that the core parts are not covered by the tests or is this a codecov issue?

2021-05-01 10:47 UTC, vulder commented on tests/provider/test_bug_provider.py
> +        def mock_revparse(commit_id: str):
Just make the comment to a function doc

2021-05-01 10:47 UTC, vulder commented on varats-core/varats/provider/bug/bug.py
> +def _find_corresponding_pygit_suspect_tuple(
This function has no test coverage but is central to functionality. I think we should try to come up with a way write basic tests for this.
@boehmseb What do you think?

2021-05-01 10:47 UTC, vulder commented on varats-core/varats/provider/bug/bug.py
> +def _find_corresponding_raw_suspect_tuple(
same here

2021-05-01 10:47 UTC, vulder commented on varats-core/varats/provider/bug/bug.py
>  def _filter_all_issue_pygit_bugs(
same here

2021-05-01 10:47 UTC, vulder commented on varats-core/varats/provider/bug/bug.py
>  def _filter_all_issue_raw_bugs(
this implementation is the same as the above, expect for small details, can we merge the two?

2021-05-03 07:23 UTC, boehmseb commented
> Am I seeing this right that the core parts are not covered by the tests or is this a codecov issue?
There are parts that are not covered, but definitely not as many as codecov claims. The coverage report seems very fishy to me and does not agree with the coverage report I just created on my local machine. My local report tells me, that `bug.py` has a total coverage of 63% and at least some of the methods you marked are definitely covered.

2021-05-03 07:25 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +def _find_corresponding_pygit_suspect_tuple(
This function is covered except for the for-loops. I guess it would be quite easy to extend existing tests to completely cover this.

2021-05-03 07:26 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
>  def _filter_all_issue_pygit_bugs(
Also covered, except for the while-loop.

2021-05-03 13:35 UTC, vulder commented
I updated to the current vara-dev version, there we fixed the coverage tracking issue.

2021-05-10 09:15 UTC, vulder approved these changes

2021-05-10 13:51 UTC, boehmseb commented on tests/provider/test_bug_provider.py
> +                    intro_first_bug = pybug.introducing_commits
```suggestion
            intro_first_bug = set()
            intro_second_bug = set()
            for pybug in pybugs:
                if pybug.fixing_commit.hex == event_close_second.commit_id:
                    intro_second_bug = pybug.introducing_commits
                if pybug.fixing_commit.hex == event_close_first.commit_id:
                    intro_first_bug = pybug.introducing_commits
```

2021-05-11 22:32 UTC, vulder approved these changes

2021-05-11 22:33 UTC, merged