Add an understandable error message to vara-cs when no paper-config exits
se-passau/VaRA-Tool-Suite pull request #434
Opened 2021-01-29 09:58 UTC by Sinerum

Add an error message explaining how to create a paper-config when no paper-config was found by vara-cs
closes se-passau/VaRA#719

2021-01-29 10:24 UTC, boehmseb requested changes
Can you please make this a decorator so that we can use this like this:
```python
@configuration_lookup_error_handler
def __casestudy_exec_command(...):
    ...
```

2021-02-01 11:43 UTC, boehmseb requested changes
Looks good now apart from the two missing type annotations and the small detail I annotated.

2021-02-01 11:43 UTC, boehmseb commented on varats/varats/tools/tool_util.py
> +    def wrapper_configuration_lookup_error_handler(*args, **kwargs):
```suggestion
    @wraps(func)
    def wrapper_configuration_lookup_error_handler(*args, **kwargs):
```

See here for an explanation: https://stackoverflow.com/questions/308999/what-does-functools-wraps-do

2021-02-08 01:06 UTC, vulder approved these changes
Looks good from my side, please clean up the open issues (mypy).

2021-02-15 08:55 UTC, boehmseb requested changes

2021-02-15 08:55 UTC, boehmseb commented on varats/varats/tools/tool_util.py
> +    """Wrapper for drivers to catche internal Exceptions and provide a helpful
```suggestion
    """Wrapper for drivers to catch internal Exceptions and provide a helpful
```

2021-02-15 08:55 UTC, boehmseb commented on varats/varats/tools/tool_util.py
> +    ) -> tp.Any:
I think, we should restrict the return type to be a function:
```suggestion
    ) -> tp.Callable[..., tp.Any]:
```

2021-02-15 11:33 UTC, boehmseb commented on varats/varats/tools/tool_util.py
> +    ) -> tp.Callable[..., tp.Any]:
My mistake. Either, we allow functions with return types to be wrapped, then we need to add a `return` in line 80, or we do not allow returns, then we need to do this change:
```suggestion
    ) -> tp.Callable[..., None]:
```

2021-02-15 13:18 UTC, boehmseb approved these changes

2021-02-15 15:33 UTC, merged