Enable vara container install
se-passau/VaRA-Tool-Suite pull request #441
Opened 2021-02-10 12:12 UTC by boehmseb

Resolves se-passau/VaRA#718
The dependency declarations in this PR will also be useful for se-passau/VaRA#626

2021-02-10 12:17 UTC, boehmseb commented on varats/varats/tools/research_tools/vara.py
> +        layers.env(BB_ENV=f"{{PATH: [{str(container_vara_dir / 'bin')}]}}")
If we do it like this, we can set `BB_ENV` only at one place, since every call to `layers.env()` overwrites existing env vars in the container. What's your opinion on this @vulder

2021-02-10 12:39 UTC, vulder requested changes

2021-02-10 12:39 UTC, vulder commented on varats/varats/tools/research_tools/research_tool.py
> +        )
Maybe use a f string here

2021-02-10 12:39 UTC, vulder commented on varats/varats/tools/research_tools/research_tool.py
> +
Does it make sense to add a `add` method for a new dependency?

2021-02-10 12:39 UTC, vulder commented on varats/varats/tools/research_tools/research_tool.py
> +class Dependencies:
We should include 1-2 tests to check that the install strings are correctly generated.

2021-02-10 12:39 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +    })
```suggestion
    __DEPENDENCIES = Dependencies({
        Distro.DEBIAN: ["libboost-all-dev"],
        Distro.ARCH: ["boost"]
    })
```
Should we make this private? Otherwise, users think they can change this.

2021-02-10 12:39 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +        layers.env(BB_ENV=f"{{PATH: [{str(container_vara_dir / 'bin')}]}}")
Hmm, one location to define it seems fine to me. But maybe we should add code that checks what is defined in the current BB env not that we miss something. Not related to the path by maybe something like this.
BB_ENV = { 'enable_instrumentation': "FooOn"}

... inside the container ... a binary could look for the env var to enable/disable instrumentation code

2021-02-10 12:39 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +        layers.copy_([str(self.install_location())], str(container_vara_dir))
I think, we still need to handle the copying of shared libraries that are provided via the LD_LIBRARY_PATH

2021-02-10 12:39 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +        Distro.DEBIAN: ["libboost-all-dev"],
Syntax looks good to me :)

2021-02-10 12:44 UTC, boehmseb commented on varats/varats/tools/research_tools/research_tool.py
> +
I don't see any use case for this right now. Currently, we only want to use them for research tools, and there all dependencies are known statically.
But this class will get additional functions anyway at some point (at least when we fix se-passau/VaRA#626).

2021-02-10 12:49 UTC, boehmseb commented on varats/varats/tools/research_tools/vara.py
> +        layers.copy_([str(self.install_location())], str(container_vara_dir))
When we use older containers, we might. But for a debian 10 container (the one I tested with) I can simply install boost as a dependency and I don't need to copy anything.
That's why I committed it that way.
Also, I'm not quite sure what's the best way to do this. Maybe look at the BB config and if there is a entry for `LD_LIBRARY_PATH` in the env copy the contents to the container? Or add a mountpoint and always let the `LD_LIBRARY_PATH` point there?

2021-02-10 12:50 UTC, boehmseb commented on varats/varats/tools/research_tools/vara.py
> +        layers.env(BB_ENV=f"{{PATH: [{str(container_vara_dir / 'bin')}]}}")
Well, that's actually a second point you are talking about here.
But I guess this will become a longer discussion we should do in person.

2021-02-11 10:31 UTC, vulder commented on varats/varats/tools/research_tools/research_tool.py
> +
kk, then no

2021-03-01 15:44 UTC, boehmseb commented on varats/varats/tools/research_tools/vara.py
> +    })
Not sure. Could be useful to others to query the dependencies of a tool though...

2021-03-01 15:46 UTC, boehmseb commented on varats/varats/tools/research_tools/vara.py
> +        layers.env(BB_ENV=f"{{PATH: [{str(container_vara_dir / 'bin')}]}}")
Should be fixed once and for all by the new `BaseImageCreationContext` class.

2021-03-01 15:49 UTC, boehmseb commented on varats/varats/containers/containers.py
> +class BaseImageCreationContext():
If we feel the need to, we could hide the complete BB-buildah interface behind this context and only allow a couple of "safe" operations. Although only during base image creation. Projects are still allowed to mess everything up if they want to...

2021-03-01 17:00 UTC, boehmseb commented on varats/varats/tools/research_tools/vara.py
> +        layers.copy_([str(self.install_location())], str(container_vara_dir))
Just copying the thing for now

2021-03-05 09:53 UTC, vulder approved these changes
Regarding the context -> sounds good

2021-03-05 09:53 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +    })
That's true but then we should provide a get that copies the list. From my current understanding I only see read_only access making sense here.

2021-03-05 09:57 UTC, boehmseb commented on varats/varats/tools/research_tools/vara.py
> +    })
Would make sense to include that as an abstract class-level function (yes, that is a thing with python's abc) in the base class then.

2021-03-08 14:01 UTC, vulder approved these changes

2021-03-08 14:01 UTC, merged