Adds blame_diff_library_interaction_database
se-passau/VaRA-Tool-Suite pull request #443
Opened 2021-02-22 20:06 UTC by cormensratio

2021-02-24 10:50 UTC, vulder requested changes
Could you also please put the tweaked command line string for the graph generation into the docs.

2021-02-24 10:50 UTC, vulder commented on varats/varats/data/databases/blame_diff_library_interaction_database.py
> +    _compare_timestamps,
The current state of how the functions are used across modules is a bit mixed up.

@boehmseb How should we handle this case?
Options:
a) Keep them protected on a module level (original module)
b) Define them in `the blame_diff_metrics_database` module, similar for others we treat the most basic module as the one that has the utility functions for this group of databases. But make the functions public so it's clear they can be reused.
c) Put both database impls (old + BDLibIterDB) into one module, and keep them protected.
c) Create a utility module for all databases, could be a bit over generic.
d) Create a utility module for the specific blame_diff databases that both import then?

2021-02-24 10:50 UTC, vulder commented on varats/varats/data/databases/blame_diff_metrics_database.py
> +    )
We should add some docs here that describe what the function does.

2021-02-24 10:50 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +            directory=str(plot_dir) + "/" + plot_subdir,
assuming `plot_dir` is a `Path`
It would be better to first concat parts of the path and then convert it into a string.

2021-02-24 10:50 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +            view_mode=view_mode, show_edge_weight=True, show_blame_diff=True
Did you want to make this configurable from the outside?

2021-02-26 10:01 UTC, cormensratio commented on varats/varats/data/databases/blame_diff_metrics_database.py
> +    )
I'll add the docs when we have decided how we handle the function scope.

2021-02-26 10:02 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +            view_mode=view_mode, show_edge_weight=True, show_blame_diff=True
Yes, my intention is to allow the user to pass params that show only the normal interaction plot or only the blame diff plot or both together, which results in a blame diff overlay.

2021-03-01 08:48 UTC, boehmseb commented on varats/varats/data/databases/blame_diff_library_interaction_database.py
> +    _compare_timestamps,
Either b) or e). I think the amount of code we reuse would justify a utility module, but we could also leave it in the `blame_diff_metrics_database` module.

2021-03-01 08:48 UTC, boehmseb commented on varats/varats/data/databases/blame_diff_metrics_database.py
> +    )
That goes for all these functions btw., they will become public regardless of the place we put them.

2021-03-01 12:12 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +            return self._get_interaction_data(True)
```suggestion
            if blame_interactions:
                inter_df = self._get_interaction_data(False)
            else:
                inter_df = self._get_interaction_data(True)
                
            if  blame_diff:
                diff_df = self._get_interaction_data(True)
                return _add_diff_amount_col_to_df(inter_df, diff_df)

            return inter_df
```
I think this could make it a bit more readable by separating the two cases

2021-03-09 19:21 UTC, vulder requested changes

2021-03-09 19:21 UTC, vulder commented on tests/data/databases/test_blame_diff_metrics_database.py
> +            )
Why do you need such a hacky way to access the parent folder? If you want to access the test data, there should be some helper function in utils.

2021-04-13 08:04 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +            view_mode=view_mode, show_edge_weight=True, show_blame_diff=True
Should be resolved after https://github.com/se-sic/VaRA/issues/545 is resolved.

2021-04-26 08:16 UTC, vulder approved these changes

2021-04-26 13:25 UTC, merged