Adds a graphviz plot feature to show interactions of the specified commit only
se-passau/VaRA-Tool-Suite pull request #444
Opened 2021-02-24 09:04 UTC by cormensratio

Adds a graphviz plot feature to show interactions of the specified commit only.

2021-02-24 10:28 UTC, vulder requested changes

2021-02-24 10:28 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +def _get_verified_commit_hash(
What do you mean with "verified" we don't differentiate between verified and non verified commit hashes here (+ this is a specific github feautre). We should not confuse the terms here.

2021-02-24 10:28 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +    return _get_verified_revision(
Maybe a quick rename here would also help :D

2021-02-24 10:28 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +    show_interactions_of_commit: tp.Optional[str] = None
```suggestion
    show_only_interactions_of_commit: tp.Optional[str] = None
```
Otherwise, it's not clear from the param that we remove all interactions that don't belong to the commit.

2021-02-24 10:28 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +    show_interactions_of_commit: tp.Optional[str] = None,
same

2021-02-24 10:28 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +        show_interactions_of_commit: tp.Optional[str] = None,
same

2021-03-01 12:06 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +        ):
But does this not also skip interactions where the "only_commit" is involved as an interacting hash?

2021-03-02 20:19 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +        ):
No i don't think so, because we only skip an interaction if the "only_commit" is neither the base commit nor the interacting commit.

2021-03-05 09:42 UTC, vulder approved these changes

2021-03-05 09:45 UTC, merged