Add docs on how to use containers with slurm
se-passau/VaRA-Tool-Suite pull request #446
Opened 2021-03-02 14:36 UTC by boehmseb

2021-05-07 13:47 UTC, boehmseb commented on varats/varats/tools/driver_container.py
> +        "container run --import` inside the `benchbuild` directory"
```suggestion
        "container run --import` inside the `benchbuild` directory "
```

2021-05-07 13:50 UTC, boehmseb commented on varats/varats/tools/templates/slurm_container.sh.inc
> +#!/bin/bash
```suggestion
{% raw %}#!/bin/bash
```

2021-05-07 21:12 UTC, vulder requested changes

2021-05-07 21:12 UTC, vulder commented on docs/source/vara-ts/slurm.rst
> +      parallel_processes: '4' # TODO: find good default
```suggestion
      parallel_processes: '1'
```

2021-05-07 21:12 UTC, vulder commented on docs/source/vara-ts/slurm.rst
> +      vara:
```suggestion
      varats:
```

2021-05-07 21:12 UTC, vulder commented on varats/varats/tools/driver_container.py
> +    prompt="Where should base images be exported to?",
```suggestion
    prompt="Where should base images be exported to for storage?",
```

2021-05-07 21:12 UTC, vulder commented on varats/varats/tools/driver_container.py
> +    prompt="Where should base images be exported to?",
Maybe, we should also hint the config option here two?

2021-05-07 21:13 UTC, vulder commented on docs/source/vara-ts/slurm.rst
> +      jobs: '10' # TODO: find good default
```suggestion
      jobs: '20'
```
We have 20 cpus at kine so maybe 20?

2021-05-10 07:54 UTC, boehmseb commented on varats/varats/tools/driver_container.py
> +    prompt="Where should base images be exported to?",
Maybe only in the docs? This tool is more intended for users that are not that familiar with the config.

2021-05-10 11:57 UTC, vulder approved these changes

2021-05-10 13:32 UTC, Sinerum approved these changes
Looks good to me

2021-05-10 17:07 UTC, merged