Add SZZUnleashed research tool, experiment, and report
se-passau/VaRA-Tool-Suite pull request #447
Opened 2021-03-04 13:56 UTC by boehmseb

This PR adds SZZUnleashed as a research tool.
It also comes with an experiment to run SZZUnleashed and a SZZReport for the results.

The implementation also anticipates to add more SZZ tools in the future.

2021-03-09 19:40 UTC, vulder requested changes

2021-03-09 19:40 UTC, vulder commented on varats-core/varats/provider/bug/bug.py
> +    resolutiondate: tp.Optional[datetime] = None
I assume you found a case where we cannot get this information, or why do you use optional here? At least from my point of view, at least creation date should always be there.

2021-03-09 19:40 UTC, vulder commented on varats/varats/data/reports/szz_report.py
> +                self.__bugs[fix] = RawBug(fix, set(introducers), None)
It's probably better to move this into a factory function and pass the values to init. This makes it easier testable.

2021-03-09 19:40 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +        bug_provider = BugProvider.get_provider_for_project(self.obj)
I like this API :smile:

2021-03-09 19:40 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +                "hash": str(bug.fixing_commit.id),
Is there a specific reason why you put the hash also into the value? Theoretically, it should be enough if we have it as key to the map.

2021-03-09 19:40 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +        results_dir = Path(self.obj.source_of_primary).parent
Not sure if `results_dir` is a good name, maybe `bb_build_dir`? or run_dir?
My first thought here was the vara results dir.

2021-03-09 19:40 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +        with local.cwd(results_dir):
```suggestion
        ) / SZZUnleashed.get_jar_name()

        with local.cwd(results_dir):
```

2021-03-09 19:40 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +        bugs: tp.Dict[str, tp.Set[str]] = {}
```suggestion
            szz_result = json.load(result_json)

        bugs: tp.Dict[str, tp.Set[str]] = {}
```

2021-03-09 19:40 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +            binary_name="",
Does this work when loading reports? Not sure if our regex allows for this.

2021-03-09 19:40 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +        return [source.context(*variants[0])]
Hmm, how do you plan on running this experiment for a case study with multiple version? Or do you just want to run this manually?

2021-03-09 19:40 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +            bb.watch(java)(
Does it make sense to wrap an error handler around this?

2021-03-09 19:40 UTC, vulder commented on varats/varats/tools/research_tools/szz_unleashed.py
> +                    "https://github.com/wogscpar/SZZUnleashed.git", "origin",
Maybe we should point this to your fork?

2021-03-10 08:55 UTC, boehmseb commented on varats-core/varats/provider/bug/bug.py
> +    resolutiondate: tp.Optional[datetime] = None
This is only there if we have an issue for it. If it was identified by commit message, this information is not available.

2021-03-10 09:09 UTC, boehmseb commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +        results_dir = Path(self.obj.source_of_primary).parent
Well, the same name is used in other experiments...

2021-03-10 09:12 UTC, boehmseb commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +                "hash": str(bug.fixing_commit.id),
That's just the format the tool needs. Technically, the keys are the issue ids/names, but since we don not necessarily have an issue for each fix, I just use the commit hash of the fixing commit.

2021-03-10 09:13 UTC, boehmseb commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +            bb.watch(java)(
Could be. I mainly left it out while developing and never remembered to reconsider this.

2021-03-10 09:15 UTC, boehmseb commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +            binary_name="",
Yes, that's fine. Only "ugly" thing is that you have two consecutive `--` in the name. But since I don't have any binary name and there is no way to change the name template, I don't know what to do else.

2021-03-10 09:17 UTC, boehmseb commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +        return [source.context(*variants[0])]
It does not make sense to run this for multiple revisions, because once a bug fixing commit is there, it cannot change. So using the newest possible revision is the best choice because it gets you the most data.

2021-03-10 09:17 UTC, boehmseb commented on varats/varats/tools/research_tools/szz_unleashed.py
> +                    "https://github.com/wogscpar/SZZUnleashed.git", "origin",
Already done locally, but not pushed yet.

2021-03-10 20:30 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +        results_dir = Path(self.obj.source_of_primary).parent
Yeah, maybe we should change this. Seems like an artefact of "historical growth"

2021-03-10 20:31 UTC, vulder commented on varats/varats/experiments/szz/szz_unleashed_experiment.py
> +            binary_name="",
If it works, fine with me. An alternative could also be `none`, I used for example `all` for the compiler errors where we don't have a binary yet.

2021-03-14 22:09 UTC, SimonFedick approved these changes
Looks good! I'm beginning to understand the research tool interface a little more. One quick question regarding the changes to the bug module:

2021-03-14 22:09 UTC, SimonFedick commented on varats-core/varats/provider/bug/bug.py
> +        resolutiondate: tp.Optional[datetime] = None
That's an oversight on my side, wouldn't we also want to default `issue_id` to `None`?

2021-04-15 11:26 UTC, boehmseb commented on varats/varats/data/reports/szz_report.py
> +                self.__bugs[fix] = RawBug(fix, set(introducers), None)
In principle yes, but then we cannot create this with our DataManager, as it relies on a constructor that takes the path. Same goes for all our reports btw.

2021-05-03 13:42 UTC, vulder approved these changes

2021-05-03 13:47 UTC, merged