Add Bug Fixing Relation Plot
se-passau/VaRA-Tool-Suite pull request #448
Opened 2021-03-05 20:29 UTC by SimonFedick

Adds a chord diagram to plots that displays fixing relations between commits, i.e. which commit has fixed a bug caused by which commit.

2021-05-21 08:18 UTC, vulder requested changes
Expect for some minor comments, this looks ok :)

Please also clean up the mypy/pylint warnings.

2021-05-21 08:18 UTC, vulder commented on mypy.ini
> +
```suggestion
```
Can be remove

2021-05-21 08:18 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +def _plot_chord_diagram_for_raw_bugs(
Yeah, this function probably needs some splitting up into smaller helper functions, so we can encapsulate the functionality and give the functions a meaningful name. Plotting functions are always a bit tricky here because they invite one to put everything into one function :laughing: happens to me all the time^^

2021-05-21 08:18 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +        fix_ind = map_commit_to_id[bug_fix]
```suggestion
        fix_id = map_commit_to_id[bug_fix]
```
Looks like a typo? Did you mean `fix_id`?

2021-05-21 08:18 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +            intro_ind = map_commit_to_id[bug_introduction]
same?

2021-05-21 08:18 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +        x=curve_points[:, 0],
@boehmseb Did you look into the issue of numpy type errors? I think you mentioned something about this.

2021-05-21 08:18 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +__distance_thresholds = [
Please try to write constant names in all caps

2021-05-21 08:18 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +        for r in range(1, n):
What is `r` here? Can we find a better/clearer name?

2021-05-21 08:18 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +            raise PlotDataEmpty
```suggestion
        elif self.__szz_tool != 'szz_unleashed':
            raise PlotDataEmpty
```
Would this also work? Would make it a bit clearer when the expection is raised.

Furthermore, I'm not sure if `PlotDataEmpty` is the correct exception here, maybe we should build a custom one like: `MissingSZZTool`?
@boehmseb Do you have an opinion about the exception/exception name?

2021-05-25 06:54 UTC, boehmseb commented on varats/varats/plots/bug_fixing_relations.py
> +        x=curve_points[:, 0],
The type should be `np.ndarray`

2021-05-25 07:00 UTC, boehmseb commented on varats/varats/plots/bug_fixing_relations.py
> +            raise PlotDataEmpty
This code does make sense as it is. This section retrieves the data depending on the selected `szz_tool`. The validation as you suggest should be already handled in the driver.
The only thing missing here is to replace the `pass` with the actual method to retrieve data from an `SZZReport`.

2021-06-01 13:00 UTC, SimonFedick commented on varats/varats/plots/bug_fixing_relations.py
> +        for r in range(1, n):
I called it `i` now since it is just a loop variable that iterates over the number of control points, I'm not really sure what I should call it otherwise

2021-06-01 15:24 UTC, SimonFedick commented on varats/varats/plots/bug_fixing_relations.py
> +            raise PlotDataEmpty
This is implemented now, the `szz_tool` can either be `pydriller`, `szz_unleashed` or `szz_diff`, which creates a different plot each.

2021-06-07 08:52 UTC, vulder approved these changes

2021-06-07 08:52 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +            )
@boehmseb Does it make sense to consider an enum here? Just passing strings around looks bug introducing to me :)

2021-06-07 08:52 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +    edge_colors = ['#d4daff', '#84a9dd', '#5588c8', '#6d8acf']
Is it fix for this plot that we will only need 4 colors? Otherwise, a color map would be helpful here.

2021-06-07 08:52 UTC, vulder commented on varats/varats/plots/bug_fixing_relations.py
> +                                         tp.Optional[tp.FrozenSet[str]], str],
Could you move this into a separate type/s so it's easier to understand. I'm not sure what this type represents.

2021-06-10 12:57 UTC, boehmseb commented on varats/varats/plots/bug_fixing_relations.py
> +            )
I just introduced such an enum in #477. That does not cover the diff case however, but one could use a separate parameter for that.

2021-07-18 11:18 UTC, vulder approved these changes

2021-07-18 11:19 UTC, merged