Adds test to check if project names are well formed
se-passau/VaRA-Tool-Suite pull request #451
Opened 2021-04-13 12:12 UTC by cormensratio

Adds a test to check if the project names are well formed, e.g., they must not contain a dash character.

closes https://github.com/se-sic/VaRA/issues/721

2021-04-15 20:08 UTC, vulder commented on tests/utils/test_project_util.py
> +        cls.bb_cfg.load(cls.tmp_file.name)
@boehmseb Shouldn't we be able to do this automatically with your helper methods?

2021-04-16 07:35 UTC, boehmseb commented on tests/utils/test_project_util.py
> +        cls.bb_cfg.load(cls.tmp_file.name)
I'm not sure why the config is loaded/copied here anyway, since the tests only ever read from the config and never modify it in any way. Just read from the real thing, i.e., `bb_cfg()`.

Otherwise, this this would be a job for `replace_config()` from the `test_utils` module. If you only need a copy of the BB config and don't need to replace the actual config, there is also a function `get_bb_test_config` in that same module. @cormensratio, you can look at the other tests in this module to see how this works.

2021-04-20 11:48 UTC, cormensratio commented on tests/utils/test_project_util.py
> +        cls.bb_cfg.load(cls.tmp_file.name)
@boehmseb I don't see how `replace_config` can help me there. To use the `replace_bb_config=True` param I already need a benchbuild config, otherwise the tuple of the context manager only contains the replaced vara config. Is this intended behaviour or should I modify the `replace_config()` method (respectively `class _ReplaceConfig`) by adding a call to `bb_cfg()` if `settings._BB_CFG` is None?

As I understand I need a temp file in which I generate the benchbuild config (containing also the vara projects) and a variable of type `Configuration` to load the written benchbuild file from. Instead of the `deepcopy()` I could use `get_bb_test_config()` function but this does internally the same. So I am not sure if I got you right.

But as you already mentioned, this code part should not be in the setUp() method. I will change that when I know how to get the benchbuild config properly.

2021-04-20 12:53 UTC, boehmseb commented on tests/utils/test_project_util.py
> +        cls.bb_cfg.load(cls.tmp_file.name)
> @boehmseb I don't see how `replace_config` can help me there. To use the `replace_bb_config=True` param I already need a benchbuild config, otherwise the tuple of the context manager only contains the replaced vara config. 

That's not true. In case no BB config is given, a copy of the current one is created (see lines 69-72).
The context manager should definitely return both configs if used like this:
```python
with replace_config(replace_bb_config=True) as (vara_cfg, bb_cfg):
```
Note that you have to use tuple notation to get python to do the unpacking right.

> As I understand I need a temp file in which I generate the benchbuild config (containing also the vara projects) and a variable of type `Configuration` to load the written benchbuild file from.

You only need a temp file to store/load the config you generate with `generate_benchbuild_config(vara_config, <tmp_file>)`. Note that `vara_config` is the one returned by the context manager. Everything else is handled by `replace_config()`.

>Instead of the `deepcopy()` I could use `get_bb_test_config()` function but this does internally the same. So I am not sure if I got you right.

It still would be better to use `get_bb_test_config()` since that allows the way how the test config is created to change without your test braking. However, with the `replace_config()` context manager, this is not necessary anyway.

2021-04-21 20:02 UTC, cormensratio commented on tests/utils/test_project_util.py
> +        cls.bb_cfg.load(cls.tmp_file.name)
I have to admit that I forgot the tuple notation `(vara_cfg, bb_cfg)`, but even with the correct unpacking, `bb_cfg` is `None`. Looking at line 68 in `test_utils.py` shows `self.old_bb_config = settings._BB_CFG`. But `_BB_CFG` is per default `None` (line 176 in settings.py), only if the function `bb_cfg()` is called it gets assigned the `CFG` as `BB_CFG`. Since bb_cfg() is never called before we start with `None` as value for the `old_bb_config`, which I think you meant with the lines (69-72).
So I think we either have to call `bb_cfg()` in the test before `replace_config()` or we add a `bb_cfg()` call to `replace_config()`.

2021-04-22 08:13 UTC, boehmseb commented on tests/utils/test_project_util.py
> +        cls.bb_cfg.load(cls.tmp_file.name)
That looks like a bug. Replacing the `_BB_CFG` in line 68 with `bb_cfg()` should fix it. And if you are at it, you can also replace the `_CFG` in line 81 with `vara_cfg()`.

2021-04-23 11:20 UTC, boehmseb requested changes

2021-04-23 11:20 UTC, boehmseb commented on tests/utils/test_project_util.py
> +        loaded_project_paths: tp.List[str] = bb_cfg["plugins"]["projects"].value
At this point, the replaced config is gone again because you left the context manager. You have to match the indent of the context manager here.

2021-04-26 08:08 UTC, vulder approved these changes

2021-04-26 08:10 UTC, boehmseb approved these changes

2021-04-26 08:10 UTC, merged