Adds blame interaction graphs
se-passau/VaRA-Tool-Suite pull request #452
Opened 2021-04-16 13:24 UTC by boehmseb

This PR adds a graph abstraction for blame interaction data with different views on the blame data.
Using graphs allows us to analyze blame interactions from a graph-theoretic perspective.

2021-04-20 09:08 UTC, cormensratio commented on varats/varats/plots/blame_interaction_graph_plots.py
> +    NAME = 'cig_node_degrees'
Regarding the consistent naming of the prior ``NAME``s of the plots, shouldn't this be 'cig_node_degree_plot'? Or do you want to keep the NAME with a maximum of two underscores?

2021-04-20 09:10 UTC, cormensratio commented on varats/varats/plots/blame_interaction_graph_plots.py
> +    NAME = 'cig_node_degrees_scatter'
same as above

2021-04-20 09:18 UTC, cormensratio commented on varats/varats/tables/blame_interaction_graph_table.py
> +    NAME = "cig_metrics_table"
Shouldn't it be called ``big_metrics_table``?

2021-04-20 09:21 UTC, cormensratio approved these changes
Besides my comments regarding the naming, lgtm.

2021-05-21 08:51 UTC, vulder requested changes
Just found a few small things and 2 questions.
Otherwise, this looks fine to me.

2021-05-21 08:51 UTC, vulder commented on varats-core/varats/project/project_util.py
> +    return tp.cast(Path, Path(target_prefix()) / source.local)
Just out of curiosity, why do we need a cast here? Should operator / on a Path not always return a Path?

2021-05-21 08:51 UTC, vulder commented on varats/varats/data/reports/blame_interaction_graph.py
> +                      ) == str(commit_lookup(v).author.name)
I bet you checked this, but is `.name` not a string?

2021-05-21 08:51 UTC, vulder commented on varats/varats/data/reports/blame_interaction_graph.py
>          def node_data(b: tp.Set[CommitRepoPair]) -> AIGNodeAttrs:
What is `b` here?

2021-05-21 08:51 UTC, vulder commented on varats/varats/data/reports/blame_interaction_graph.py
> +            commit: commit_lookup(commit).author.name
Here it seems to work without the extra `str()`

2021-05-21 08:51 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +from plotly import io as pio  # type: ignore
Shouldn't this be ignored by the plotly.* ignore in the config?

2021-05-21 08:52 UTC, vulder commented
A one thing I missed, try to update to vara-dev and check how the TC coverage is :wink: 
I like that it works now :laughing:

2022-03-02 17:40 UTC, vulder commented on tests/utils/test_git_util.py
> +        try:
Why do you need a try here?

2022-03-02 17:40 UTC, vulder commented on tests/utils/test_git_util.py
> +        try:
same here

2022-03-02 17:40 UTC, vulder commented on tests/utils/test_git_util.py
> +        repo = get_local_project_git_path("brotli")
above `repo` was rename to `repo_path` because you switched the func, we should keep this consistent

2022-03-02 17:40 UTC, vulder commented on varats-core/varats/project/project_util.py
> +    return Path(source.fetch())
Fetch does return a Path tot the git? This is a strange API

2022-03-02 17:40 UTC, vulder commented on varats-core/varats/project/project_util.py
> +        repos[source_name] = get_local_project_git(project_name, source_name)
We should add a check here that the source is actually a git/gitsubmodule source and skip the others.

We'll have a lot of non git sources in the future.

2022-03-02 17:40 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +def git_checkout(
There should be a checkout method in the vara_manager.py, which uses the ProcessManager.

2022-03-02 17:40 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +        return self.__str__()
```suggestion
        return str(self)
```

2022-03-02 17:40 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +        func(commit_lookup(cr_pair))
How does this work, without knowing the corresponding repository?

2022-03-02 17:40 UTC, vulder commented on varats-core/varats/utils/git_util.py
> -    return calc_code_churn_range(repo, churn_config, commit, commit)[
Why do/can we no longer reuse range here?

2022-03-02 17:40 UTC, vulder commented on varats/varats/data/metrics.py
> +def apply_tukeys_fence(
Just checking, was there no tukeys_fence in scipy or some other lib ?

2022-03-02 17:40 UTC, vulder commented on varats/varats/paper_mgmt/case_study.py
> +def newest_processed_revision_for_case_study(
Do I understand this correctly: This function retrieves the newest revision (newest commit) that actually has results and, e.g., ignores newer revs that have no results up to now?

2022-03-02 17:40 UTC, vulder commented on varats/varats/plots/blame_interaction_graph_plots.py
> +        # TODO: make filter configurable
If we don't need this, we should remove the TODO or?
Maybe just leave a comment with a hint: # Filter could be made configurable

2022-03-03 08:42 UTC, boehmseb commented on tests/utils/test_git_util.py
> +        try:
Currently, we do not have a good way to isolate git repos in tests (using our test environment does a full clone each time).
Therefore, I need to ensure that I leave the repo in the state it was before the test. Hence the `finally` block with the checkout.

2022-03-03 08:49 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +    return Path(source.fetch())
Yes it does.

2022-03-03 08:55 UTC, boehmseb commented on varats-core/varats/utils/git_util.py
> +def git_checkout(
There is, but it is framed to only be used for branches and needs to be adapted to also be used for commits.

On a side note: `vara_manager.py` probably isn't the best module for these kind of functions anymore.

2022-03-03 09:03 UTC, boehmseb commented on varats-core/varats/utils/git_util.py
> +        func(commit_lookup(cr_pair))
It does now. All I do here is avoid unpacking the commit-repo-pair.

2022-03-03 09:28 UTC, boehmseb commented on varats-core/varats/utils/git_util.py
> -    return calc_code_churn_range(repo, churn_config, commit, commit)[
The range implementation does not work for merge commits as it displays diffs for multiple commits in that case but not the one you want. This implementation does not have that problem.
It  could be that you can merge these implementations if you find the right options but I do not know them.

2022-03-03 09:31 UTC, boehmseb commented on varats/varats/data/metrics.py
> +def apply_tukeys_fence(
Nope, just IQR calculations.

2022-03-03 09:32 UTC, boehmseb commented on varats/varats/paper_mgmt/case_study.py
> +def newest_processed_revision_for_case_study(
Exactly

2022-03-03 09:38 UTC, boehmseb commented on varats/varats/plots/blame_interaction_graph_plots.py
> +        # TODO: make filter configurable
We didn't really use this plot yet except for some early visualizations, but it will only be useful if the filter is adjustable. However, I would postpone this to when we actually need the plot because then we will have a better understanding of what filters we need, hence, the TODO.

2022-03-16 12:40 UTC, vulder approved these changes

2022-03-16 13:00 UTC, boehmseb commented on tests/table/test_blame_interaction_graph_table.py
> +\textbf{xz} &    1325 &      28 &   124 &   928 &       14.97 &    8.0 &   1 &  154 &             4.0 &   0 &  64 &            3.0 &   0 &  92 \\
```suggestion
\textbf{xz} &    1143 &      28 &   124 &   928 &       14.97 &    8.0 &   1 &  154 &             4.0 &   0 &  64 &            3.0 &   0 &  92 \\
```

2022-03-16 13:00 UTC, boehmseb commented on tests/table/test_blame_interaction_graph_table.py
> +\textbf{xz} &    1325 &      28 &     1 &     0 &         0.0 &    0.0 &   0 &   0 &             0.0 &   0 &   0 &            0.0 &   0 &   0 \\
```suggestion
\textbf{xz} &    1143 &      28 &     1 &     0 &         0.0 &    0.0 &   0 &   0 &             0.0 &   0 &   0 &            0.0 &   0 &   0 \\
```

2022-03-16 13:00 UTC, boehmseb commented on tests/table/test_blame_interaction_graph_table.py
> +\textbf{xz} &    1325 &      28 &   125 &    92 &        1.47 &    1.0 &   0 &  92 &             1.0 &   0 &   1 &            0.0 &   0 &  92 \\
```suggestion
\textbf{xz} &    1143 &      28 &   125 &    92 &        1.47 &    1.0 &   0 &  92 &             1.0 &   0 &   1 &            0.0 &   0 &  92 \\
```

2022-03-16 13:00 UTC, boehmseb commented on varats/varats/tables/blame_interaction_graph_table.py
> +                        int(project_git("rev-list", "--count", "HEAD")),
```suggestion
                        int(project_git("rev-list", "--count", revision.hash)),
```

2022-03-16 14:22 UTC, merged