Draft: Add test_suite project
se-passau/VaRA-Tool-Suite pull request #463
Opened 2021-05-13 15:12 UTC by J03D03

### Description

This PR adds the [Test-Suite](https://github.com/SVF-tools/Test-Suite) project "a micro-benchmark suite designed for validating various static analysis algorithms".

2021-05-13 16:01 UTC, vulder requested changes

2021-05-13 16:01 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +            shallow=False,
If you only need the last commit you can enable shallow here.

2021-05-13 16:01 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +                    self.LOCAL_PATHS.append(directory + '/' + filename)
I don't think you should change the class variable in this method. This would add new PATHS to the variable every time someone wants to look up which binaries are generated by this project.

2021-05-13 16:01 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +                with local.env(CC=str(clang)):
If you also have cpp files you need to also override CXX with something like this `CXX=str(clang)`

Also, if you don't use a build system, meaning you call clang you self for the compilation you don't need to set the env vars at all.

2021-05-13 16:01 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +                clang = bb.compiler.cxx(self)
Just to point this out, you are also compiling your `c` files with clang++ in this case because you don't differentiate between `bb.compiler.cxx` and `bb.compiler.cc`

2021-05-14 12:22 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +            shallow=False,
```
==== ERROR ====
Execution of a binary failed in step: * Project environment for: test_suite @ (Variant(version='ab0923aabe'),)
Unexpected exit code: 128
Command line: | /usr/bin/git clone --dissociate --recurse-submodules --reference /home/user/Git/PhASAR/VARA/vara-root/benchbuild/tmp/svf-test-suite https://github.com/SVF-tools/Test-Suite.git .
Stderr:       | Cloning into '.'...
              | fatal: reference repository '/home/user/Git/PhASAR/VARA/vara-root/benchbuild/tmp/svf-test-suite' is shallow
==== ERROR ====
```

Seems like shallow should stay disabled.

2021-05-14 12:26 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +                    self.LOCAL_PATHS.append(directory + '/' + filename)
Agree. It was moved into an `init_file_paths` function which is called on `__init__`.

2021-05-14 12:30 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +                with local.env(CC=str(clang)):
Missed that. Thank you!

Omitted the env part.

2021-05-14 12:34 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +                clang = bb.compiler.cxx(self)
Missed that. Thanks

2021-05-21 07:56 UTC, vulder requested changes

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +    DOMAIN = 'testing'
We could pick better names for the class and the project. How does one of these sound like?

- Class: SVFPointsToAnalysisBenchmark | Name: SVFPointsToBench
- Class: SVFMemoryAnalysisBenchmark | Name: SVFMemBench
- Class: ??? | Name: ???

any other ideas?

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +        self.init_file_paths()
Please move the `__init__` method to the top of the class so it's the first method (just a convention we have)

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +        source = os.getcwd() + '/tmp/' + self.source[0].local
hmm, I'm not sure where this path points to in the end. Try to use `self.source_of_primary` to access the current primaries source location (the primary source is the first one specified in `SOURCE`). Take a look at gravity.py s `compile_cmake` method as an example.

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +                    self.FILE_PATHS.append(directory + '/' + filename)
After changing to the source access function you'll get a python pathlib Path back, with this type you can simplify parts of this code here, e.g.,
```
p = Path('some/location/foo')
p / "subfolder"
```
Will automatically do the correct path extension, picking the correct platform specific separator etc.

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +                    "{source}/{file}".format(source=source, file=file),
```suggestion
                    f"{source}/{file}",
```
Try to use python f-strings, they are a very handy way to insert data into a string.
```
f"Some text {code} other text"
```
With f-strings you can just insert curly braces in the string and inside the braces write code, e.g., access variables and even write more complex statements like this:
```
f"Trying to execute {command if command else 'empty command'}, may the emperor protect us."
```

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +                    self.FILE_PATHS.append(directory + '/' + filename)
Create a `pathib.Path` here, makes it easier to work with later on.

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +    FILE_PATHS = []  # type: tp.List[str]
```suggestion
    FILE_PATHS: tp.List[Path] = []
```
easier to work with later on

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +import typing as tp
```suggestion
import typing as tp
from pathlib import Path
```

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +                if os.path.splitext(file)[1] == '.c':
```suggestion
                if file.suffix == 'c':
```
After switching to path, is becomes easier to write and more readable :smiley:

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +                                                  ''), BinaryType.executable
```suggestion
            file_name.with_suffix(''), BinaryType.executable
```

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +                    file.replace('.cpp', '').replace('.c', '')
```suggestion
                    file.with_suffix('')
```

2021-05-21 07:56 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +    Get examples from the Test-Suite micro-benchmark suite.
```suggestion
    (InsertProjectName) provides and easy way to execute the examples from the Test-Suite micro-benchmark suite for testing points to analyses.
```

2021-05-21 09:07 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +    DOMAIN = 'testing'
SVFPointsToAnalysisBenchmark sounds good to me

2021-05-21 09:08 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +    Get examples from the Test-Suite micro-benchmark suite.
The description has been updated

2021-05-21 09:10 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +        self.init_file_paths()
Sure! Done

2021-05-21 10:31 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +                    self.FILE_PATHS.append(directory + '/' + filename)
Done

2021-05-21 10:31 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +                if os.path.splitext(file)[1] == '.c':
True that :)

2021-05-26 09:07 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +        source = os.getcwd() + '/tmp/' + self.source[0].local
Hi @vulder, I have a little problem with your suggestion.
I can't use `self.source_of_primary` in the `__init__` method since it isn't set yet.
Since the `binaries` method is called before `compile` i can't call `init_file_paths` from there either :thinking:

2021-05-30 22:12 UTC, vulder commented on varats/varats/projects/test_projects/test_suite.py
> +        source = os.getcwd() + '/tmp/' + self.source[0].local
hmm, then we need to specify the paths manually or do you have other ideas?
The problem with `os.getcwd()` is it depends on the exec location/current location, which is not portable to other systems, machines or containers.
I currently see two options here:
1) find a way to safely checkout the repo before have/find the location with the repository
2) manually add the file paths to the list

2021-06-02 10:09 UTC, J03D03 commented on varats/varats/projects/test_projects/test_suite.py
> +        source = os.getcwd() + '/tmp/' + self.source[0].local
I've no better idea, that's why I picked option two and added the file paths manually with https://github.com/se-sic/VaRA-Tool-Suite/pull/463/commits/c81be36bddc593109307261c5be73d27d9052101.

2021-06-09 13:30 UTC, vulder approved these changes

2021-06-09 13:32 UTC, merged