Add PhASAR experiment
se-passau/VaRA-Tool-Suite pull request #469
Opened 2021-05-27 14:15 UTC by J03D03

### Description

This PR adds an experiment for an analysis that creates an resultPAMM.json file and some textoutput.

The following example tool takes a `.bc` or `.ll` file and creates a `PAMM.json` file and some text output.
```
#include <filesystem>
#include <iostream>

#include "phasar/DB/ProjectIRDB.h"
#include "phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h"
#include "phasar/PhasarLLVM/Pointer/LLVMPointsToSet.h"
#include "phasar/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.h"
#include "phasar/Utils/Logger.h"
#include "phasar/Utils/PAMM.h"

using namespace psr;

int main(int Argc, const char **Argv) {
  initializeLogger(false);

  // Check arguments
  if (Argc != 3 || !std::filesystem::exists(Argv[1])) {
    std::cerr << "pammtool\n"
                 "Usage: pammtool <LLVM IR file> <PAMM output file>\n";
    return 1;
  }

  PAMM &Pamm = PAMM::getInstance();
  Pamm.startTimer("timer1");
  Pamm.regHistogram("Test-Set");
  Pamm.addToHistogram("Test-Set", "1");
  Pamm.addToHistogram("Test-Set", "2");
  Pamm.addToHistogram("Test-Set", "3");
  Pamm.stopTimer("timer1");
  // Export PAMM file
  Pamm.exportMeasuredData(Argv[2]);

  // Check for a main function
  ProjectIRDB DB({Argv[1]});
  if (const auto *F = DB.getFunctionDefinition("main")) {
    std::cout << "The file contains a 'main' function!\n";
  } else {
    std::cerr << "ERROR: file does not contain a 'main' function!\n";
  }

  return 0;
}
```

Currently the binary of the dummytool/analysistool has to be copied manually to `vara-root/tools/phasar/bin/pammtool`

2021-06-16 21:24 UTC, vulder requested changes
code overall looks fine to me, have you run this on your examples?
Maybe try to run this on the `xz` project, to see hat happens?

2021-06-16 21:24 UTC, vulder commented on varats/varats/data/reports/points_to_analysis_perf_report.py
> +        file_ext: str = ".txt"
```suggestion
        file_ext: str = PointsToAnalysisPerfReport.FILE_TYPE
```

2021-06-16 21:24 UTC, vulder commented on varats/varats/experiments/phasar/points_to_analysis_experiment.py
> +    ):
```suggestion
    ) -> None:
```

2021-06-16 21:24 UTC, vulder commented on varats/varats/experiments/phasar/points_to_analysis_experiment.py
> +        tool
`tool` needs a type

2022-11-06 20:13 UTC, vulder commented
@pdschubert @fabianbs96 @MMory 
Hoi, as Jo was working on Phasar. What's the goal/state of this PR. Do you still need this or can we just close the PR?

2022-11-08 15:13 UTC, J03D03 commented on varats/varats/experiments/phasar/points_to_analysis_experiment.py
> +        tool
Type set in https://github.com/se-sic/VaRA-Tool-Suite/pull/469/commits/49d4b6afd7b38c63b54ffd69aebd8dbb3ad66b07

2022-11-08 15:28 UTC, J03D03 commented
> @pdschubert @fabianbs96 @MMory Hoi, as Jo was working on Phasar. What's the goal/state of this PR. Do you still need this or can we just close the PR?

Hi @vulder, sorry i didn't notice that this PR is still open. `state = abandoned`. I can resolve the remaining conflicts and do a short test run this weekend if you are interested in keeping the experiment. IMO we can close it otherwise.

2022-11-08 22:22 UTC, vulder commented
I probably don't need it, I just wanted to make sure we don't delete/remove stuff that @MMory or someone else needs.

2023-02-21 10:25 UTC, vulder commented
Ok, then let's close this for know.

2023-02-21 10:25 UTC, closed without merging