BB update with auto case study executer
se-passau/VaRA-Tool-Suite pull request #49
Opened 2019-04-04 14:08 UTC by vulder

Enhance the VaRA tool suite with case studie and paper configs, which can automatically be executed by benchbuild.

resolves se-passau/VaRA#388
resolves se-passau/VaRA#385

2019-04-04 14:11 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- varats/jupyterhelper/file.py  1
- varats/driver.py  1
- varats/experiments/GitBlameAnnotationReport.py  12
         

Complexity decreasing per file
==============================
+ varats/experiments/Extract.py  -1
+ varats/tools/commit_map.py  -2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-04 14:16 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/jupyterhelper/file.py  1
- varats/driver.py  1
         

Complexity decreasing per file
==============================
+ varats/experiments/Extract.py  -1
+ varats/tools/commit_map.py  -2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-04 17:19 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/jupyterhelper/file.py  1
- varats/driver.py  1
- varats/experiments/GitBlameAnnotationReport.py  12
         

Complexity decreasing per file
==============================
+ varats/tools/commit_map.py  -2
+ varats/experiments/Extract.py  -1
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-04 17:31 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/driver.py  1
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/jupyterhelper/file.py  1
         

Complexity decreasing per file
==============================
+ varats/tools/commit_map.py  -2
+ varats/experiments/Extract.py  -1
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-04 18:18 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/driver.py  1
- varats/jupyterhelper/file.py  1
         

Complexity decreasing per file
==============================
+ varats/experiments/Extract.py  -1
+ varats/tools/commit_map.py  -2
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-05 08:50 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- varats/jupyterhelper/file.py  1
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/driver.py  1
         

Complexity decreasing per file
==============================
+ varats/experiments/Extract.py  -1
+ varats/tools/commit_map.py  -2
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-05 08:58 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/jupyterhelper/file.py  1
- varats/driver.py  1
         

Complexity decreasing per file
==============================
+ varats/tools/commit_map.py  -2
+ varats/experiments/Extract.py  -1
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-09 11:06 UTC, julianbreiteneicher commented on README.md
> +In order to execute an experiment on a project we use BenchBuild an empirical-research toolkit.
Comma after BenchBuild?

2019-04-09 11:08 UTC, julianbreiteneicher commented on README.md
> +If one wants to analyze a particular set of revisions or wants to reevaluate the same revision over and over again, we can fix the analyzed revisions by creating a `CaseStudy`. First, create a folder
should be saved

2019-04-09 11:22 UTC, julianbreiteneicher commented on README.md
> +For example, we can generate a new case study for `gzip`, drawing 10 revision from the projects history based on a half-normal distribution, with:
Perhaps quickly explain the half-normal distribution. Probability for newer or older commits higher?

2019-04-09 11:24 UTC, vulder commented on README.md
> +For example, we can generate a new case study for `gzip`, drawing 10 revision from the projects history based on a half-normal distribution, with:
no, otherwise I have to explain all x other distributions and the readme get's to bloated. If one wants to understand stuff they have to read other stuff anyhow.

2019-04-09 11:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/jupyterhelper/file.py  1
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/driver.py  1
         

Complexity decreasing per file
==============================
+ varats/experiments/Extract.py  -1
+ varats/tools/commit_map.py  -2
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-09 12:47 UTC, julianbreiteneicher requested changes

2019-04-09 12:47 UTC, julianbreiteneicher commented on varats/driver.py
> +    cs_group.add_argument("--paper-path", help="Path to paper folder.")
Crash (FileNotFoundError) if the directory of the paper-path does not yet exist.

2019-04-09 12:47 UTC, julianbreiteneicher commented on varats/paper/case_study.py
> +A case studie to ping down project settings and the exact set of revisions that
pin down

2019-04-09 12:47 UTC, julianbreiteneicher commented on varats/paper/case_study.py
> +    elif sampling_method == sorted(SamplingMethod.uniform):
Crashes when using uniform distribution. Used command:
```shell
vara-gen-commitmap benchbuild/tmp/gzip-HEAD --case-study --distribution uniform --num-rev 10 --paper-path paper_configs/commit_interactions/
```

Stacktrace:
```text
Traceback (most recent call last):
  File "/home/jb/opt/virtualenvs/vara-tool-suite/bin/vara-gen-commitmap", line 11, in <module>
    load_entry_point('VaRA-Tool-Suite', 'gui_scripts', 'vara-gen-commitmap')()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/driver.py", line 272, in main_gen_commitmap
    args.version)
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/paper/case_study.py", line 160, in generate_case_study
    elif sampling_method == sorted(SamplingMethod.uniform):
TypeError: 'SamplingMethod' object is not iterable
```

2019-04-09 12:47 UTC, julianbreiteneicher commented on varats/paper/paper_config.py
> +                [x for x in self.__path.iterdir()
`folder_path` is not a dir when called from `load_paper_config()`. It is the path to the config _file_, so `iterdir()` crashes:

```text
Traceback (most recent call last):
  File "/home/jb/opt/virtualenvs/vara-tool-suite/bin/benchbuild", line 11, in <module>
    load_entry_point('benchbuild', 'console_scripts', 'benchbuild')()
  File "/home/jb/opt/virtualenvs/vara-tool-suite/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jb/opt/virtualenvs/vara-tool-suite/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/jb/opt/virtualenvs/vara-tool-suite/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/jb/opt/virtualenvs/vara-tool-suite/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jb/work/hiwi/repos/benchbuild/benchbuild/__init__.py", line 11, in <module>
    __PROJECTS__.discover()
  File "/home/jb/work/hiwi/repos/benchbuild/benchbuild/projects/__init__.py", line 23, in discover
    importlib.import_module(project_plugin)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/projects/c_projects/gzip.py", line 19, in <module>
    version_filter=project_filter_generator("gzip"))
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/paper/paper_config.py", line 106, in project_filter_generator
    str(CFG["paper_config"]["current_config"]))
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/paper/paper_config.py", line 130, in load_paper_config
    __G_PAPER_CONFIG = PaperConfig(config_path)
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/paper/paper_config.py", line 25, in __init__
    [x for x in self.__path.iterdir()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/paper/paper_config.py", line 25, in <listcomp>
    [x for x in self.__path.iterdir()
  File "/usr/lib/python3.7/pathlib.py", line 1083, in iterdir
    for name in self._accessor.listdir(self):
NotADirectoryError: [Errno 20] Not a directory: '/home/jb/work/hiwi/paper_configs/commit_interactions/gzip_0.case_study'
```

Used vara config snippet:
```text
paper_config:
    current_config:
        value: gzip_0.case_study
    folder:
        value: /home/jb/work/hiwi/paper_configs/commit_interactions
```

Used command:
```shell
benchbuild run -E GitBlameAnnotationReport gzip
```

2019-04-09 12:49 UTC, julianbreiteneicher commented on varats/driver.py
> +    parser.add_argument("--case-study", action="store_true",
When the user specifies `--case-study` as well as `--output`, we could output a warning to notify the user that `--output` is ignored.

2019-04-09 22:29 UTC, simbuerg commented on varats/paper/case_study.py
> +A case studie to ping down project settings and the exact set of revisions that
(studie -> study)

2019-04-10 12:30 UTC, vulder commented on varats/paper/case_study.py
> +    elif sampling_method == sorted(SamplingMethod.uniform):
oh boy, was i drunk? I added sorting to the result, why would I sort the enum ;D

2019-04-10 12:33 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/jupyterhelper/file.py  1
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/driver.py  1
         

Complexity decreasing per file
==============================
+ varats/tools/commit_map.py  -2
+ varats/experiments/Extract.py  -1
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-10 16:06 UTC, vulder commented on varats/paper/paper_config.py
> +                [x for x in self.__path.iterdir()
no that's correct, a paper_config should be a folder with case studies.
The folder config param is for a set of paper_configs

```
paper_config:
    current_config:
        value: commit_interactions
    folder:
        value: /home/jb/work/hiwi/paper_configs/
```

2019-04-10 16:09 UTC, vulder commented on varats/paper/paper_config.py
> +                [x for x in self.__path.iterdir()
Example:
```
paper_configs
    ├── ase-17
    │       ├── gzip_0.case_study
    │       ├── gzip_1.case_study
    │       └── git_0.case_study
    └── icse-18
            ├── gzip_0.case_study
            └── git_0.case_study
```

2019-04-10 16:11 UTC, vulder commented on varats/driver.py
> +    cs_group.add_argument("--paper-path", help="Path to paper folder.")
well I you provide a path that does not exist...
I can add an error to tell the user he should pass correct paths to the tool

2019-04-10 16:19 UTC, julianbreiteneicher commented on varats/driver.py
> +    cs_group.add_argument("--paper-path", help="Path to paper folder.")
Correct. But the application shouldn't crash. It should output a warning and exit gracefully in my opinion.

2019-04-10 16:21 UTC, julianbreiteneicher commented on varats/paper/paper_config.py
> +                [x for x in self.__path.iterdir()
Ah, ok, I see. I thought the current_config should be a single case study file. But that doesn't make much sense, of couse...

2019-04-10 16:27 UTC, vulder commented on varats/driver.py
> +    parser.add_argument("--case-study", action="store_true",
do we need this? I mean if the user looks at `--help` output is listed under commit_map params not under case_study params, so it should be clear that providing `--output` will not do anything.
Otherwise, we need to print warnings for every option that is provided in the wrong mode because providing any case_study option will not impact the commit_map result.

2019-04-10 16:37 UTC, julianbreiteneicher commented on varats/driver.py
> +    parser.add_argument("--case-study", action="store_true",
No, I don't think it's absolutely necessary. I just found it a little bit confusing.

2019-04-11 09:10 UTC, vulder commented on varats/paper/paper_config.py
> +                [x for x in self.__path.iterdir()
Added an example to the readme, this should explains this.

2019-04-11 09:10 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/jupyterhelper/file.py  1
- varats/driver.py  1
- varats/experiments/GitBlameAnnotationReport.py  12
         

Complexity decreasing per file
==============================
+ varats/tools/commit_map.py  -2
+ varats/experiments/Extract.py  -1
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-11 09:38 UTC, vulder commented on varats/driver.py
> +    parser.add_argument("--case-study", action="store_true",
kk, changed it to use sub parsers

2019-04-11 10:11 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/driver.py  1
- varats/jupyterhelper/file.py  1
         

Complexity decreasing per file
==============================
+ varats/experiments/Extract.py  -1
+ varats/tools/commit_map.py  -2
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-16 11:40 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/jupyterhelper/file.py  1
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/driver.py  1
         

Complexity decreasing per file
==============================
+ varats/tools/commit_map.py  -2
+ varats/experiments/Extract.py  -1
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-16 11:49 UTC, julianbreiteneicher commented on varats/driver.py
> +    parser.add_argument("--case-study", action="store_true",
One last small remark: I would switch the order of the PATH parameter and the {cmap,case-study} paramter. That way you can use 'vara-gen-commitmap cmap -h to get help for the cmap subcommant. Otherwise you need to specify a repository path just to get help for the cmap command.

2019-04-24 18:54 UTC, julianbreiteneicher approved these changes
Looks good now :+1:
~~Just added one small remark in driver.py, but it's not very important.~~

2019-04-25 08:19 UTC, vulder commented on varats/driver.py
> +    parser.add_argument("--case-study", action="store_true",
that's not so easy, at least for me, I found no way to do this with the argparse interface. After the first parser the sub parser runs and flags for the first parser can no longer be added. 

patches welcome^^

2019-04-25 10:58 UTC, julianbreiteneicher commented on varats/driver.py
> +    parser.add_argument("--case-study", action="store_true",
Ah, I see. I also couldn't find an easy way.

2019-04-30 11:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- varats/experiments/GitBlameAnnotationReport.py  12
- varats/jupyterhelper/file.py  1
- varats/driver.py  1
         

Complexity decreasing per file
==============================
+ varats/tools/commit_map.py  -2
+ varats/experiments/Extract.py  -1
         

Clones added
============
- tests/data/test_commit_report.py  2
         

Clones removed
==============
+ varats/experiments/GitBlameAnnotationReport.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3383148&bid=12173121)

2019-04-30 11:32 UTC, merged