Add a table showing general info about case studies
se-passau/VaRA-Tool-Suite pull request #503
Opened 2021-07-22 09:24 UTC by boehmseb

2021-07-22 22:09 UTC, vulder requested changes

2021-07-22 22:09 UTC, vulder commented on tests/table/test_case_study_metrics_table.py
> +\textbf{brotli} &  compression &  37033 &     1030 &       87 \\
Will tests not be brittle? To calculate the commits/locs/authors we clone the brotli repo and run our code (which is good) but it the brotli repo state changes, the tests afterwards will fail.

Can we pin the table calc to a specific brotli repo version?

2021-07-23 06:51 UTC, boehmseb commented on tests/table/test_case_study_metrics_table.py
> +\textbf{brotli} &  compression &  37033 &     1030 &       87 \\
You are right. I did not think about that. I will try to fix that

2021-07-23 09:02 UTC, vulder approved these changes

2021-07-23 09:02 UTC, merged