Implement vara-run command line tool
se-passau/VaRA-Tool-Suite pull request #508
Opened 2021-08-03 13:50 UTC by boehmseb

This tool allows running benchbuild experiments directly from the tool suite.
It provides the (to us) relevant functionalities of benchbuild's `run`, `slurm`, and `container` commands in a unified interface and enables a simpler handling of paper configs. For example it checks whether selected projects and versions are contained in the current paper config and if no projects are specified, it runs the experiment on all case studies in the current paper config.

resolves se-sic/VaRA#777

2021-08-03 13:52 UTC, boehmseb commented
We probably should also write a short tutorial/documentation before merging this.

2021-08-30 11:33 UTC, vulder commented on varats/varats/tools/driver_run.py
> +    help="Only run experiments for the given project."
```suggestion
    help="Only run experiments for the given project. "
```

2021-08-30 12:22 UTC, vulder requested changes
- [ ] Pass extra -vvvv flags
- [ ] Maybe provide project list as last paramters (make projects arguments instead of options)
- [ ] Stream output from BB to stdout
- [ ] Add option for auto submitting (by default no submission, with option submission)

2021-08-30 12:22 UTC, vulder commented on docs/source/tutorials/getting_started.rst
> +**Unless noted otherwise, ``vara-*`` commands should always be run from this directory.**
```suggestion
**Unless noted otherwise,** ``vara-*`` **commands should always be run from this directory.**
```

2021-08-30 19:05 UTC, vulder approved these changes
Looks good to me. Let's wait for some feedback from our other testers and then merge it :grin:

2021-08-31 08:33 UTC, Sinerum approved these changes
Looks good to me.

2021-08-31 08:51 UTC, MMory commented
The output of vara-run -vvvv is not consistent with benchbuild -vvvv - when compiling xz, vara-run does not print the output of the configure script and furthermore the coloring does not work.

2021-08-31 09:18 UTC, boehmseb commented
> The output of vara-run -vvvv is not consistent with benchbuild -vvvv - when compiling xz, vara-run does not print the output of the configure script and furthermore the coloring does not work.

As for the color, I think this is stripped because I'm using `tee` to forward the output. Not sure how I can circumvent this. The plumbum documentation doesn't say anything about that issue.
I have no idea however, why the output of configure is missing. Both, `stdout` and `stderr` should be forwarded.
I might have to ask the BenchBuild  dev what other tricks he uses there :thinking:

2021-09-01 13:15 UTC, cormensratio approved these changes
Test runs worked flawlessly. Lgtm

2021-09-01 14:16 UTC, J03D03 approved these changes
Tested the `JustCompile` experiment with the `vara-run` command line tool against several C projects.
Lgtm

2021-09-05 15:08 UTC, boehmseb commented
We have 2 smaller issues left:

se-sic/VaRA#797
se-sic/VaRA#798

2021-09-05 15:47 UTC, merged

2021-10-07 21:10 UTC, vulder commented
resolves se-sic/VaRA#779