Plot rework for the interaction-degree-multi-lib-plot
se-passau/VaRA-Tool-Suite pull request #510
Opened 2021-08-12 09:37 UTC by cormensratio

Adapts the `b_interaction_degree_multi_lib` plot to the click CLI.
Merges with the f-PlotRework branch.

2021-10-20 18:25 UTC, boehmseb requested changes

2021-10-20 18:25 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> -            'xtick_size': 10 if view_mode else 2,
Plot config options can have separate defaults for view mode. If these values here are consistent between mutliple plots, you may put these as defaults in the PlotConfig class.

2021-10-20 18:25 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +                vertical_alignment=self.plot_kwargs["vertical_alignment"]
Didn't we agree to just pass the kwargs through to the plot as-is?

2021-10-21 09:16 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> -            'xtick_size': 10 if view_mode else 2,
Some of them are indeed consistent. I'll change these defaults appropriately.

2021-10-21 09:19 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +                vertical_alignment=self.plot_kwargs["vertical_alignment"]
You are right, I only passed the `PlotConfig` as a whole and forgot the `kwargs`. This is also the case for the reworked plots of the `PlotRework` branch. Therefore I am going to open another PR to fix these too.

2021-10-25 11:56 UTC, boehmseb requested changes
Almost done ;)

2021-10-25 11:56 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +            ) for cs in self.plot_kwargs["case_study"]
I think this can be simplified:

```suggestion
            BlameInteractionDegreeMultiLib(
                self.plot_config, case_study=cs, **plot_kwargs
            ) for cs in self.plot_kwargs["case_study"]
```

2021-10-25 12:45 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +            ) for cs in self.plot_kwargs["case_study"]
Initially I tried the same, but this fails with:
`TypeError:  varats.plots.blame_interaction_degree.BlameInteractionDegreeMultiLib() got multiple values for keyword argument 'case_study'`

2021-10-25 12:48 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +            ) for cs in self.plot_kwargs["case_study"]
Then I suggest deleting the entry from the kwargs before. This makes it also more obvious that it is overridden.

2021-10-25 13:02 UTC, boehmseb approved these changes

2021-10-27 08:56 UTC, vulder approved these changes

2021-10-27 08:56 UTC, vulder commented on varats/varats/plot/plots.py
> +                    view_default=8,
Just to double check, the new default view numbers are the numbers that are common between the different plots?

2021-10-27 08:56 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +        OPTIONAL_BUG_COLOR, OPTIONAL_VERTICAL_ALIGNMENT
@boehmseb Maybe it could make sense to group some of those conceptually together? Like, `get_all_X()`, so one does not have so specify everything by hand. *not sure* if this makes it easier or less clear

2021-10-27 09:05 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +        OPTIONAL_BUG_COLOR, OPTIONAL_VERTICAL_ALIGNMENT
Hmm, the problem here is that those options occur in many different combinations. It could make sense for things like `OPTIONAL_SHOW_CVE`, `OPTIONAL_CVE_COLOR`, and `OPTIONAL_CVE_LINE_WIDTH`, but for many others I don't see that much benefit. We have to find a balance between increasing readability here, and having too many groups of options.

2021-10-27 09:36 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +        OPTIONAL_BUG_COLOR, OPTIONAL_VERTICAL_ALIGNMENT
Yes, that's group is in the direction of my idea, however, I'm still not sure about the trade offs.
@cormensratio What do you think?

2021-10-27 16:50 UTC, cormensratio commented on varats/varats/plot/plots.py
> +                    view_default=8,
Exactly. Before the plot rework, there were some plots that explicitly set a view default for these options in a `extra_plot_cfg` or `plot_cfg` `dict`. The values of these options were the same in each `dict` and therefore the origin of our `view_default` values here.

2021-10-27 17:06 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +        OPTIONAL_BUG_COLOR, OPTIONAL_VERTICAL_ALIGNMENT
I think that we currently would not really benefit from such groups, mainly because of 2 reasons:
1. These `OPTIONAL_...`s are currently specific for one or two plots. If they were more commonly used among other plots they would already be in the `PlotConfig` or `CommonPlotOptions`. Groups out of these options would therefore hardly find another application as in the few plots that already use them.
2. As @boehmseb already stated, I think that the introduction of such groups would result in too many combinations, too. As long as we do not have more plots that rely on the same set of options I think we have a better readability by sticking to the current state and pass them one by one.

2021-10-30 14:01 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +        OPTIONAL_BUG_COLOR, OPTIONAL_VERTICAL_ALIGNMENT
Ok, then we leave them out for now. Should a pattern emerge, we can always adapt things :)

2021-10-30 14:02 UTC, merged