Plot rework for the fraction-overview-plot
se-passau/VaRA-Tool-Suite pull request #514
Opened 2021-08-12 10:59 UTC by cormensratio

Adapts the `b_interaction_fraction_overview` plot to the click CLI.
Merges with the f-PlotRework branch.

2021-11-11 15:07 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +        f'{plot_config.fig_title("Fraction overview")} - Project {project_name}'
I'm not sure I like the idea that the user can only customize a part of the title. I believe the most common use case to override the title via command line is to customize figures for use in a paper or presentation. And in that case I would like to have full control over the title. I see the point that one might still like to include the project name but having both would mean to implement some kind of templating solution (which I think is overkill here).

What's your opinion on this?

2021-11-13 06:59 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +        f'{plot_config.fig_title("Fraction overview")} - Project {project_name}'
I agree. With the the new default value handler for `PlotConfig` values one could leave the title untouched and get, e.g., the project name as a default, so this information is not lost. Therefore allowing the user to modify the complete title makes sense.
As this is also the case for the title in, e.g., the `degree_plot()` I'll open another PR to fix this for plots that already got "reworked". For plots that are going to be reworked I am going apply this fix directly.

2021-11-20 08:35 UTC, vulder commented on varats/varats/plots/blame_interaction_degree.py
> +    unique_short_revisions: tp.List[ShortCommitHash],
Was this initially typed incorrectly? Or what did change that we now only have `ShortCommitHashes`?

2021-11-23 09:37 UTC, boehmseb requested changes

2021-11-23 09:37 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +    unique_short_revisions: tp.List[ShortCommitHash],
I can see that this was changed because of the change in line 1194. But I have no idea why since the commits just got completed to their long form in the line before.
@cormensratio what's the background here?

2021-11-23 10:42 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
>              )
I initially thought that it is better to work with `ShortCommitHashes` rather than `FullCommitHashes` as the dataframe already provides `ShortCommitHashes` and the final plot image only shows the `ShortCommitHashes` anyway. My main problem there was the grouping on `ShortCommitHashes` in line 1200 and the required `FullCommitHashes` in line 1206.
As I now looked over the code again I realized that it should be rather simple to work with `FullCommitHashes` up to the point where we reduce the revision hashes to their short form for better readability in the final plot image.
I`ll push my fix in one sec. .

2021-11-23 10:42 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +    unique_short_revisions: tp.List[ShortCommitHash],
See my comment below.

2021-11-23 12:09 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
>              )
Sounds good

2021-11-29 08:33 UTC, boehmseb approved these changes

2021-11-29 11:13 UTC, vulder approved these changes

2021-11-29 11:20 UTC, merged