Integrates experiment and evaluation table for the phasar globals analysis evalution
se-passau/VaRA-Tool-Suite pull request #522
Opened 2021-08-17 08:24 UTC by vulder

Integrates experiment and evaluation table for the globals paper evalution. The experiment evaluates the state with and without the new phasar globals support. It measures the execution time impact of the global analysis support as well as the impact on the generated facts for a linear constant analysis.

2021-08-29 16:14 UTC, boehmseb requested changes

2021-08-29 16:14 UTC, boehmseb commented on varats/varats/data/reports/globals_report.py
> +        # Calculate timeings
```suggestion
        # Calculate timings
```
;)

2021-08-29 16:14 UTC, boehmseb commented on varats/varats/data/reports/globals_report.py
> +class GlobalsReportWith(GlobalsReport, BaseReport):
Same as with "Without"

2021-08-29 16:14 UTC, boehmseb commented on varats/varats/data/reports/globals_report.py
> +class GlobalsReportWithout(GlobalsReport, BaseReport):
Without what? Kinda confusing class name here.

2021-08-29 16:14 UTC, boehmseb commented on varats/varats/tools/research_tools/phasar.py
> +        container_vara_dir = image_context.varats_root / "tools/phasar"
Rename to `container_phasar_dir`

2021-08-29 16:17 UTC, vulder commented on varats/varats/data/reports/globals_report.py
> +class GlobalsReportWith(GlobalsReport, BaseReport):
Well, the experiment specifically compares our analysis with/without globals support. In that context it's quite clear what they refer to.

2021-08-29 20:59 UTC, boehmseb commented on varats/varats/data/reports/globals_report.py
> +class GlobalsReportWith(GlobalsReport, BaseReport):
Sure, but Reports are used in other places than the experiment (e.g., Plots). And then, it's not immediately obvious.

2021-08-30 08:02 UTC, anonymousx721337 approved these changes

2021-08-30 10:19 UTC, boehmseb approved these changes

2021-08-30 10:19 UTC, merged