Plot rework for the verifier-no-opt-plot
se-passau/VaRA-Tool-Suite pull request #526
Opened 2021-08-17 10:53 UTC by cormensratio

Adapts the `b_verifier_report_no_opt_plot` plot to the click CLI.
Merges with the f-PlotRework branch.

2021-08-17 10:55 UTC, cormensratio commented
Currently untested due to an error in the generation of BlameVerifierNoOpt reports: 
`...benchbuild/environments/entrypoints/cli.py", line 15, in <module>
    rich.traceback.install()
AttributeError: module 'rich' has no attribute 'traceback'`

2022-01-03 10:17 UTC, vulder approved these changes
lgtm but again, pre-commit is unhappy

2022-01-03 13:23 UTC, boehmseb requested changes

2022-01-03 13:23 UTC, boehmseb commented on varats/varats/plots/blame_verifier_report_plots.py
> +    case_study: CaseStudy, opt_level: OptLevel, plot_kwargs: tp.Any
`plot_kwargs` as you use it is of type `Dict[str, Any]`. Only if you use the notation `**plot_kwargs` you only need to annotate the value type of the dict. Same goes for other locations in this file where you pass kwargs.

2022-02-28 14:34 UTC, cormensratio commented on varats/varats/plots/blame_verifier_report_plots.py
> +    case_study: CaseStudy, opt_level: OptLevel, plot_kwargs: tp.Any
Done

2022-02-28 16:50 UTC, boehmseb approved these changes

2022-02-28 16:51 UTC, boehmseb commented on varats/varats/plots/blame_verifier_report_plots.py
> +                 )  # type: ignore
Same as #527. I don't mind where you fix it. The other one will know it after merging.

2022-02-28 20:42 UTC, cormensratio commented on varats/varats/plots/blame_verifier_report_plots.py
> +                 )  # type: ignore
Fixed in https://github.com/se-sic/VaRA-Tool-Suite/pull/527

2022-03-02 18:38 UTC, merged