Plot rework for the verifier-opt-plot
se-passau/VaRA-Tool-Suite pull request #527
Opened 2021-08-17 11:02 UTC by cormensratio

Adapts the `b_verifier_report_opt_plot` plot to the click CLI.
Merges with the f-PlotRework branch.

2021-08-17 11:03 UTC, cormensratio commented
Currently untested due to an error in the generation of BlameVerifierOpt reports:
...benchbuild/environments/entrypoints/cli.py", line 15, in <module> rich.traceback.install() AttributeError: module 'rich' has no attribute 'traceback'

2022-01-03 10:14 UTC, vulder approved these changes
lgtm

2022-01-03 13:27 UTC, boehmseb requested changes

2022-01-03 13:27 UTC, boehmseb commented on varats/varats/plots/blame_verifier_report_plots.py
> +    case_study: CaseStudy, opt_level: OptLevel, plot_kwargs: tp.Any
Same kwargs typing issue as mentioned in one of the other PRs.

2022-02-28 14:53 UTC, cormensratio commented on varats/varats/plots/blame_verifier_report_plots.py
> +    case_study: CaseStudy, opt_level: OptLevel, plot_kwargs: tp.Any
Done

2022-02-28 16:47 UTC, boehmseb approved these changes
After you fix the small suggestion we can merge this

2022-02-28 16:47 UTC, boehmseb commented on varats/varats/plots/blame_verifier_report_plots.py
> +                 )  # type: ignore
```suggestion
        verifier_plot_df['revision'].unique()
```

2022-02-28 20:44 UTC, cormensratio commented on varats/varats/plots/blame_verifier_report_plots.py
> +                 )  # type: ignore
That's better ;)

2022-03-02 16:27 UTC, merged