Prepare 14 projects to work in Containers
se-passau/VaRA-Tool-Suite pull request #529
Opened 2021-08-18 07:33 UTC by Sinerum

Adds containers with the necesarry dependencies to build the latest Commit for the follwing projects:
bison, curl, htop, libjpeg_turbo, libssh, libxml2, lrzip, lz4, grep,  gzip, opus, openssl, poppler, tmux, xz,
Closes se-sic/VaRA#457,
Closes se-sic/VaRA#458

Also adds a container for gawk but something still does not work there

2021-08-18 18:48 UTC, boehmseb approved these changes
Looks good apart from the unused imports reported by pylint.

2021-08-19 07:24 UTC, vulder requested changes
Can you please fix the open linter warnings, otherwise, this looks fine to me.

2021-08-19 07:24 UTC, vulder commented on varats/varats/projects/c_projects/libssh.py
> +        with local.cwd(libssh_source):
```suggestion

        with local.cwd(libssh_source):
```

2021-08-19 12:29 UTC, vulder approved these changes
Fixes pre-commit errors

@Sinerum If you install pre-commit on your machine, these errors will be fixed automatically before creating an commit.

2021-08-19 12:29 UTC, vulder commented on varats/varats/projects/c_projects/libssh.py
> +)
```suggestion
from benchbuild.utils.revision_ranges import block_revisions, GoodBadSubgraph
```

2021-08-19 12:29 UTC, vulder commented on varats/varats/projects/c_projects/libssh.py
> +    verify_binaries
```suggestion
    verify_binaries,
```

2021-08-19 12:29 UTC, vulder commented on varats/varats/projects/c_projects/libvpx.py
> +    ).run('apt', 'install', '-y', 'yasm')
```suggestion
    CONTAINER = get_base_image(ImageBase.DEBIAN_10
                              ).run('apt', 'install', '-y', 'yasm')
```

2021-08-19 12:29 UTC, vulder commented on varats/varats/projects/cpp_projects/poppler.py
> +)
```suggestion
from benchbuild.utils.revision_ranges import block_revisions, RevisionRange
```

2021-08-19 12:49 UTC, merged