Replace revision strings with CommitHash types
se-passau/VaRA-Tool-Suite pull request #543
Opened 2021-09-01 10:26 UTC by cormensratio

Starts the replacement of revision strings with `CommitHash` types by adapting the evaluation database and the `interaction_degree_plot` as first plot. Further adaptations will be performed in the PlotRework PR (https://github.com/se-sic/VaRA-Tool-Suite/pull/453) or one of its sub-PRs.

2021-09-01 15:49 UTC, boehmseb requested changes

2021-09-01 15:49 UTC, boehmseb commented on varats-core/varats/utils/git_util.py
> +                    f"Could not find commit {c_hash.hash} in {project_name}"
Shouldn't this be converted with `str()` automatically by python?

2021-09-01 15:49 UTC, boehmseb commented on varats/varats/data/databases/evaluationdatabase.py
> +        # Cast all revisions to ShortCommitHash(es)
Technically not a cast, but a conversion

2021-09-01 15:49 UTC, boehmseb commented on varats/varats/plots/repository_churn.py
> +        lambda x: x.hash[:10]
This case is so common that `FullCommitHash` has its own property for this:

```suggestion
        lambda x: x.short_hash
```

2021-09-01 15:49 UTC, boehmseb commented on varats-core/varats/utils/git_util.py
> +    def __len__(self) -> int:
What do you need this for?
I don't really like the idea of allowing `len(commit_hash)` since the length of a commit hash is a static property based on the class and does not depend on the concrete instance.

2021-09-01 15:49 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +    unique_rev_strings: tp.List[str] = [rev.hash for rev in unique_revisions]
Maybe using `short_hash` would be more readable in a plot.

2021-09-01 15:49 UTC, boehmseb commented on varats/varats/plots/repository_churn.py
> +    #  https://github.com/se-sic/VaRA-Tool-Suite/pull/453
What exactly is the problem here and how does it relate to the plot rework?

2021-09-01 15:49 UTC, boehmseb commented on varats/varats/plots/repository_churn.py
> +    #  default. Relates to https://github.com/se-sic/VaRA-Tool-Suite/pull/453
In my opinion, this should be consistent with the length of short commit hashes and therefore not be configurable by plots.

2021-09-02 12:20 UTC, cormensratio commented on varats-core/varats/utils/git_util.py
> +                    f"Could not find commit {c_hash.hash} in {project_name}"
You are right.

2021-09-02 12:20 UTC, cormensratio commented on varats/varats/data/databases/evaluationdatabase.py
> +        # Cast all revisions to ShortCommitHash(es)
Changed it to `Convert`

2021-09-02 12:22 UTC, cormensratio commented on varats-core/varats/utils/git_util.py
> +    def __len__(self) -> int:
Some subroutine failed due to the missing `__len__`. Now I tried to build the database again and generated a plot without any issues, so i guess I can remove it again.

2021-09-02 12:23 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +    unique_rev_strings: tp.List[str] = [rev.hash for rev in unique_revisions]
Wasn't sure for the cases where the `short_hash` is not unique, but for most cases I agree. Changed it now to `short_hash`es.

2021-09-02 12:26 UTC, cormensratio commented on varats/varats/plots/repository_churn.py
> +    #  default. Relates to https://github.com/se-sic/VaRA-Tool-Suite/pull/453
Perhaps this option would bring more trouble than good. Changed it to the fixed length of a `short_hash`.

2021-09-02 12:38 UTC, cormensratio commented on varats/varats/plots/repository_churn.py
> +    #  https://github.com/se-sic/VaRA-Tool-Suite/pull/453
With the implementation as it is right now, we have all unique revision strings as x-ticks on the x-axis. When we pass the option to additionally plot the `code_churn`, the revisions are prepended with their `time_id` in the corresponding function `draw_code_churn_for_revisions()`. Now we have two versions of the x-ticks, the one with and without the `time_id`s prepended, which leads to a broken plot as we now have duplicates. 
I am a little confused right now how prior implementations did not cause the same wrong behaviour, as it seems that the corresponding code parts did not get changed, or I do not know how my implementation is involved in this.
I attach an example of such a broken plot below.
![TwoLibsOneProjectInteractionDiscreteLibsSingleProject_0_b_interaction_degree](https://user-images.githubusercontent.com/38688755/131844529-9bb4dbf5-cf81-46ba-a580-113758dcae9e.png)

2021-09-02 12:55 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +    unique_rev_strings: tp.List[str] = [rev.hash for rev in unique_revisions]
Collisions are only expected in larger projects. And for displaying in a plot, it is not that important.

2021-09-02 13:03 UTC, boehmseb commented on varats/varats/plots/repository_churn.py
> +    #  https://github.com/se-sic/VaRA-Tool-Suite/pull/453
I would blame that to changing the function `_get_unique_revisions`. I would assume that at some point, it generated the same format as the churn code. Maybe the best way to fix this is to make the code churn plotting code use the same format as the rest and then replace the axis labels with the version including the time id.

2021-09-02 13:06 UTC, cormensratio commented on varats/varats/plots/repository_churn.py
> +    #  https://github.com/se-sic/VaRA-Tool-Suite/pull/453
I'll try that, thank you.

2021-09-02 14:19 UTC, cormensratio commented on varats/varats/plots/repository_churn.py
> +    with warnings.catch_warnings():
Catches `'UserWarning: FixedFormatter should only be used together with FixedLocator'` due to a missing, but redundant `set_xticks()` call.

2021-09-06 08:52 UTC, boehmseb approved these changes

2021-09-06 09:19 UTC, boehmseb commented on varats/varats/plots/repository_churn.py
> +        lambda x: x
I think that map can safely be removed ;)

2021-09-06 10:55 UTC, cormensratio commented on varats/varats/plots/repository_churn.py
> +        lambda x: x
True ;)

2021-09-11 20:23 UTC, merged