Initial work on experiment specific report files
se-passau/VaRA-Tool-Suite pull request #549
Opened 2021-09-20 08:27 UTC by vulder

2021-09-21 08:21 UTC, boehmseb requested changes
I have not much to add from a conceptional point of view since we already discussed this in person. But I found a few smaller things, basically the usual stuff :wink:

2021-09-21 08:21 UTC, boehmseb commented on varats-core/varats/report/report.py
> +            the experiment  shorthand from a result file
```suggestion
            the experiment shorthand from a result file
```

2021-09-21 08:21 UTC, boehmseb commented on varats-core/varats/report/report.py
> +        cls.SHORTHAND = shorthand
mypy is right here. You need to add class-level declarations.

2021-09-21 08:21 UTC, boehmseb commented on varats-core/varats/experiment/experiment_util.py
> +        """Experiment shorthand."""
I guess this should work the same as with reports:

```suggestion
    @classmethod
    def shorthand(cls) -> str:
        """Experiment shorthand."""
        return cls.SHORTHAND
```

2021-09-21 09:17 UTC, vulder commented on varats-core/varats/report/report.py
> +        cls.SHORTHAND = shorthand
I know, I'm still trying to fix out all the bugs before I fix type decls

2021-09-21 10:37 UTC, cormensratio requested changes
Besides my comments and mypys' the `get_file_name()` function in the experiments misses the new `experiment_shorthand` parameter. 
From a conceptional point of view this should allow us to identify reports specific to their experiments, but some test runs may not hurt.

2021-09-21 10:37 UTC, cormensratio commented on tests/data/test_diff_correlation_overview_table.py
> +            #print(table)
Remove debug prints if not needed anymore.

2021-09-21 10:37 UTC, cormensratio commented on varats-core/varats/report/report.py
> +        raise ValueError(f'File {self.filename} name was wrongly formated.')
```suggestion
        raise ValueError(f'File {self.filename} name was wrongly formatted.')
```

2021-09-21 10:37 UTC, cormensratio commented on varats-core/varats/report/report.py
> +        #  Add the missing '.' if none was given by the report
```suggestion
        # Add the missing '.' if none was given by the report
```

2021-09-21 10:37 UTC, cormensratio commented on varats-core/varats/report/report.py
>          return ReportFilename.__RESULT_FILE_TEMPLATE.format(
Returns a `str` and not the required `'ReportFilename'`.
Use:
```
ReportFilename.get_file_name(
...
```

2021-09-21 10:37 UTC, cormensratio commented on varats/varats/data/reports/blame_report.py
>          return cls.SHORTHAND
`SHORTHAND` got replaced by `shorthand()`
```suggestion
        return cls.shorthand()
```

2021-09-21 10:37 UTC, cormensratio commented on varats-core/varats/report/gnu_time_report.py
> +class TimeReport(BaseReport, shorthand="TR", file_type=""):
Should the `file_type` be an empty string?

2021-09-21 17:27 UTC, vulder commented on varats-core/varats/report/gnu_time_report.py
> +class TimeReport(BaseReport, shorthand="TR", file_type=""):
yes

2021-09-22 13:28 UTC, boehmseb approved these changes
lgtm

2021-09-22 13:28 UTC, boehmseb commented on tests/data/test_report.py
> +        """Tests if the different accessor functions work."""
"work" might be a bit misleading if `ValueError`s are expected :wink:

2021-09-23 07:22 UTC, cormensratio approved these changes
Looks good 👍🏽.

2021-09-23 11:29 UTC, merged