Cleans up result folder handling
se-passau/VaRA-Tool-Suite pull request #551
Opened 2021-09-22 13:44 UTC by vulder

2021-09-24 06:27 UTC, boehmseb requested changes

2021-09-24 06:27 UTC, boehmseb commented on varats-core/varats/experiment/experiment_util.py
> +def get_vara_result_folder(project: Project) -> Path:
A test for this function would be nice. This should be easy enough to do.

2021-09-24 06:27 UTC, boehmseb commented on varats-core/varats/experiment/experiment_util.py
> +def get_vara_result_folder(project: Project) -> Path:
This is maybe a bit picky, but is it good to include `vara` in the function name? Other tools/experiments also put their results there.

2021-09-24 08:42 UTC, cormensratio approved these changes
Lgtm

2021-09-29 10:39 UTC, vulder commented on varats-core/varats/experiment/experiment_util.py
> +def get_vara_result_folder(project: Project) -> Path:
done

2021-09-29 10:40 UTC, vulder commented on varats-core/varats/experiment/experiment_util.py
> +def get_vara_result_folder(project: Project) -> Path:
varats is probably better, that's what I aimed for anyhow

2021-09-29 11:06 UTC, boehmseb approved these changes

2021-09-29 11:12 UTC, merged