Port vara-cs to use click
se-passau/VaRA-Tool-Suite pull request #557
Opened 2021-10-12 13:06 UTC by Sinerum

Basic  port of the functionality of vara-cs to use the click package. For now ext functionality is removed, will be added again in the acctual rework.

resolves se-sic/VaRA#793

related se-sic/VaRA-Tool-Suite#561
related se-sic/VaRA-Tool-Suite#563
related se-sic/VaRA-Tool-Suite#562

2021-10-13 20:48 UTC, boehmseb requested changes
Some commands and arguments have lost their documentation or help strings. Please (re-) add them. Other than that, I found only some small things.

2021-10-13 20:48 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +    initialize_plots()  # needed for vara-cs ext smooth_plot
If this is only needed for ext, then I suggest moving it to the subcommand.

2021-10-13 20:48 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +@click.argument("report_names", type=_create_report_type_choice(), nargs=-1)
Consider moving directly below `@main.command` to be consistent with the other subcommands.

2021-10-18 10:27 UTC, vulder commented
@Sinerum Regarding the integration tests. If it helps, try to replace integration tests with unittests. With the click unittesting setup, handling these cases there is much easier.

@boehmseb What do you think, how close are we to replace all of them? Especially, because some in the chain depend on the previous steps, which makes removing them a bit more difficult.

2021-10-18 10:29 UTC, vulder requested changes
Overall the port looks good, we just need to fix the interface comparability issues, which fail the integration tests.

2021-10-18 10:50 UTC, boehmseb commented
> @Sinerum Regarding the integration tests. If it helps, try to replace integration tests with unittests. With the click unittesting setup, handling these cases there is much easier.
> 
> @boehmseb What do you think, how close are we to replace all of them? Especially, because some in the chain depend on the previous steps, which makes removing them a bit more difficult.

All tests where the CLI is ported to click should be ready to be ported. You can always prepare the environment in the test to your likings, so dependencies between tests should not be necessary anymore. However, until all tests are replaced, it might be necessary to preserve some of them in the old script so that tests that are not yet replaced continue to work.

The failing `gen` test is one of those that needs to be preserved for following tests to work properly. However, it should still be possible to write an equivalent test with unittest.

2021-11-02 15:52 UTC, boehmseb requested changes
The report type choice is now also available from the new `click_param_types` module. Otherwise, looks good.

2021-11-02 15:52 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +    return TypedChoice(BaseReport.REPORT_TYPES)
This should now be available from the `click_param_types` module.

2021-12-03 10:52 UTC, closed without merging