Remove passing of explicit generator plot_kwargs
se-passau/VaRA-Tool-Suite pull request #558
Opened 2021-10-21 11:01 UTC by cormensratio

Removes the explicit pass of `plot_kwargs` to plots within their corresponding generator, but passes all `plot_kwargs` instead.
Affected plots/generators: `interaction-degree-plot`, `sankey-plot-rev`, `sankey-plot-cs`, `graphviz-plot-rev`, `graphviz-plot-cs`, `cs-overview-plot`, `pc-overview-plot`

2021-11-02 15:43 UTC, boehmseb requested changes

2021-11-02 15:43 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +        )
Why use `update()` here and not simply `self.plot_kwargs[revision] = cmap.convert_to_full_or_warn(...)`?

2021-11-02 16:02 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +        )
Does it make a difference semantically or is `update()` just not as readable?

2021-11-03 08:39 UTC, boehmseb commented on varats/varats/plots/blame_interaction_degree.py
> +        )
I'd say that `update()` is less readable. It is usually used to update multiple values at once. But here, you only set a single value.

2021-11-03 14:36 UTC, cormensratio commented on varats/varats/plots/blame_interaction_degree.py
> +        )
Thanks for the clarification, I'll update it accordingly.

2021-11-04 09:19 UTC, boehmseb approved these changes

2021-11-20 08:51 UTC, vulder approved these changes

2021-11-20 09:19 UTC, merged