Updates CLion setup docs
se-passau/VaRA-Tool-Suite pull request #560
Opened 2021-10-21 13:55 UTC by boehmseb

2021-11-02 09:07 UTC, vulder requested changes

2021-11-02 09:07 UTC, vulder commented on docs/source/research_tool_docs/vara/add_setup_infos/clion_setup.rst
> +           -DBUILD_SHARED_LIBS=ON
Do you think it makes sense/is needed to list all options here? Does it not work otherwise with Clion?

2021-11-02 09:07 UTC, vulder commented on docs/source/research_tool_docs/vara/add_setup_infos/clion_setup.rst
> +           -DLLVM_TARGETS_TO_BUILD=X86
It was not the case before, but could you please sort them, makes reading a long list easier :laughing:

2021-11-02 09:07 UTC, vulder commented on docs/source/research_tool_docs/vara/add_setup_infos/clion_setup.rst
> +         - ``CXXFLAGS=-O2 -g -fno-omit-frame-pointer``
You don't have to pass a `env` vars if you just add the value directly to the cmake variable `CMAKE_C_FLAGS` etc. For the setup script it was just easier to aggregate and pass them in this way.

2021-11-02 09:07 UTC, vulder commented on docs/source/research_tool_docs/vara/add_setup_infos/clion_setup.rst
> +      - **Build type:** Debug
Should we call this Debug here? From the setup script there is `Debug` vs `Dev`, from the CFLAGS that I see below this looks more like an `Dev` build. They are quite similar, the big difference is `-O0` vs `-O2`.
From a naming point of view, we should keep things consistent, however, I don't like duplicating the rest. Maybe we write Name: Debug/Dev
And below when setting the cmake variable with the CFLAGS we say something like this: For Debug pass `-O0` and for Dev pass `-O2`

2021-11-02 09:52 UTC, boehmseb commented on docs/source/research_tool_docs/vara/add_setup_infos/clion_setup.rst
> +           -DBUILD_SHARED_LIBS=ON
I just listed all options that would also get set when using `vd` to set up a debug build.

2021-11-02 09:53 UTC, boehmseb commented on docs/source/research_tool_docs/vara/add_setup_infos/clion_setup.rst
> +           -DLLVM_TARGETS_TO_BUILD=X86
I tried to group the variables the same way they are grouped in your build config scripts.

2021-11-02 09:55 UTC, boehmseb commented on docs/source/research_tool_docs/vara/add_setup_infos/clion_setup.rst
> +      - **Build type:** Debug
Yes, that's the dev build. I can include both here.

2021-11-02 09:58 UTC, boehmseb commented on docs/source/research_tool_docs/vara/add_setup_infos/clion_setup.rst
> +         - ``CXXFLAGS=-O2 -g -fno-omit-frame-pointer``
Both things are equally easy to configure in CLion. As I said, I tried to stay close to the way how the build config scripts configure things. I figured, that way it is easier to stay in sync (and for you to find problems, e.g., when students use CLion)

2021-11-29 22:18 UTC, vulder approved these changes

2021-11-29 22:25 UTC, merged