Port vara-pc and its tests to click
se-passau/VaRA-Tool-Suite pull request #561
Opened 2021-10-27 13:11 UTC by Sinerum

2021-11-02 10:26 UTC, vulder commented
From a quick peak into the failing test. Keep in mind that the currently selected paper config is marked with an `*`

2021-11-02 15:48 UTC, boehmseb requested changes
You forgot to remove an old mock in a test. Otherwise looks good.

2021-11-02 15:48 UTC, boehmseb commented on tests/tools/test_driver_paper_config.py
> -        output = stdout.getvalue()
You can remove the stdout mock now.

2021-11-29 12:07 UTC, vulder approved these changes

2021-11-29 12:14 UTC, boehmseb approved these changes

2021-11-29 12:18 UTC, merged