port gen-bbconfig to click and create a unit tests for the command
se-passau/VaRA-Tool-Suite pull request #563
Opened 2021-11-03 10:07 UTC by Sinerum

2021-11-04 10:21 UTC, boehmseb commented on tests/tools/test_driver_gen_benchbuild_config.py
> +        )
Have you checked that the file is not present in the beginning? If i remember correctly, the `@run_in_test_environment()` does create fresh configs.

2021-11-04 11:49 UTC, boehmseb requested changes

2021-11-04 11:49 UTC, boehmseb commented on tests/tools/test_driver_gen_benchbuild_config.py
> +        )
Prefer using `pathlib` over `os`. You can simply use [`Path.unlink()`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.unlink) to remove a file.

2021-11-20 09:23 UTC, vulder approved these changes
lgtm

Is there an issue for this PR?

2021-11-23 09:43 UTC, boehmseb commented
> lgtm
> 
> Is there an issue for this PR?

No, only for the vara-cs stuff.

2021-11-23 09:43 UTC, boehmseb approved these changes

2021-11-29 11:11 UTC, merged