Port vara-cs to use click
se-passau/VaRA-Tool-Suite pull request #569
Opened 2021-12-03 10:55 UTC by Sinerum

Basic  port of the functionality of vara-cs to use the click package. For now ext functionality is removed, will be added again in the acctual rework.

resolves se-sic/VaRA#793

related se-sic/VaRA-Tool-Suite#561
related se-sic/VaRA-Tool-Suite#563
related se-sic/VaRA-Tool-Suite#562

Renamed branch for PR History view related se-sic/VaRA-Tool-Suite#557

2022-01-11 08:17 UTC, boehmseb requested changes

2022-01-11 08:17 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +)
Remove this option.

2022-01-11 08:17 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +@click.argument("commit-hash", required=False)
Not sure, but maybe mandatory options would be easier to understand for the user since the option name gives additional context.

2022-01-11 08:17 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +        max_num_hashes = 42
42 might be a bit much to display.

2022-01-11 09:43 UTC, Sinerum commented on varats/varats/tools/driver_casestudy.py
> +        max_num_hashes = 42
What would be an appropriate amount.

2022-01-11 09:46 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +        max_num_hashes = 42
I'm not sure. I would say 20 at most. Maybe 10 is already enough. @vulder what do you think?

2022-01-11 14:38 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +        max_num_hashes = 42
When we added this, nobody knew what we should pick, so I picked `42`.
In the end, I don't really care, 10 seems a bit short 20 could be ok.

2022-01-17 08:12 UTC, vulder approved these changes

2022-01-17 08:12 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +@click.argument("paper_config_path", type=click.Path(exists=True))
We wanted to remove this one, or am I wrong?
@boehmseb

2022-01-17 08:12 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +    "-er",
Does this work? I'm used to only have 1 char, for single `-` flags

2022-01-17 08:15 UTC, vulder commented
@Sinerum From what I see, the `rm` stuff was never really tested. If you have a bit of time, adding 1-2 simple tests for the commands would be good I guess.

https://app.codecov.io/gh/se-sic/VaRA-Tool-Suite/compare/569/tree/varats/varats/tools/driver_casestudy.py

2022-01-17 08:58 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +@click.argument("paper_config_path", type=click.Path(exists=True))
We wanted to have it removed in the other PR. This here is just the port to click and gets immediately overridden by merging the other PR.

2022-01-17 08:58 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +    "-er",
Click allows this.

2022-01-17 14:13 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +@click.argument("paper_config_path", type=click.Path(exists=True))
ok

2022-01-18 13:35 UTC, boehmseb approved these changes

2022-01-18 13:38 UTC, merged