Refactor the vara-cs gen/ext interface
se-passau/VaRA-Tool-Suite pull request #582
Opened 2022-01-06 13:56 UTC by Sinerum

Refactors the vara-cs gen/ext interface to make better use of click and allow for a more intuitive use 

new sturcure is:

`vara-cs gen [general Options] select_[strategy] [strategy Options] [further Strategies]`

additionaly a new latest startegy was add to easily generate to latest revision of a project

2022-01-06 16:31 UTC, boehmseb requested changes
Quite a lot going on here :smiley: 

I would take the chance to clean up some of the CLI and remove obsoloete options.

There is also one major and a few minor aspects that we should discuss in our next meeting.

2022-01-06 16:31 UTC, boehmseb commented on tests/tools/test_driver_casestudy.py
> +class TestDriverContainer(unittest.TestCase):
Copy-Paste error?

2022-01-06 16:31 UTC, boehmseb commented on varats/varats/paper_mgmt/case_study.py
> +    **kwargs: tp.Any
rename to `plot_kwargs`

2022-01-06 16:31 UTC, boehmseb commented on varats/varats/paper_mgmt/case_study.py
> +    plot = plot_type(None, **kwargs)
Passing `None` here is dangerous because it requires all plots to not access the plot config in the interpolation function.

Also this wouldn't type-check because the config object is not optional even if the type checker wouldn't fail here for a different reason. Suppress the warning for now and reference the issue se-sic/VaRA#830.

As for the config object, we can either pass in the default config (which should suffice in my opinion) or we need to extract this from the CLI arguments (which would require to add all those params to the `vara-cs gen` CLI).

2022-01-06 16:31 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +)
Didn't even know we had this option before. Do we want to keep this? It would require some additional checks whether the paper config is valid (or an appropriate click-choice type)

2022-01-06 16:31 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +def __casestudy_gen(
We should clean up some options here:

I would kick out the paper config path for good. It comes from a time where we had no `vara-pc` and is now bound to only cause issues. At the very least restrict it to existing paper config names via an appropriate type but I would prefer to only work on the paper config specified in the varats config file.

Next, the git path should go. I would only allow to specify projects.

Then, `ext` should not specify a path, but a case study name + an optional version (which defaults to 0). Again restrict via types to existing case studies of the current paper config.

@vulder do you agree?

2022-01-06 16:31 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +)
@vulder do we really still need this option? I would prefer to use what the varats config says.

2022-01-06 16:31 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +@click.argument("plot_type", type=create_plot_type_choice())
I fear this is not as simple as you think. The plots need their plot-specific arguments to work, even for the extend case. Otherwise, most of them don't even know what data to use. We actually need to mimic the functionality of the `vara-plot` tool here, but instead of generating the plot, we need to call the `calc_missing_revisions` function. I guess we best talk about this in our next meeting.

2022-01-06 16:31 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +@click.argument("report_type", type=create_report_type_choice())
Can we restrict this to only reports from SZZ tools?

2022-01-06 16:31 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +                "Please select a hash:",
```suggestion
                "Please select a commit hash:",
```

2022-01-09 10:47 UTC, Sinerum commented on tests/tools/test_driver_casestudy.py
> +class TestDriverContainer(unittest.TestCase):
yeah same as on the other branch as this comes from the parrent this has already been fixed on that branch

2022-01-09 10:50 UTC, Sinerum commented on varats/varats/paper_mgmt/case_study.py
> +    plot = plot_type(None, **kwargs)
I agree passing `None` is a bad Idea. But it was an easy way to make it work and i wasn't able to find a default Config probably should have added a todo.

2022-01-09 10:51 UTC, Sinerum commented on varats/varats/tools/driver_casestudy.py
> +)
When using `gen` a paper config path had to be given this is basically that but smarter, as it chooses the current config by default.

2022-01-17 08:30 UTC, vulder requested changes

2022-01-17 08:30 UTC, vulder commented on varats/varats/paper_mgmt/case_study.py
> +    case_study: CaseStudy, cmap: CommitMap, boundary_gradient_int: int,
```suggestion
    case_study: CaseStudy, cmap: CommitMap, boundary_gradient: int,
```

2022-01-17 08:30 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +    extend_with_extra_revs,
What's your reasoning to pull all of them directly into the driver? I initially provided the two dispatching functions in the case_study module, so they are colocated with the case study code, group togetter and we don't have to adapt the driver every time we add a new extension method.

Is it because you need to create a CLI function for every strat?

2022-01-17 08:30 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +@__casestudy_gen.command("select_simple")
Would `select_revs` or `select_specific` not be a more fitting name?

2022-01-17 08:31 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +def __casestudy_gen(
Yes, gen actually does also not have so specify the path, as we can just require from the user to create a paper config beforehand

2022-01-17 08:32 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +)
Yes, this one should not really be needed anymore

2022-01-17 08:34 UTC, Sinerum commented on varats/varats/tools/driver_casestudy.py
> +    extend_with_extra_revs,
Exactly because the split into strategies is now done by the CLI it seemd unecessary to keep the strategy enum and switch over that instead of calling the right function directly.

2022-01-18 11:51 UTC, vulder approved these changes

2022-01-18 13:38 UTC, boehmseb approved these changes

2022-01-18 13:54 UTC, merged