Pull project repository before generating CaseStudy
se-passau/VaRA-Tool-Suite pull request #604
Opened 2022-02-23 11:30 UTC by Sinerum

`vara-cs gen` now pulls before generating a case study, can be disabled with a `--no-update` flag.
Fixes se-sic/VaRA#847

2022-02-23 14:25 UTC, boehmseb requested changes

2022-02-23 14:25 UTC, boehmseb commented on varats-core/varats/utils/git_util.py
> +        git('pull')
Wouldn't it be cleaner to call `fetch` on the project's primary source?

2022-02-28 09:35 UTC, vulder requested changes

2022-02-28 09:35 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +        git('pull')
Depends, I think select_latest picks from master (or the current branch?)
but, anyhow we probably need to update the branch with pull and not only fetch it

2022-02-28 09:35 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +        git('pull')
I think, we should use the `pull_current_branch` implemented for the vara manager to not double the impl here.
The `pull_current_branch` does also work well when working with multiple repos in parallel

2022-02-28 09:35 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +)
a) which default do we want? update or no update?
b) we should invert the flag and set it by default to false, makes the code easier to understand

2022-03-01 10:35 UTC, Sinerum commented on varats-core/varats/utils/git_util.py
> +        git('pull')
It uses the current branch.

2022-03-02 16:19 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +        git('pull')
I thought so. This means pull is better than just fetch.

2022-03-21 12:07 UTC, vulder approved these changes

2022-03-21 12:21 UTC, boehmseb approved these changes

2022-03-21 12:34 UTC, merged