FeatureModelProvider to FTA experiment
se-passau/VaRA-Tool-Suite pull request #610
Opened 2022-03-03 18:00 UTC by Keller-1998

Added FeatureModelProvider to phasar_fta experiment

2022-03-04 09:05 UTC, vulder requested changes
You should also merge the changes from vara-dev into this branch, as there are a few that should make your life a bit easier.

2022-03-04 09:05 UTC, vulder commented on varats/varats/experiments/vara/phasar_fta.py
> +        report_type: tp.Type[BaseReport],
It's easier to just hand the experiment handle to the Step, this let's you access a lot of the experiment infos.

2022-03-04 09:05 UTC, vulder commented on varats/varats/experiments/vara/phasar_fta.py
> +        mkdir("-p", vara_result_folder)
There is an easier helper function for this, use `get_varats_result_folder` from `experiment_util`

2022-03-04 09:05 UTC, vulder commented on varats/varats/experiments/vara/phasar_fta.py
> +            result_file = self.__report_type.get_file_name(
There was a slight change here, that makes creating these file names a bit easier/different.
+ You should not need an error filename anymore

See blame_report_experiment.py as an example

2022-03-04 09:05 UTC, vulder commented on varats/varats/experiments/vara/phasar_fta.py
> +    REPORT_TYPE = EMPTY
Let's talk about adding a specific report here.

2022-06-20 14:49 UTC, vulder requested changes

2022-06-20 14:49 UTC, vulder commented on varats/varats/data/reports/feature_analysis_report.py
> +                    if tainted_inst.is_br_switch():
Maybe we could just call `is_br_switch` is_terminator` as we are, in general, interested in terminator instructions.

2022-06-20 14:49 UTC, vulder commented on varats/varats/data/reports/feature_analysis_report.py
> +        features: tp.List[str] = None
The type needs to be `tp.Optional[tp.List[str]]` to be `None`

2022-06-20 17:35 UTC, Keller-1998 commented on varats/varats/data/reports/feature_analysis_report.py
> +                    if tainted_inst.is_br_switch():
I've called it that way because it only checks for br and switch instructions as these have the crucial influence on feature-related control-flow decisions. Other terminator instructions are not considered. But yeah, probably `is_terminator` looks a bit prettier.

2022-06-21 07:42 UTC, vulder commented on varats/varats/data/reports/feature_analysis_report.py
> +                    if tainted_inst.is_br_switch():
The checking behavior is ok for now, as currently only the two are relevant for us, I just wanted a more general name.

2022-06-23 06:59 UTC, vulder commented on varats/varats/data/reports/feature_analysis_report.py
>          self.__initialize_eval_data(features)
Now, you moved the type missmatch to here :wink:
You have two choices now:
a) propagate the optional type further down the call chain
b) check if `features` is `None`, and if so, pass a new empty list to `__initialize_eval_data`

2022-06-24 08:23 UTC, vulder approved these changes

2022-06-30 14:32 UTC, vulder commented on varats/varats/tables/feature_analysis_eval.py
> +            ShortCommitHash(str(cs_revisions[0]))
This should no longer be necessary with this patch https://github.com/se-sic/VaRA-Tool-Suite/pull/656

Could you please try if it works without the manual ShortCommitHash conversion :)

2022-07-01 10:22 UTC, Keller-1998 commented on varats/varats/tables/feature_analysis_eval.py
> +            ShortCommitHash(str(cs_revisions[0]))
Works!

2022-07-01 11:46 UTC, merged