Rework table architecture
se-passau/VaRA-Tool-Suite pull request #618
Opened 2022-03-17 23:19 UTC by cormensratio

This PR reworks how tables can be generated with the tool suite. 
The rework allows the generation of tables mostly identical to the generation of plots (https://github.com/se-sic/VaRA-Tool-Suite/pull/453), namely with the `click` CLI.

2022-04-19 12:41 UTC, vulder requested changes
The PR was quite large, but actually not that difficult to understand :laughing: Knowing the plot impl the table one is actually quite straight forward

2022-04-19 12:41 UTC, vulder commented on tests/TEST_INPUTS/paper_configs/test_artefacts_driver/artefacts.yaml
> +  dry_run: false
Why is the `dry_run` flag saved here?

2022-04-19 12:41 UTC, vulder commented on tests/table/test_blame_interaction_graph_table.py
> +            case_study=get_loaded_paper_config().get_all_case_studies()
This seems like a small miss match. `case_study = list_of_case_studies`

2022-04-19 12:41 UTC, vulder commented on tests/table/test_case_study_metrics_table.py
> +        ).tabulate(TableFormat.LATEX_BOOKTABS, False)
Doesn't this make the test brittle? We pinned the brotli version for the table, so the stats would stay the same. In the new setup, I don't see how the results are stable now.

2022-04-19 12:41 UTC, vulder commented on tests/table/test_case_study_metrics_table.py
> +        ).tabulate(TableFormat.LATEX_BOOKTABS, False)
same here

2022-04-19 12:41 UTC, vulder commented on varats/varats/table/table.py
> +    def __init_subclass__(
Is this a pylint confusion or what am I missing here?

2022-04-19 12:41 UTC, vulder commented on varats/varats/table/table.py
> +    def get_class_for_table_type(table_type: str) -> tp.Type['Table']:
I always find these types strangely looking, maybe it would be good idea to introduce a type alias `TableTy = tp.Type['Table']` or something like this?

2022-04-19 12:41 UTC, vulder commented on varats/varats/table/tables.py
> +    def __init_subclass__(
same here

2022-04-19 12:41 UTC, vulder commented on varats/varats/tools/driver_plot.py
> +    initialize_plots()
Why does driver_plot need tables to be loaded?

2022-04-25 11:09 UTC, boehmseb commented on tests/TEST_INPUTS/paper_configs/test_artefacts_driver/artefacts.yaml
> +  dry_run: false
You could also argue for other options such as `view` whether they need to be stored. So we simply persist all options in the artefact file. Excluding them would require to distinguish yet another type of options, e.g., by filtering a hard-coded list of unwanted options. On a positive note, this way an artefact will not change when a default value changes.

2022-04-25 11:14 UTC, boehmseb commented on tests/table/test_blame_interaction_graph_table.py
> +            case_study=get_loaded_paper_config().get_all_case_studies()
This misnomer stems from the CLI option name, which is named `--case-study`. Thanks to code reuse, this is used in many plots and tables and would need to be replaced everywhere; doable, but laborious.

2022-04-25 11:19 UTC, boehmseb commented on tests/table/test_case_study_metrics_table.py
> +        ).tabulate(TableFormat.LATEX_BOOKTABS, False)
The table uses the newest revision from the case study, hence it is stable (that's also why the expected result changed below).

2022-04-25 11:26 UTC, boehmseb commented on varats/varats/table/table.py
> +    def __init_subclass__(
Apparently, pylint does not understand this correctly. We don't suppress this warning anywhere else, so I didn't bother here either.

2022-04-25 11:27 UTC, boehmseb commented on varats/varats/table/table.py
> +    def get_class_for_table_type(table_type: str) -> tp.Type['Table']:
I agree in principle, but since it has only this one usage, I think that giving it its own alias is a bit overkill.

2022-04-25 11:36 UTC, boehmseb commented on varats/varats/tools/driver_plot.py
> +    initialize_plots()
TL;DR: We always need to initialize plots and tables when we access the paper config because of artefacts.

Somewhere during construction of the CLI, the paper config is loaded so a plot can ask you to provide a valid case study as a parameter. When the paper config is loaded, it also loads the artefact file. The internal representation of an artefact stores which plot or table it can generate (and also sanity-checks the type's existance during loading). And since an artefact file can store plots _and_ tables we need to initialize both registries.

2022-04-26 12:04 UTC, vulder commented on tests/TEST_INPUTS/paper_configs/test_artefacts_driver/artefacts.yaml
> +  dry_run: false
kk

2022-04-26 12:05 UTC, vulder commented on tests/table/test_blame_interaction_graph_table.py
> +            case_study=get_loaded_paper_config().get_all_case_studies()
Yeah, seems currently not worth it :rofl: Maybe a clean up task for a rainy day

2022-04-26 12:07 UTC, vulder commented on tests/table/test_case_study_metrics_table.py
> +        ).tabulate(TableFormat.LATEX_BOOKTABS, False)
I see, hmm. So from an functionality perspective, the table no longer is customization and only defaults to the current case study version. I guess that's ok, I did not understand the initial change like that.

2022-04-26 12:09 UTC, vulder commented on varats/varats/table/table.py
> +    def __init_subclass__(
Hmm, I never saw this error before, is it new?
The more important question: Is pylint correct here? I would assume not... what do you think?

2022-04-26 12:11 UTC, vulder commented on varats/varats/table/table.py
> +    def get_class_for_table_type(table_type: str) -> tp.Type['Table']:
Do you expect that other code will need this type?
If such cases are to be expected, providing a type def would make it easier and more consistent later on.

2022-04-26 12:12 UTC, vulder commented on varats/varats/tools/driver_plot.py
> +    initialize_plots()
Oh :laughing: 
If this is the case, we probably should do one of the following:
a) Remove the loop (hard)
b) provide an aggregated initializer function so the CLI only needs to call one and new usages don't fall into this tar pit^^

2022-04-26 12:36 UTC, boehmseb commented on varats/varats/table/table.py
> +    def __init_subclass__(
Pylint is incorrect here. What we do here is perfectly fine as you can see in the [official python docs](https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__). Mypy also flagged this at some point, but they have fixed this already.

2022-04-26 12:41 UTC, boehmseb commented on varats/varats/table/table.py
> +    def get_class_for_table_type(table_type: str) -> tp.Type['Table']:
I don't expect this. Currently, we don't even use this function (but that could change in the future).

2022-04-26 12:43 UTC, boehmseb commented on varats/varats/tools/driver_plot.py
> +    initialize_plots()
It's not really a loop, but I agree that we should improve how we initialize all of our registries. This, however, sounds like its own PR and we should discuss this first.

2022-04-26 14:49 UTC, vulder commented on varats/varats/table/table.py
> +    def get_class_for_table_type(table_type: str) -> tp.Type['Table']:
ok then let's keep it that way

2022-04-26 14:50 UTC, vulder approved these changes
Expect for the pylint warning in `varats/varats/ts_utils/cli_util.py`

LGTM

2022-04-28 14:31 UTC, vulder approved these changes

2022-04-28 14:33 UTC, merged