Additional verification for VaRA in buildsetup
se-passau/VaRA-Tool-Suite pull request #621
Opened 2022-03-19 17:07 UTC by LuAbelt

Added additional verification to the `verify_install` step for VaRA

Additionally, VaRA now runs the `check_vara` target to verify that it not only compiles but also passes unittests.

Not sure if we really want this in a separate `verify_build` but in `verify_install` we currently don't have access to the build directory in which we run `ninja`.

Closes: https://github.com/se-sic/VaRA/issues/801

2022-03-19 20:07 UTC, vulder requested changes
Impl looks good, thx.

I only have a few small issue/questions.

2022-03-19 20:07 UTC, vulder commented on varats/varats/tools/research_tools/research_tool.py
> +        return True
```suggestion
```

Should we really provide a default impl here? Could be better to force every `research_tool` to implement the method by making it abstract. If the tool wants to default to `true` they can.

2022-03-19 20:07 UTC, vulder commented on varats/varats/tools/research_tools/research_tool.py
> +
```suggestion

            build_type: which type of build should be used, e.g., debug,
                        development or release
            build_folder_suffix: a suffix that is appended to the build folder
```

PS: not sure if this is correctly aligned, gh makes it hard so see this

2022-03-19 20:07 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +        (ret, stdout, _) = clang.run("--version")
```suggestion
        # Check that clang++ can display it's version
        clang = local[str(install_location / "bin/clang++")]
        ret, stdout, _ = clang.run("--version")
```
Python does not require braces to unpack the return values

2022-03-19 20:07 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +        status_ok &= (ret == 0)
```suggestion
        status_ok &= (ret == 0)
```
What's the idea behind putting braces around the comparision?

2022-03-19 20:07 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +        status_ok &= (ret == 0)
```suggestion
        phasar_llvm = local[str(install_location / "bin/phasar-llvm")]
        ret, stdout, _ = phasar_llvm.run("--version")
        status_ok &= ret == 0
```

2022-03-19 20:07 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +                        development or release
```suggestion
            build_type: which type of build should be used, e.g., debug,
                        development or release
            build_folder_suffix: a suffix that is appended to the build folder
```

2022-03-19 20:07 UTC, vulder commented on varats/varats/tools/research_tools/vara.py
> +        return bool(ret == 0)
```suggestion
        ninja = local["ninja"].with_cwd(full_path)
        ret, _, _ = ninja.run("check-vara")
        return ret == 0
```

2022-03-20 10:39 UTC, LuAbelt commented on varats/varats/tools/research_tools/vara.py
> +        return bool(ret == 0)
If we remove the explicit cast to `bool`, mypy will complain about the function returning `Any` even though it was declared as `bool`

2022-03-20 11:46 UTC, boehmseb approved these changes

2022-03-20 12:19 UTC, vulder approved these changes

2022-03-20 13:22 UTC, merged