Create seperate Module for basic git command wrapper
se-passau/VaRA-Tool-Suite pull request #629
Opened 2022-03-23 08:16 UTC by Sinerum

Create a new module that houses wrapper for basic git commands. And move and refactor the implementations from vara_manager to it and make use of plumbum.

2022-04-05 11:42 UTC, boehmseb requested changes
Found some instances where code can be simplified.

Also, how did you decide which functions to put in `git_util` and which in `git_commands`?

2022-04-05 11:42 UTC, boehmseb commented on varats-core/varats/utils/git_commands.py
> +    args += extra_args
```suggestion
    args = ["branch"]
    if extra_args:
        args += extra_args
```

2022-04-05 11:42 UTC, boehmseb commented on varats-core/varats/utils/git_commands.py
> +    args += extra_args
```suggestion
    args = ["tag"]
    if extra_args:
        args += extra_args
```

2022-04-05 11:42 UTC, boehmseb commented on varats-core/varats/utils/git_commands.py
> +    args += extra_args
```suggestion
    args = ["fetch"]
    if extra_args:
        args += extra_args
```

2022-04-05 12:04 UTC, boehmseb approved these changes

2022-04-19 11:19 UTC, vulder approved these changes
Did you try a "new" blank install of VaRA with vara-buildsetup after moving all the commands?

If not, could you please make a test run :D The install code is not fully tested an I'm a bit scared we could break things there.

2022-04-25 08:40 UTC, Sinerum commented
> Did you try a "new" blank install of VaRA with vara-buildsetup after moving all the commands?
> 
> If not, could you please make a test run :D The install code is not fully tested an I'm a bit scared we could break things there.

`vara-buildsetup init` works fine, but building afterwards fails. I am not sure if that is related to this change.

2022-04-27 18:13 UTC, vulder approved these changes

2022-04-27 19:49 UTC, merged