report aggregates for time and TEF
se-passau/VaRA-Tool-Suite pull request #631
Opened 2022-03-28 12:31 UTC by Kaufi-Jonas

2022-04-06 09:05 UTC, vulder requested changes
Overall, this looks good, will be a nice addition to the tool suite :smile: , we just need to figure out the thing about the context mgr for finaliztion.

2022-04-06 09:05 UTC, vulder commented on varats-core/varats/report/gnu_time_report.py
> +class TimeReport(BaseReport, shorthand="TR", file_type="txt"):
Why do you think we should a txt as a file type for the time reports?

2022-04-06 09:05 UTC, vulder commented on varats-core/varats/report/gnu_time_report.py
> +
```suggestion
```

2022-04-06 09:05 UTC, vulder commented on varats-core/varats/report/gnu_time_report.py
> +
```suggestion
```

2022-04-06 09:05 UTC, vulder commented on varats-core/varats/report/gnu_time_report.py
> +
```suggestion
```

2022-04-06 09:05 UTC, vulder commented on varats-core/varats/report/gnu_time_report.py
> +    def wall_clock_time_mean(self) -> float:
```suggestion
    def mean_wall_clock_time(self) -> float:
```
I think this would read better.

```
df = ...
report = ...
df["mean"] = report.mean_wall_clock_time
```

2022-04-06 09:05 UTC, vulder commented on varats-core/varats/report/gnu_time_report.py
> +    def wall_clock_time_std(self) -> float:
same here

2022-04-06 09:05 UTC, vulder commented on varats-core/varats/report/report.py
> +):
I'm still not fully convinced we should implement the Aggregated report with a context manager, as the typical report usage pattern in varats does not use `with`, but just hands report objects from `a` to `b`.

In my opinion, using a finalizer to clean up the tmpdir after object destruction is the better way.
See the example here https://docs.python.org/3.6/library/weakref.html#comparing-finalizers-with-del-methods

2022-04-06 09:05 UTC, vulder commented on varats-core/varats/report/report.py
> +    BaseReport, tp.Generic[T], shorthand="Agg", file_type="zip"
@boehmseb Can you please take a look at the typing here, I'm not 100% sure how mypy likes typechecking when using run-time types (parameters) as generic `T`s.

2022-04-06 09:05 UTC, vulder commented on tests/report/test_aggregated_reports.py
> +
```suggestion
```

2022-04-06 09:05 UTC, vulder commented on tests/report/test_aggregated_reports.py
> +
```suggestion
```

2022-04-06 09:05 UTC, vulder commented on tests/report/test_aggregated_reports.py
> +
```suggestion
```

2022-04-06 09:05 UTC, vulder commented on tests/report/test_aggregated_reports.py
> +
```suggestion
```

2022-04-06 10:55 UTC, boehmseb commented on varats-core/varats/report/report.py
> +    BaseReport, tp.Generic[T], shorthand="Agg", file_type="zip"
Not sure where you see a potential problem. Mypy does not complain on this PR and I also can't see any problems.

2022-04-06 19:41 UTC, vulder commented on varats-core/varats/report/report.py
> +    BaseReport, tp.Generic[T], shorthand="Agg", file_type="zip"
Yeah, it does not complain that's what makes me anxious :laughing: 
With dynamic types for `T` you cannot really do a lot of type checking at mypy time and I was wondering if that could lead to problems in certain scenarios.

2022-04-06 19:44 UTC, boehmseb commented on varats-core/varats/report/report.py
> +    BaseReport, tp.Generic[T], shorthand="Agg", file_type="zip"
From what I see, this should be fine. We do similar things in other locations. A better name for `T` would be nice though.

2022-04-08 09:38 UTC, vulder approved these changes

2022-04-08 09:40 UTC, merged