Set  mounting parameters according to the Buildah version when building Containers
se-passau/VaRA-Tool-Suite pull request #632
Opened 2022-04-11 09:13 UTC by Sinerum

Set the `rw` mounting parameter when the installed buildah version requires it and not if it does not. Also update the required benchbuild version to 3.6.1. to include this fix in benchbuild as well.

2022-04-11 14:13 UTC, boehmseb approved these changes

2022-04-11 14:15 UTC, boehmseb commented
Only this one test needs fixing. It just needs to include the `,rw` in teh expected output.

2022-04-11 14:22 UTC, Sinerum commented
> Only this one test needs fixing. It just needs to include the `,rw` in the expected output.
It needs to be removed, but that would mean the test would fail depending on the buildah version would that be okay?

2022-04-13 07:39 UTC, boehmseb requested changes

2022-04-13 07:39 UTC, boehmseb commented on varats/varats/containers/containers.py
> +            'libffi-dev', 'libyaml-dev', 'graphviz-dev'
Can you please also add this dependency to the install guide in `docs/source/tutorials/getting_started.rst` and `docs/source/vara-ts/vara-buildsetup.rst`?

2022-04-14 07:55 UTC, vulder commented
> > Only this one test needs fixing. It just needs to include the `,rw` in the expected output.
> 
> It needs to be removed, but that would mean the test would fail depending on the buildah version would that be okay?

Neither, just use the buildah version check to determine if `rm` should be there or not.

2022-04-19 10:21 UTC, vulder approved these changes
Except for the missing test adaption this PR looks good to me.

2022-04-20 10:31 UTC, merged