Casestudy Generation Gui
se-passau/VaRA-Tool-Suite pull request #633
Opened 2022-04-11 09:15 UTC by Sinerum

Adds a gui for generating casestudies. the gui can be started using `vara-cs gen-gui`

resolves se-sic/VaRA#795

2022-04-19 10:42 UTC, vulder requested changes
Did you write the gui without a ui file? If not, you should add the ui file for generation to the appropriate folder (`uicomponents/`) and add the generation call to the script.

Furthermore, I think we should name the `main_window` files a bit more specific.

Otherwise, the GUI looks nice, thx.

2022-04-19 10:42 UTC, vulder commented on varats/varats/gui/cs_gen/main_window.py
> +    SELECTREVISION = 0
```suggestion
    SELECT_REVISION = 0
```
To follow the naming schema, this needs an `_` or?

2022-04-20 08:24 UTC, vulder approved these changes
thx, lgtm now :grinning:

2022-04-25 10:56 UTC, boehmseb reviewed
Do we have any chance of testing anything of this, e.g., the filter logic or similar?

2022-04-25 10:56 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +from varats.gui.cs_gen.case_study_generation import start_gui
We should be careful with imports that require Qt since as soon as a module imports `PyQt5` it will not work in our containers. That means that with this import, we can no longer run any `vara-cs` commands in a container. As far as I know we don't do this now anywhere maybe apart from manual debugging, but who knows what will happen in the future.
Maybe making this a local import could avoid this issue, but I'm not certain.
@vulder what do you think?

2022-04-26 12:16 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +from varats.gui.cs_gen.case_study_generation import start_gui
Yeah, that could become a problem, we probably should also include a test at some point to ensure we don't break anything on accident.

For this specific case, maybe we should split of the `gui` tools into separate drivers? This would at least make it clear on which qt may depend.

Far fetched idea for the future: Introduce a new namespace `varats-gui`, which implements all `gui` tools and gui related stuff AND only the setup.py for this namespace is allowed to depend on `qt`.

2022-04-26 12:47 UTC, boehmseb commented on varats/varats/tools/driver_casestudy.py
> +from varats.gui.cs_gen.case_study_generation import start_gui
For now i vote for the separate driver module. I think we did (or at least discussed) something similar with vara-buildsetup.
The namespace idea sounds like something that should be done after our long desired jupyter idea as it would require the same kind of API layer.

2022-04-26 14:48 UTC, vulder commented on varats/varats/tools/driver_casestudy.py
> +from varats.gui.cs_gen.case_study_generation import start_gui
Works for me. Then let's move the code into a separated driver module and talk about the rework afterwards :+1:

@Sinerum If you're interested in joining out "new and fancy idea", we could meet in the following weeks in our office to discuss more details :wink:

2022-05-02 11:35 UTC, boehmseb approved these changes

2022-05-02 11:46 UTC, merged