Introduces better VaRA documentation
se-passau/VaRA-Tool-Suite pull request #636
Opened 2022-04-20 10:06 UTC by vulder

2022-04-25 10:34 UTC, boehmseb requested changes
Overall a good addition to improve the VaRA documentation. I found some spots where the formulation could be a bit clearer or where some additional information would be nice. And of course some typos ;)

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +VaRA's feature performance analysis is build to make the impact of software features measurable.
```suggestion
VaRA's feature performance analysis is built to make the impact of software features measurable.
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +How to setup and use the feature performance analysis
```suggestion
How to set up and use the feature performance analysis
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +1) Setup VaRA by following our :ref:`setup guide<Build VaRA with vara-buildsetup>`.
```suggestion
1) Set up VaRA by following our :ref:`setup guide<Build VaRA with vara-buildsetup>`.
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/using.rst
> +Overall, VaRA is build for two different usage scenarios:
```suggestion
Overall, VaRA is built for two different usage scenarios:
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/vara.rst
> +VaRA is an analysis framework that enables users to build static and dynamic analyses for analyzing high-level concepts, using advanced compiler and analysis technology in the background.
```suggestion
VaRA is an analysis framework that enables users to build static and dynamic analyses for analyzing high-level concepts using advanced compiler and analysis technology in the background.
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/vara.rst
> +Our goal is to enable the user to build these analyses by only focusing on the highlevel conceptual information that should be analyzed, without worrying about low-level details, such as, building co
```suggestion
Our goal is to enable the user to build these analyses by only focusing on the high-level conceptual information that should be analyzed without worrying about low-level details, such as building complicated compiler modifications or configuring precise but difficult to use static analyses.
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/vara.rst
> +In general, VaRA and our modified clang compiler take in source code together with highlevel conceptual information and either directly analyze it, using various static analyses, or generate an instr
```suggestion
In general, VaRA and our modified clang compiler take as input source code together with high-level conceptual information and either directly analyze it, using various static analyses, or generate an instrumented binary, which can run different dynamic analyses.
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +The different instrumentation options can be found here :ref:`Instrumentations`.
```suggestion
The different instrumentation options can be found :ref:`here<Instrumentations>`.
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +Without LTO, only within translation unit analysis is possible, hence, cross translation unit feature usage is not possible.
```suggestion
Without LTO, the analysis can only run within a translation unit, hence, features that are used across different translation units can not be correctly analyzed.
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +    bool MyFeatureVariable __attribute__((feature_variable("FEATURE_NAME"))) = false /*default*/;
A bit more explanation here would be good:
- what does the feature model do?
- Where does the feature model come from and how do I get one for my project?
- what happens if I mark a variable this way?

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +* `clock`: Add hw-clock based measurements that determine the time spend in a feature
```suggestion
* `clock`: Add hw-clock based measurements that determine the time spent in a feature
```

2022-04-25 10:34 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +* `instr_verify`: Add verifier instrumentation that check if regions are correctly opened/closed
```suggestion
* `instr_verify`: Add verifier instrumentation that checks if feature regions are correctly opened/closed
```

2022-04-26 14:46 UTC, vulder commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +    bool MyFeatureVariable __attribute__((feature_variable("FEATURE_NAME"))) = false /*default*/;
Ok now?

2022-04-26 14:57 UTC, boehmseb approved these changes

2022-04-26 14:57 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/feature_performance_analysis.rst
> +    bool MyFeatureVariable __attribute__((feature_variable("FEATURE_NAME"))) = false /*default*/;
Yes

2022-04-27 18:12 UTC, merged