Remove extra_test.sh from ci
se-passau/VaRA-Tool-Suite pull request #638
Opened 2022-05-02 11:44 UTC by Sinerum

2022-05-03 15:22 UTC, vulder requested changes
Overall, this looks good thx for remove the old "extra tests" :laughing:

2022-05-03 15:22 UTC, vulder commented on tests/tools/test_driver_casestudy.py
> +        case_study = load_case_study_from_file(case_study_path)
Just to make sure, The case study had one revision already did it not?
Because you check for two different ones afterwards but only select one.

What could improve this test is add two constants at the top of the test func `new_commit = ...` and `already_existing_commit = ...` and the afterwards use the constants.

2022-05-03 15:22 UTC, vulder commented on tests/tools/test_driver_casestudy.py
> +        """Test the extend-functionality of vara-cs gen."""
same for this test

2022-05-09 09:20 UTC, Sinerum commented on tests/tools/test_driver_casestudy.py
> +        case_study = load_case_study_from_file(case_study_path)
Yes since the test is about the extending feature we need to make sure the original commits are still present.

2022-05-09 20:22 UTC, vulder commented on tests/tools/test_driver_casestudy.py
> +        case_study = load_case_study_from_file(case_study_path)
Yeah, makes sense :+1:

2022-05-09 20:22 UTC, vulder approved these changes

2022-05-16 11:12 UTC, boehmseb approved these changes

2022-05-17 10:29 UTC, merged