Adds more documentation for VaRA
se-passau/VaRA-Tool-Suite pull request #641
Opened 2022-05-06 11:45 UTC by vulder

2022-05-09 12:29 UTC, boehmseb requested changes

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/instr_verify.rst
> +The instrumentation verifier is an instrumention build to debug and verify regions.
```suggestion
The instrumentation verifier is an instrumentation built to debug and verify regions.
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/print_instr.rst
> +VaRA inserts at the beginning and end of the program, as well as, at every start/end of a region a print call that prints out the current regions name.
```suggestion
VaRA inserts at the beginning and end of the program as well as at every start/end of a region a print call that prints the current region's name.
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/print_instr.rst
> +An example output could look like this.
```suggestion
An example output could look like this:
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/clock_instr.rst
> +===================================
Why no explanation here?

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/trace_event_instr.rst
> +VaRA can automatically insert TEF instrumentation markers for measuring the time that's spend withing a region.
```suggestion
VaRA can automatically insert TEF instrumentation markers for measuring the time that's spent within a region.
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/trace_event_instr.rst
> +Good tools for viewing the generated trace file are the newly developer trace viewer `perfetto <https://ui.perfetto.dev/>`_ or the chrome's internal trace viewer, which can be accessed by typing `abo
```suggestion
Good tools for viewing the generated trace file are the newly developed trace viewer `perfetto <https://ui.perfetto.dev/>`_ or the chrome's internal trace viewer, which can be accessed by typing `about:tracing` into the search box.
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/trace_event_instr.rst
> +For more information, see the format definition `here <https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview>`_
```suggestion
For more information, see the format definition `here <https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview>`_.
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/instr_verify.rst
> +Should a region be not correctly instrumented, the verifyer reports the problem and provides extra information about the region, e.g., the region ID or the file location of the code region (in case t
```suggestion
Should a region instrumented incorrectly, the verifier reports the problem and provides extra information about the region, e.g., the region ID or the file location of the code region (in case the code was compiled with ``-g``).
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/instr_verify.rst
> +The verifyer checks if every start instrumentation for a region has a matching end instrumentation.
```suggestion
The verifier checks if every start instrumentation for a region has a matching end instrumentation.
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/instr_verify.rst
> +
```suggestion

Example output:

```
Or similar

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/instrumentations/usdt.rst
> +USDT Probe Instrumentations (``usdt``)
Why no documentation here? At least leave a _TODO_.

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/regions/highlight_region.rst
> +The idea behind a `HighlightRegion` is to highlight a specific code region and attach additional customizable identifyer.
```suggestion
The idea behind a `HighlightRegion` is to highlight a specific code region by attaching additional customizable identifiers.
```
Did I get the meaning of this sentence correctly?

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/regions/highlight_region.rst
> +The boundary of the region is defined by ``___REGION_START`` and ``___REGION_END``, the region type ``__RT_High`` and the identifyer afterwards.
```suggestion
The boundary of the region is defined by ``___REGION_START`` and ``___REGION_END``, the region type ``__RT_High`` and the identifier afterwards.
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/regions/highlight_region.rst
> +To highlight the part where the answert to everything is computed, we put a ``___REGION_START`` marker before the call and a ``___REGION_END`` marker after we printed the answer.
```suggestion
To highlight the part where the answer to everything is computed, we put a ``___REGION_START`` marker before the call and a ``___REGION_END`` marker after we printed the answer.
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/regions/highlight_region.rst
> +Afterwards, clang processes the region and annotates the interal compiler IR with our region information, enabling further analyses to recognize the code we highlighted.
```suggestion
Afterwards, clang processes the region and annotates the internal compiler IR with our region information, enabling further analyses to recognize the code we highlighted.
```

2022-05-09 12:29 UTC, boehmseb commented on docs/source/research_tool_docs/vara/usages/highlight_analysis.rst
> +Highlight-Interaction Analysis
Why no documentation here? At least leave a _TODO_.

2022-05-09 20:23 UTC, vulder commented on docs/source/research_tool_docs/vara/instrumentations/clock_instr.rst
> +===================================
They are not really used/fleshed out currently. I only added the entry for completness.

2022-05-09 20:25 UTC, vulder commented on docs/source/research_tool_docs/vara/instrumentations/usdt.rst
> +USDT Probe Instrumentations (``usdt``)
As above, we are currently working on fleshing these out. Before this is don't doc's would be more confusing as helpful.

2022-05-09 20:26 UTC, vulder commented on docs/source/research_tool_docs/vara/usages/highlight_analysis.rst
> +Highlight-Interaction Analysis
Because there is no highlight-interaction analysis, a TODO would not help here.
I's more an idea that needs to be worked on.

2022-05-09 20:27 UTC, vulder commented on docs/source/research_tool_docs/vara/instrumentations/clock_instr.rst
> +===================================
```suggestion
===================================

TODO: add docs
```

2022-05-09 20:27 UTC, vulder commented on docs/source/research_tool_docs/vara/instrumentations/usdt.rst
> +======================================
```suggestion
======================================

TODO: add docs
```

2022-05-13 11:43 UTC, s9latimm approved these changes

2022-05-13 12:29 UTC, merged