USDT execution stats experiment, projects gzip and bzip2
se-passau/VaRA-Tool-Suite pull request #642
Opened 2022-05-08 21:25 UTC by Kaufi-Jonas

- New experiment 'VaraUS', which captures tracing execution statistics using VaRA's USDT instrumented USDT probes and the included script 'UsdtExecutionStats.bt'
- Fixed bug in gzip, which always executes local machine's binary
- Added project bzip2
- Updated project FeaturePerfCSCollection to include binaries 'SimpleSleepLoop' and 'SimpleBusyLoop'

Example output of experiment:
```
Attaching 8 probes...

@nanoseconds_between_probes: 
[256, 512)             1 |                                                    |
[512, 1K)              0 |                                                    |
[1K, 2K)               0 |                                                    |
[2K, 4K)               3 |                                                    |
[4K, 8K)               1 |                                                    |
[8K, 16K)              0 |                                                    |
[16K, 32K)             0 |                                                    |
[32K, 64K)           522 |                                                    |
[64K, 128K)        98550 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[128K, 256K)         915 |                                                    |
[256K, 512K)          13 |                                                    |

@num_probes_fired[finalize]: 1
@num_probes_fired[init]: 1
@num_probes_fired[end]: 2
@num_probes_fired[begin]: 100002
```

2022-05-09 07:51 UTC, vulder requested changes
Very nice work :+1:

2022-05-09 07:51 UTC, vulder commented on varats-core/varats/report/gnu_time_report.py
> +                # print("Not matched: ", line)
```suggestion
                print("Not matched: ", line)
```
Left over comment or should we remove this line?

2022-05-09 07:51 UTC, vulder commented on varats/varats/data/reports/usdt_stats_report.py
> +class VaraUsdtStatsReport(BaseReport, shorthand="VaraUS", file_type="txt"):
I'm currently debating in my head what a better name would be.
UsdtStats is correct, but I think we should be a bit more specific and not focus on the technology to much.
What are your ideas? Maybe something in the direction of `InstStatistics`, not sure :thinking:

2022-05-09 07:51 UTC, vulder commented on varats/varats/projects/c_projects/gzip.py
> +
Good catch :+1:

PS: could it be that the line of the comment is to long?

2022-05-09 07:51 UTC, vulder commented on varats/varats/projects/c_projects/gzip.py
> +        with local.cwd(gzip_version_source / "build"), local.env(CC=str(clang)):
```suggestion
        c_compiler = bb.compiler.cc(self)
        with local.cwd(gzip_version_source / "build"), local.env(CC=str(c_compiler)):
```
When we already hear, fixing this we can clean up the old "bad" name :laughing:

2022-05-09 07:51 UTC, vulder commented on varats/varats/experiments/vara/usdt_stats_experiment.py
> +            # TODO Change this.
```suggestion
            # TODO (se-sic/VaRA#841): refactor to bb workloads if possible
```

2022-05-09 07:51 UTC, vulder commented on varats/varats/experiments/vara/usdt_stats_experiment.py
> +            workload = workload_provider.get_workload_for_binary(binary.name)
You need to first check if a provider was available, for some projects it might not be :)

2022-05-09 07:51 UTC, vulder commented on varats/varats/experiments/vara/usdt_stats_experiment.py
> +                sleep(1)  # give bpftrace time to start up
Is there another way we could guarantee this?

What happens when 1 sec is not enough? Could happen on an old and slow machine.

2022-05-09 07:51 UTC, vulder commented on varats-core/varats/provider/workload/workload_provider.py
> +    }
We could slightly refactor this to make it "a bit" more reusable.
Put a option into the varats config `workload_base_location`, which you can set to `/home/jonask/Repos/WorkloadsForConfigurableSystems`. Then in the provider we concatenate the location on the rest of the path. With this, we have the option that you send you workloads to me/or someone an still run the experiment ;)

2022-05-09 07:51 UTC, vulder commented on varats-core/varats/provider/workload/workload_provider.py
> +        return self.WORKLOADS.get(key, None)
You have two options here:
a) return an empty list
b) return an optional list (however, I'm not sure if `Provider` requires the signature)

2022-05-09 08:33 UTC, Kaufi-Jonas commented on varats-core/varats/report/gnu_time_report.py
> +                # print("Not matched: ", line)
I'd say let's remove it. For example, when parsing 100 time reports, stdout will be full of 'Not matched'.

2022-05-17 07:30 UTC, vulder approved these changes

2022-05-17 10:53 UTC, merged