Make the compile function of brotli version specific
se-passau/VaRA-Tool-Suite pull request #643
Opened 2022-05-19 13:02 UTC by Sinerum

related se-sic/VaRA#492

2022-05-23 06:44 UTC, vulder requested changes
The compile function looks fine.
However, due to the revision blocking some tests are broken and need to be fixed before we can merge this.

2022-05-23 06:44 UTC, vulder commented on varats/varats/projects/c_projects/brotli.py
> +        if brotli_version in configure_revisions:
```suggestion

        if brotli_version in configure_revisions:
```

2022-05-23 11:45 UTC, boehmseb commented on varats/varats/projects/c_projects/brotli.py
> +                "building not unified"
What do you mean by "building not unified"? Maybe this message could be a bit more expressive.

2022-05-23 12:11 UTC, Sinerum commented on varats/varats/projects/c_projects/brotli.py
> +                "building not unified"
There is no Makefile that builds everything. Every part of brotli so the encoder and decoder had seperate Makefiles at this point,but this range is acctually smaller. I discoverd, that after a certain revision the commanline tool was introduced, and the Makefile for this builds everything. This method has now also been added.

2022-05-24 14:11 UTC, boehmseb approved these changes

2022-05-24 14:11 UTC, boehmseb commented on varats/varats/projects/c_projects/brotli.py
> +
```suggestion
```

2022-05-24 14:11 UTC, boehmseb commented on varats/varats/projects/c_projects/brotli.py
> +
```suggestion
```

2022-05-25 17:17 UTC, vulder approved these changes

2022-05-25 18:39 UTC, merged