Fix/Improve/Update slurm and container related docs.
se-passau/VaRA-Tool-Suite pull request #648
Opened 2022-05-25 15:38 UTC by boehmseb

2022-05-25 15:45 UTC, boehmseb commented
Here links to the relevant sections in the rendered docs:
https://vara.readthedocs.io/en/f-updateslurmdocs/vara-ts/slurm.html
https://vara.readthedocs.io/en/f-updateslurmdocs/vara-ts/benchbuild.html#running-benchbuild-in-a-container

2022-05-25 17:11 UTC, vulder requested changes

2022-05-25 17:11 UTC, vulder commented on docs/source/vara-ts/slurm.rst
> +   This guide assumes that your VaRA-TS root directory is ``/scratch/<user>/varats``:
Is `varats` the best name that we should advertise? Maybe calling the folder `varats_root` or `varats-root` is better, as it's more explicit when we talk about the varats root.

2022-05-26 08:59 UTC, vulder commented on docs/source/vara-ts/slurm.rst
> +   This guide assumes that your VaRA-TS root directory is ``/scratch/<user>/varats``:
@boehmseb Ok, as we discussed yesterday. We'll leave this here for now, merge the PR, and you clean this up in another PR.

2022-05-26 08:59 UTC, vulder approved these changes

2022-05-26 09:16 UTC, merged