adds feature performance analysis experiments
se-passau/VaRA-Tool-Suite pull request #652
Opened 2022-06-04 17:06 UTC by Kaufi-Jonas

2022-06-04 17:12 UTC, Kaufi-Jonas commented
The newly added `FeaturePerfAnalysisTef` experiment should cover the functionality from [`varats/varats/experiments/vara/feature_perf_runner.py`](https://github.com/se-sic/VaRA-Tool-Suite/blob/vara-dev/varats/varats/experiments/vara/feature_perf_runner.py) with the difference of collecting gnu time statistics. What's your opinion, should I remove it?

2022-06-07 08:44 UTC, vulder requested changes
The overall Idea is good, we should talk about this a bit more in our 1o1 tomorrow, as I also was working on unifying feature perf analyses. Maybe we can merge/extend your abstraction to handle everything.

2022-06-07 08:44 UTC, vulder commented on varats-core/varats/experiment/experiment_util.py
> +
We should not export the `Experiment` here. The idea behind the handle was to control which information can be accessed by a step and how. The `Experiment` has many details that we don't want to expose to the underlying steps or a project.
I checked your usages below, you only need the `shorthand`, which would be ok to export (i.e., make accessible).
So, I would remove this part here and only add a property for the `shorthand`.

2022-06-07 08:44 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_analysis_experiments.py
> +    USE_USDT = False
I'm currently a bit undecided if modeling these two values as class variables is a good idea. I normally only use object variables for these this and pass the correct state via the `__init__` method.

What was you reasoning behind it?

2022-06-07 12:06 UTC, Kaufi-Jonas commented on varats-core/varats/experiment/experiment_util.py
> +
Makes sense, will change that.

2022-06-07 12:14 UTC, Kaufi-Jonas commented on varats/varats/experiments/vara/feature_perf_analysis_experiments.py
> +    USE_USDT = False
Actually don't know the reason anymore. Guess it was somehow simpler to do it with class variables in the past but I then removed the reason for it. Gonna change that since in my opinion passing the parameters in `__init__` is the proper way to do it.

2022-10-25 12:07 UTC, closed without merging