fta-locations-eval-table
se-passau/VaRA-Tool-Suite pull request #665
Opened 2022-07-25 16:43 UTC by Keller-1998

The fta-locations-eval-table contains information about the false-tainted locations. I also decided to switch from sets to lists in the evaluation process in order to recognize multiple taints at one location.

2022-11-08 09:32 UTC, vulder requested changes
Looks good :+1:

2022-11-08 09:32 UTC, vulder commented on varats/varats/projects/cpp_projects/ect.py
> +
Does the tool have any dependencies? If `yes`, it would be cool to add a container install spec like:
```
    CONTAINER = get_base_image(
        ImageBase.DEBIAN_10
    ).run('apt', 'install', '-y', 'cmake', 'g++', 'git', 'make', 'python3')
```

2022-11-08 09:32 UTC, vulder commented on varats/varats/projects/cpp_projects/ect.py
> +
+ Please fix the broken test, there is just a small config specification missing probably

2023-03-14 14:48 UTC, vulder commented on varats/varats/table/table.py
> +            case_studies = self.table_kwargs['case_study']
@boehmseb is this necessary?

2023-03-14 16:02 UTC, boehmseb commented on varats/varats/table/table.py
> +            case_studies = self.table_kwargs['case_study']
`Plot.table_kwargs['case_study']` should never be a list.
Therefore, this change should not be necessary.
If there is a plot that can be created for different subsets of case studies, I suggest that plot should override this function.

2023-03-14 20:15 UTC, Keller-1998 commented on varats/varats/table/table.py
> +            case_studies = self.table_kwargs['case_study']
With the CLI Option `REQUIRE_MULTI_CASE_STUDY`, the case studies are passed as a list. Therefore, I thought this might be a bug. 

I just pushed a commit that implements your suggestion.

2023-03-15 08:07 UTC, boehmseb commented on varats/varats/table/table.py
> +            case_studies = self.table_kwargs['case_study']
It's not a bug. The intended usage of `REQUIRE_MULTI_CASE_STUDY` is that the plot/table generator creates one plot/table per case study.
A plot/table typically requires either a single case study or all case studies from a paper config at once.

2023-03-15 09:59 UTC, Keller-1998 commented on varats/varats/table/table.py
> +            case_studies = self.table_kwargs['case_study']
Ohh, alright, got it!

2023-09-02 07:33 UTC, closed without merging