Adds workload support to varats
se-passau/VaRA-Tool-Suite pull request #667
Opened 2022-08-16 11:14 UTC by vulder

2022-09-28 08:29 UTC, boehmseb requested changes

2022-09-28 08:29 UTC, boehmseb commented on varats-core/varats/experiment/workload_util.py
> +            "Workload/Command labels should not contain underscores '_'!"
```suggestion
            "Workload/Command labels must not contain underscores '_'!"
```

2022-09-28 08:29 UTC, boehmseb commented on varats-core/varats/utils/exceptions.py
> +                           should be save
```suggestion
                           should be safe
```

2022-09-28 08:29 UTC, boehmseb commented on varats-core/varats/utils/exceptions.py
> +    returns an optinal is declared to always return a concret value. Should no
```suggestion
    returns an optional is declared to always return a concrete value. Should no
```

2022-09-28 08:29 UTC, boehmseb commented on varats/varats/experiments/base/time_workloads.py
> +"""Implements an experiment times the execution of all project binaries."""
```suggestion
"""Implements an experiment that times the execution of all project binaries."""
```

2022-09-28 08:29 UTC, boehmseb commented on varats/varats/experiments/base/time_workloads.py
> +    """Times the execution of all project workloads."""
Do you intend to execute all workloads or all example workloads?

```suggestion
    """Times the execution of all project example workloads."""
```

2022-09-28 08:29 UTC, boehmseb commented on varats/varats/experiments/base/time_workloads.py
> +    DESCRIPTION = "Time the execution of all project workloads."
```suggestion
    DESCRIPTION = "Time the execution of all project example workloads."
```

2022-09-28 08:29 UTC, boehmseb commented on varats/varats/experiments/base/time_workloads.py
> +        measurment_repetitions = 2
Is this a debug value or do you really intend to only make 2 repetitions?

2022-09-28 08:29 UTC, boehmseb commented on varats/varats/projects/c_projects/gzip.py
> +        # TODO: auto unzipper for BB?
What would this auto-unzipper do?

2022-09-28 08:29 UTC, boehmseb commented on varats/varats/tables/time_workloads.py
> +                                    )
This could be factored out since you need it for the mean and the standard deviation (also would help with this atrocity of code layout yapf produces :smiley:).

2022-09-28 08:58 UTC, vulder commented on varats/varats/experiments/base/time_workloads.py
> +        measurment_repetitions = 2
This is "intended" in the way that the experiment is only meant as a show case and should complete in time. Not sure what value to pick here...

2022-09-28 08:59 UTC, vulder commented on varats/varats/projects/c_projects/gzip.py
> +        # TODO: auto unzipper for BB?
BB will add a new HTTP with unzip at some point, so we can specify zip files which will automatically be unpacked. This is "just" not ready and will come in the next BB version.

2022-09-28 12:19 UTC, boehmseb approved these changes

2022-09-28 18:22 UTC, vulder commented on varats/varats/tables/time_workloads.py
> +                                    )
done

2022-09-29 10:59 UTC, jonas-kaufmann commented on varats-core/varats/report/gnu_time_report.py
> +    file."""
I suggest a better doc string. How about the following?
```suggestion
    """Context Manager for parsing multiple time reports stored inside a zip
    file and grouping them based on the workload they belong to."""
```

2022-09-29 10:59 UTC, Kaufi-Jonas commented on varats/varats/projects/c_projects/gzip.py
> +                "--force",  # needed because BB creats symlinks for the inputs
```suggestion
                "--force",  # needed because BB creates symlinks for the inputs
```

2022-09-29 10:59 UTC, Kaufi-Jonas commented on varats/varats/projects/c_projects/gzip.py
> +                    SourceRoot('gzip') / "../countries-land-1km.geo.json.gz"
Can't we just specify `countries-land-1km.geo.json.gz` without referring to SourceRoot here since we pass the workload file to gzip like this as well? I find the `../` confusing as I was wondering what the parent directory of `SourceRoot('gzip')` contains. I suppose this is simply `<vara_root>/benchbuild/tmp`.

2022-09-29 11:41 UTC, Kaufi-Jonas requested changes

2022-09-29 11:41 UTC, Kaufi-Jonas commented on varats/varats/plots/time_workloads.py
> +                "Plot can currently only handle on experiment, "
```suggestion
                "Plot can currently only handle a single experiment, "
```

2022-09-29 11:41 UTC, Kaufi-Jonas commented on varats/varats/tables/time_workloads.py
> +                    "Table can currently only handle on experiment, "
```suggestion
                    "Table can currently handle only a single experiment, "
```

2022-09-29 11:41 UTC, Kaufi-Jonas commented on varats/varats/tables/time_workloads.py
> +                )
Does this work at runtime? `workload_name` is unbound in the scope where `wall_clock_time_in_msecs` is defined. Does the function inherit the scope it is called in, in our case the scope of the following for-loop, which defines `workload_name`?

2022-09-29 13:20 UTC, vulder commented on varats/varats/projects/c_projects/gzip.py
> +                    SourceRoot('gzip') / "../countries-land-1km.geo.json.gz"
No, the `SourceRoot` is where the gzip copy is put into the build directory.
However, if I remember this correctly we fixed this indirection problem on the BB side already so the BuildDir is always taken as a default starting point

2022-09-29 13:21 UTC, vulder commented on varats/varats/projects/c_projects/lrzip.py
> +                    SourceRoot('lrzip') / "../countries-land-1km.geo.json.lrz"
```suggestion
                    "countries-land-1km.geo.json.lrz"
```

2022-09-29 13:21 UTC, vulder commented on varats/varats/projects/c_projects/gzip.py
> +                    SourceRoot('gzip') / "../countries-land-1km.geo.json.gz"
```suggestion
                    "countries-land-1km.geo.json.gz"
```

2022-09-29 13:42 UTC, merged