Use experiment type in addition to report type for result file selection
se-passau/VaRA-Tool-Suite pull request #668
Opened 2022-08-18 07:55 UTC by boehmseb

2022-08-18 09:03 UTC, boehmseb commented on tests/paper/test_paper_config_manager.py
> +    Mock function to replace a lazy commit map loader callback.
```suggestion
    Create a dummy commit map.
```

2022-08-25 07:53 UTC, vulder requested changes

2022-08-25 07:53 UTC, vulder commented on varats/varats/tables/time_stats_table.py
> +                report_file = report_files[0]
That looks wrong, why do we suddenly only need one report file?

2022-08-25 08:02 UTC, boehmseb commented on varats/varats/tables/time_stats_table.py
> +                report_file = report_files[0]
Well, not more wrong than before, at least :sweat_smile: 

As I understood the old version, you retrieve all report files because you expect that different experiments have produced each one time report.
That is now handled by explicitly specifying the experiment types via a command line parameter.
And then I assumed, we only want to compare one report file per experiment type (hence the `[0]).
This, of course, also assumes, that there was only one revision analyzed per project and I think that this assumption was also made in the old version.
A better solution would be to either specify a revision via commandline, or extend the table to have a separate entry per found revision.

2022-08-25 08:09 UTC, vulder commented on varats/varats/tables/time_stats_table.py
> +                report_file = report_files[0]
@Kaufi-Jonas What did you envisioned here?

2022-08-25 08:52 UTC, Kaufi-Jonas commented on varats/varats/tables/time_stats_table.py
> +                report_file = report_files[0]
Yes, @boehmseb is right. I used the assumption here that I am only working with a single revision per case study. If there are more, the table will look off in that it contains two rows for the same binary and experiment with no way to differentiate them. I want to use the table in my bachelor thesis and therefore want to avoid cluttering it up with unnecessary information. Now that I think about it I agree though that this prevents it from being generally useful. I will change this and in some form include the revision information.

2022-08-25 08:55 UTC, vulder approved these changes

2022-08-25 08:55 UTC, merged