Support non master branches
se-passau/VaRA-Tool-Suite pull request #672
Opened 2022-09-03 14:49 UTC by bnico99

2022-09-08 09:12 UTC, boehmseb reviewed
This already looks quite good. The only thing I found is that I think you mixed up the log commands a bit.

As for the failing tests: 
- TestCommitMap: you need to find out why the range is invalid
- TestPaperConfigManager: I think the best is to create a subclass of `CommitMap` that overrides the relevant functions to return the test data and make the mocked function return an instance of that subclass.

2022-09-08 09:12 UTC, boehmseb commented on varats-core/varats/mapping/commit_map.py
> +                )
Shouldn't the commands look like this?

```suggestion
            if master:
                full_out = git(
                    "--no-pager", "log", "--all", "--pretty=format:'%H'"
                )
                wanted_out = git(
                    "--no-pager", "log", "--pretty=format:'%H'",
                    search_range
                )
            else:
                full_out = git("--no-pager", "log", "--all", "--pretty=format:'%H'")
                wanted_out = git(
                    "--no-pager", "log", "--all", "--pretty=format:'%H'", search_range
                )
```

2022-09-08 11:27 UTC, bnico99 commented on varats-core/varats/mapping/commit_map.py
> +                )
Yes, you're absolutely right, I somehow mixed that up, thanks! I fixed it in a new commit.

2022-09-13 14:14 UTC, boehmseb requested changes
One small refactoring remaining, but otherwise looks good.

2022-09-13 14:14 UTC, boehmseb commented on varats-core/varats/mapping/commit_map.py
> +                )
Since `full_out` is the same for both branches you should pull it out of the `if` to simplify, but also to make it more obvious that the commit ids are indeed always the same regardless of which "view" we use.

2022-09-15 08:55 UTC, bnico99 commented on varats-core/varats/mapping/commit_map.py
> +                )
Valid point. I pushed a new commit that fixes this.

2022-09-15 09:10 UTC, boehmseb approved these changes

2022-09-15 19:22 UTC, vulder approved these changes

2022-09-15 19:24 UTC, merged