New tool: case-study extender
se-passau/VaRA-Tool-Suite pull request #69
Opened 2019-05-26 19:59 UTC by vulder

Implemented new case-study extender tool that allows users to adapt and extend existing case-studies.
Case studies now have different stages, i.e., partitions of revisions that logically group revisions. 

related se-passau/VaRA#401

2019-05-26 20:00 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 20:07 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 20:26 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 20:34 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/case_study.py  -6
+ varats/paper/paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 20:41 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/case_study.py  -6
+ varats/paper/paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 21:13 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/case_study.py  -6
+ varats/paper/paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 21:17 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 21:26 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/case_study.py  -6
+ varats/paper/paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 21:30 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/case_study.py  -6
+ varats/paper/paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 21:46 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 21:50 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 22:03 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 22:19 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 22:22 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 22:28 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/case_study.py  -6
+ varats/paper/paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 22:38 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 22:45 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/case_study.py  -6
+ varats/paper/paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 22:51 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-26 22:57 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- varats/driver.py  5
         

Complexity decreasing per file
==============================
+ varats/paper/case_study.py  -6
+ varats/paper/paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-28 09:19 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- varats/tools/commit_map.py  1
- varats/driver.py  8
         

Complexity decreasing per file
==============================
+ varats/paper/paper_config.py  -1
+ varats/paper/case_study.py  -6
         

Clones added
============
- varats/vara_manager.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-05-28 09:22 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-06-04 20:08 UTC, julianbreiteneicher requested changes
Looks good so far, but there are still a few issues.

One additional thing that I just noticed:
We recently talked about the consistency of the command line parameters.
More specifically, you said that a parameter with a specific name should always mean the same thing.
But I think with `num_rev` this is not completely the case:
When I create a case-study then it says how many revisions should be in the resulting study in total.
However, when extending a case-study it says how many revisions should be added (and not how many will exist after the extension).
Is my thinking correct or am I misunderstanding something here?

2019-06-04 20:08 UTC, julianbreiteneicher commented on varats/paper/case_study.py
> +            revisions: List of triples with (commit_hash, id) to be inserted
triple or tuple?

2019-06-04 20:08 UTC, julianbreiteneicher commented on varats/driver.py
>          if 'paper_config' in args:
`args['subcommand']` crashes if I start `vara-cs` without any params:

```
(vara-tool-suite) [jb@scotty ~/work/hiwi:master*] vara-cs
Traceback (most recent call last):
  File "/home/jb/opt/virtualenvs/vara-tool-suite/bin/vara-cs", line 11, in <module>
    load_entry_point('VaRA-Tool-Suite', 'console_scripts', 'vara-cs')()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/driver.py", line 428, in main_casestudy
    if args['subcommand'] == 'status':
KeyError: 'subcommand'
```

I suggest to print the output of '-h' in this case instead.

2019-06-04 20:08 UTC, julianbreiteneicher commented on varats/driver.py
>      args = {
The command `vara-cs ext -h` crashes:

```
Traceback (most recent call last):
  File "/home/jb/opt/virtualenvs/vara-tool-suite/bin/vara-cs", line 11, in <module>
    load_entry_point('VaRA-Tool-Suite', 'console_scripts', 'vara-cs')()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/driver.py", line 425, in main_casestudy
    for k, v in vars(parser.parse_args()).items() if v is not None
  File "/usr/lib/python3.7/argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1969, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1946, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.7/argparse.py", line 1855, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1152, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib/python3.7/argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1987, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1927, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1855, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1037, in __call__
    parser.print_help()
  File "/usr/lib/python3.7/argparse.py", line 2474, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.7/argparse.py", line 2458, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.7/argparse.py", line 525, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib/python3.7/argparse.py", line 614, in _expand_help
    return self._get_help_string(action) % params
```

2019-06-04 20:08 UTC, julianbreiteneicher commented on varats/paper/case_study.py
> +        if self.num_stages <= num_stage:
Crash for `vara-cs ext paper_configs/test/gzip_0.case_study distrib_add benchbuild/tmp/gzip-HEAD --distribution uniform --num-rev 5 --merge-stage 1`:

```
Traceback (most recent call last):
  File "/home/jb/opt/virtualenvs/vara-tool-suite/bin/vara-cs", line 11, in <module>
    load_entry_point('VaRA-Tool-Suite', 'console_scripts', 'vara-cs')()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/driver.py", line 468, in main_casestudy
    extend_case_study(case_study, cmap, args['strategy'], **args)
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/paper/case_study.py", line 364, in extend_case_study
    extend_with_distrib_sampling(case_study, cmap, **kwargs)
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/plot_utils.py", line 28, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/paper/case_study.py", line 394, in extend_with_distrib_sampling
    key=lambda x: x[1]) if not case_study.
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/paper/case_study.py", line 395, in <listcomp>
    has_revision_in_stage(rev_item[0], kwargs['merge_stage'])
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/paper/case_study.py", line 169, in has_revision_in_stage
    if self.num_stages <= num_stage:
TypeError: '<=' not supported between instances of 'int' and 'str'
```

2019-06-11 17:25 UTC, vulder commented on varats/driver.py
>      args = {
python what are you doing:
```
        help="Maximal expected gradient in percent between " +
        "two revisions, e.g., 5 for 5%")
```
help is know a format string... guess what the correct escape is...
```
        help="Maximal expected gradient in percent between " +
        "two revisions, e.g., 5 for 5%%")
```
double %
*face -> wall*

2019-06-11 17:34 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- varats/driver.py  9
         

Complexity decreasing per file
==============================
+ varats/paper/case_study.py  -6
+ varats/paper/paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3636280&bid=12867868)

2019-06-11 17:37 UTC, julianbreiteneicher approved these changes
Looks good now! :+1:

2019-06-11 17:39 UTC, merged