BlameReport: Parse file name from function
se-passau/VaRA-Tool-Suite pull request #694
Opened 2022-10-25 07:18 UTC by boehmseb

2022-10-25 09:39 UTC, vulder requested changes

2022-10-25 09:39 UTC, vulder commented on varats/varats/data/reports/blame_report.py
> +        file_name = str(raw_function_entry.get('file'))
This is problematic in the case where no file is specified. `get` correctly handles this and returns `None`, however, `str(None)` results in `'None'`. So, we always get a string and not an optional string.
We need to separate the conversion logic.

2022-10-25 12:09 UTC, boehmseb commented on varats/varats/data/reports/blame_report.py
> +        file_name = str(raw_function_entry.get('file'))
You are right, stupid mistake.

2022-10-27 07:41 UTC, vulder approved these changes

2022-10-27 07:42 UTC, merged