Add distcc support to RunWLLVM
se-passau/VaRA-Tool-Suite pull request #698
Opened 2022-10-27 16:09 UTC by danjujan

This pull request allows RunWLLVM projects to opt for distributed compilation with distcc.

2022-10-28 08:38 UTC, vulder requested changes
Overall, this look like a nice addition for people that want to use distcc to speed up the project compilation.

thx for contributing this

2022-10-28 08:38 UTC, vulder commented on varats-core/varats/experiment/wllvm.py
> +        *extensions: 'Extension',
```suggestion
        *extensions: base.Extension,
```

2022-10-28 08:38 UTC, vulder commented on varats-core/varats/experiment/wllvm.py
> +        *extensions: 'Extension',
Defaulted parameters are normally placed at the end, is this not possible for this?

Also, what does this mean for the API surface? Could you please add 2 examples to the doc string (one without and one with) that show how one would use this class.

2022-10-28 08:38 UTC, vulder commented on varats-core/varats/experiment/wllvm.py
> +        projdir = Path(sys.argv[0]).parent
```suggestion
        project_dir = Path(sys.argv[0]).parent
```
This is the more common spelling in the code base

2022-10-28 10:52 UTC, danjujan commented on varats-core/varats/experiment/wllvm.py
> +        *extensions: 'Extension',
Fixed in 3e5d671

2022-10-28 10:54 UTC, danjujan commented on varats-core/varats/experiment/wllvm.py
> +        *extensions: 'Extension',
It is possible. Placed it at the end and added examples in 3e5d671.

2022-10-28 10:54 UTC, danjujan commented on varats-core/varats/experiment/wllvm.py
> +        projdir = Path(sys.argv[0]).parent
Fixed in 3e5d671

2022-11-02 09:30 UTC, vulder approved these changes

2022-12-06 11:30 UTC, merged