Allow Git Blame overhead measurement in BlameReportExperiment
se-passau/VaRA-Tool-Suite pull request #714
Opened 2022-11-22 09:39 UTC by boehmseb

- Adds possibility to adapt existing steps to work with ZippedExperimentSteps
- Inject blame measurement flag in BlameReportExperiment compile step

2022-11-24 21:00 UTC, vulder approved these changes

2022-12-22 09:25 UTC, vulder requested changes
Overall, everything looks nice and tidy.

The only thing we should discuss is: Should we keep the WTReport for BlameReports? As we don't plan on expanding/by default using the measurement infra on the vara side.

2022-12-22 09:25 UTC, vulder commented on varats/varats/experiments/vara/blame_report_experiment.py
> +    REPORT_SPEC = ReportSpecification(BR, WallTimeReportAggregate)
Do we want to keep this?

2023-01-04 11:12 UTC, boehmseb commented on varats/varats/experiments/vara/blame_report_experiment.py
> +    REPORT_SPEC = ReportSpecification(BR, WallTimeReportAggregate)
I don't think we really need this. But we could maybe leave this branch lying around somewhere,

2023-01-09 16:45 UTC, vulder commented on varats/varats/experiments/vara/blame_report_experiment.py
> +    REPORT_SPEC = ReportSpecification(BR, WallTimeReportAggregate)
Ok, I'll keep the branch and just close the PR

2023-01-09 16:45 UTC, vulder commented
Keep the changes alive but remove the PR

2023-01-09 16:45 UTC, closed without merging