Reduce memory overhead tef report
se-passau/VaRA-Tool-Suite pull request #721
Opened 2022-12-11 16:07 UTC by bnico99

2022-12-12 09:56 UTC, vulder requested changes

2022-12-12 09:56 UTC, vulder commented on varats-core/varats/report/tef_report.py
> +        return self.__name_id
The name id part should not be in the public API, as it is only a implementation detail. As user should still just call `.name` and get the name transparently, without knowing that locally only an ID was stored.

2022-12-12 09:56 UTC, vulder commented on varats-core/varats/report/tef_report.py
> +        return self.key_name_map[name_id]
Should not be public, i.e., only be used by the `TraceEvent` class.

2022-12-12 09:56 UTC, vulder commented on varats-core/varats/report/tef_report.py
> +import ijson
If ijson does not support type hints, we need to adapt the mypy file to ignore types from there.

2022-12-12 13:54 UTC, bnico99 commented on varats-core/varats/report/tef_report.py
> +        return self.__name_id
@vulder I was not sure how to handle that best. The "problem" is that in this implementation, the TraceEvent does not know its name, it only knows its name id since the id-name mapping is saved in the TEFReport. Should the `name` method take the `TEFReport` as an argument or should we add a `TEFReport` attribute to the `TraceEvent` or did you imaging something entirely different?

2022-12-12 14:31 UTC, boehmseb commented on varats-core/varats/report/tef_report.py
> +                    name_id = self.__key_name_map.index(trace_event["name"])
Depending on how often you have to look up an index like this and how large this list can become it might be better to use an actual map instead.

2022-12-12 14:31 UTC, boehmseb commented on varats-core/varats/report/tef_report.py
> +        self.__trace_events: tp.List[TraceEvent] = trace_events
You could, at least, reuse the already open file instead of opening it a second time. But other than that, I also see no better way.

2022-12-12 16:34 UTC, bnico99 commented on varats-core/varats/report/tef_report.py
> +        self.__trace_events: tp.List[TraceEvent] = trace_events
@boehmseb I re-opened the file because the pointer needs to be reset to the first byte (due to how ijson works - at least I could not figure another way to do it via the high-level APIs that ijson offers; it might be possible with lower-level APIs of ijson though) and `f.seek(0)` made some tests fail, though I am honestly not sure why.

2022-12-14 12:43 UTC, bnico99 commented on varats-core/varats/report/tef_report.py
> +                    name_id = self.__key_name_map.index(trace_event["name"])
@boehmseb I used a list instead of a map since a list makes it easy to use incremental indices (by just appending) and I did not expect the list to reach a size (since it just contains the name of each traced region once) such that the performance influence is substantial. Additionally, with a map, we would still have to do a reverse-lookup at this point (to get the ID of existing entries).

2022-12-14 12:51 UTC, boehmseb commented on varats-core/varats/report/tef_report.py
> +                    name_id = self.__key_name_map.index(trace_event["name"])
If you think the benefits of using a list here outweigh the complexity of the lookup than that's Ok.

2022-12-14 12:52 UTC, boehmseb commented on varats-core/varats/report/tef_report.py
> +        self.__trace_events: tp.List[TraceEvent] = trace_events
I see. Then there probably is no better way. Although I'm a little bit surprised that the library works this way. This is not apparent from their documentation.

2022-12-14 13:08 UTC, bnico99 commented on varats-core/varats/report/tef_report.py
> +        return self.__name_id
@vulder Fixed the leaky abstraction as discussed.

2022-12-14 13:08 UTC, bnico99 commented on varats-core/varats/report/tef_report.py
> +import ijson
Fixed.

2022-12-14 15:27 UTC, vulder commented on varats-core/varats/report/tef_report.py
> +        self.__trace_events: tp.List[TraceEvent] = trace_events
That sounds strange, normally seek or a similar method should be able to reset the file to the beginning :thinking:

2022-12-19 18:11 UTC, bnico99 commented on varats-core/varats/report/tef_report.py
> +        self.__trace_events: tp.List[TraceEvent] = trace_events
@boehmseb It might be possible with some lower-level APIs that the library offers. I will have a look into it. If it is not possible or feasible, I will have a look at the `f.seek(0)` problem (@vulder)

2022-12-22 14:14 UTC, bnico99 commented on varats-core/varats/report/tef_report.py
> +        self.__trace_events: tp.List[TraceEvent] = trace_events
@boehmseb I implemented a different approach that makes use of lower-level APIs that ijson offers. It requires a bit more logic on our side (instead of ijson's side), but it prevents having to read the (potentially huge) file twice.

2022-12-23 09:40 UTC, boehmseb approved these changes

2022-12-23 09:40 UTC, boehmseb commented on varats-core/varats/report/tef_report.py
> +                    key = value
I'm surprised that mypy does not complain that `key` might be used in line 164 without prior definition here.
It still might be a good idea to define it with an empty string or so outside the loop.

2022-12-23 09:40 UTC, boehmseb commented on varats-core/varats/report/tef_report.py
> +        self.__trace_events: tp.List[TraceEvent] = trace_events
Looks good. The question now is whether all these `startswith` checks are in the end faster than re-opening the file once :sweat_smile:
The correct way would probably to profile both versions on a large trace file but I'm not sure whether thta's worth the effort.

2023-01-16 16:08 UTC, bnico99 commented on varats-core/varats/report/tef_report.py
> +                    key = value
Done

2023-01-16 16:18 UTC, bnico99 commented on varats-core/varats/report/tef_report.py
> +        self.__trace_events: tp.List[TraceEvent] = trace_events
Fair point. I did not test it yet. If you insist, I can try to figure it out. Otherwise, I would leave it this way for now.

2023-02-06 13:31 UTC, vulder approved these changes

2023-02-07 12:05 UTC, boehmseb approved these changes

2023-02-08 12:00 UTC, merged