Added DummyCaseStudy
se-passau/VaRA-Tool-Suite pull request #723
Opened 2022-12-14 15:36 UTC by bnico99

2022-12-15 10:21 UTC, vulder commented on varats/varats/projects/cpp_projects/dummy_case_study.py
> +"""Project file for the feature performance case study collection."""
This file is not a real cpp_project, we should put it in the perf examles

2023-02-07 09:55 UTC, vulder requested changes

2023-02-07 09:55 UTC, vulder commented on varats/varats/projects/perf_tests/feature_perf_regression.py
> +        self.cflags += ["-fvara-instruction-threshold=1", "-fno-exceptions"]
```suggestion
        self.cflags += ["-fvara-instruction-threshold=1", "-fno-exceptions"]
```
The threshold is experiment specific for feature instr. and should not be part of the project.

I'm not sure what the best solution is here :thinking:

2023-02-07 09:55 UTC, vulder commented on varats/varats/projects/perf_tests/feature_perf_regression.py
> +            remote="https://github.com/bnico99/FeaturePerfRegression.git",
We should move this repo to `se-sic` so that it's preserved into the future.

2023-02-23 07:24 UTC, bnico99 commented on varats/varats/projects/perf_tests/feature_perf_regression.py
> +            remote="https://github.com/bnico99/FeaturePerfRegression.git",
@vulder I transferred the repo (I though starting the transferring process opens a request, but it seems like it has directly been transferred: https://github.com/se-sic/FeaturePerfRegression)

2023-02-23 09:03 UTC, bnico99 commented on varats/varats/projects/perf_tests/feature_perf_regression.py
> +        self.cflags += ["-fvara-instruction-threshold=1", "-fno-exceptions"]
Maybe the threshold could be added as a command line option that is passed to the experiment or incorporated into the case_study file somehow, if that makes sense to you?

2023-02-23 09:55 UTC, vulder commented on varats/varats/projects/perf_tests/feature_perf_regression.py
> +            remote="https://github.com/bnico99/FeaturePerfRegression.git",
Yes, seems it worked. Update the `remote` and we can merge it afterwards :)

2023-02-23 10:10 UTC, vulder commented on varats/varats/projects/perf_tests/feature_perf_regression.py
> +        self.cflags += ["-fvara-instruction-threshold=1", "-fno-exceptions"]
The case_study file is a bit to generic for that and would then need some form of custom section :thinking: 

@Kaufi-Jonas at least added a variable way to pass the threshold to the base class for correctly setting it in the cflags, however, this still does not solve the problem of choosing a correct value. From the conceptual point of view, it's the job of the experiment to define "how fine grained" measurements should be made. So, the problem is that we currently don't have a good way for the experiment to determine this. One idea I currently have floating in my head would be to use the 'Domain' of the project. If it's a test project set it to 0/1 if not use the default. For more elaborate work one could come up with a better strategy to select the threshold, however, that would also require some form of project introspection to determine it.

2023-03-08 14:39 UTC, vulder approved these changes

2023-03-09 08:34 UTC, merged