Update several blame interaction related plots
se-passau/VaRA-Tool-Suite pull request #728
Opened 2023-01-04 11:10 UTC by boehmseb

Waiting on #714 and #715

2023-02-07 11:23 UTC, vulder requested changes

2023-02-07 11:23 UTC, vulder commented on varats/varats/tables/case_study_metrics_table.py
> +                        loc,
Maybe we should include both LOC numbers here? For some it's important to see the full project, however, we probably also want to see the locs that are "just" part of the repo without it's dependencies.

2023-02-07 12:12 UTC, boehmseb commented on varats/varats/tables/case_study_metrics_table.py
> +                        loc,
Depends on what our goal is. If we want to make the table from the SEAL paper exactly reproducible then we should leave it as is and maybe include both in the future when needed.
Otherwise, it's easy enough to include both.

2023-03-03 10:47 UTC, vulder commented on varats/varats/tables/case_study_metrics_table.py
> +                        loc,
I'm fine with both. The only thing I currently see is that we should indicate what `LOC` means. Maybe `LOC_WS`
for `with submodule`? Got a better idea?

2023-03-03 12:43 UTC, boehmseb commented on varats/varats/tables/case_study_metrics_table.py
> +                        loc,
I added both locs and named the columns `LOC (repo)` and `LOC (project)`.

2023-03-03 13:22 UTC, vulder approved these changes

2023-03-03 14:12 UTC, merged