rework feature tracing experiments and time-stats table, add feature sampling experiment
se-passau/VaRA-Tool-Suite pull request #748
Opened 2023-02-17 10:28 UTC by Kaufi-Jonas

Requires https://github.com/se-sic/VaRA/pull/972 and https://github.com/se-sic/vara-llvm-project/pull/84.

Even though this contains a lot of changes, the commit history is clean meaning each commit touches different files. I recommend reviewing based on that.

2023-02-22 20:43 UTC, vulder requested changes
Overall this looks quite good, I only found a few nits we should clean up before merging.

2023-02-22 20:43 UTC, vulder commented on varats-core/varats/experiment/experiment_util.py
> +    def shorthand(self) -> str:
Why do you need to access this directly? I try to keep such low-level accesses low and more use high-level APIs.

2023-02-22 20:43 UTC, vulder commented on varats/varats/data/reports/feature_tracing_stats_report.py
> +class FeatureTracingStatsReport(BaseReport, shorthand="FTS", file_type="txt"):
Is this now specific to tracing?

2023-02-22 20:43 UTC, vulder commented on varats/varats/ts_utils/click_param_types.py
> +        converted = []
@boehmseb Can you take an additional look at this CLI changes.

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_experiment.py
> +    """Verify markers."""
```suggestion
    """Don't add any instrumentation."""
    NONE = ""
    """Print tracing information to stdout."""
    PRINT = "print"
    """Produce a trace file."""
    TEF = "trace_event"
    """Insert USDT probes."""
    USDT = "usdt"
    """Insert raw USDT probes."""
    USDT_RAW = "usdt_raw"
    """Verify markers."""
    VERIFY = "instr_verify"
```
we normally put comments above

2023-02-22 20:43 UTC, vulder commented on varats/varats/projects/c_projects/gzip.py
> +        HTTP(
If you need more, you can just download the whole zip archive with `HTTPUntar` from benchbuild.

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_instrumentation_points.py
> +    NAME = "CollectnstrumentationPoints"
```suggestion
    NAME = "CollectInstrumentationPoints"
```

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_instrumentation_points.py
> +    """See `DESCRIPTION`."""
Just write a quick class desc, the description might overlap but in the docs this is rendered differently.

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_instrumentation_points.py
> +        project.cflags += self.get_vara_feature_cflags(project)
With your action rework in the base class, could this code not be simplified?

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_sampling.py
> +    """See `DESCRIPTION`."""
same

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_sampling.py
> +        vara_results_dir = get_varats_result_folder(self.project)
```suggestion
        vara_results_dir = get_varats_result_folder(self.project)

```

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_sampling.py
> +                )
Why is only one workload supported? Could we not run multiple after each other?

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_sampling.py
> +    """See `DESCRIPTION`."""
same

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_tracing.py
> +    """See `DESCRIPTION`."""
same

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_tracing.py
> +    DESCRIPTION = """Trace feature performance and collect execution time using
I think it's better to use this as a class comment, the Step description should be a small desc., as they are shown during BB execution.

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_tracing.py
> +                )
same question as above

2023-02-22 20:43 UTC, vulder commented on varats/varats/experiments/vara/feature_tracing_stats.py
> +    DESCRIPTION = """Collect execution statistics about the events produced
same

2023-02-22 20:43 UTC, vulder commented on varats/varats/projects/c_projects/bzip2.py
>          )
You can simplify this with the BB HTTPuntar source, which can download the countries archive and automatically unpack it for you.

2023-02-22 20:43 UTC, vulder commented on varats/varats/projects/c_projects/bzip2.py
> +                ]
Do I understand this correctly, you want to compress all files in one pass?
This is probably related to the "only one workload" part :thinking:

2023-02-22 20:43 UTC, vulder commented on varats/varats/projects/perf_tests/feature_perf_cs_collection.py
> -                "27f17080376e409860405c40744887d81d6b3f34"
Why do you remove this one? With the range ending at `27f1` it's only considered in the commit range it was valid in the repo. Do you think this binary does not/never made any sense at all? Which would be a reason to fully remove it.

2023-02-22 20:43 UTC, vulder commented on varats/varats/projects/c_projects/bzip2.py
> +                "--verbose",
```suggestion
                "--vvv",
```
same?

2023-02-24 08:42 UTC, boehmseb commented on varats/varats/ts_utils/click_param_types.py
> +    value_dict["all"] = [v[0] for v in value_dict.values()]
Better properly flatten the list:
```suggestion
    value_dict["all"] = [experiment for value in value_dict.values() for experiment in value]
```

2023-02-24 08:42 UTC, boehmseb commented on varats/varats/ts_utils/click_param_types.py
> +        converted = []
For this change, I don't understand why it should be necessary. To me it seems that the two versions are equivalent.

2023-02-26 13:00 UTC, Kaufi-Jonas commented on varats-core/varats/experiment/experiment_util.py
> +    def shorthand(self) -> str:
That's for the filename of the compiled binaries I copy into the results directory during the feature tracing and sampling experiments. I currently assemble a filename manually there, which I agree, doesn't make sense as we, for example, use the information which commit the binary originates from. I will change that.

2023-02-26 13:00 UTC, Kaufi-Jonas commented on varats/varats/data/reports/feature_tracing_stats_report.py
> +class FeatureTracingStatsReport(BaseReport, shorthand="FTS", file_type="txt"):
It has always been specific to tracing of feature performance. It provides statistics about how many tracing events are produced over the whole execution and what the distribution of the amount of time between the occurrence of these events looks like. The old name was `VaraInstrumentationStatsReport`, which I found to not express the high-level idea well enough.

2023-02-26 13:00 UTC, Kaufi-Jonas commented on varats/varats/ts_utils/click_param_types.py
> +        converted = []
They are equivalent but I find the original version quite hard to read / understand / counter-intuitive. The main reasons were that it was basically one large expression and that I had to take a close look at the two intermingled list comprehensions to grasp how the data flows.

2023-02-26 13:00 UTC, Kaufi-Jonas commented on varats/varats/experiments/vara/feature_experiment.py
> +    """Verify markers."""
These are intended as doc strings that should be visible from IntelliSense. If you put them above then at least VS Code doesn't correctly relate them.

2023-02-26 13:00 UTC, Kaufi-Jonas commented on varats/varats/projects/c_projects/gzip.py
> +        HTTP(
I am unsure how to use this. Having done a quick Google search, I didn't find a URL to download all release files as a single zip file. Instead, people seem to use self-written scripts to download all release files one by one. There's the option to download all of the source code as a zip file but that doesn't contain the workload files.

2023-02-26 13:00 UTC, Kaufi-Jonas commented on varats/varats/experiments/vara/feature_instrumentation_points.py
> +        project.cflags += self.get_vara_feature_cflags(project)
Yes, it definitely can, thanks for pointing that out.

2023-02-26 13:01 UTC, Kaufi-Jonas commented on varats/varats/experiments/vara/feature_perf_sampling.py
> +                )
I suppose the changes necessary to support multiple workloads would indeed be straightforward. I have not worked with multiple workloads yet and didn't want to invest the time to adjust everything I have written to work with them. This is also the case for the `TimeStatsTable`.

2023-02-26 13:01 UTC, Kaufi-Jonas commented on varats/varats/experiments/vara/feature_perf_tracing.py
> +    DESCRIPTION = """Trace feature performance and collect execution time using
Ah, I was always wondering what the `DESCRIPTION` was about. Makes sense, I am going to change that.

2023-02-26 13:01 UTC, Kaufi-Jonas commented on varats/varats/projects/c_projects/bzip2.py
>          )
I can't find the URL to the countries archive (see above), can you point me to it?

2023-02-26 13:01 UTC, Kaufi-Jonas commented on varats/varats/projects/c_projects/bzip2.py
> +                ]
The issue with bzip2 is that it compresses quite fast, even on the strongest compression setting. As such, I needed multiple input files in a single workload to get it to the 30s mark of total execution time as even the largest JSON files didn't suffice.

2023-02-26 13:01 UTC, Kaufi-Jonas commented on varats/varats/projects/perf_tests/feature_perf_cs_collection.py
> -                "27f17080376e409860405c40744887d81d6b3f34"
Yes, I actually think that one shouldn't use it. In order to get interesting results, you have to sleep for a small amount of time (only a few milliseconds or even in the microsecond domain). The variation from run to run then becomes quite high. However, it would make sense to include it again when updated to use the busy sleep implementation. The clear advantage over SimpleBusyLoop would then be that you could specify a concrete amount of time to sleep for each iteration instead of how often to increment the counter.

2023-02-26 13:01 UTC, Kaufi-Jonas commented on varats/varats/projects/c_projects/bzip2.py
> +                "--verbose",
Yes, if the binary offers long arguments, I much prefer those though because they immediately spell out what their effect is. This means that when quickly glancing at the workload you don't have to do a `<binary> --help` first to understand the configuration.

2023-02-26 13:02 UTC, Kaufi-Jonas commented on varats/varats/ts_utils/click_param_types.py
> +    value_dict["all"] = [v[0] for v in value_dict.values()]
In my opinion, the two intermingled list comprehensions are quite hard to understand and somewhat counter-intuitive. As the definition of value_dict is just above and therefore not defined somewhere outside this function, I prefer my simpler expression. If you want to have this rewritten, I would propose to do it as a for loop explicitly concatenating arrays via the `+=` operator instead.

2023-02-28 08:00 UTC, vulder commented on varats/varats/experiments/vara/feature_experiment.py
> +    """Verify markers."""
That's weird, if find placing string "after" the value strings below the var as highly confusing :thinking:
1) I read the name/value and afterwards can only see the doc -> reading flow is bad
2) If the string below somehow get's formatted to the above (or the line ends in `\`) the values change. But this would, without new lines, also be the case for the above variant.

However, if this is the only option to get the docs to work, we should at least add linebreaks for the comments and an empty line inbetween.

```
class Foo(Enum):

    FOO = "f"
    """
    Foo doc
    """

    BAR = "b"
    """
    Bar doc
    """
```

2023-02-28 08:07 UTC, vulder commented on varats/varats/projects/c_projects/gzip.py
> +        HTTP(
I see :see_no_evil: Well, I guess then the zip version does not work.

Could you maybe write a small source class that can download and handle multiple files, such as http?

```
class MultiHTTP(
            local="example.cnf",
            remote={
                "1.0":
                    "https://github.com/simonepri/geo-maps/releases/"
                    "download/v0.6.0/"
            }
            files = ["countries-land-1km.geo.json", ...]
)
```
I mean, the core of the problem is that when we want 10 different files, we need to add 10 sources, which turn the unique proj/exp name into `...1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...`. Something, I would like to not have :laughing: 

Maybe @simbuerg has a better idea? @Kaufi-Jonas If want, maybe the BB people would like such as contribution.

2023-02-28 08:07 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_sampling.py
> +                )
ok, then let's keep it at 1 for the moment

2023-02-28 08:09 UTC, vulder commented on varats/varats/projects/c_projects/bzip2.py
> +                ]
Nice for `bzip2` I guess :rofl: 

Ok, then let's keep it that way. Maybe just not your reasoning in a comment, so people don't forget why this was choosen.

2023-02-28 08:10 UTC, vulder commented on varats/varats/projects/perf_tests/feature_perf_cs_collection.py
> -                "27f17080376e409860405c40744887d81d6b3f34"
Ok, them let's completely remove it

2023-02-28 08:11 UTC, vulder commented on varats/varats/projects/c_projects/bzip2.py
> +                "--verbose",
Isn't `-vvv` common to chain multiple verboses together? I, at least, no of no tool that uses multiple `v`s otherwise.

3x `--verbose` is kind "verbose"

2023-02-28 08:14 UTC, boehmseb commented on varats/varats/ts_utils/click_param_types.py
> +        converted = []
I actually prefer the conciseness of the list comprehension here and once you know in which order the `for`s are processed by python it's not that hard to understand. But maybe, we can use @vulder's opinion as a tie-breaker here.

2023-02-28 08:14 UTC, vulder commented on varats/varats/ts_utils/click_param_types.py
> +    value_dict["all"] = [v[0] for v in value_dict.values()]
Nested list comprehension are quite common in python and list comprehensions are also deemed to be "pythonic". After you know how they are build, they are often super easy to read/understand.
We also use them all over the place in the TS, so I would prefer to keep it.

2023-02-28 08:17 UTC, boehmseb commented on varats/varats/experiments/vara/feature_experiment.py
> +    """Verify markers."""
Unfortunately, they indeed have to be after the variable when using docstrings.
However, there is an alternative with special comments we could try.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute

2023-02-28 08:24 UTC, boehmseb commented on varats/varats/ts_utils/click_param_types.py
> +    value_dict["all"] = [v[0] for v in value_dict.values()]
I don't like loops for such simple tasks, they take up so much space :smiley: 
But that's just my opinion.
I still vote for fully flattening the list since that respects the semantics of the type rather than some implementation detail on our side.

2023-02-28 10:22 UTC, vulder commented on varats/varats/ts_utils/click_param_types.py
> +        converted = []
We use list comprehensions all over the place and should keep doing this.

2023-03-04 18:00 UTC, Kaufi-Jonas commented on varats/varats/projects/c_projects/gzip.py
> +        HTTP(
Done :)

https://github.com/PolyJIT/benchbuild/pull/546

2023-03-05 10:57 UTC, Kaufi-Jonas commented on varats/varats/experiments/vara/feature_experiment.py
> +    """Verify markers."""
I quickly tried replacing the doc strings with comments starting with `#:  ` as @boehmseb suggested. The issue with this approach is that VS Code's Intellisense feature doesn't handle them resulting in no documentation at all being shown. In my opinion, if you don't have another idea, the best option is to stick with doc strings below the declarations. I already inserted the newlines.

2023-03-07 12:06 UTC, Kaufi-Jonas commented on varats/varats/projects/c_projects/gzip.py
> +        HTTP(
The pull request has been merged and a benchbuild release has been created. I therefore added a commit to make use of the new `HTTPMultiple` source class. I also removed the `TODO: auto unzipper for BB?` comments.

2023-03-09 08:33 UTC, vulder approved these changes

2023-03-09 15:09 UTC, boehmseb approved these changes

2023-03-10 11:10 UTC, merged