Add first work for author disambiguation
se-passau/VaRA-Tool-Suite pull request #756
Opened 2023-03-15 14:29 UTC by vulder

2023-06-12 11:47 UTC, vulder commented
@Sinerum Did you pick those changes and integrate them somewhere? Or what is the plan to work in authors disambig?

2023-06-13 06:19 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +        existing_author.add_data(name, mail)
```suggestion
            existing_author = ambiguos_authors[0]

        existing_author.add_data(name, mail)
```

2023-06-13 06:20 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +        self._look_up_invalid = False
```suggestion
                self.name_dict[name] = author

        self._look_up_invalid = False
```

2023-06-13 06:20 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +        return author_map
```suggestion
            author_map.add_entry(name, email)

        return author_map
```

2023-06-13 06:20 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +    print(a)
```suggestion
```

2023-06-13 06:21 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +        if len(ambiguos_authors) > 1:
```suggestion
            return

        if len(ambiguos_authors) > 1:
```

2023-06-13 06:21 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +        if self.mail_dict[mail] == self.name_dict[name]:
```suggestion
            self._gen_lookup_dicts()

        if self.mail_dict[mail] == self.name_dict[name]:
```

2023-06-13 06:21 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +            return self
```suggestion
        self.names.append(other.names)
        self.mail_addresses.append(other.mail_addresses)
        return self
```

2023-06-13 06:23 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +name_regex = re.compile("\s*\d+\t(.*) <(.*)>")
```suggestion
name_regex = re.compile("\s*\d+\t(.*) <(.*)>")
```
@Sinerum can you make the constant upper case?

2023-06-13 06:24 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +            raise AmbiguousAuthor
```suggestion

        raise AmbiguousAuthor
```

2023-06-13 07:09 UTC, boehmseb requested changes
In addition to my other remarks, there are a lot of return-type annotations missing.

2023-06-13 07:09 UTC, boehmseb commented on varats-core/varats/mapping/author_map.py
> +    def merge(self, other: ['Author']) -> ['Author']:
Why the `['Author']` here instead of `'Author'`?

2023-06-13 07:09 UTC, boehmseb commented on varats-core/varats/mapping/author_map.py
> +        if self.mail_dict[mail] == self.name_dict[name]:
What if one or both keys cannot be found in the map?
That's a case that would also deserve a small test ;)

2023-06-13 07:09 UTC, boehmseb commented on varats-core/varats/mapping/author_map.py
> +        author matches the combination."""
If the exception is raised if no match is found, then "ambiguous" is probably not the best name for the exception.
Ambiguous means that there are multiple possible matches.
Maybe call it `AuthorLookupError` or something along those lines.

2023-06-13 07:09 UTC, boehmseb commented on varats-core/varats/mapping/author_map.py
> +    with local.cwd(path):
Use `git -C` instead of `local.cwd`

2023-06-13 07:09 UTC, boehmseb commented on varats-core/varats/mapping/author_map.py
> +                LOG.info("Invalid author format.")
In what cases does this happen? Wouldn't be a warning more appropriate?

2023-06-13 07:09 UTC, boehmseb commented on tests/mapping/test_author_map.py
> +            Author(19, "Jim Meyering", "meyering@redhat.com")
Checking the Id seems very brittle as it can easily change when new commits are made.
Also, you have implemented equality on authors such that it only checks for the id anyway.
Therefore, you should check whether the lists of names and email addresses match instead on using the equality.

2023-06-13 08:11 UTC, Sinerum commented on varats-core/varats/mapping/author_map.py
> +        author matches the combination."""
Acctualy the docu is wrong the error is thrwon only when multiple authors match the combination. If there is no entry in either map a LookupError is thrown by the dict.

2023-06-13 08:13 UTC, Sinerum commented on varats-core/varats/mapping/author_map.py
> +        if self.mail_dict[mail] == self.name_dict[name]:
I am unsure what should happen in that case for now a Look up error is thrown but we may want change that to either return an author if either map has one and only throw an error if both do not contain a matching author

2023-06-13 08:18 UTC, boehmseb commented on varats-core/varats/mapping/author_map.py
> +        if self.mail_dict[mail] == self.name_dict[name]:
If you explicitly look up using name and email and we cannot find something, then I think we should return `None`. Same goes for the `by_name` and `by_email` versions btw.
I'm not a fan of throwing exceptions around in such a case.

2023-06-13 08:23 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +        if self.mail_dict[mail] == self.name_dict[name]:
For me, not finding a name is expected behavior for such an API, hence returning an optional (i.e., `None`) seems like the most telling design. Especially, as a caller I see from the func signature that the author I'm looking might not be there.

2023-06-13 08:49 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +            return None
```suggestion

        return None
```
@Sinerum You don't need an else if you return within the then clause

2023-06-13 09:08 UTC, vulder commented on varats-core/varats/mapping/author_map.py
> +        return None
```suggestion
        if self._look_up_invalid:
            self._gen_lookup_dicts()

        mail_author = self.mail_dict.get(mail, None)
        if mail_author == (name_author := self.name_dict.get(name, None)):
            return name_author

        return None
```

2023-06-13 09:14 UTC, boehmseb approved these changes

2023-06-13 09:23 UTC, Sinerum approved these changes

2023-06-13 10:52 UTC, merged