Add missing labels to workloads in FeaturePerfCSCollection
se-passau/VaRA-Tool-Suite pull request #780
Opened 2023-03-27 14:06 UTC by danjujan

https://github.com/se-sic/VaRA-Tool-Suite/pull/748 added new workloads without labels for FeaturePerfCSCollection. However, `create_workload_specific_filename` expects labels https://github.com/se-sic/VaRA-Tool-Suite/blob/06c2d3466a862039f5e08361e1899a15750a1593/varats-core/varats/experiment/workload_util.py#L106 and fails if `cmd.label` is `None`.
It might be a good idea to add a check for missing labels when creating a workload. But for now just define some labels.

2023-03-27 15:17 UTC, Kaufi-Jonas requested changes
Otherwise LGTM

2023-03-27 15:17 UTC, Kaufi-Jonas commented on varats/varats/projects/perf_tests/feature_perf_cs_collection.py
> +                label="SBL-iterations-count-to"
Thanks for catching this.

```suggestion
                label="SBL-iterations-10M-count-to-5K"
```
SimpleBusyLoop only has these two configuration options and both are required. They directly influence how many feature tracing events SBL will generate together with their frequency. I therefore recommend that we add this information to the label.

2023-03-27 15:26 UTC, Kaufi-Jonas approved these changes

2023-04-03 09:30 UTC, vulder approved these changes

2023-04-03 09:31 UTC, vulder commented
> #748 added new workloads without labels for FeaturePerfCSCollection. However, `create_workload_specific_filename` expects labels
> 
> https://github.com/se-sic/VaRA-Tool-Suite/blob/06c2d3466a862039f5e08361e1899a15750a1593/varats-core/varats/experiment/workload_util.py#L106
> 
> and fails if `cmd.label` is `None`.
> It might be a good idea to add a check for missing labels when creating a workload. But for now just define some labels.

I'll relay this to the BB devs. For me a label would always make sense, if no label is provided we could just take the name of the command as a label. In the end, everything should have some form of printable name.

@simbuerg

2023-04-04 18:37 UTC, merged