F feature blame test repo
se-passau/VaRA-Tool-Suite pull request #788
Opened 2023-04-26 14:40 UTC by sisteu56

2023-04-28 07:09 UTC, boehmseb requested changes

2023-04-28 07:09 UTC, boehmseb commented on varats/varats/projects/test_projects/feature_test_repo.py
> +class FeatureBlameTestRepo(VProject):
We usually name the project the same as the yaml file responsible for creating the repo.
I'm not sure why this convention was not used for the other project in this file.
Anyway, every occurrence of `FeatureBlameTestRepo` or `CommitFeatureInteractionRepo` should be replaced with `CommitFeatureInteractionExample`. I think this is a way better name for the project.

2023-04-28 07:09 UTC, boehmseb commented on varats/varats/projects/test_projects/feature_test_repo.py
> +    }
We didn't create any workloads for this project yet, so you should delete this.
Workloads are used for performance measurements---which we do not consider in your work.

2023-04-28 07:09 UTC, boehmseb commented on varats/varats/projects/test_projects/feature_test_repo.py
> +        self.cflags += ["-fno-exceptions"]
Do you really need this?
@vulder what was the reason to include this in the other feature test project?

2023-05-09 09:30 UTC, sisteu56 commented
Docs CI failed nachdem ich heute einen Commit gepusht hatte bei dem eine leer zeile von der pre-commit hook hinzugefügt wurde.
Davor war Docs CI succesful.

2023-05-10 07:10 UTC, boehmseb commented
That fail has nothing to do with your change. A package we use got an update which broke our docs. I pushed a fix here: #793

2023-05-10 07:50 UTC, vulder approved these changes

2023-05-10 07:50 UTC, vulder commented on varats/varats/projects/test_projects/feature_test_repo.py
> +        self.cflags += ["-fno-exceptions"]
This makes debugging and analyzing test projects much easier, as it removes strange control-flow for exceptions. It's not 100% needed but probably good to keep this here.

2023-05-10 07:59 UTC, boehmseb approved these changes

2023-06-27 10:48 UTC, merged