Hashable Configurations
se-passau/VaRA-Tool-Suite pull request #789
Opened 2023-05-02 09:02 UTC by danjujan

Our configurations are currently not hashable because they contain mutable objects, e.g `dict` or `list`. Therefore, they cannot be used as a key in a `dict` or as element in a `set` which limits their usability.
For example, in my other PR https://github.com/se-sic/VaRA-Tool-Suite/pull/718 I need a mapping from `Configuration -> Reports`. Currently my workaround was to rewrite my own immutable configuration class to make that work: https://github.com/se-sic/VaRA-Tool-Suite/pull/718/files#diff-46ee8773a540aedfd0d1cfbb2d2721a6191d64d3868c538d282c34f85a048492R50. But that basically duplicates functionality and it would be nice to reuse our existing configuration classes for that.
However, a lot of our code relies on the mutability of configurations. Therefore, my proposal is to keep configurations mutable by default but make them immutable (freeze them) on demand. The [immutables.map](https://github.com/MagicStack/immutables) datatype provides these properties.

The committed code is a rough and far from perfect sketch how such a solution could look like. Apart from loosing the insertion order of configuration options it passes all tests. But I would like to collect some opinions first before pursuing this.

2023-05-03 07:38 UTC, boehmseb commented
If hashing is the only issue, it should be easier to simply add a custom `__hash__()` function to the `ConfigurationImpl` class.
Depending on our requirements, `hash(frozenset(__config_values.items()))` should suffice as a hashing function.
This should be stable as long as you stay in the same python process. Also see this SO for more discussion regarding this topic: https://stackoverflow.com/questions/5884066/hashing-a-dictionary

2023-05-03 19:01 UTC, danjujan commented
After discussing with @vulder I added a `freeze` and `unfreeze` function and `deepcopy`  between them to guarantee immutability.
The other changes are usability improvements.

2023-05-10 13:13 UTC, vulder requested changes
freezing impl looks fine to me, just suggested a bit of clean up

However, should we maybe add tests for the new FrozenConfiguration?

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def create_configuration_from_str(config_str: str) -> "Configuration":
```suggestion
    def create_configuration_from_str(config_str: str) -> 'Configuration':
```
We normally use single quotes for types.

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def create_configuration_from_str(config_str: str) -> "Configuration":
```suggestion
    def create_configuration_from_str(config_str: str) -> 'Configuration':
```
We normally use single quotes for types.

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def create_configuration_from_str(config_str: str) -> "Configuration":
```suggestion
    def create_configuration_from_str(config_str: str) -> 'Configuration':
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def unfreeze(self) -> "Configuration":
```suggestion
    def freeze(self) -> 'FrozenConfiguration':
        raise NotImplementedError

    def unfreeze(self) -> 'Configuration':
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +        raise NotImplementedError
Is the impl here not just `return self`?

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def create_configuration_from_str(config_str: str) -> "Configuration":
```suggestion
    def create_configuration_from_str(config_str: str) -> 'Configuration':
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +        raise AssertionError(DummyConfiguration.USAGE_ERROR_TEXT)
```suggestion
    def freeze(self) -> 'FrozenConfiguration':
        raise AssertionError(DummyConfiguration.USAGE_ERROR_TEXT)

    def unfreeze(self) -> 'Configuration':
        raise AssertionError(DummyConfiguration.USAGE_ERROR_TEXT)
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def create_configuration_from_str(config_str: str) -> "Configuration":
```suggestion
    def create_configuration_from_str(config_str: str) -> 'Configuration':
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def unfreeze(self) -> "Configuration":
```suggestion
    def freeze(self) -> 'FrozenConfiguration':
        return FrozenConfiguration(deepcopy(self))

    def unfreeze(self) -> 'Configuration':
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def unfreeze(self) -> "Configuration":
```suggestion
    def freeze(self) -> 'FrozenConfiguration':
        return FrozenConfiguration(deepcopy(self))

    def unfreeze(self) -> 'Configuration':
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +        raise NotImplementedError
```suggestion
        return self
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def create_configuration_from_str(config_str: str) -> "Configuration":
```suggestion
    def create_configuration_from_str(config_str: str) -> 'Configuration':
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
> +    def unfreeze(self) -> "Configuration":
```suggestion
    def unfreeze(self) -> 'Configuration':
```

2023-05-10 13:13 UTC, vulder commented on varats-core/varats/base/configuration.py
>          raise NotImplementedError
```suggestion
        return self
```

2023-05-10 13:13 UTC, vulder requested changes
freezing impl looks fine to me, just suggested a bit of clean up

However, should we maybe add tests for the new FrozenConfiguration?

2023-05-10 13:13 UTC, vulder requested changes
freezing impl looks fine to me, just suggested a bit of clean up

However, should we maybe add tests for the new FrozenConfiguration?

2023-05-10 13:14 UTC, vulder commented
Looks like github has some issues currently... Somehow it registered by review twice

2023-05-17 10:47 UTC, vulder approved these changes

2023-05-17 10:47 UTC, merged