Adds back picosat workloads to picosat project definition
se-passau/VaRA-Tool-Suite pull request #790
Opened 2023-05-04 10:06 UTC by Ramdambo

2023-05-05 11:30 UTC, bnico99 approved these changes

2023-05-10 07:42 UTC, vulder requested changes
lgtm overall, but could you please fix the pylint issues bevor we merge?

2023-05-10 07:42 UTC, vulder commented on varats/varats/projects/c_projects/picosat.py
> +    # TODO: Not sure about the categories here
categories look fine

2023-05-16 10:33 UTC, vulder approved these changes

2023-05-16 10:43 UTC, merged