Add Dune project
se-passau/VaRA-Tool-Suite pull request #794
Opened 2023-05-12 13:55 UTC by LuAbelt

Adds exemplary examples from Dune for compile-time variability (Template based)

Based on test cases in dune-pdelab

2023-09-05 08:52 UTC, boehmseb requested changes

2023-09-05 08:52 UTC, boehmseb commented on varats-core/varats/report/gnu_time_report.py
> +    shorthand="WL" + TimeReport.SHORTHAND + ReportAggregate.SHORTHAND,
What does the "WL" stand for?

2023-09-05 08:52 UTC, boehmseb commented on varats/varats/projects/cpp_projects/dune.py
> +        self.cflags += ["-mllvm", "--vara-disable-phasar"]
Why do you need this? Maybe add a small comment.
Also, why is this only needed here and not during recompile?

2023-09-05 09:41 UTC, LuAbelt commented on varats/varats/projects/cpp_projects/dune.py
> +        self.cflags += ["-mllvm", "--vara-disable-phasar"]
Unfortunately, the Phasar pass to annotate feature information currently crashes the compiler with Dune. 
So for now we are limited to analysing compile time features that do not require Phasar.

But good point, I should add a comment regarding this and I also forgot it for recompile

2023-09-05 09:50 UTC, LuAbelt commented on varats-core/varats/report/gnu_time_report.py
> +    shorthand="WL" + TimeReport.SHORTHAND + ReportAggregate.SHORTHAND,
I introduced this as a shorthand for "Workload".

I added this as previously the `WLTimeReportAggregate` and `TimeReportAggregate` shared the same shorthand which caused issues for me when running the `TimeWorkloads` experiment.

2023-10-06 14:27 UTC, vulder commented on varats/varats/projects/cpp_projects/dune.py
> +         passes.
```suggestion
        If you use Dune with an experiment that uses the vara compiler,
        add `-mllvm --vara-disable-phasar` to the projects `cflags` to 
        disable phasar passes.
```

2023-10-06 17:01 UTC, vulder commented on varats/varats/projects/cpp_projects/dune.py
> +        add `-mllvm --vara-disable-phasar` to the projects `cflags` to
```suggestion
        add `-mllvm --vara-disable-phasar` to the projects `cflags` to
```

2023-10-06 17:10 UTC, vulder approved these changes

2023-10-06 17:11 UTC, merged