Add container declarations to some projects
se-passau/VaRA-Tool-Suite pull request #796
Opened 2023-05-31 11:14 UTC by Sinerum

Add containers declarations to bzip2, git, hypre and z3 and also add revision base compilation fixes to bzip2 and libxml2

2023-05-31 13:04 UTC, vulder approved these changes
Looks good overall

2023-05-31 13:04 UTC, vulder commented on varats/varats/projects/c_projects/bzip2.py
> +        clang = bb.compiler.cc(self)
```suggestion
```

2023-05-31 13:04 UTC, vulder commented on varats/varats/projects/c_projects/bzip2.py
> +                with local.env(CC=str(clang)):
```suggestion
                with local.env(CC=str(cc_compiler)):
```

2023-05-31 13:04 UTC, vulder commented on varats/varats/projects/c_projects/bzip2.py
> +                with local.env(CC=str(clang)):
```suggestion
                with local.env(CC=str(cc_compiler)):
```

2023-05-31 14:20 UTC, boehmseb requested changes

2023-05-31 14:20 UTC, boehmseb commented on varats/varats/projects/c_projects/bzip2.py
> +        binary_map.specify_binary(
Is `build/bzip2` always valid or only in the revisions that are not in this range?

2023-05-31 14:20 UTC, boehmseb commented on varats/varats/projects/c_projects/bzip2.py
>          bzip2_source = local.path(self.source_of(self.primary_source))
```suggestion
        bzip2_source = local.path(self.source_of_primary)```

2023-05-31 14:20 UTC, boehmseb commented on varats/varats/projects/c_projects/libxml2.py
>          libxml2_version_source = local.path(self.source_of(self.primary_source))
```suggestion
        libxml2_version_source = local.path(self.source_of_primary)
```

2023-06-01 09:49 UTC, Sinerum commented on varats/varats/projects/c_projects/bzip2.py
> +        binary_map.specify_binary(
Only for revisions not in the range which is equvivalent to revisions newer than e264a7f7c44fae62f5be9840946f6bc0e8cd6512

2023-06-01 10:51 UTC, boehmseb commented on varats/varats/projects/c_projects/bzip2.py
> +        binary_map.specify_binary(
Then this should also be reflected in the map.

2023-06-07 06:57 UTC, boehmseb approved these changes

2023-06-07 06:57 UTC, boehmseb commented on varats/varats/projects/c_projects/bzip2.py
> +        bzip2_source = local.path(self.source_of_primary)
It should be possible to use the `pathlib.Path` object in all locations where you use this.
At the very least, it should be possible to do `str(bzip2_version_source)`.
Could you please try? Then we could get rid of this duplication of variables that plumbum always causes here.

2023-06-12 11:42 UTC, merged