Fix multi case study plots and tables
se-passau/VaRA-Tool-Suite pull request #799
Opened 2023-06-06 15:43 UTC by Sinerum

Plots and tables containing multiple case studies no longer crash when generating the filename.
Their file name is now based on all projects in the provided case studies

2023-06-07 06:44 UTC, boehmseb approved these changes

2023-06-12 11:40 UTC, vulder requested changes
Fix looks good but could you please remove the pylint errors before merging :)

2023-06-20 12:09 UTC, vulder commented on varats/varats/table/table.py
> +            f"{reduce(lambda x, y: f'{x}{y.project_name}_', case_study, '')}"
Sorry to be a bit picky here, but we should the string or somehow else make the line fit. The problem with this formatting ist, da it looks like the `f` string is on the level of the outer if case.

2023-06-20 12:13 UTC, Sinerum commented on varats/varats/table/table.py
> +            f"{reduce(lambda x, y: f'{x}{y.project_name}_', case_study, '')}"
I don't like this either, the only options i see is to shorten the name of the local variable case_study to something like cs_list or extract this String into its own method.

2023-06-20 12:22 UTC, vulder commented on varats/varats/table/table.py
> +            f"{reduce(lambda x, y: f'{x}{y.project_name}_', case_study, '')}"
You can also just move the reduce out of the f-string and create a local variable. That seems like the simplest solution

2023-06-20 13:55 UTC, Sinerum commented on varats/varats/table/table.py
> +            f"{reduce(lambda x, y: f'{x}{y.project_name}_', case_study, '')}"
Or even better just remove the f string as the reduce returns a string 🤦

2023-06-20 15:30 UTC, vulder approved these changes

2023-06-20 15:31 UTC, merged