Add feature to add n revisions per year to a case-study
se-passau/VaRA-Tool-Suite pull request #80
Opened 2019-06-13 15:45 UTC by julianbreiteneicher

2019-06-13 15:48 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3716902&bid=13085681)

2019-06-16 23:25 UTC, vulder requested changes
sampling looks good

2019-06-16 23:25 UTC, vulder commented on varats/paper/case_study.py
> +                        cmap, proj_name: str, case_study_version: int,
```suggestion
                        cmap, project_name: str, case_study_version: int,
```
I alwaysed tried to used `project_name` for variables and kwargs

2019-06-16 23:25 UTC, vulder commented on varats/paper/case_study.py
> +    case_study = CaseStudy(proj_name, case_study_version)
```suggestion
    case_study = CaseStudy(project_name, case_study_version)
```

2019-06-17 12:25 UTC, julianbreiteneicher commented
I've integrated your suggested changes.

2019-06-17 12:27 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3716902&bid=13085681)

2019-06-17 13:29 UTC, vulder approved these changes
lgtm

2019-06-17 13:30 UTC, merged