Patch Provider Infrastructure
se-passau/VaRA-Tool-Suite pull request #804
Opened 2023-06-27 11:43 UTC by LuAbelt

Infrastructure to add support for applying patches to projects and measure these

2023-07-17 11:01 UTC, vulder commented on varats-core/varats/provider/patch/patch_provider.py
> +            refspec="origin/f-StaticAnalysisMotivatedSynthBenchmarksImpl",
```suggestion
            refspec="origin/HEAD",
```

2023-07-21 09:55 UTC, LuAbelt commented
Ready for review, still needs #816 to be merged into it before finally integrating it with `vara-dev`

2023-07-24 12:05 UTC, vulder approved these changes

2023-07-24 14:46 UTC, boehmseb requested changes

2023-07-24 14:46 UTC, boehmseb commented on varats-core/varats/provider/patch/patch_provider.py
> +    )
That function seems to be unused.

2023-07-24 14:46 UTC, boehmseb commented on varats-core/varats/provider/patch/patch_provider.py
> +class ApplyPatch(actions.ProjectStep):
Wouldn't it make sense to put the steps in a module `experiment/steps/patch.py`?

2023-07-24 14:46 UTC, boehmseb commented on varats-core/varats/provider/patch/patch_provider.py
> +                f"{self.project.source_of(self.project.primary_source)}"
```suggestion
                f"{self.project.source_of_primary}"
```

2023-07-24 14:46 UTC, boehmseb commented on varats-core/varats/provider/patch/patch_provider.py
> +                Path(self.project.source_of(self.project.primary_source)),
```suggestion
                Path(self.project.source_of_primary),
```

2023-07-24 14:46 UTC, boehmseb commented on varats-core/varats/provider/patch/patch_provider.py
> +                f"{self.project.source_of(self.project.primary_source)}"
```suggestion
                f"{self.project.source_of_primary}"
```

2023-07-24 14:46 UTC, boehmseb commented on varats-core/varats/provider/patch/patch_provider.py
> +                Path(self.project.source_of(self.project.primary_source)),
```suggestion
                Path(self.project.source_of_primary),
```

2023-07-24 14:46 UTC, boehmseb commented on varats-core/varats/provider/patch/patch_provider.py
> +        )
You could make this a class variable

2023-07-24 14:46 UTC, boehmseb commented on varats-core/varats/provider/patch/patch_provider.py
> +    def _get_patches_repository_path() -> Path:
This should be a `@classmethod` because it refers to the class variable `PatchProvider.patches_repository`.

2023-08-02 14:47 UTC, boehmseb approved these changes

2023-08-22 11:35 UTC, merged