Implements feature based perf instrumentation comparision
se-passau/VaRA-Tool-Suite pull request #806
Opened 2023-07-08 20:33 UTC by vulder

2023-11-27 13:00 UTC, vulder commented on varats-core/varats/report/linux_perf_report.py
> +        # TODO: fix return type
```suggestion
```

2024-01-24 11:35 UTC, boehmseb requested changes
Still needs some cleanup (see pylint and mypy complaints).

2024-01-24 11:35 UTC, boehmseb commented on varats/varats/experiments/vara/feature_experiment.py
> +                                print(f"{pb_cmd=}")
Is this an overlooked debug print?

2024-01-24 11:35 UTC, boehmseb commented on varats/varats/data/databases/feature_perf_precision_database.py
> +                # open_events.append(trace_event)
```suggestion
```

2024-01-24 11:35 UTC, boehmseb commented on varats/varats/data/databases/feature_perf_precision_database.py
> +        """Hame of the profiler used."""
```suggestion
        """Name of the profiler used."""
```

2024-01-24 11:35 UTC, boehmseb commented on varats/varats/data/databases/feature_perf_precision_database.py
> +        """Experiment used to produce this profilers information."""
Why is this description the same as for `experiment`?

2024-01-24 11:35 UTC, boehmseb commented on varats/varats/experiments/vara/feature_perf_precision.py
> +            print("Don't instrument everything")
Debug print?

2024-01-24 11:35 UTC, boehmseb commented on varats/varats/experiments/vara/feature_perf_precision.py
> +class RunBackBoxBaseline(OutputFolderStep):  # type: ignore
I assume this should be `RunBlackBoxBaseline`?

2024-01-24 11:35 UTC, boehmseb commented on varats/varats/plots/feature_perf_precision.py
> +
```suggestion
```

2024-01-24 11:35 UTC, boehmseb commented on varats/varats/experiments/vara/feature_perf_precision.py
> +    ) and project.name != "SynthSAFieldSensitivity":
It's annoying that we have to break the abstraction between projects and experiments here (and also later in the tables). But I also don't have a good practical idea how to avoid this...

2024-01-25 09:30 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_precision.py
> +    ) and project.name != "SynthSAFieldSensitivity":
I could not avoid this for all cases, some I got removed but depending on what one wants, it's difficult.

2024-01-25 15:18 UTC, boehmseb approved these changes

2024-01-29 08:41 UTC, LuAbelt commented on varats/varats/experiments/vara/feature_perf_runner.py
> +            FeatureInstrType.TEF, instruction_threshold=1
Is there a specific reason to choose 1 here, instead of 0?

2024-01-29 08:41 UTC, LuAbelt commented on varats/varats/data/databases/feature_perf_precision_database.py
> +    def __cliffs_delta(  # pylint: disable=W0238
If I see correctly this is currently not used anywhere, right? I assume it is part of the base class such that people can use it when overriding `is_regression` or one of the `*_regression_check` methods?

2024-01-29 08:41 UTC, LuAbelt commented on varats/varats/data/databases/feature_perf_precision_database.py
> +            ". config_id=0, profiler=Baseline"
```suggestion
            f". config_id={config_id}, profiler=Baseline"
```
See above

2024-01-29 08:41 UTC, LuAbelt commented on varats/varats/data/databases/feature_perf_precision_database.py
> +    )
Wouldn't it be better to also make the `config_id` a parameter?
```suggestion
def get_patch_names(case_study: CaseStudy, config_id: int = 0) -> tp.List[str]:
    """Looks up all patch names from the given case study."""
    report_files = get_processed_revisions_files(
        case_study.project_name,
        fpp.BlackBoxBaselineRunner,
        fpp.MPRTimeReportAggregate,
        get_case_study_file_name_filter(case_study),
        config_id=config_id
    )
```
There might be scenarios in which you have different patches for different configs (At least this was the case in my thesis)

2024-01-29 08:41 UTC, LuAbelt commented on varats/varats/experiments/vara/feature_perf_precision.py
> +    print(f"{patches=}")
Is this intended to still be here or was this just a debug print?

2024-01-29 08:41 UTC, LuAbelt commented on varats/varats/plots/feature_perf_precision.py
> +        case_studies = get_loaded_paper_config().get_all_case_studies()
See below

2024-01-29 08:41 UTC, LuAbelt commented on varats/varats/plots/feature_perf_precision.py
> +):
Do you think it would be useful/helpful to have another another generator that can generate these plots for individual case studies?

2024-01-29 08:41 UTC, LuAbelt commented on varats/varats/projects/cpp_projects/hyteg.py
> +        update_all_submodules(hyteg_source, recursive=True, init=True)
Technically, `HyTeG` also performs a submodule update through its CMakeList, but it cannot hurt to keep this in, if at any point they decide to change this.

2024-01-30 11:56 UTC, vulder commented on varats/varats/data/databases/feature_perf_precision_database.py
> +    def __cliffs_delta(  # pylint: disable=W0238
Yes, it's not used. My idea was to have all test methods t-test/clifss-delta/u-test etc. follow an "indirect" interface so one can swap them in/out for testing purposes.

2024-01-30 11:59 UTC, vulder commented on varats/varats/experiments/vara/feature_perf_runner.py
> +            FeatureInstrType.TEF, instruction_threshold=1
I think there was one, not 100% sure but if my mind does not play tricks on me it was to ignore super small regions, e.g., selects. Selects are one inst and usually optimized on the backend side, hence measuring them (even when we want to measure everything) is not a good idea.

In the future, this should be cleaned up on the llvm side by implementing a better "should I instrument this region" API.

2024-01-30 12:03 UTC, vulder commented on varats/varats/data/databases/feature_perf_precision_database.py
> +    )
Hmm, I'm not sure if that can/should happen here in this case. In generell, I would agree with you, however here we fetch the patch names for our regression patches that we compare in the experiment. If the returned names would differ, the experiment setup would have a problem. So, I'm not sure if we should make the config_id a variable part here.

2024-01-30 12:05 UTC, vulder commented on varats/varats/plots/feature_perf_precision.py
> +):
Yes, actual something like that would make analyzing individual case studies easier. I'm not planning to include this in this PR but we can extend/refactor this for future use and have 1) generator for "all" and another one that generates one plot per case study.

2024-01-30 12:07 UTC, vulder commented on varats/varats/projects/cpp_projects/hyteg.py
> +        update_all_submodules(hyteg_source, recursive=True, init=True)
If I remember correctly, I had some issue without this but I'm not sure if it is still necessary. But maybe let's keep it as it does not hurt.

2024-01-30 12:08 UTC, vulder commented on varats/varats/plots/feature_perf_precision.py
> +):
I already have a draft :smile: 
I'll post the PR after this one is merged

2024-01-30 12:20 UTC, vulder commented on varats/varats/plots/feature_perf_precision.py
> +):
Ok, two generators are actually a stupid idea :laughing:, we can make do with one. The plot interface allows one to specify `all` as case study, which then is the same as the "original plot" :rofl:

2024-01-30 14:28 UTC, merged