Implements classification evaluation helper
se-passau/VaRA-Tool-Suite pull request #809
Opened 2023-07-11 19:24 UTC by vulder

2023-07-12 07:44 UTC, boehmseb reviewed
lgtm

2023-07-13 14:05 UTC, danjujan requested changes

2023-07-13 14:05 UTC, danjujan commented on varats/varats/data/metrics.py
> +    Actual Negative (N) |  False Positive     (FP)  |  True Negative      (TN)
I would find it useful if one could visualize the ConfusionMatrix easily.
Does it make sense to add a `__str__` method in a similar style that also includes the interpretations?
Maybe we could use [tabulate](https://pypi.org/project/tabulate/) for this to be able to generate tables in different formats, e.g. for LaTeX.

2023-07-13 19:51 UTC, danjujan commented on varats/varats/data/metrics.py
> +        )
```suggestion
    def TP(self) -> tp.Set[tp.Any]:  # pylint: disable=C0103
        return set(self.__actual_positive_values
               ).intersection(self.__predicted_positive_values)
```
We should add a way to retrieve the classified elements instead of just their number. Either we could change the interface as suggested or introduce seperate methods.

2023-07-15 16:52 UTC, vulder commented on varats/varats/data/metrics.py
> +        )
Why would you need the elements? I did not plan to allow users to access them, as (1) the values should be enough for a eval and (2) during construction, the user already passes correctly attributed lists to us.
What you be your use case where you need access to the elements?

2023-07-17 09:20 UTC, danjujan commented on varats/varats/data/metrics.py
> +        )
I would like to inspect/print the FP and FN elements. If we don't expose them, I have to build the intersections myself. That duplicates code and kind of defeats the purpose of using this confusion matrix implementation. I.e., if I have to classify the elements myself anyway, why should I put them again in the attributed lists just to be able to instantiate a `ConfusionMatrix`? If I have my TP/TN/FP/FN lists already, I can use these directly to compute the needed interpretations.

2023-07-18 18:22 UTC, vulder commented on varats/varats/data/metrics.py
> +        )
Yes, but you don't have to implement all the different values. If you need the TP values a simple intersection is enough :thinking:

2023-07-24 13:56 UTC, boehmseb approved these changes
Seems like I just left a comment last time instead of approving...

2023-07-24 14:51 UTC, danjujan approved these changes

2023-07-26 07:46 UTC, merged