Show failed projects in vara-cs status
se-passau/VaRA-Tool-Suite pull request #81
Opened 2019-06-14 17:25 UTC by julianbreiteneicher

A `*.failed` file is created is created in the results directory if the
analysis of the project fails.
Currently, the "failed" file is only created if the opt command
fails. If the analysis fails at an earlier stage, the failed file
is not created.

The `vara-cs status` command interprets this file if present, and shows the analysed revision
as failure. If no yaml report and no failure file is present it prints "missing".

2019-06-14 17:29 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3723074&bid=13100183)

2019-06-16 23:14 UTC, vulder requested changes

2019-06-16 23:14 UTC, vulder commented on varats/data/commit_report.py
> +                                 "(?P<file_commit_hash>.*)_(?P<UUID>.*).failed")
Why did you triplicate the regex instead of just extending the original one by another capture group?
Triplicating them now requires to keep them consistent.

Just add `"\.(?P<file_stem>.*)"`
Then checking for failiure is just.
```
@staticmethod
def is_fail(file_name):
  match = self.FILE_NAME_REGEX.search(file_name)
  return match.group("file_stem") == "failed"
```

2019-06-16 23:14 UTC, vulder commented on varats/experiments/GitBlameAnnotationReport.py
> +        "{project_name}-{binary_name}-{project_version}_{project_uuid}.failed"
same here

2019-06-16 23:14 UTC, vulder commented on varats/plots/commit_interactions.py
> +                reports.append(file_path)
with `is_fail` or `is_success` as static methods we could improve the checking, removing the regex handling from the caller
```
if CommitReport.is_success(file_path):
  reports.append(file_path)
```

2019-06-17 13:33 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3723074&bid=13100183)

2019-06-17 13:54 UTC, julianbreiteneicher commented
Should be done now.

2019-06-17 13:55 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3723074&bid=13100183)

2019-06-17 14:07 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3723074&bid=13100183)

2019-06-17 14:25 UTC, vulder approved these changes

2019-06-17 14:29 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/case_study.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3723074&bid=13100183)

2019-06-17 14:41 UTC, merged