Add tig project
se-passau/VaRA-Tool-Suite pull request #821
Opened 2023-07-27 19:25 UTC by LeonievonMann

2023-07-27 22:32 UTC, vulder requested changes
Except for the two small things and the missing module doc string, this PR LGTM

2023-07-27 22:32 UTC, vulder commented on varats/varats/projects/c_projects/tig.py
> +                bb.watch(make)("install", "j", get_number_of_jobs(bb_cfg()))
This should probably be skipped as we don't want to install the build tig

2023-07-27 22:32 UTC, vulder commented on varats/varats/projects/c_projects/tig.py
> +            with local.env(CC=str(clang)):
```suggestion
        cc_compiler = bb.compiler.cc(self)
        with local.cwd(tig_version_source):
            with local.env(CC=str(cc_compiler)):
```
Calling it compiler is "more correct", as theoretically it can also be gcc or something else.

2023-07-31 09:07 UTC, boehmseb approved these changes

2023-08-21 18:49 UTC, vulder approved these changes

2023-08-21 19:14 UTC, merged