Add requires attribute to Command
se-passau/VaRA-Tool-Suite pull request #822
Opened 2023-08-04 15:17 UTC by danjujan

The `requires` attribute is used by `workload_commands` to check if the command includes all necessary arguments.

2023-08-04 15:23 UTC, danjujan commented on varats/varats/projects/c_projects/xz.py
> +                output=SourceRoot("geo-maps/countries-land-250m.geo.json"),
Benchbuild appends the output params always after the command arguments. This should be sufficient for our use case. No need to implement insertion points right now.

2023-08-07 07:33 UTC, boehmseb requested changes
Looks good overall. Only some small suggestions.

2023-08-07 07:33 UTC, boehmseb commented on varats/varats/projects/c_projects/xz.py
> +                output=SourceRoot("geo-maps/countries-land-250m.geo.json"),
Not sure whether what you are doing here right now is the intended way.
As I understand it, the `output_param` and `output` are intended for the output file the command produces.
The json given here is the input to the command.

But I see your point about where to insert our own arguments.

2023-08-07 07:33 UTC, boehmseb commented on tests/experiment/test_workload_util.py
> +        commands[0]._requires = {"--compress"}
You can implement this change directly in the project.

2023-08-07 07:33 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +class Command(_Command):  # type: ignore [misc]
I would prefer to give this class its own name to better distinguish it from the base class.
Users typically don't see the import right away and thus, may get confused.

2023-08-25 07:47 UTC, boehmseb requested changes
Still needs a little bit of cleanup.
Also, my comment from last time is still open.

2023-08-25 07:47 UTC, boehmseb commented on varats-core/varats/experiment/workload_util.py
> +            return bool(args.intersection(prj_cmd.command.requires))
Is this correct? As far as I can see, this only checks if there is an intersection, but not if all required commands are contained. The following should do the trick:
```suggestion
            return prj.command.requires.issubset(args)
```

2023-08-25 07:47 UTC, boehmseb commented on tests/experiment/test_workload_util.py
> +        project = deepcopy(Xz(revision=revision))
Why the deepcopy here? You are already creating a new instance of `Xz`.

2023-08-25 07:47 UTC, boehmseb commented on varats-core/varats/project/project_util.py
> +class WrappedCommand(Command):  # type: ignore [misc]
Can we find a better name for this? `WrappedCommand` is quite generic and does not tell the user how it is different to a normal `Command`.
We could either go the same route as we did with projects and call it `VCommand` (for "VaRA-TS specific Command") or bring the required argument aspect into the name.

2023-08-25 09:12 UTC, danjujan commented on varats-core/varats/experiment/workload_util.py
> +            return bool(args.intersection(prj_cmd.command.requires))
That is intended behavior. It must be in the requires set. Otherwise I would have to duplicate commands for my use case: https://github.com/se-sic/VaRA-Tool-Suite/blob/37793ec0aff6def2c867bc69dde1c71be3d31c33/varats/varats/projects/c_projects/xz.py#L144
If someone needs the all required functionality, we can still add a `requires_all` field.

2023-08-25 09:17 UTC, boehmseb commented on varats-core/varats/experiment/workload_util.py
> +            return bool(args.intersection(prj_cmd.command.requires))
I see, that is something we should definitely consider here.
It would probably be a good idea to have both, a `requires_all` and a `requires_any`.
The check then should only succeed if both are fulfilled.

2023-08-25 09:26 UTC, danjujan commented on tests/experiment/test_workload_util.py
> +        project = deepcopy(Xz(revision=revision))
Good catch. Will remove that.

2023-08-25 09:26 UTC, danjujan commented on varats-core/varats/project/project_util.py
> +class WrappedCommand(Command):  # type: ignore [misc]
I prefer `VCommand`. That is more generic and maybe we want to additional functionality in the future.

2023-08-25 10:20 UTC, danjujan commented on varats/varats/projects/c_projects/xz.py
> +                output=SourceRoot("geo-maps/countries-land-250m.geo.json"),
This is the code in benchbuild that handles this: https://github.com/PolyJIT/benchbuild/blob/master/benchbuild/command.py#L555-L561
As long as `output` is a `PathToken` `output_param` gets appended to the args. While it might not be the intended use case, we can use this to insert our `extra_args` wherever we want. Just put everything that has to come after the extra_args in the `output_param` list. If an element in the list does not contain `{output}` it stays untouched.
Actually, I think the naming on the benchbuild side is a bit off. This functionality can also used for inputs. So why is `output_param` only for `output`? It could be renamed to `end_params` or so and additionally `{input}` placeholders could be replaced too.

2023-09-07 13:41 UTC, boehmseb commented on tests/experiment/test_workload_util.py
> +from copy import deepcopy
This import should be unused now, right?

2023-09-07 13:41 UTC, boehmseb commented on varats/varats/projects/c_projects/xz.py
> +                requires_all={"--compress"},
Is this both intenden? Looks to me a bit like line 114 is a leftover from debugging :thinking:

2023-09-11 07:34 UTC, boehmseb approved these changes

2023-09-12 20:31 UTC, vulder approved these changes

2023-09-12 20:31 UTC, merged