Handle multiple binaries for same RevisionRange in RevisionBinaryMap
se-passau/VaRA-Tool-Suite pull request #826
Opened 2023-08-23 14:08 UTC by LuAbelt

2023-08-23 14:36 UTC, boehmseb approved these changes

2023-08-24 06:43 UTC, vulder requested changes
Two small things, we should discuss, otherwise this looks good :+1:

2023-08-24 06:43 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +                ]
Instead of explicitly checking, just use a DefaultDict and always append.

2023-08-24 06:43 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +            'AbstractRevisionRange', tp.List[ProjectBinaryWrapper]] = {}
It works with fine with list, but maybe a set would work better so wrapper cannot be inserted twice?
However, a `set` would have the drawback of having no guaranteed iteration order, so we would need to convert it to a list and sort bevor returning it.

What's your opinion on that topic?

2023-08-24 12:15 UTC, LuAbelt commented on varats-core/varats/utils/git_util.py
> +            'AbstractRevisionRange', tp.List[ProjectBinaryWrapper]] = {}
I also thought about a `set` first, but I choose `list` first, to keep it consistent with `__always_valid_mappings`. So if we change to `set` here I would suggest to do it for the always valid mappings as well.

Regarding guaranteed iteration order: Is this something we actually need/use at the moment?
From what I see all experiments use all binaries anyways and create separate result files for each binary.

But since we return the binaries as a `list` anyways in `__getitem__`, I also wouldn't mind just returning a sorted version of that list

2023-08-24 13:17 UTC, vulder commented on varats-core/varats/utils/git_util.py
> +            'AbstractRevisionRange', tp.List[ProjectBinaryWrapper]] = {}
Ok, then lest sort the list but keep a `list` for now. By that we reduce a bit of randomness and if we later find problems with with duplicates we can switch to a set afterwards.

2023-08-24 18:51 UTC, vulder approved these changes

2023-08-24 18:52 UTC, merged