Add experiment CompareASTBlame
se-passau/VaRA-Tool-Suite pull request #876
Opened 2024-02-02 15:06 UTC by LeonievonMann

Needs se-sic/VaRA#1054

2024-02-10 10:59 UTC, vulder reviewed
Overall setup looks good. Maybe the file format could be improved to be easier read/parse able but overall the code should work.

2024-02-10 10:59 UTC, vulder commented on varats/varats/data/reports/blame_annotations.py
> +        self.__varahash = varahash
Are you reusing another format for the file? varahash seems to be the "current" thing and "dbg" will refer to the ast-ones? I'm only a bit confused why you choose those names.

2024-02-10 16:34 UTC, LeonievonMann commented on varats/varats/data/reports/blame_annotations.py
> +        self.__varahash = varahash
The dbghash is the one calculated with the debug information about the location and is line based. And varahash is taken from the blame annotation made by VaRA. Depending on which flag is used to create the .ll file on which the report is based on, this is either line based or AST based.

2024-02-12 14:05 UTC, boehmseb commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +        project.cflags += ["-fvara-ast-GB"]
Does this work like intended? I'm not sure, but I think this would also modify the cflags for actions you added before.

2024-02-16 14:04 UTC, LeonievonMann commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +        project.cflags += ["-fvara-ast-GB"]
This would be a problem. How else could I do this?

2024-02-17 08:35 UTC, vulder commented on varats/varats/data/reports/blame_annotations.py
> +        self.__varahash = varahash
Ah, I see. Then it's good, maybe call it `__dbg_hash` and `__vara_computed_hash` so it's a bit more distinct (and the word hash is separated in snake_case), otherwise I'm the naming then makes sense. Maybe add a small comment for the getter/variable that the vara_computed_hash can be produced in different ways, so that readers can be aware.

2024-02-17 08:38 UTC, vulder commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +        project.cflags += ["-fvara-ast-GB"]
I don't think this works, as the c_flags are all collected and afterwards put into the generated compiler wrapper.
I also do not see a "simple" other way to do this in one go, as for one compile run of the project we can only have one type of commit meta data (with or without ast-blame).
The best and probably cleanest option would be to have 2 experiments, 1 producing the ast-blame based data, the other one the normal/baseline data. Afterwards, in your report you could then load both files and join them together, so you can represent the data uniformly to the users (plots/tables etc.).

2024-06-27 12:32 UTC, boehmseb requested changes

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/data/reports/blame_annotations.py
> +        """Creates a :class`BlameInstrucion`from the corresponding yaml document
```suggestion
        """Creates a :class:`BlameInstrucion` from the corresponding yaml document
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/data/reports/blame_annotations.py
> +        """Intermediate representation of LLVM instruction."""
```suggestion
        """Textual representation of LLVM-IR instruction."""
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/data/reports/blame_annotations.py
> +        Blame based on IRegion.
```suggestion
        Blame based on VaRA's BlameRegion.
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/data/reports/blame_annotations.py
> +        Can be produced in different ways, based on which flag is used.
```suggestion
        Either line-based or AST-based depending on whether `-fvara-ast-GB` is used or not.
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/data/reports/blame_annotations.py
> +    """Report containing debug blame and blame annotations."""
```suggestion
    """Report containing debug-based and VaRA-based blame annotations."""
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/data/reports/blame_annotations.py
> +    """Compares the debug based to the AST based annotations as well as the line
```suggestion
    """Compares the debug-based to the AST-based blame annotations as well as the line
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/data/reports/blame_annotations.py
> +    """Collection of debug blame and VaRA blame."""
```suggestion
    """Debug-based and VaRA-based blame annotations for a single instruction."""
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/data/reports/blame_annotations.py
> +class ASTBlameReport(BaseReport, shorthand="BAST", file_type="yaml"):
The report explicitly deals with the comparison of different blame reports or a quality-check of the AST-based blame report. Maybe we can find a more fitting name.

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +        """
This comment seems very copy-pasted. Pleas reformulate to better fit this step.

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +            # run.
```suggestion
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +        # still add optimizations flags after the experiment specified cflags.
```suggestion
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +        # still add optimizations flags after the experiment specified cflags.
```suggestion
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +        # Generate blame annotation report
```suggestion
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +        # Generate blame annotation report
```suggestion
```

2024-06-27 12:32 UTC, boehmseb commented on varats/varats/experiments/vara/blame_ast_experiment.py
> +        """
This comment seems very copy-pasted. Pleas reformulate to better fit this experiment.

2024-07-08 11:49 UTC, boehmseb approved these changes

2024-07-08 12:00 UTC, merged