Adds lock to FM provider
se-passau/VaRA-Tool-Suite pull request #882
Opened 2024-03-28 14:03 UTC by LuAbelt

Adds a lock to the feature model provider.

When running experiments on slurm, it can happen that multiple nodes fetch the feature model repository at the same time. As nodes may use a shared feature model repository (E.g. on `/scratch/`) this can lead to issues.

This is no issue if the feature model repository is already up-to-date, however if there are any upstream changes this leads to errors in the fetch on some nodes and subsequent failure of the slurm jobs.

2024-04-02 19:37 UTC, vulder requested changes

2024-04-02 19:37 UTC, vulder commented on varats-core/varats/provider/feature/feature_model_provider.py
> +
```suggestion

        lock_path = Path(target_prefix()) / "fm_provider.lock"
```

2024-04-22 07:40 UTC, boehmseb approved these changes

2024-04-22 18:50 UTC, vulder approved these changes

2024-04-23 07:21 UTC, merged