Implements experiment to detect the hot functions of a project
se-passau/VaRA-Tool-Suite pull request #884
Opened 2024-04-27 10:12 UTC by vulder

2024-08-19 06:50 UTC, boehmseb requested changes
The `HotFunctionsReport` still needs a little bit of cleanup and some typing stuff needs fixing.

2024-08-19 06:50 UTC, boehmseb commented on varats/varats/projects/c_projects/xz.py
> +                output=SourceRoot("geo-maps/countries-land-1km.geo.json"),
Should this change be in this PR?

2024-08-19 06:50 UTC, boehmseb commented on varats-core/varats/report/hot_functions_report.py
> +            threshold: min percentage a function needs as self time to count as hot
This currently does not use self time, but time including children.
This should be reflected in the function's documentation.

2024-08-19 06:50 UTC, boehmseb commented on varats-core/varats/report/hot_functions_report.py
> +        total_time_tracked = self.__function_data["sum"].sum()
This currently calculates the sum of all measured functions' execution times including their children and, thus, gives a number much larger than the total execution time.
To get the correct total time, you should use `max()` instead.

```suggestion
        total_time_tracked = self.__function_data["sum"].max()
```

2024-08-19 06:50 UTC, boehmseb commented on varats-core/varats/report/hot_functions_report.py
> +            threshold: min percentage a function needs as self time to count as hot
Same as above.

2024-08-19 19:59 UTC, vulder commented on varats/varats/projects/c_projects/xz.py
> +                output=SourceRoot("geo-maps/countries-land-1km.geo.json"),
It's a quick fix on the side, If you want I can create a separate PR for this but the change itself is correct and fixes a bug.

2024-08-20 08:09 UTC, boehmseb commented on varats/varats/projects/c_projects/xz.py
> +                output=SourceRoot("geo-maps/countries-land-1km.geo.json"),
It would be the cleaner solution.

2024-08-20 18:10 UTC, vulder commented on varats/varats/projects/c_projects/xz.py
> +                output=SourceRoot("geo-maps/countries-land-1km.geo.json"),
If you insist -.-

2024-08-21 08:34 UTC, boehmseb approved these changes

2024-08-21 09:03 UTC, merged