Implement PaperConfigOverviewPlot
se-passau/VaRA-Tool-Suite pull request #92
Opened 2019-06-20 17:56 UTC by julianbreiteneicher

2019-06-20 21:26 UTC, vulder requested changes
Graph looks good, found just a few nits

2019-06-20 21:26 UTC, vulder commented on varats/driver.py
> +    if args['plot_type'] is not PlotTypes.paper_config_overview_plot:
why do you need this? The Idea behind the lazy init is that it does not matter if the plot needs a cmap or not. Do you get any special requirements if you include this?

2019-06-20 21:26 UTC, vulder commented on varats/driver.py
> +                res_folder=args['result_folder']))
We should merge these to result folder setups, and only choose if we want to append the `args['project']`

2019-06-20 21:26 UTC, vulder commented on varats/plots/paper_config_overview.py
> +        str(CFG["paper_config"]["current_config"]))
Should we move this, config based, paper config path into the load_paper_config function as a default argument? It starts to look redundant to pass the default config path.

2019-06-20 21:26 UTC, vulder commented on varats/plots/paper_config_overview.py
> +        repo = pygit2.Repository(repo_path)
Maybe we should start a small git utils module in utils that makes repo handling easier, so we do not have to call discover in all places. As far as I understand it discover is mandatory before loading a repository.

2019-06-20 21:26 UTC, vulder commented on varats/plots/paper_config_overview.py
> +        return set()
Maybe throwing NotImplemented here would be better, this way the failure is silent.

2019-06-20 21:26 UTC, vulder commented on varats/plots/paper_config_overview.py
> +        self.plot(False)
```suggestion
        self.plot(True)
```
currently plot does not use this information but, show is called in view mode so we should at least pass the correct value

2019-06-21 11:05 UTC, julianbreiteneicher commented on varats/driver.py
> +    if args['plot_type'] is not PlotTypes.paper_config_overview_plot:
I will improve that code. The reason was that `args['project']` doesn't exist, so `create_lazy_commit_map_loader` doesn't work.
Should I simply do `if args['project'] ...`? But then i guess it will also not be executed when you don't supply the -p parameter for an interaction plot?

2019-06-21 11:05 UTC, julianbreiteneicher commented on varats/driver.py
> +                res_folder=args['result_folder']))
Good idea. Will do

2019-06-21 11:06 UTC, julianbreiteneicher commented on varats/plots/paper_config_overview.py
> +        str(CFG["paper_config"]["current_config"]))
You mean so you can simply call `PC.load_paper_config()` instead? I think thats a good idea

2019-06-21 11:06 UTC, julianbreiteneicher commented on varats/plots/paper_config_overview.py
> +        return set()
Will do

2019-06-21 11:07 UTC, julianbreiteneicher commented on varats/plots/paper_config_overview.py
> +        self.plot(False)
Makes sense

2019-06-21 11:08 UTC, julianbreiteneicher commented on varats/plots/paper_config_overview.py
> +        repo = pygit2.Repository(repo_path)
Not sure if it's really worth it. You have to use the pygit2 API anyways. So the difference is that you either call `pygit2.discover_repository()` or our `foo.load_repository()` or whatever...

2019-06-23 18:22 UTC, vulder commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3748314&bid=13166186)

2019-06-23 20:00 UTC, vulder requested changes

2019-06-23 20:00 UTC, vulder commented on varats/driver.py
> +        print("ERROR: interaction_plot requires argument \'project\'")
This should not be needed. By design this checking is done with the @check_required_args(['project'])

did you get an error when creating an interaction plot?

2019-06-24 12:31 UTC, julianbreiteneicher commented on varats/driver.py
> +        print("ERROR: interaction_plot requires argument \'project\'")
Correct. I've removed the line.

2019-06-26 18:22 UTC, vulder approved these changes

2019-06-26 18:22 UTC, merged